{{- if .Values.inventory.enabled }}
{{- if .Values.inventory.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elitea-inventory.serviceAccountName" . }}
  labels:
    {{- include "elitea-inventory.labels" . | nindent 4 }}
  {{- with .Values.inventory.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
