package repos

import (
	"context"
	"errors"
	"fmt"
	"io"
	"strconv"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/EliteaAI/elitea-platform/services/elitea-main/internal/application/agentexecution"
	"github.com/EliteaAI/elitea-platform/services/elitea-main/internal/infra/storage"
)

// attachmentBucketType is the bucket_type the chat upload path creates its
// reserved bucket with (internal/api/attachment_store.go,
// RequireAttachmentBucket → BucketType: "system"). It is checked here rather
// than assumed because it is the difference between "the bucket the upload
// endpoint owns" and "a bucket a user made"; see ReadAttachmentObject.
const attachmentBucketType = "system"

// CurrentAttachmentObjectRepository reads one stored chat attachment for the
// private runtime object route.
//
// It deliberately does NOT reuse the artifacts HTTP handler's store adapter
// (internal/api/attachment_store.go): that adapter's job is to let a REQUEST
// name a project, and this repository must never be able to. The project
// arrives from the claim, and every lookup below is scoped by it.
type CurrentAttachmentObjectRepository struct {
	buckets *ArtifactBucketsRepository
	objects *ArtifactObjectsRepository
	store   storage.ObjectStore
}

func NewCurrentAttachmentObjectRepository(
	pool *pgxpool.Pool,
	store storage.ObjectStore,
) (*CurrentAttachmentObjectRepository, error) {
	if store == nil {
		return nil, errors.New("current attachment object store is required")
	}
	buckets, err := NewArtifactBucketsRepository(pool)
	if err != nil {
		return nil, err
	}
	objects, err := NewArtifactObjectsRepository(pool)
	if err != nil {
		return nil, err
	}
	return &CurrentAttachmentObjectRepository{
		buckets: buckets,
		objects: objects,
		store:   store,
	}, nil
}

// ReadAttachmentObject returns one attachment's bytes from the project the
// CLAIM resolved.
//
// FOUR THINGS MUST HOLD, and each rules out a different way the bytes could be
// something other than a chat attachment of this project:
//
//  1. THE BUCKET IS THE PROJECT'S OWN. `elitea_storage.buckets` is keyed
//     (project_id, name), so a bucket name is only ever resolved inside the
//     authorized project — a name from another tenant simply does not exist
//     here.
//  2. THE BUCKET IS THE RESERVED SYSTEM ONE. The chat upload path creates its
//     bucket with bucket_type 'system'; user-facing artifact buckets are
//     'local' or 'autogenerated'. Without this check the route would read any
//     artifact bucket in the project whose key happened to start with the
//     conversation's uuid, which is a file the caller could have UPLOADED
//     rather than one the chat upload path wrote.
//  3. THERE IS A METADATA ROW. The delete path already reasons this way
//     ("an object in it with no metadata row was not written by
//     finalizeAttachment", internal/api/v2/conversations/attachments.go), and
//     the row is also the only trustworthy declared length — the store's own
//     reported size is a backend answer, not a platform record.
//  4. THE BYTES MATCH THE ROW. A length disagreement between the metadata row
//     and the object is not something to paper over by preferring one of them:
//     it means the two halves of the write drifted, and serving either answer
//     would hand a model a document nobody can account for.
//
// The size cap is applied to the ROW first, so an oversized object is refused
// without reading it at all, and again to the bytes, so a store that reports a
// small size and streams a large body cannot outgrow the caller's budget.
func (repository *CurrentAttachmentObjectRepository) ReadAttachmentObject(
	ctx context.Context,
	projectID int64,
	bucket string,
	name string,
	maxBytes int64,
) (storage.AttachmentObjectRecord, error) {
	if repository == nil || repository.buckets == nil ||
		repository.objects == nil || repository.store == nil || ctx == nil {
		return storage.AttachmentObjectRecord{}, errors.New(
			"current attachment object repository is unavailable",
		)
	}
	if projectID <= 0 || bucket == "" || name == "" || maxBytes <= 0 {
		return storage.AttachmentObjectRecord{}, storage.ErrContentNotFound
	}

	bucketRow, err := repository.buckets.GetBucket(ctx, projectID, bucket)
	if errors.Is(err, storage.ErrNotFound) {
		return storage.AttachmentObjectRecord{}, storage.ErrContentNotFound
	}
	if err != nil {
		return storage.AttachmentObjectRecord{}, fmt.Errorf("get attachment bucket: %w", err)
	}
	if bucketRow.ProjectID != projectID || bucketRow.BucketType != attachmentBucketType {
		return storage.AttachmentObjectRecord{}, storage.ErrContentNotFound
	}

	// ListObjects with the FULL key as its prefix, because this repository has
	// no single-object query and adding one would mean regenerating sqlc for a
	// lookup the prefix query already answers. The exact-match filter below is
	// what makes that safe: `key LIKE $2 || '%'` treats `%` and `_` in the key
	// as wildcards, so the prefix alone could match a neighbouring object.
	rows, err := repository.objects.ListObjects(ctx, bucketRow.ID, name)
	if err != nil {
		return storage.AttachmentObjectRecord{}, fmt.Errorf("list attachment object: %w", err)
	}
	var record ObjectRow
	found := false
	for _, row := range rows {
		if row.Key == name {
			record = row
			found = true
			break
		}
	}
	if !found {
		return storage.AttachmentObjectRecord{}, storage.ErrContentNotFound
	}
	if record.ByteLength <= 0 || record.ByteLength > maxBytes {
		return storage.AttachmentObjectRecord{}, storage.ErrContentRejected
	}

	ref, err := storage.NewObjectRef(strconv.FormatInt(projectID, 10), bucket, name)
	if err != nil {
		// A key the metadata row holds but NewObjectRef refuses is a row whose
		// bytes nothing can address — the same condition the admission path
		// refuses on the way in (addressableObjectKey). Not found is the honest
		// answer: there is no object this reference can reach.
		return storage.AttachmentObjectRecord{}, storage.ErrContentNotFound
	}
	body, _, err := repository.store.Get(ctx, ref, nil)
	if errors.Is(err, storage.ErrNotFound) {
		return storage.AttachmentObjectRecord{}, storage.ErrContentNotFound
	}
	if err != nil {
		return storage.AttachmentObjectRecord{}, fmt.Errorf("get attachment object: %w", err)
	}
	defer func() {
		_ = body.Close()
	}()
	content, err := io.ReadAll(io.LimitReader(body, maxBytes+1))
	if err != nil {
		return storage.AttachmentObjectRecord{}, fmt.Errorf("read attachment object: %w", err)
	}
	if int64(len(content)) > maxBytes || int64(len(content)) != record.ByteLength {
		return storage.AttachmentObjectRecord{}, storage.ErrContentRejected
	}
	return storage.AttachmentObjectRecord{
		Bucket:     bucket,
		Name:       name,
		MediaType:  record.MediaType,
		ByteLength: record.ByteLength,
		Content:    content,
	}, nil
}

var _ storage.AttachmentObjectSource = (*CurrentAttachmentObjectRepository)(nil)

// ReadCurrentAttachmentImage is the ADMISSION path's read (#979): the bytes of
// one attached image, so `attachmentContentScaffold` can embed them as an
// `image_url` chunk instead of naming the file and hoping.
//
// It is `ReadAttachmentObject` with the record dropped, deliberately and not
// for brevity. The four guarantees that read enforces — the bucket is this
// project's, it is the RESERVED system bucket the chat upload path owns, a
// metadata row exists, and the row's length matches the object's — are exactly
// the ones an admission-time read needs, and having one implementation means
// the two paths cannot come to disagree about what a chat attachment is. The
// media type is NOT carried over: the application layer derives it from the
// extension, because the recorded one is whatever the browser sent.
//
// `storage.ErrContentRejected` (over the cap, or a length disagreement) and
// `storage.ErrContentNotFound` both reach the caller as an error, which it
// treats as "no bytes, announce the file" — the pre-#979 behaviour.
func (repository *CurrentAttachmentObjectRepository) ReadCurrentAttachmentImage(
	ctx context.Context,
	projectID int64,
	bucket string,
	name string,
	maxBytes int64,
) ([]byte, error) {
	record, err := repository.ReadAttachmentObject(ctx, projectID, bucket, name, maxBytes)
	if err != nil {
		return nil, err
	}
	return record.Content, nil
}

var _ agentexecution.CurrentAttachmentImageReader = (*CurrentAttachmentObjectRepository)(nil)
