"""Regenerate python_retrieval.json: the tables the retrieval tools read,
taken from the Python Inventory engine's source as data.

Run from the repository root (standard library only):

    python3 services/elitea-inventory-engine/assets/generate_retrieval.py

Nothing is transcribed by hand: every value is the Python module's own
object (assignments executed with `ast`, as generate.py does) — the ingestion
presets (`presets.py`), the pattern engine's grammar constants
(`KnowledgeGraph.RELATION_SYNONYMS`, `PATTERN_SYNTAX_HELP`, the hop, result
and segment caps), the communities' `TYPE_PRIORITY`, and the canonical type
list `smart_normalize_types` maps onto (`constants.CANONICAL_TYPES`).
"""

import ast
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.join(HERE, "../../elitea-inventory/src/elitea_inventory/engine")


def parse(path):
    with open(path, encoding="utf-8") as handle:
        return ast.parse(handle.read())


def run_assignments(body, path, names=None, namespace=None):
    """Execute the assignments of `body` (all of them, or those in `names`)."""
    namespace = {} if namespace is None else namespace
    for node in body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = (
            [t.id for t in node.targets if isinstance(t, ast.Name)]
            if isinstance(node, ast.Assign)
            else [node.target.id] if isinstance(node.target, ast.Name) else []
        )
        if names is None or any(t in names for t in targets):
            exec(compile(ast.Module([node], []), path, "exec"), namespace)
    return namespace


presets_path = os.path.join(PKG, "inventory/presets.py")
presets = run_assignments(parse(presets_path).body, presets_path)["PRESETS"]

kg_path = os.path.join(PKG, "inventory/knowledge_graph.py")
kg_class = next(
    node
    for node in parse(kg_path).body
    if isinstance(node, ast.ClassDef) and node.name == "KnowledgeGraph"
)
kg = run_assignments(
    kg_class.body,
    kg_path,
    {
        "RELATION_SYNONYMS",
        "PATTERN_SYNTAX_HELP",
        "MAX_PATTERN_HOPS",
        "MAX_PATTERN_RESULTS",
        "MAX_CHAIN_SEGMENTS",
    },
)

communities_path = os.path.join(PKG, "inventory/communities.py")
communities = run_assignments(
    parse(communities_path).body,
    communities_path,
    {"TYPE_PRIORITY", "ARCHITECTURAL_MIN_PRIORITY"},
)

constants_path = os.path.join(PKG, "constants.py")
constants = run_assignments(parse(constants_path).body, constants_path, {"CANONICAL_TYPES"})

asset = {
    "_comment": "Generated by generate_retrieval.py from the Python Inventory engine's source. Do not edit by hand.",
    "presets": presets,
    "relation_synonyms": kg["RELATION_SYNONYMS"],
    "pattern_syntax_help": kg["PATTERN_SYNTAX_HELP"],
    "max_pattern_hops": kg["MAX_PATTERN_HOPS"],
    "max_pattern_results": kg["MAX_PATTERN_RESULTS"],
    "max_chain_segments": kg["MAX_CHAIN_SEGMENTS"],
    "community_type_priority": communities["TYPE_PRIORITY"],
    "architectural_min_priority": communities["ARCHITECTURAL_MIN_PRIORITY"],
    "canonical_types": list(constants["CANONICAL_TYPES"]),
}
with open(os.path.join(HERE, "python_retrieval.json"), "w", encoding="utf-8") as handle:
    json.dump(asset, handle, indent=1, ensure_ascii=False)
    handle.write("\n")
