"""Regenerate python_inventory.json: the prompts, taxonomies and type tables
of the Python Inventory engine, taken from its source as data.

Run from the repository root (standard library only):

    python3 services/elitea-inventory-engine/assets/generate.py

Nothing is transcribed by hand: every value is the Python module's own
object (assignments executed with `ast`), so the Rust engine extracts with
the prompts and normalises with the tables the Python engine used. The
same run records goldens for the type normaliser (normalize_goldens),
computed by the Python functions themselves.
"""

import ast
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.join(HERE, "../../elitea-inventory/src/elitea_inventory/engine")


def module_values(path, names, namespace=None):
    """Execute the top-level assignments (and functions) named in `names`."""
    with open(path, encoding="utf-8") as handle:
        tree = ast.parse(handle.read())
    namespace = {} if namespace is None else namespace
    for node in tree.body:
        targets = []
        if isinstance(node, ast.Assign):
            targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            targets = [node.target.id]
        elif isinstance(node, (ast.FunctionDef, ast.For)):
            targets = [getattr(node, "name", None)]
        if any(t in names for t in targets if t):
            for arg in getattr(getattr(node, "args", None), "args", []) or []:
                arg.annotation = None
            if isinstance(node, ast.FunctionDef):
                node.returns = None
            exec(compile(ast.Module([node], []), path, "exec"), namespace)
    return namespace


constants = module_values(
    os.path.join(PKG, "constants.py"),
    {
        "TYPE_NORMALIZATION_MAP",
        "TYPE_PRIORITY",
        "TYPE_SUFFIX_NORMALIZATION",
        "KNOWN_TYPE_PREFIXES",
        "KNOWN_TYPE_SUFFIXES",
        "SIGNIFICANT_ENTITY_TYPES",
        "INVENTORY_CHAT_SYSTEM_PROMPT",
        "TOOL_DESCRIPTIONS",
        "READ_ONLY_PREFIXES",
        "WRITE_OPERATION_PATTERNS",
        "DEFAULT_MAX_ITERATIONS",
        "DEFAULT_LLM_TEMPERATURE",
        "DEFAULT_LLM_MAX_TOKENS",
    },
)
extractors = module_values(
    os.path.join(PKG, "inventory/extractors.py"),
    {
        "ENTITY_TAXONOMY",
        "RELATIONSHIP_TAXONOMY",
        "ENTITY_EXTRACTION_PROMPT",
        "RELATION_EXTRACTION_PROMPT",
        "FACT_EXTRACTION_PROMPT",
        "CODE_FACT_EXTRACTION_PROMPT",
        "CANONICAL_FACT_TYPES",
        "CODE_FACT_TYPES",
    },
)

# The two normalisers, executed from their source with the tables above.
kg_namespace = dict(constants)
module_values(
    os.path.join(PKG, "inventory/knowledge_graph.py"),
    {"_normalize_entity_type", "_pick_best_type_part", "_insert_word_boundaries"},
    kg_namespace,
)
ingestion_namespace = dict(constants)
ingestion_namespace["ENTITY_TAXONOMY"] = extractors["ENTITY_TAXONOMY"]
module_values(
    os.path.join(PKG, "inventory/ingestion.py"),
    {"_CANONICAL_TYPES", "normalize_entity_type"},
    ingestion_namespace,
)
# The module-level `for` that fills _CANONICAL_TYPES.
with open(os.path.join(PKG, "inventory/ingestion.py"), encoding="utf-8") as handle:
    tree = ast.parse(handle.read())
for node in tree.body:
    if isinstance(node, ast.For) and "_CANONICAL_TYPES" in ast.unparse(node):
        exec(compile(ast.Module([node], []), "ingestion.py", "exec"), ingestion_namespace)

CASES = [
    "", "Feature", "feature", "Features", "Business Rule", "businessrule", "business-rule",
    "api_contract_/integration", "api_contract___parameter", "documentation::guide",
    "documentation:guide", "api_contract(parameter)", "api_contract_or_integration_point",
    "workflows,processes,procedures", "Screen/Page", "class", "Classes", "validation_rule",
    "user_stories", "UI Component", "REST Endpoint", "domainconcept", "test case", "TestCase",
    "glossary_terms", "data__model", "_service_", "Service", "microservice", "API", "apis",
    "configuration_option", "env var", "Toolkit", "mcp tool", "Person", "team member",
    "requirement/feature", "unknown_thing", "process", "Process", "steps", "a/b/c",
    "concept(term)", "x", "status", "Statuses", "endpoint(", "()",
]
goldens = [
    {
        "raw": case,
        "ingestion": ingestion_namespace["normalize_entity_type"](case),
        "graph": kg_namespace["_normalize_entity_type"](
            ingestion_namespace["normalize_entity_type"](case)
        ),
    }
    for case in CASES
]

asset = {
    "_comment": "Generated by generate.py from the Python Inventory engine's source. Do not edit by hand.",
    "prompts": {
        "entity": extractors["ENTITY_EXTRACTION_PROMPT"],
        "relation": extractors["RELATION_EXTRACTION_PROMPT"],
        "fact": extractors["FACT_EXTRACTION_PROMPT"],
        "code_fact": extractors["CODE_FACT_EXTRACTION_PROMPT"],
    },
    "canonical_types": sorted(ingestion_namespace["_CANONICAL_TYPES"]),
    "fact_types": list(extractors["CANONICAL_FACT_TYPES"]),
    "code_fact_types": list(extractors["CODE_FACT_TYPES"]),
    "type_normalization_map": constants["TYPE_NORMALIZATION_MAP"],
    "type_priority": constants["TYPE_PRIORITY"],
    "type_suffix_normalization": constants["TYPE_SUFFIX_NORMALIZATION"],
    "known_type_prefixes": list(constants["KNOWN_TYPE_PREFIXES"]),
    "known_type_suffixes": list(constants["KNOWN_TYPE_SUFFIXES"]),
    "significant_entity_types": sorted(constants["SIGNIFICANT_ENTITY_TYPES"]),
    "normalize_goldens": goldens,
    "investigate": {
        "system_prompt": constants["INVENTORY_CHAT_SYSTEM_PROMPT"],
        "tool_descriptions": constants["TOOL_DESCRIPTIONS"],
        "read_only_prefixes": list(constants["READ_ONLY_PREFIXES"]),
        "write_operation_patterns": list(constants["WRITE_OPERATION_PATTERNS"]),
        "max_iterations": constants["DEFAULT_MAX_ITERATIONS"],
        "temperature": constants["DEFAULT_LLM_TEMPERATURE"],
        "max_tokens": constants["DEFAULT_LLM_MAX_TOKENS"],
    },
}
with open(os.path.join(HERE, "python_inventory.json"), "w", encoding="utf-8") as handle:
    json.dump(asset, handle, indent=1, ensure_ascii=False)
    handle.write("\n")
