"""Regenerate source_tools.json: the read-only tools `investigate` may call on
an Inventory source toolkit, with their argument schemas.

Run from the repository root (standard library only):

    python3 services/elitea-inventory-engine/assets/source_tools.py

The schemas are elitea-main's snapshot of the SDK catalogue
(internal/runtimecomposition/current_toolkit_schema_snapshot.json); the
read-only rule is the Python engine's `_filter_read_only_tools`
(READ_ONLY_PREFIXES, WRITE_OPERATION_PATTERNS, in python_inventory.json).
A test fails while this file and the snapshot disagree.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SNAPSHOT = os.path.join(
    HERE, "../../elitea-main/internal/runtimecomposition/current_toolkit_schema_snapshot.json"
)
with open(os.path.join(HERE, "python_inventory.json"), encoding="utf-8") as handle:
    rules = json.load(handle)["investigate"]
with open(SNAPSHOT, encoding="utf-8") as handle:
    snapshot = json.load(handle)


def read_only(name):
    lowered = name.lower()
    return any(lowered.startswith(p) for p in rules["read_only_prefixes"]) and not any(
        w in lowered for w in rules["write_operation_patterns"]
    )


tools = {}
for entry in snapshot["entries"]:
    if entry["type"] in ("github", "ado_repos"):
        tools[entry["type"]] = {
            name: schema for name, schema in sorted(entry["args_schemas"].items()) if read_only(name)
        }
with open(os.path.join(HERE, "source_tools.json"), "w", encoding="utf-8") as handle:
    json.dump({"_comment": "Generated by source_tools.py. Do not edit by hand.", "tools": tools}, handle, indent=1, sort_keys=False)
    handle.write("\n")
