-- 0117_browser_sessions.sql — the server-side browser session.
--
-- WHAT THIS REPLACES. Until now the browser credential of an OIDC or SAML
-- deployment was a self-contained signed token. `makeSessionToken`
-- (internal/api/v2/auth/session.go) put `uid`, `email` and a 24-hour `exp` in a
-- base64 payload, appended an HMAC of that payload, and named the result
-- `elitea_session`. Nothing on the server recorded that the session existed.
--
-- WHY THAT IS NOT ENOUGH. Three properties a session needs, and a signed token
-- cannot give any of them:
--
--   1. REVOCATION. Logout only deleted the cookie in the browser. A copy of the
--      value kept working until its `exp`. So did every session of a user an
--      operator suspended, until the principal validator refused the account —
--      which is an account check, not a session check.
--   2. IDLE EXPIRY. The token carried one absolute deadline. A browser left
--      open for a day held the same credential as one used continuously.
--   3. A PROVIDER RECORD. SAML single logout and OIDC end-session both need to
--      know which provider started a session, and SAML needs the session index
--      of the assertion. A signed cookie carries neither, so
--      internal/api/router.go mounts `/auth_saml/logout` as a LOCAL clear only
--      and says so in a comment.
--
-- THE ROW IS THE SESSION. The cookie carries an opaque 256-bit identifier and
-- nothing else, so a stolen value proves membership of this table and stops
-- proving anything the moment the row is revoked or expires. No claim travels
-- in the cookie, so no claim can be replayed after the account changed.
--
-- WHY POSTGRES AND NOT REDIS. This service already keeps ONE kind of auth state
-- in Redis: `internal/infra/authsession`, the Form graph's login-transaction
-- store. That store is a short-lived transaction, and losing it costs a user
-- one retry of a login they are in the middle of. A browser session is not
-- that: losing the store signs every user out, and an OIDC-only deployment —
-- the shape the Kubernetes chart and the standalone stack both run — composes
-- no Redis at all (internal/authcomposition/redis.go). Postgres is present in
-- every deployment and is where this service already keeps identity state.
--
-- WHY SHARED, NOT TENANT. A session is created before any project is selected,
-- and it is platform-wide. The same reason 0095 gives for the provider rows.
--
-- WHAT IS NOT HERE. No claim set, no id_token, no refresh token, no bearer of
-- any kind. `email` is denormalised because `/forward-auth/info` answers it on
-- every probe and a join to `auth_core__user` on the hot path buys nothing;
-- it is display text, never a credential. `provider_session_index` is the ONE
-- provider value stored, because SAML single logout cannot be built without it.
--
-- LIFETIMES ARE PER ROW, NOT PER DEPLOYMENT. `expires_at` and
-- `idle_timeout_seconds` are stamped when the row is created, from the auth
-- configuration in force at that moment. A deployment that shortens its idle
-- timeout must not have to wait for the old rows to age out under the old rule,
-- and a deployment that lengthens it must not silently extend sessions that
-- were issued under the short one. Reading the policy off the row makes both
-- explicit.
--
-- NO FOREIGN KEY TO `auth_core__user`. That table is owned by the legacy
-- runtime and a shared migration that claims it breaks the repository seeds
-- (see migrations/tenant/0128's header for the same rule about ownership). The
-- principal validator already refuses a session whose user is gone, so a
-- dangling `user_id` is refused at validation rather than at insert.
--
-- IDEMPOTENT throughout. No BEGIN/COMMIT: the ledgered runner executes each
-- file inside one transaction with its ledger row (migrate/runner.go apply).

CREATE SCHEMA IF NOT EXISTS elitea_auth;

CREATE TABLE IF NOT EXISTS elitea_auth.browser_sessions (
    -- id is the opaque value the cookie carries: 32 random bytes in unpadded
    -- base64url. It is the WHOLE credential, so it is generated by
    -- crypto/rand and never derived from anything about the user.
    id                     text        PRIMARY KEY,
    -- user_id is auth_core__user.id. Deliberately not a foreign key; see the
    -- header.
    user_id                bigint      NOT NULL,
    -- email is display text for `/forward-auth/info`. Never a credential.
    email                  text        NOT NULL DEFAULT '',
    -- provider names the plane that created the row. Logout and any future
    -- federated single logout switch on it.
    provider               text        NOT NULL,
    -- provider_session_index is the SAML assertion's SessionIndex, empty for
    -- every other provider. It is the value a LogoutRequest must name.
    provider_session_index text        NOT NULL DEFAULT '',
    created_at             timestamptz NOT NULL DEFAULT now(),
    -- last_seen_at moves at most once a minute. The throttle is in Go; this
    -- column only records what it wrote.
    last_seen_at           timestamptz NOT NULL DEFAULT now(),
    -- expires_at is the ABSOLUTE deadline. It never moves.
    expires_at             timestamptz NOT NULL,
    -- idle_timeout_seconds is the second deadline, measured from last_seen_at.
    -- Zero means the session has no idle limit, which is a policy a deployment
    -- may choose and is not the same as an absent value.
    idle_timeout_seconds   integer     NOT NULL,
    -- revoked_at is set by logout and by an administrative revocation. The row
    -- is KEPT rather than deleted so a support question about a sign-out has an
    -- answer; the sweeper below removes it once it is long past use.
    revoked_at             timestamptz,
    CONSTRAINT browser_sessions_id_present
        CHECK (length(id) BETWEEN 32 AND 128),
    CONSTRAINT browser_sessions_user_positive
        CHECK (user_id > 0),
    CONSTRAINT browser_sessions_provider_known
        CHECK (provider IN ('oidc', 'saml', 'form')),
    CONSTRAINT browser_sessions_idle_not_negative
        CHECK (idle_timeout_seconds >= 0)
);

-- Every session of one user, for logout-everywhere and for an operator's
-- revocation of an account's sessions.
CREATE INDEX IF NOT EXISTS browser_sessions_user_idx
    ON elitea_auth.browser_sessions (user_id);

-- The sweep reads this one. A partial index would exclude exactly the revoked
-- rows the sweep also has to remove.
CREATE INDEX IF NOT EXISTS browser_sessions_expires_idx
    ON elitea_auth.browser_sessions (expires_at);
