-- 0135_scim_clients.sql — dedicated SCIM client credentials.
--
-- WHAT THIS REPLACES. Until this file the SCIM 2.0 tree (0096, 0098) accepted a
-- PERSONAL ACCESS TOKEN of an account that holds `admin.auth.users`. That token
-- carries the full rights of a person, every identity provider change is
-- attributed to that person, it stops working when the person leaves, and an
-- operator cannot scope or rotate it per identity provider. SCIM now accepts
-- ONLY a credential from the two tables below, and refuses a personal access
-- token and a browser session.
--
-- TWO AUTHENTICATION METHODS, one row shape. They are the two methods Microsoft
-- Entra ID provisioning offers:
--
--   bearer             The secret IS the bearer token. The identity provider
--                      sends `Authorization: Bearer scim_<secret>` on every call.
--   client_credentials The identity provider posts `client_id` and
--                      `client_secret` to `/api/v2/scim/oauth/token`
--                      (RFC 6749 §4.4) and receives a short-lived access token,
--                      which it then sends as the bearer token. `client_id` is
--                      public; the secret is not.
--
-- ONLY A HASH IS STORED. A secret and an access token are 32 random bytes,
-- base64url encoded behind a recognisable prefix (`scim_`, `scimcs_`,
-- `scimat_`), so a secret scanner can find a leaked one. The row keeps the
-- SHA-256 of the whole string and the last four characters for the admin
-- screen. A plain hash is enough because the input has 256 bits of entropy: a
-- slow password hash protects a low-entropy secret, and this is not one.
--
-- NO FOREIGN KEY TO `auth_core__user`. `created_by` is the id of the operator
-- who made the client, recorded for the admin screen. 0096 and 0098 state why a
-- reference into the pylon corpus is not possible here: `migrate.ApplyShared`
-- runs this corpus against a database that may hold nothing else.
--
-- NO NEW PERMISSION. The admin surface that manages these rows is gated on
-- `admin.auth.users`, the permission the SCIM tree itself required until now.
-- A SCIM client can create and deactivate every account, so the right to mint
-- one must not be weaker than the right to do that by hand.
--
-- IDEMPOTENT throughout. No BEGIN/COMMIT: the ledgered runner executes each file
-- inside one transaction with its ledger row (migrate/runner.go apply).

CREATE SCHEMA IF NOT EXISTS elitea_auth;

CREATE TABLE IF NOT EXISTS elitea_auth.scim_clients (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- name is the operator's label for the identity provider, and it is what
    -- the audit trail records as the actor: `scim:<name>`.
    name         text        NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 100),
    auth_method  text        NOT NULL CHECK (auth_method IN ('bearer', 'client_credentials')),
    -- client_id is set for `client_credentials` only. It is public: it appears
    -- in the identity provider's configuration screen and in the token
    -- request body.
    client_id    text        CHECK (client_id IS NULL OR length(client_id) BETWEEN 8 AND 128),
    -- secret_hash is the hex SHA-256 of the full secret string, prefix included.
    secret_hash  text        NOT NULL CHECK (secret_hash ~ '^[0-9a-f]{64}$'),
    secret_hint  text        NOT NULL CHECK (length(secret_hint) BETWEEN 1 AND 8),
    created_by   integer,
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    rotated_at   timestamptz,
    revoked_at   timestamptz,
    expires_at   timestamptz,
    CONSTRAINT scim_clients_client_id_matches_method CHECK (
        (auth_method = 'client_credentials') = (client_id IS NOT NULL)
    )
);

-- A bearer secret is looked up by its hash on every SCIM request.
CREATE UNIQUE INDEX IF NOT EXISTS scim_clients_secret_hash
    ON elitea_auth.scim_clients (secret_hash);
-- A token request names its client by client_id.
CREATE UNIQUE INDEX IF NOT EXISTS scim_clients_client_id
    ON elitea_auth.scim_clients (client_id) WHERE client_id IS NOT NULL;
-- Two clients with one name would make the audit trail ambiguous.
CREATE UNIQUE INDEX IF NOT EXISTS scim_clients_name
    ON elitea_auth.scim_clients (lower(btrim(name)));

CREATE TABLE IF NOT EXISTS elitea_auth.scim_access_tokens (
    -- token_hash is the hex SHA-256 of the access token string.
    token_hash text        PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    -- Deleting or revoking a client ends every access token it holds. The
    -- revoke path deletes them explicitly; the cascade covers the delete path.
    client_id  bigint      NOT NULL REFERENCES elitea_auth.scim_clients (id) ON DELETE CASCADE,
    -- client_secret_hash is the client's secret_hash at issue time. A token
    -- authenticates only while it still equals the client's CURRENT
    -- secret_hash, so a token minted with a secret that a concurrent rotation
    -- replaced never authenticates, even if its INSERT commits after the
    -- rotation deleted the other tokens.
    client_secret_hash text NOT NULL CHECK (client_secret_hash ~ '^[0-9a-f]{64}$'),
    issued_at  timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL
);

-- The issue path deletes expired rows; this index keeps that delete cheap.
CREATE INDEX IF NOT EXISTS scim_access_tokens_expiry
    ON elitea_auth.scim_access_tokens (expires_at);
CREATE INDEX IF NOT EXISTS scim_access_tokens_client
    ON elitea_auth.scim_access_tokens (client_id);
