-- 0141_native_auth.sql — native authorization for registered public clients
-- (ADR-0025 WP2): the client registry's DB layer, the authorization requests
-- between /authorize and code exchange, the DEVICE REGISTRY (one row per
-- refresh-token family), the hashed refresh and access tokens, and the
-- administration grant that guards the admin surfaces.
--
-- WHY elitea_auth AND SHARED. Identity is deployment-wide, not per tenant: a
-- device signs a USER in before any project is selected, exactly like a browser
-- session (0117) or a SCIM client (0135).
--
-- ONLY HASHES ARE STORED. Every credential (`elnat_` access token, `elnrt_`
-- refresh token, `elnac_` authorization code, the authorize handle and the
-- browser binder) is 32 random bytes; the row keeps the hex SHA-256 of the whole
-- string. A plain hash is enough because the input has 256 bits of entropy.
--
-- THE ANCHOR. Each device session owns one row in public.auth_core__token with
-- `uuid` NULL. That row is the principal every downstream check already keys on
-- (the principal re-check, legacy RBAC, the edge kernel, the forwarded X-Auth-*
-- contract, the ADR-0018 binding), so a native principal is shaped exactly like
-- a personal access token principal and no new AuthType branch exists anywhere.
-- `uuid` NULL means no PAT reader can select it and no PAT JWT can name it.
-- This file issues NO DDL against public.auth_core__token: the foreign key from
-- native_sessions to it is added only when that table exists (the guard below),
-- because elitea-migrate can run this corpus against a database that holds
-- nothing else (0071, 0125).
--
-- THE RE-DELIVERY GRACE WINDOW (coordinator decision 7). A refresh response lost
-- on a mobile network must not wipe a device. The consumed refresh-token row
-- keeps its SUCCESSOR PAIR sealed (AES-256-GCM under a key derived from the
-- consumed token itself, which the server does not store), so presenting the
-- immediately-previous token within the window returns the same pair; outside
-- the window, or once the successor itself has been used, it is reuse and the
-- family is revoked. `successor_sealed` is cleared when the successor rotates.
--
-- IDEMPOTENT throughout. No BEGIN/COMMIT: the ledgered runner executes each file
-- inside one transaction with its ledger row (migrate/runner.go apply).

CREATE SCHEMA IF NOT EXISTS elitea_auth;

-- Registered native public clients, the DB layer. The file layer
-- (NATIVE_CLIENTS_PATH) has no rows here; a DB row overrides a file entry with
-- the same client_id.
CREATE TABLE IF NOT EXISTS elitea_auth.native_clients (
    client_id     text        PRIMARY KEY
                              CHECK (client_id ~ '^[a-z0-9][a-z0-9._-]{2,63}$'),
    display_name  text        NOT NULL CHECK (length(btrim(display_name)) BETWEEN 1 AND 64),
    redirect_uris text[]      NOT NULL CHECK (cardinality(redirect_uris) BETWEEN 1 AND 5),
    enabled       boolean     NOT NULL DEFAULT true,
    created_by    integer,
    updated_by    integer,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- One row per authorization request, from /authorize until code exchange.
CREATE TABLE IF NOT EXISTS elitea_auth.native_authorizations (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle_hash      text        NOT NULL UNIQUE CHECK (handle_hash ~ '^[0-9a-f]{64}$'),
    binder_hash      text        NOT NULL CHECK (binder_hash ~ '^[0-9a-f]{64}$'),
    -- No foreign key: a file-layer client has no row.
    client_id        text        NOT NULL,
    redirect_uri     text        NOT NULL CHECK (length(redirect_uri) <= 512),
    code_challenge   text        NOT NULL CHECK (code_challenge ~ '^[A-Za-z0-9_-]{43}$'),
    state            text        NOT NULL CHECK (length(state) BETWEEN 1 AND 512),
    device_name      text        NOT NULL CHECK (length(device_name) BETWEEN 1 AND 64),
    platform         text        NOT NULL
                                 CHECK (platform IN ('ios', 'android', 'macos', 'windows', 'linux', 'other')),
    client_version   text        NOT NULL DEFAULT '' CHECK (length(client_version) <= 32),
    status           text        NOT NULL DEFAULT 'pending'
                                 CHECK (status IN ('pending', 'approved', 'denied', 'exchanged')),
    login_redirects  smallint    NOT NULL DEFAULT 0,
    user_id          integer,
    code_hash        text        UNIQUE CHECK (code_hash IS NULL OR code_hash ~ '^[0-9a-f]{64}$'),
    code_expires_at  timestamptz,
    -- The family the code produced; a replayed code revokes it.
    session_id       uuid,
    created_at       timestamptz NOT NULL DEFAULT now(),
    expires_at       timestamptz NOT NULL,
    decided_at       timestamptz,
    exchanged_at     timestamptz,
    CONSTRAINT native_authorizations_code_when_approved
        CHECK ((status IN ('approved', 'exchanged')) = (code_hash IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS native_authorizations_expires_idx
    ON elitea_auth.native_authorizations (expires_at);

-- THE DEVICE REGISTRY: one row per refresh-token family (ADR-0025 decision 4).
--
-- No foreign key on user_id: a hard-deleted user's device must still read as
-- revoked, so readers LEFT JOIN the owner and treat a missing one as revoked.
CREATE TABLE IF NOT EXISTS elitea_auth.native_sessions (
    id                   uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id              integer     NOT NULL CHECK (user_id > 0),
    -- The auth_core__token ANCHOR; NULL once the family is revoked.
    token_id             integer     UNIQUE,
    client_id            text        NOT NULL,
    device_name          text        NOT NULL CHECK (length(device_name) BETWEEN 1 AND 64),
    platform             text        NOT NULL
                                     CHECK (platform IN ('ios', 'android', 'macos', 'windows', 'linux', 'other')),
    client_version       text        NOT NULL DEFAULT '' CHECK (length(client_version) <= 32),
    created_at           timestamptz NOT NULL DEFAULT now(),
    last_seen_at         timestamptz NOT NULL DEFAULT now(),
    last_refreshed_at    timestamptz NOT NULL DEFAULT now(),
    -- Stamped at creation, as 0117 does for browser sessions: changing the
    -- idle TTL affects new devices only.
    idle_timeout_seconds integer     NOT NULL CHECK (idle_timeout_seconds > 0),
    -- Absolute cap; NULL = none.
    expires_at           timestamptz,
    revoked_at           timestamptz,
    revoke_reason        text        CHECK (revoke_reason IN
        ('signed_out', 'user', 'admin', 'refresh_reuse', 'code_replay', 'user_deactivated',
         'client_disabled', 'client_removed', 'expired')),
    revoked_by           integer,
    CONSTRAINT native_sessions_revocation_consistent
        CHECK ((revoked_at IS NULL) = (revoke_reason IS NULL))
);
CREATE INDEX IF NOT EXISTS native_sessions_user_idx
    ON elitea_auth.native_sessions (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS native_sessions_client_idx
    ON elitea_auth.native_sessions (client_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS native_sessions_idle_idx
    ON elitea_auth.native_sessions (last_refreshed_at) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS elitea_auth.native_refresh_tokens (
    token_hash       text        PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    session_id       uuid        NOT NULL REFERENCES elitea_auth.native_sessions (id) ON DELETE CASCADE,
    generation       integer     NOT NULL CHECK (generation >= 1),
    issued_at        timestamptz NOT NULL DEFAULT now(),
    consumed_at      timestamptz,
    -- The successor pair, sealed under a key derived from THIS token (see the
    -- header). Set when this token is consumed; cleared when the successor is.
    successor_sealed bytea,
    UNIQUE (session_id, generation)
);

CREATE TABLE IF NOT EXISTS elitea_auth.native_access_tokens (
    token_hash text        PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    session_id uuid        NOT NULL REFERENCES elitea_auth.native_sessions (id) ON DELETE CASCADE,
    issued_at  timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS native_access_tokens_session_idx
    ON elitea_auth.native_access_tokens (session_id);
CREATE INDEX IF NOT EXISTS native_access_tokens_expires_idx
    ON elitea_auth.native_access_tokens (expires_at);

-- Guarded foreign key: anchor -> auth_core__token, ON DELETE SET NULL. The
-- device row survives for the registry's "revoked" view; a NULL anchor is itself
-- a revoked state.
DO $$
BEGIN
    IF to_regclass('public.auth_core__token') IS NULL THEN
        RAISE NOTICE '0141: auth_core absent, native anchor foreign key skipped';
        RETURN;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'native_sessions_token_id_fkey') THEN
        RETURN;
    END IF;
    ALTER TABLE elitea_auth.native_sessions
        ADD CONSTRAINT native_sessions_token_id_fkey
        FOREIGN KEY (token_id) REFERENCES public.auth_core__token (id) ON DELETE SET NULL;
END
$$;

-- The ADMINISTRATION-mode grant behind both native admin surfaces (coordinator
-- decision 6): the `native_clients` registration editor (this WP) and the
-- `native_client_policy` section (WP4), which reuses this grant.
--
--   configuration.native_clients  <- GET/PUT/DELETE /admin/native_clients/administration
--                                    the `native_clients` and `native_client_policy` sections
--
-- WHO HOLDS IT. `super_admin` and `admin` in the `administration` mode, the same
-- holder set as every other central configuration grant (0060, 0061, 0082,
-- 0110). Registering a client decides which applications may hold a refresh
-- token for every user of the deployment.
--
-- WHY HERE AND NOT IN 0060. 0060 returns early when any administration-mode role
-- exists, so an edit there would seed fresh databases only; migrations are also
-- checksum-immutable. The to_regclass guard and ON CONFLICT DO NOTHING make this
-- block inert on a database without roles and on a repeat run.
DO $$
BEGIN
    IF to_regclass('public.auth_core__role') IS NULL
       OR to_regclass('public.auth_core__role_permission') IS NULL THEN
        RAISE NOTICE '0141: auth_core tables absent, nothing to grant';
        RETURN;
    END IF;

    INSERT INTO public.auth_core__role_permission (role_id, permission)
    SELECT role.id, grant_row.permission
    FROM public.auth_core__role AS role
    CROSS JOIN (VALUES
        ('configuration.native_clients')
    ) AS grant_row(permission)
    WHERE role.mode = 'administration' AND role.name IN ('super_admin', 'admin')
    ON CONFLICT (role_id, permission) DO NOTHING;
END
$$;
