-- The index is scoped by project.
--
-- WHY. 0001 keyed every index table by `wiki_id` alone, in this one
-- database shared by every platform project. A `wiki_id` is derived from
-- the repository (`owner--repo--branch`, `artifact--bucket--prefix--branch`),
-- not from the project. Each index row now belongs to one project, and
-- every access is scoped by `(project_id, wiki_id)`.
--
-- WHAT CHANGES. Every index table carries `project_id` (the platform's
-- `centry.project.id`, an INTEGER), and it leads every primary key, unique
-- key, foreign key and lookup index: `(project_id, wiki_id, ...)`. The
-- engine filters, inserts and deletes by the pair. A build records the
-- project it publishes into (`deepwiki_build.builds.project_id`); the
-- staging tables stay keyed by `build_id`, a server-drawn UUID that only
-- the build's own `builds` row names, so the pair is fixed when the build
-- opens and the publish copies it from there.
--
-- WHY THE ROWS ARE DELETED. A row written before this migration cannot be
-- attributed to a project: the same `wiki_id` may have been generated by
-- several projects, the last one replacing the others, and nothing recorded
-- which. A row is kept only when its project is known, so the index
-- tables are recreated empty and every build in progress is deleted. An index is rebuilt by the next generation of its
-- wiki; until then `ask` and `deep_research` answer "no wiki index found".
-- The generated wiki pages live in the platform artifact store, not here,
-- and are not touched (see docs/UPGRADING.md).
--
-- WHY DROP AND CREATE, NOT ALTER. The tables are emptied anyway, and
-- 0001's constraints carry server-generated names. Recreating the tables
-- states the whole new key in one place and depends on no generated name.
-- The text-search configuration and the `vector` extension of 0001 stay.
--
-- 0001-0004 are applied and checksummed in the ledger; they are not edited.

-- ---------------------------------------------------------------------------
-- The live index, recreated with the project in every key
-- ---------------------------------------------------------------------------

DROP TABLE IF EXISTS wiki_bm25_postings;
DROP TABLE IF EXISTS wiki_bm25_terms;
DROP TABLE IF EXISTS wiki_bm25_docs;
DROP TABLE IF EXISTS wiki_bm25_meta;
DROP TABLE IF EXISTS wiki_node_embeddings;
DROP TABLE IF EXISTS wiki_edges;
DROP TABLE IF EXISTS wiki_nodes;
DROP TABLE IF EXISTS wikis;

CREATE TABLE wikis (
    project_id                INTEGER     NOT NULL,
    wiki_id                   TEXT        NOT NULL,
    repo                      TEXT        NOT NULL,
    branch                    TEXT        NOT NULL,
    provider                  TEXT        NOT NULL DEFAULT 'github',
    host                      TEXT        NOT NULL DEFAULT 'github.com',
    display_name              TEXT        NOT NULL DEFAULT '',
    description               TEXT        NOT NULL DEFAULT '',
    topics                    JSONB       NOT NULL DEFAULT '[]'::jsonb,
    folder_path               TEXT        NOT NULL DEFAULT '',
    commit_hash               TEXT,
    canonical_repo_identifier TEXT,
    analysis_key              TEXT,
    wiki_version_id           TEXT,
    artifact_status           JSONB       NOT NULL DEFAULT '{}'::jsonb,
    stats                     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, wiki_id),
    CHECK (project_id > 0)
);

CREATE INDEX idx_wikis_repo_branch ON wikis (project_id, repo, branch);

-- The `fts` expression is 0001's, character for character: the query side
-- folds with the same expression (see 0001, "Text search configuration").
CREATE TABLE wiki_nodes (
    project_id     INTEGER NOT NULL,
    wiki_id        TEXT    NOT NULL,
    node_id        TEXT    NOT NULL,
    rel_path       TEXT    NOT NULL DEFAULT '',
    file_name      TEXT    NOT NULL DEFAULT '',
    language       TEXT    NOT NULL DEFAULT '',
    start_line     INTEGER NOT NULL DEFAULT 0,
    end_line       INTEGER NOT NULL DEFAULT 0,
    symbol_name    TEXT    NOT NULL DEFAULT '',
    symbol_type    TEXT    NOT NULL DEFAULT '',
    parent_symbol  TEXT,
    source_text    TEXT    NOT NULL DEFAULT '',
    docstring      TEXT    NOT NULL DEFAULT '',
    signature      TEXT    NOT NULL DEFAULT '',
    chunk_type     TEXT,
    macro_cluster  INTEGER,
    micro_cluster  INTEGER,
    is_architectural BOOLEAN NOT NULL DEFAULT FALSE,
    is_doc           BOOLEAN NOT NULL DEFAULT FALSE,
    is_test          BOOLEAN NOT NULL DEFAULT FALSE,
    fts            TSVECTOR GENERATED ALWAYS AS (
        to_tsvector(
            'deepwiki_porter',
            regexp_replace(
                symbol_name || ' ' || signature || ' ' || docstring
                    || ' ' || source_text,
                '[^[:alnum:]]+', ' ', 'g'
            )
        )
    ) STORED,
    PRIMARY KEY (project_id, wiki_id, node_id),
    FOREIGN KEY (project_id, wiki_id)
        REFERENCES wikis (project_id, wiki_id) ON DELETE CASCADE
);

CREATE INDEX idx_wiki_nodes_fts   ON wiki_nodes USING GIN (fts);
CREATE INDEX idx_wiki_nodes_path  ON wiki_nodes (project_id, wiki_id, rel_path);
CREATE INDEX idx_wiki_nodes_name  ON wiki_nodes (project_id, wiki_id, symbol_name);
CREATE INDEX idx_wiki_nodes_type  ON wiki_nodes (project_id, wiki_id, symbol_type);
CREATE INDEX idx_wiki_nodes_macro ON wiki_nodes (project_id, wiki_id, macro_cluster);

CREATE TABLE wiki_edges (
    project_id INTEGER NOT NULL,
    wiki_id    TEXT    NOT NULL,
    source_id  TEXT    NOT NULL,
    target_id  TEXT    NOT NULL,
    rel_type   TEXT    NOT NULL,
    edge_class TEXT,
    weight     REAL    NOT NULL DEFAULT 1.0,
    metadata   JSONB   NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (project_id, wiki_id, source_id, target_id, rel_type),
    FOREIGN KEY (project_id, wiki_id)
        REFERENCES wikis (project_id, wiki_id) ON DELETE CASCADE
);

CREATE INDEX idx_wiki_edges_source ON wiki_edges (project_id, wiki_id, source_id);
CREATE INDEX idx_wiki_edges_target ON wiki_edges (project_id, wiki_id, target_id);

CREATE TABLE wiki_node_embeddings (
    project_id INTEGER NOT NULL,
    wiki_id    TEXT    NOT NULL,
    node_id    TEXT    NOT NULL,
    embedding  VECTOR  NOT NULL,
    PRIMARY KEY (project_id, wiki_id, node_id),
    FOREIGN KEY (project_id, wiki_id, node_id)
        REFERENCES wiki_nodes (project_id, wiki_id, node_id) ON DELETE CASCADE
);

-- The BM25 statistics. As in 0001 they have no foreign key: the publish
-- writes millions of postings for a large repository, and a per-row key
-- check on each would lengthen the publish transaction. The publish deletes
-- and writes them by `(project_id, wiki_id)` explicitly.
CREATE TABLE wiki_bm25_meta (
    project_id INTEGER          NOT NULL,
    wiki_id    TEXT             NOT NULL,
    branch     TEXT             NOT NULL,
    doc_count  INTEGER          NOT NULL,
    avgdl      DOUBLE PRECISION NOT NULL,
    k1         DOUBLE PRECISION NOT NULL,
    b          DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (project_id, wiki_id, branch)
);

CREATE TABLE wiki_bm25_docs (
    project_id INTEGER NOT NULL,
    wiki_id    TEXT    NOT NULL,
    branch     TEXT    NOT NULL,
    doc_idx    INTEGER NOT NULL,
    node_id    TEXT    NOT NULL,
    length     INTEGER NOT NULL,
    PRIMARY KEY (project_id, wiki_id, branch, doc_idx)
);

CREATE INDEX idx_wiki_bm25_docs_node
    ON wiki_bm25_docs (project_id, wiki_id, branch, node_id);

CREATE TABLE wiki_bm25_terms (
    project_id INTEGER NOT NULL,
    wiki_id    TEXT    NOT NULL,
    branch     TEXT    NOT NULL,
    term       TEXT    NOT NULL,
    df         INTEGER NOT NULL,
    PRIMARY KEY (project_id, wiki_id, branch, term)
);

CREATE TABLE wiki_bm25_postings (
    project_id INTEGER NOT NULL,
    wiki_id    TEXT    NOT NULL,
    branch     TEXT    NOT NULL,
    term       TEXT    NOT NULL,
    doc_idx    INTEGER NOT NULL,
    tf         INTEGER NOT NULL,
    PRIMARY KEY (project_id, wiki_id, branch, term, doc_idx)
);

CREATE INDEX idx_wiki_bm25_postings_term
    ON wiki_bm25_postings (project_id, wiki_id, branch, term);

-- ---------------------------------------------------------------------------
-- The build space: a build names the project it publishes into
-- ---------------------------------------------------------------------------
--
-- Every build in progress is deleted (the cascade removes its staged rows):
-- it was opened without a project, so it cannot be published into one. Its
-- generation fails at the publish and is run again. The lock keeps an engine
-- pod from before this migration from inserting a build between the DELETE
-- and the NOT NULL column below (it would make the ALTER fail).
LOCK TABLE deepwiki_build.builds IN ACCESS EXCLUSIVE MODE;
DELETE FROM deepwiki_build.builds;

ALTER TABLE deepwiki_build.builds ADD COLUMN project_id INTEGER NOT NULL;
ALTER TABLE deepwiki_build.builds
    ADD CONSTRAINT builds_project_id_positive CHECK (project_id > 0);

CREATE INDEX idx_builds_project_wiki
    ON deepwiki_build.builds (project_id, wiki_id);
