#!/usr/bin/env python3
"""Re-copy the engine from the legacy checkout and record its digests.

The engine under ``src/elitea_deepwiki/engine/`` is a plain copy of
``deepwiki_plugin/plugin_implementation/``. This tool performs that copy and
writes ``COPY_MANIFEST.json`` beside it, which
``tests/engine/test_copy_is_verbatim.py`` then enforces.

Two modes:

    python tools/refresh_engine_copy.py            re-copy and rewrite the manifest
    python tools/refresh_engine_copy.py --check    verify the copy against the manifest

``--check`` needs no legacy checkout — it hashes what is committed here — so it
is what CI runs. The default mode needs the legacy tree and is how a deliberate
re-sync is performed.

``__init__.py`` is never copied: the legacy one was empty and ours installs the
``plugin_implementation`` compatibility alias. It is excluded from the manifest
for the same reason.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

SERVICE_ROOT = Path(__file__).resolve().parents[1]
ENGINE_DIR = SERVICE_ROOT / "src" / "elitea_deepwiki" / "engine"
MANIFEST = ENGINE_DIR / "COPY_MANIFEST.json"

#: ``methods/tool_operations.py`` is the tool layer: the real ``generate_wiki``
#: / ``ask`` / ``deep_research`` implementations, the subprocess and Job launch
#: paths, and the worker-slot accounting. It lives under ``methods/`` in the
#: legacy tree, so it looked like part of the Pylon shim — but it is not. It
#: needs exactly five things from the Pylon module (``invocation_thinking``,
#: ``invocation_stop_checkpoint``, ``invocation_process_add/remove``,
#: ``runtime_config``) and this service supplies all five.
#:
#: It cannot be copied byte for byte, because it imports Pylon at module scope
#: and decorates seven methods with ``@web.method()``. ADR-0022 decision 1 says
#: nothing of Pylon survives into the service, so rather than shipping a fake
#: ``pylon`` package to keep the copy literal, the two constructs are removed
#: by the declared substitutions below. They are mechanical and reproducible:
#: re-running this tool against the legacy source regenerates the file byte for
#: byte, and ``--check`` verifies both the transformed result AND the digest of
#: the source it was derived from.
TOOLS_SOURCE = "methods/tool_operations.py"
TOOLS_TARGET = SERVICE_ROOT / "src" / "elitea_deepwiki" / "tool_operations.py"

TOOLS_HEADER = '''# Copied from deepwiki_plugin methods/tool_operations.py.
#
# Generated by tools/refresh_engine_copy.py — do not edit by hand. Two declared
# substitutions are applied to the legacy source and nothing else:
#
#   0. Each subprocess launcher's child environment gains the artifact
#      source's platform credentials (elitea_deepwiki.artifact_source).
#   1. `from pylon.core.tools import log, web` becomes a stdlib logger.
#   2. The seven `@web.method()` decorators are removed.
#   3. `from ..plugin_implementation.` becomes `from .engine.` (5 sites).
#   4. The three subprocess worker module names become their real dotted
#      names in this package (3 sites).
#
# Both exist because ADR-0022 decision 1 keeps Pylon out of the service. The
# class below is otherwise the legacy `Method` mixin unchanged, and it binds to
# any host object providing runtime_config(), invocation_thinking(),
# invocation_stop_checkpoint() and invocation_process_add/remove() —
# see elitea_deepwiki.legacy_runner.ToolHost.
'''

#: Files transformed IN PLACE inside the engine tree. Unlike tool_operations.py
#: these cannot move: engine modules import them relatively
#: (``from .artifacts_platform_client import ...``), so relocating one would
#: break the copy. They are excluded from the verbatim digest set and recorded
#: under ``transformed_files`` instead, with the substitutions that produced
#: them, so the edit is auditable rather than invisible.
#:
#: ADR-0022 decision 6 is why this one is here: "the legacy X-SECRET
#: shared-string header is retired; no surface of the ported service sends or
#: honours it" and "TLS verification is mandatory on every outbound call.
#: verify=False does not appear in the ported code." Both were still true of
#: the copied client, which is a violation of the ADR in shipped code — found
#: by grepping the copy for the claim the README was making about it.
IN_PLACE_TRANSFORMS = {
    # ── A WIKI FROM AN ARTIFACT FOLDER ──
    #
    # The engine indexes a DIRECTORY, and the only way it could obtain one was
    # a clone: get_repository_local_path builds a GitCloneConfig, asks the
    # remote for its HEAD and runs `git clone`. A source that is a folder in
    # the project's artifact store has no remote and no HEAD, so it cannot
    # reach that code at all — and the entry point takes no local path, so
    # there is nowhere else to hand it one.
    #
    # Two early branches, and nothing else. Each returns before the git work
    # starts, so every existing provider keeps byte-identical behaviour; a
    # repository string that is not `artifact://…` cannot reach either.
    #
    #   1. get_repository_local_path materialises the folder instead of
    #      cloning it.
    #   2. get_repository_info answers for the materialised folder, which is
    #      not a git tree. WITHOUT THIS ONE the first branch is worse than
    #      useless: `git rev-parse HEAD` fails, the method returns its error
    #      dict with no commit_hash, and every generation of that folder keys
    #      its cache on the literal string "unknown" — so a CHANGED folder
    #      silently reuses the previous index and reports success.
    #
    # The materialiser itself is ours and unfrozen
    # (src/elitea_deepwiki/artifact_source.py); these two branches are only
    # the seam it attaches to.
    "local_repository_manager.py": (
        (
            "        # Build clone configuration using provider factory\n"
            "        clone_config = self._get_clone_config(repository_url, branch, project)",
            "        # An ARTIFACT FOLDER is a source too, and there is nothing to clone:\n"
            "        # elitea_deepwiki.artifact_source downloads the folder into the same\n"
            "        # cache directory a clone would have produced, and everything after\n"
            "        # this branch is unchanged. See that module for the identity, which\n"
            "        # is a sha256 over the listing where a clone has a commit sha.\n"
            "        from elitea_deepwiki.artifact_source import (\n"
            "            is_artifact_source,\n"
            "            materialise_artifact_source,\n"
            "        )\n"
            "\n"
            "        if is_artifact_source(repository_url):\n"
            "            local_path = materialise_artifact_source(\n"
            "                repository_url,\n"
            "                branch,\n"
            "                self.cache_dir,\n"
            "                force=force_reclone,\n"
            "            )\n"
            "            self.active_repos[f\"{repository_url}:{branch}\"] = local_path\n"
            "            return local_path\n"
            "\n"
            "        # Build clone configuration using provider factory\n"
            "        clone_config = self._get_clone_config(repository_url, branch, project)",
        ),
        (
            '    def get_repository_info(self, local_path: str) -> Dict[str, Any]:\n'
            '        """Get repository information from local clone"""\n'
            '        try:',
            '    def get_repository_info(self, local_path: str) -> Dict[str, Any]:\n'
            '        """Get repository information from local clone"""\n'
            '        # A materialised artifact folder is not a git tree. Its identity was\n'
            '        # recorded beside it when it was downloaded; answering from that\n'
            '        # record is what keeps the commit-shaped cache key content-derived.\n'
            '        from elitea_deepwiki.artifact_source import artifact_repository_info\n'
            '\n'
            '        artifact_info = artifact_repository_info(local_path)\n'
            '        if artifact_info is not None:\n'
            '            return artifact_info\n'
            '\n'
            '        try:',
        ),
    ),
    "artifacts_platform_client.py": (
        # The X-SECRET header, gone from every outbound artifact call. The
        # value it carried defaulted to the literal string "secret".
        (
            '        return {\n'
            '            "Authorization": f"Bearer {self.api_key}",\n'
            '            "X-SECRET": self.x_secret,\n'
            '        }',
            '        return {\n'
            '            "Authorization": f"Bearer {self.api_key}",\n'
            '        }',
        ),
        # TLS verification, on. _TLS_VERIFY is True by default and takes a CA
        # bundle path from the environment, because an internal mTLS mesh
        # signs with a private CA that the system trust store does not carry.
        (
            'DEFAULT_BUCKET = "wiki-artifacts"',
            'def _tls_verify():\n'
            '    """CA bundle path, or True for the system trust store."""\n'
            '    return os.environ.get("ELITEA_DEEPWIKI_TLS_CA_FILE") or True\n'
            '\n'
            '\n'
            'DEFAULT_BUCKET = "wiki-artifacts"',
        ),
        ("verify=False", "verify=_tls_verify()"),
        # ── issue #665: the client spoke routes elitea-main does not serve ──
        #
        # These run AFTER the three above and depend on them: two of them
        # match text the earlier substitutions produced (`verify=_tls_verify()`
        # in the upload call, and the `DEFAULT_BUCKET` line the TLS helper is
        # inserted before). Reordering this tuple breaks the chain, and the
        # tool fails loudly on the first needle it cannot find.
        # The routes this client speaks (#665). The legacy family is pylon's and
        # elitea-main serves no route in it, so every call was a 404 on the
        # target platform. This header block states the ones that exist.
        (
            "In ELITEA, all artifact storage goes through the platform's artifact endpoints:\\n"
            "    - Upload:   POST  /api/v2/artifacts/artifacts/default/{project_id}/{bucket}\\n"
            "    - Download: GET   /api/v2/artifacts/artifact/default/{project_id}/{bucket}/{name}\\n"
            "    - List:     GET   /api/v2/artifacts/artifacts/default/{project_id}/{bucket}\\n"
            "    - Delete:   DELETE /api/v2/artifacts/artifact/default/{project_id}/{bucket}/{name}\\n"
            "\\n"
            "The platform internally routes these to Minio/S3 with proper bucket prefixing,\\n"
            "access control, and project scoping.",
            "In ELITEA, all artifact storage goes through the platform's OBJECT endpoints:\\n"
            "    - Upload:   POST   /api/v2/artifacts/objects/{project_id}/{bucket}?overwrite=true\\n"
            "    - Download: GET    /api/v2/artifacts/objects/{project_id}/{bucket}/{key}\\n"
            "    - List:     GET    /api/v2/artifacts/objects/{project_id}/{bucket}?prefix=...\\n"
            "    - Delete:   DELETE /api/v2/artifacts/objects/{project_id}/{bucket}/{key}\\n"
            "\\n"
            "WHY THESE AND NOT THE ONES THIS FILE USED TO NAME (issue #665). The legacy\\n"
            "family \u2014 `/artifacts/artifacts/default/...` and `/artifacts/artifact/default/...`\\n"
            "\u2014 is implemented by pylon and by nothing else. elitea-main serves three object\\n"
            "families and that is not one of them, so on the standalone stack and on the Go\\n"
            "target platform every call above was a 404. It worked only where pylon was still\\n"
            "in the request path.\\n"
            "\\n"
            "The consequence was silent in the worst way: uploads failed, so no wiki content\\n"
            "ever reached the store the native UI reads, and the browser showed an empty list\\n"
            "that no screen could tell from \"you have not generated a wiki yet\".\\n"
            "\\n"
            "The platform internally routes these to Minio/S3 with proper bucket prefixing,\\n"
            "access control, and project scoping.",
        ),
        # The two URL builders. `/artifacts/artifacts/default/{p}/{b}` becomes
        # `/artifacts/objects/{p}/{b}`, and the single-object form loses the
        # `/default/` segment with it.
        (
            "    def _artifact_url(self, bucket: str) -> str:\\n"
            "        \"\"\"URL base for artifact operations (upload / list).\"\"\"\\n"
            "        bucket_segment = quote(str(bucket).lower(), safe=\"\")\\n"
            "        return (\\n"
            "            f\"{self.base_url}{self.api_path}/artifacts/artifacts\"\\n"
            "            f\"/default/{self.project_id}/{bucket_segment}\"\\n"
            "        )\\n"
            "\\n"
            "    def _single_artifact_url(self, bucket: str, name: str) -> str:\\n"
            "        \"\"\"URL for a specific artifact (download / delete).\"\"\"\\n"
            "        bucket_segment = quote(str(bucket).lower(), safe=\"\")\\n"
            "        name_segment = quote(str(name), safe=\"/\")\\n"
            "        return (\\n"
            "            f\"{self.base_url}{self.api_path}/artifacts/artifact\"\\n"
            "            f\"/default/{self.project_id}/{bucket_segment}/{name_segment}\"\\n"
            "        )",
            "    def _artifact_url(self, bucket: str) -> str:\\n"
            "        \"\"\"URL base for bucket-level operations (upload / list).\"\"\"\\n"
            "        bucket_segment = quote(str(bucket).lower(), safe=\"\")\\n"
            "        return (\\n"
            "            f\"{self.base_url}{self.api_path}/artifacts/objects\"\\n"
            "            f\"/{self.project_id}/{bucket_segment}\"\\n"
            "        )\\n"
            "\\n"
            "    def _single_artifact_url(self, bucket: str, name: str) -> str:\\n"
            "        \"\"\"URL for one object (download / delete).\\n"
            "\\n"
            "        `safe=\"/\"` is deliberate: a wiki key is multi-segment\\n"
            "        (``{wiki_id}/wiki_pages/{section}/{page}.md``) and the route declares\\n"
            "        that the key \"may itself contain `/` characters\". Escaping the\\n"
            "        separators would ask for one object whose name contains slashes,\\n"
            "        which does not exist.\\n"
            "        \"\"\"\\n"
            "        bucket_segment = quote(str(bucket).lower(), safe=\"\")\\n"
            "        name_segment = quote(str(name), safe=\"/\")\\n"
            "        return (\\n"
            "            f\"{self.base_url}{self.api_path}/artifacts/objects\"\\n"
            "            f\"/{self.project_id}/{bucket_segment}/{name_segment}\"\\n"
            "        )",
        ),
        # overwrite=true on upload. The object route answers 409 AlreadyExists by
        # default, and every caller here rewrites: a manifest on each
        # generation, a page on each edit.
        (
            "        files = {\"file\": (name, data)}\\n"
            "        response = requests.post(\\n"
            "            url, headers=self._headers(), files=files, verify=_tls_verify(), timeout=300\\n"
            "        )",
            "        # The KEY travels as the multipart filename, and the route reads the\\n"
            "        # raw Content-Disposition rather than filepath.Base, so a multi-segment\\n"
            "        # key survives.\\n"
            "        files = {\"file\": (name, data)}\\n"
            "        # overwrite=true, because every caller here re-uploads: a manifest is\\n"
            "        # rewritten on each generation and a page is rewritten on each edit.\\n"
            "        # The route's default is 409 AlreadyExists, which would turn the second\\n"
            "        # generation of any wiki into a failure.\\n"
            "        response = requests.post(\\n"
            "            url,\\n"
            "            headers=self._headers(),\\n"
            "            params={\"overwrite\": \"true\"},\\n"
            "            files=files,\\n"
            "            verify=_tls_verify(),\\n"
            "            timeout=300,\\n"
            "        )",
        ),
        # DELETE takes the key as a PATH segment. The legacy route took it as a
        # `filename` query parameter, which the object route ignores — a
        # delete sent that way would remove nothing and report success.
        (
            "    def _delete_artifact_url(self, bucket: str) -> str:\\n"
            "        \"\"\"URL for DELETE artifact (filename goes as query param).\"\"\"\\n"
            "        bucket_segment = quote(str(bucket).lower(), safe=\"\")\\n"
            "        return (\\n"
            "            f\"{self.base_url}{self.api_path}/artifacts/artifact\"\\n"
            "            f\"/default/{self.project_id}/{bucket_segment}\"\\n"
            "        )",
            "    def _delete_artifact_url(self, bucket: str, name: str) -> str:\\n"
            "        \"\"\"URL for DELETE object \u2014 the key is a PATH segment, not a query.\"\"\"\\n"
            "        return self._single_artifact_url(bucket, name)",
        ),
        # The delete call itself, following the builder above.
        (
            "        url = self._delete_artifact_url(bucket)\\n"
            "        logger.debug(\"Deleting artifact: %s/%s\", bucket, name)\\n"
            "\\n"
            "        response = requests.delete(\\n"
            "            url,\\n"
            "            headers=self._headers(),\\n"
            "            params={\"filename\": name},\\n"
            "            verify=_tls_verify(),\\n"
            "            timeout=60,\\n"
            "        )",
            "        url = self._delete_artifact_url(bucket, name)\\n"
            "        logger.debug(\"Deleting artifact: %s/%s\", bucket, name)\\n"
            "\\n"
            "        response = requests.delete(\\n"
            "            url,\\n"
            "            headers=self._headers(),\\n"
            "            verify=_tls_verify(),\\n"
            "            timeout=60,\\n"
            "        )",
        ),
        # The docstring that described the query-parameter route.
        (
            "        \"\"\"Delete a file from the platform bucket.\\n"
            "\\n"
            "        Platform DELETE endpoint expects filename as a query parameter,\\n"
            "        not as a path segment (unlike GET which uses path).\\n"
            "\\n"
            "        Raises:",
            "        \"\"\"Delete a file from the platform bucket.\\n"
            "\\n"
            "        Raises:",
        ),
        # The listing: a different response shape (`objects` / `key` / `size_bytes`
        # / `modified_at`, not `rows` / `name` / `size`), a SERVER-side prefix,
        # and cursor paging. Reading only the first page would show a wiki
        # with most of its pages missing.
        (
            "        url = self._artifact_url(bucket)\\n"
            "        logger.debug(\"Listing artifacts in bucket %s (prefix=%s)\", bucket, prefix)\\n"
            "\\n"
            "        response = requests.get(\\n"
            "            url, headers=self._headers(), verify=_tls_verify(), timeout=60\\n"
            "        )\\n"
            "\\n"
            "        if response.status_code == 404:\\n"
            "            return []\\n"
            "        if response.status_code != 200:\\n"
            "            logger.warning(\"List artifacts returned HTTP %d\", response.status_code)\\n"
            "            return []\\n"
            "\\n"
            "        try:\\n"
            "            data = response.json()\\n"
            "            # Platform response may be a list directly or wrapped in a key\\n"
            "            if isinstance(data, list):\\n"
            "                items = data\\n"
            "            elif isinstance(data, dict):\\n"
            "                items = data.get(\"rows\", data.get(\"items\", []))\\n"
            "            else:\\n"
            "                items = []\\n"
            "\\n"
            "            result = []\\n"
            "            for item in items:\\n"
            "                name = item.get(\"name\", item.get(\"file_name\", \"\"))\\n"
            "                if prefix and not name.startswith(prefix):\\n"
            "                    continue\\n"
            "                result.append({\\n"
            "                    \"name\": name,\\n"
            "                    \"size\": item.get(\"size\", 0),\\n"
            "                    \"modified\": item.get(\"modified\", item.get(\"upload_date\", \"\")),\\n"
            "                })\\n"
            "            return result\\n"
            "        except Exception as e:\\n"
            "            logger.warning(\"Failed to parse artifact list: %s\", e)\\n"
            "            return []",
            "        url = self._artifact_url(bucket)\\n"
            "        logger.debug(\"Listing artifacts in bucket %s (prefix=%s)\", bucket, prefix)\\n"
            "\\n"
            "        result: List[Dict[str, Any]] = []\\n"
            "        # The listing is PAGED, and a caller that reads only the first page sees\\n"
            "        # a wiki with most of its pages missing rather than an error. A wiki of\\n"
            "        # any size exceeds one page.\\n"
            "        cursor = \"\"\\n"
            "        for _ in range(MAX_LIST_PAGES):\\n"
            "            params: Dict[str, str] = {}\\n"
            "            # The prefix is applied SERVER-SIDE. Filtering after the fact\\n"
            "            # would page through the whole bucket to find one wiki's files.\\n"
            "            if prefix:\\n"
            "                params[\"prefix\"] = prefix\\n"
            "            if cursor:\\n"
            "                params[\"cursor\"] = cursor\\n"
            "\\n"
            "            response = requests.get(\\n"
            "                url,\\n"
            "                headers=self._headers(),\\n"
            "                params=params or None,\\n"
            "                verify=_tls_verify(),\\n"
            "                timeout=60,\\n"
            "            )\\n"
            "\\n"
            "            if response.status_code == 404:\\n"
            "                return result\\n"
            "            if response.status_code != 200:\\n"
            "                logger.warning(\"List artifacts returned HTTP %d\", response.status_code)\\n"
            "                return result\\n"
            "\\n"
            "            try:\\n"
            "                data = response.json()\\n"
            "            except Exception as exc:\\n"
            "                logger.warning(\"Failed to parse artifact list: %s\", exc)\\n"
            "                return result\\n"
            "\\n"
            "            if not isinstance(data, dict):\\n"
            "                logger.warning(\"Artifact listing was not an object: %r\", type(data))\\n"
            "                return result\\n"
            "\\n"
            "            for item in data.get(\"objects\") or []:\\n"
            "                if not isinstance(item, dict):\\n"
            "                    continue\\n"
            "                result.append({\\n"
            "                    \"name\": item.get(\"key\", \"\"),\\n"
            "                    \"size\": item.get(\"size_bytes\", 0),\\n"
            "                    \"modified\": item.get(\"modified_at\", \"\"),\\n"
            "                })\\n"
            "\\n"
            "            # Omitted when the listing is exhausted.\\n"
            "            cursor = data.get(\"next_cursor\") or \"\"\\n"
            "            if not cursor:\\n"
            "                return result\\n"
            "\\n"
            "        logger.warning(\\n"
            "            \"Artifact listing for bucket %s stopped at the %d-page ceiling; \"\\n"
            "            \"results are incomplete\",\\n"
            "            bucket, MAX_LIST_PAGES,\\n"
            "        )\\n"
            "        return result",
        ),
        # The page ceiling the loop above needs.
        (
            "DEFAULT_BUCKET = \"wiki-artifacts\"",
            "# A ceiling on the paging loop above, not a page size. It exists so a server\\n"
            "# that echoed a cursor for ever could not hang a generation; it is logged when\\n"
            "# hit, because a silently truncated listing is a wiki missing pages.\\n"
            "MAX_LIST_PAGES = 1000\\n"
            "\\n"
            "DEFAULT_BUCKET = \"wiki-artifacts\"",
        ),
    ),
}

TOOLS_SUBSTITUTIONS = (
    # The artifact source's platform credentials, placed in the CHILD's
    # environment rather than the server's. A worker process serves one
    # invocation; the server process serves several at once, so a bearer
    # written into os.environ would let one invocation read a folder with
    # another invocation's token. child_environment() returns nothing at all
    # unless this payload's own source is an `artifact://` folder.
    #
    # All three subprocess launchers take the same `payload` parameter and
    # build their child environment with the same two lines, so one
    # substitution covers generate_wiki, ask and deep_research.
    (
        '        env = os.environ.copy()\n        env["PYTHONUNBUFFERED"] = "1"',
        '        env = os.environ.copy()\n'
        '        env["PYTHONUNBUFFERED"] = "1"\n'
        '        from .artifact_source import child_environment\n'
        '        env.update(child_environment(payload))',
    ),
    (
        "from pylon.core.tools import log, web",
        "import logging\n\nlog = logging.getLogger(__name__)",
    ),
    ("    @web.method()\n", ""),
    # The legacy file sat at deepwiki_plugin/methods/, so `..` reached the
    # plugin root and `..plugin_implementation` was the engine. Here it sits at
    # elitea_deepwiki/, one level higher, and `..` escapes the package. Found
    # by running generate_wiki, not by reading: the import is inside a function
    # a third of the way through the tool.
    ("from ..plugin_implementation.", "from .engine."),
    # The subprocess launcher picks a worker module name by trying to import
    # each candidate IN THE PARENT, then hands the winner to a child that only
    # gets the parent's sys.path. In the parent, "plugin_implementation.X"
    # imports fine — the engine package installs that alias — but the child
    # never imports the engine package, so the alias does not exist there and
    # the name is unresolvable. Naming the real module makes the child import
    # something sys.path can actually find, and importing it installs the alias
    # for the engine's own absolute imports. Diagnosed by running the
    # subprocess path and reading the worker log:
    #   ModuleNotFoundError: No module named 'plugin_implementation'
    ('"plugin_implementation.wiki_subprocess_worker"', '"elitea_deepwiki.engine.wiki_subprocess_worker"'),
    ('"plugin_implementation.ask_subprocess_worker"', '"elitea_deepwiki.engine.ask_subprocess_worker"'),
    ('"plugin_implementation.deep_research_subprocess_worker"', '"elitea_deepwiki.engine.deep_research_subprocess_worker"'),
)

#: Owned by this repository, not copied. These are RELATIVE PATHS, not bare
#: names: the engine has eight subpackage ``__init__.py`` files that ARE part
#: of the copy, and matching on the name alone would silently drop every one of
#: them from the manifest — leaving them unguarded while the count still looked
#: plausible.
NOT_COPIED = {"__init__.py", "COPY_MANIFEST.json"}

LEGACY_ENV_VAR = "DEEPWIKI_LEGACY_ROOT"
_DEFAULT_CANDIDATES = (
    "projects/eliteaai/legacy/plugins/deepwiki_plugin",
    "eliteaai/legacy/plugins/deepwiki_plugin",
)


def legacy_root() -> Path:
    import os

    override = os.environ.get(LEGACY_ENV_VAR)
    if override:
        path = Path(override).expanduser().resolve()
        if (path / "plugin_implementation").is_dir():
            return path
        raise SystemExit(f"{LEGACY_ENV_VAR}={path} is not a deepwiki_plugin checkout")

    for candidate in _DEFAULT_CANDIDATES:
        path = (Path.home() / candidate).resolve()
        if (path / "plugin_implementation").is_dir():
            return path

    raise SystemExit(
        f"deepwiki_plugin checkout not found; set {LEGACY_ENV_VAR} "
        "(read-only access is enough)"
    )


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(65536), b""):
            digest.update(block)
    return digest.hexdigest()


def copied_files() -> list[Path]:
    """Every file the manifest covers, relative to the engine directory."""
    return sorted(
        path
        for path in ENGINE_DIR.rglob("*")
        if path.is_file()
        and "__pycache__" not in path.parts
        and path.relative_to(ENGINE_DIR).as_posix() not in NOT_COPIED
        and path.relative_to(ENGINE_DIR).as_posix() not in IN_PLACE_TRANSFORMS
    )


def transform_tools(source_text: str) -> str:
    """Apply the declared substitutions to the tool layer's source."""
    text = source_text
    for needle, replacement in TOOLS_SUBSTITUTIONS:
        if needle not in text:
            raise SystemExit(
                f"tool_operations.py no longer contains {needle!r}; the "
                "declared substitutions are stale and must be reviewed"
            )
        text = text.replace(needle, replacement)
    return TOOLS_HEADER + text


def build_manifest(revision: str | None) -> dict:
    entries = {}
    for path in copied_files():
        relative = path.relative_to(ENGINE_DIR).as_posix()
        entries[relative] = {"bytes": path.stat().st_size, "sha256": sha256(path)}

    transformed = {}
    for relative, substitutions in IN_PLACE_TRANSFORMS.items():
        target = ENGINE_DIR / relative
        if not target.is_file():
            continue
        transformed[f"plugin_implementation/{relative}"] = {
            "target": target.relative_to(SERVICE_ROOT).as_posix(),
            "bytes": target.stat().st_size,
            "sha256": sha256(target),
            "in_place": True,
            "substitutions": [
                {"from": needle, "to": replacement}
                for needle, replacement in substitutions
            ],
        }

    if TOOLS_TARGET.is_file():
        transformed[TOOLS_SOURCE] = {
            "target": TOOLS_TARGET.relative_to(SERVICE_ROOT).as_posix(),
            "bytes": TOOLS_TARGET.stat().st_size,
            "sha256": sha256(TOOLS_TARGET),
            "substitutions": [
                {"from": needle, "to": replacement}
                for needle, replacement in TOOLS_SUBSTITUTIONS
            ],
        }

    return {
        "source_repository": "deepwiki_plugin",
        "source_path": "plugin_implementation",
        "source_revision": revision,
        "file_count": len(entries),
        "total_bytes": sum(entry["bytes"] for entry in entries.values()),
        "not_copied": sorted(NOT_COPIED),
        "files": entries,
        "transformed_files": transformed,
    }


def do_copy() -> str | None:
    root = legacy_root()
    source = root / "plugin_implementation"

    try:
        revision = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        revision = None

    keep = {}
    for name in NOT_COPIED:
        path = ENGINE_DIR / name
        if path.is_file():
            keep[name] = path.read_bytes()

    if ENGINE_DIR.exists():
        shutil.rmtree(ENGINE_DIR)
    shutil.copytree(
        source, ENGINE_DIR, ignore=shutil.ignore_patterns("__pycache__", "*.pyc")
    )

    for name in NOT_COPIED:
        target = ENGINE_DIR / name
        if name in keep:
            target.write_bytes(keep[name])
        elif target.is_file():
            target.unlink()

    TOOLS_TARGET.write_text(
        transform_tools((root / TOOLS_SOURCE).read_text(encoding="utf-8")),
        encoding="utf-8",
    )

    for relative, substitutions in IN_PLACE_TRANSFORMS.items():
        target = ENGINE_DIR / relative
        text = target.read_text(encoding="utf-8")
        for needle, replacement in substitutions:
            if needle not in text:
                raise SystemExit(
                    f"{relative} no longer contains {needle!r}; the declared "
                    "in-place substitutions are stale and must be reviewed"
                )
            text = text.replace(needle, replacement)
        target.write_text(text, encoding="utf-8")

    return revision


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed copy against the manifest (no legacy checkout needed)",
    )
    args = parser.parse_args()

    if args.check:
        if not MANIFEST.is_file():
            print(f"{MANIFEST} is missing", file=sys.stderr)
            return 1
        manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
        current = build_manifest(manifest.get("source_revision"))

        if current.get("transformed_files") != manifest.get("transformed_files"):
            print(
                "  modified: the transformed tool layer no longer matches its "
                "manifest entry",
                file=sys.stderr,
            )
            return 1

        if current["files"] == manifest["files"]:
            print(f"engine copy is verbatim ({current['file_count']} files)")
            return 0

        expected = set(manifest["files"])
        present = set(current["files"])
        for name in sorted(present - expected):
            print(f"  extra:    {name}", file=sys.stderr)
        for name in sorted(expected - present):
            print(f"  missing:  {name}", file=sys.stderr)
        for name in sorted(expected & present):
            if manifest["files"][name] != current["files"][name]:
                print(f"  modified: {name}", file=sys.stderr)
        return 1

    revision = do_copy()
    manifest = build_manifest(revision)
    MANIFEST.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(
        f"copied {manifest['file_count']} files "
        f"({manifest['total_bytes']} bytes) from {revision}, "
        f"plus {len(manifest['transformed_files'])} transformed"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
