// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_static_pause.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const resolveCurrentStaticContinuation = `-- name: ResolveCurrentStaticContinuation :one
SELECT conversation.uuid AS conversation_uuid,
       question.uuid AS question_id,
       response.author_participant_id AS target_participant_id,
       question_text.content::text AS user_input,
       COALESCE((response.meta -> 'pipeline_static_v1')::text, '')::text AS static_pause_json,
       COALESCE(response.meta ->> 'thread_id', '')::text AS thread_id,
       COALESCE(response.meta ->> 'execution_generation', '')::text AS execution_generation,
       entry.content_bytes, entry.content_digest
FROM chat_message_group AS response
JOIN chat_conversations AS conversation ON conversation.id = response.conversation_id
JOIN chat_message_group AS question
  ON question.id = response.reply_to_id AND question.conversation_id = conversation.id
JOIN chat_participants AS question_author
  ON question_author.id = question.author_participant_id AND question_author.entity_name = 'user'
JOIN chat_participants AS response_author
  ON response_author.id = response.author_participant_id AND response_author.entity_name = 'application'
JOIN chat_participant_mapping AS actor_mapping ON actor_mapping.conversation_id = conversation.id
JOIN chat_participants AS actor_participant
  ON actor_participant.id = actor_mapping.participant_id AND actor_participant.entity_name = 'user'
 AND (actor_participant.entity_meta ->> 'id')::bigint = $1::bigint
JOIN LATERAL (
    SELECT text_item.content FROM chat_message_items AS item
    JOIN chat_messages_text AS text_item ON text_item.id = item.id
    WHERE item.message_group_id = question.id AND item.item_type = 'text_message'
    ORDER BY item.order_index DESC, item.id DESC LIMIT 1
) AS question_text ON TRUE
JOIN elitea_runtime.execution_jobs AS job
  ON job.execution_id = response.task_id
 AND job.tenant_id = $2::integer::text
 AND job.resource_project_id = $2::integer
 AND job.projection_project_id = $2::integer
 AND job.actor_id = $1::bigint::text
 AND job.capability_id = 'agent.execute.application.v1'
JOIN elitea_runtime.agent_execution_jobs AS binding
  ON binding.execution_id = job.execution_id AND binding.generation = job.generation
 AND binding.input_bundle_id = job.input_bundle_id
 AND binding.client_stream_id = conversation.uuid::text
 AND binding.client_message_id = response.uuid::text
 AND binding.client_execution_generation = response.meta ->> 'execution_generation'
JOIN elitea_runtime.input_bundle_entries AS entry
  ON entry.input_bundle_id = job.input_bundle_id AND entry.entry_id = binding.request_entry_id
 AND entry.semantic_role = 'agent.execution_request'
WHERE conversation.uuid = $3::uuid
  AND response.uuid = $4::uuid
  AND NOT response.is_streaming
  AND (conversation.author_id = $1::bigint
       OR (question_author.entity_meta ->> 'id')::bigint = $1::bigint)
  AND (response_author.entity_meta ->> 'project_id')::integer = $2::integer
  AND jsonb_typeof(response.meta -> 'pipeline_static_v1') = 'object'
  AND COALESCE(response.meta ->> 'thread_id', '') <> ''
  AND COALESCE(response.meta ->> 'execution_generation', '') <> ''
  AND NOT (response.meta ? 'hitl_interrupt') AND NOT (response.meta ? 'hitl_interrupts')
  AND NOT (response.meta ? 'authorization_requests') AND NOT (response.meta ? 'output_limit_reached')
`

type ResolveCurrentStaticContinuationParams struct {
	ActorUserID       int64       `db:"actor_user_id" json:"actor_user_id"`
	ProjectID         int32       `db:"project_id" json:"project_id"`
	ConversationUuid  pgtype.UUID `db:"conversation_uuid" json:"conversation_uuid"`
	ResponseMessageID pgtype.UUID `db:"response_message_id" json:"response_message_id"`
}

type ResolveCurrentStaticContinuationRow struct {
	ConversationUuid    pgtype.UUID `db:"conversation_uuid" json:"conversation_uuid"`
	QuestionID          pgtype.UUID `db:"question_id" json:"question_id"`
	TargetParticipantID int32       `db:"target_participant_id" json:"target_participant_id"`
	UserInput           string      `db:"user_input" json:"user_input"`
	StaticPauseJson     string      `db:"static_pause_json" json:"static_pause_json"`
	ThreadID            string      `db:"thread_id" json:"thread_id"`
	ExecutionGeneration string      `db:"execution_generation" json:"execution_generation"`
	ContentBytes        []byte      `db:"content_bytes" json:"content_bytes"`
	ContentDigest       []byte      `db:"content_digest" json:"content_digest"`
}

// Static pauses use the original command input and exact persisted response.
// Checkpoint state stays in the worker; this query carries only its public proof.
func (q *Queries) ResolveCurrentStaticContinuation(ctx context.Context, arg ResolveCurrentStaticContinuationParams) (ResolveCurrentStaticContinuationRow, error) {
	row := q.db.QueryRow(ctx, resolveCurrentStaticContinuation,
		arg.ActorUserID,
		arg.ProjectID,
		arg.ConversationUuid,
		arg.ResponseMessageID,
	)
	var i ResolveCurrentStaticContinuationRow
	err := row.Scan(
		&i.ConversationUuid,
		&i.QuestionID,
		&i.TargetParticipantID,
		&i.UserInput,
		&i.StaticPauseJson,
		&i.ThreadID,
		&i.ExecutionGeneration,
		&i.ContentBytes,
		&i.ContentDigest,
	)
	return i, err
}

const resolveCurrentStaticToolContinuation = `-- name: ResolveCurrentStaticToolContinuation :one
SELECT conversation.uuid AS conversation_uuid,
       question.uuid AS question_id,
       response.author_participant_id AS target_participant_id,
       question_text.content::text AS user_input,
       COALESCE((response.meta -> 'pipeline_static_tools_v1')::text, '')::text AS static_tools_json,
       COALESCE(response.meta ->> 'thread_id', '')::text AS thread_id,
       COALESCE(response.meta ->> 'execution_generation', '')::text AS execution_generation,
       entry.content_bytes, entry.content_digest
FROM chat_message_group AS response
JOIN chat_conversations AS conversation ON conversation.id = response.conversation_id
JOIN chat_message_group AS question
  ON question.id = response.reply_to_id AND question.conversation_id = conversation.id
JOIN chat_participants AS question_author
  ON question_author.id = question.author_participant_id AND question_author.entity_name = 'user'
JOIN chat_participants AS response_author
  ON response_author.id = response.author_participant_id AND response_author.entity_name = 'application'
JOIN chat_participant_mapping AS actor_mapping ON actor_mapping.conversation_id = conversation.id
JOIN chat_participants AS actor_participant
  ON actor_participant.id = actor_mapping.participant_id AND actor_participant.entity_name = 'user'
 AND (actor_participant.entity_meta ->> 'id')::bigint = $1::bigint
JOIN LATERAL (
    SELECT text_item.content FROM chat_message_items AS item
    JOIN chat_messages_text AS text_item ON text_item.id = item.id
    WHERE item.message_group_id = question.id AND item.item_type = 'text_message'
    ORDER BY item.order_index DESC, item.id DESC LIMIT 1
) AS question_text ON TRUE
JOIN elitea_runtime.execution_jobs AS job
  ON job.execution_id = response.task_id
 AND job.tenant_id = $2::integer::text
 AND job.resource_project_id = $2::integer
 AND job.projection_project_id = $2::integer
 AND job.actor_id = $1::bigint::text
 AND job.capability_id = 'agent.execute.application.v1'
JOIN elitea_runtime.agent_execution_jobs AS binding
  ON binding.execution_id = job.execution_id AND binding.generation = job.generation
 AND binding.input_bundle_id = job.input_bundle_id
 AND binding.client_stream_id = conversation.uuid::text
 AND binding.client_message_id = response.uuid::text
 AND binding.client_execution_generation = response.meta ->> 'execution_generation'
JOIN elitea_runtime.input_bundle_entries AS entry
  ON entry.input_bundle_id = job.input_bundle_id AND entry.entry_id = binding.request_entry_id
 AND entry.semantic_role = 'agent.execution_request'
WHERE conversation.uuid = $3::uuid
  AND response.uuid = $4::uuid
  AND NOT response.is_streaming
  AND (conversation.author_id = $1::bigint
       OR (question_author.entity_meta ->> 'id')::bigint = $1::bigint)
  AND (response_author.entity_meta ->> 'project_id')::integer = $2::integer
  AND jsonb_typeof(response.meta -> 'pipeline_static_tools_v1') = 'object'
  AND COALESCE(response.meta ->> 'thread_id', '') <> ''
  AND COALESCE(response.meta ->> 'execution_generation', '') <> ''
  AND NOT (response.meta ? 'output_limit_reached')
`

type ResolveCurrentStaticToolContinuationParams struct {
	ActorUserID       int64       `db:"actor_user_id" json:"actor_user_id"`
	ProjectID         int32       `db:"project_id" json:"project_id"`
	ConversationUuid  pgtype.UUID `db:"conversation_uuid" json:"conversation_uuid"`
	ResponseMessageID pgtype.UUID `db:"response_message_id" json:"response_message_id"`
}

type ResolveCurrentStaticToolContinuationRow struct {
	ConversationUuid    pgtype.UUID `db:"conversation_uuid" json:"conversation_uuid"`
	QuestionID          pgtype.UUID `db:"question_id" json:"question_id"`
	TargetParticipantID int32       `db:"target_participant_id" json:"target_participant_id"`
	UserInput           string      `db:"user_input" json:"user_input"`
	StaticToolsJson     string      `db:"static_tools_json" json:"static_tools_json"`
	ThreadID            string      `db:"thread_id" json:"thread_id"`
	ExecutionGeneration string      `db:"execution_generation" json:"execution_generation"`
	ContentBytes        []byte      `db:"content_bytes" json:"content_bytes"`
	ContentDigest       []byte      `db:"content_digest" json:"content_digest"`
}

// Static pauses use the original command input and exact persisted response.
// Checkpoint state stays in the worker; this query carries only its public proof.
func (q *Queries) ResolveCurrentStaticToolContinuation(ctx context.Context, arg ResolveCurrentStaticToolContinuationParams) (ResolveCurrentStaticToolContinuationRow, error) {
	row := q.db.QueryRow(ctx, resolveCurrentStaticToolContinuation,
		arg.ActorUserID,
		arg.ProjectID,
		arg.ConversationUuid,
		arg.ResponseMessageID,
	)
	var i ResolveCurrentStaticToolContinuationRow
	err := row.Scan(
		&i.ConversationUuid,
		&i.QuestionID,
		&i.TargetParticipantID,
		&i.UserInput,
		&i.StaticToolsJson,
		&i.ThreadID,
		&i.ExecutionGeneration,
		&i.ContentBytes,
		&i.ContentDigest,
	)
	return i, err
}

const resumeCurrentAgentStatic = `-- name: ResumeCurrentAgentStatic :one
WITH resolved AS MATERIALIZED (
    SELECT response.id, response.uuid
    FROM chat_message_group AS response
    JOIN chat_conversations AS conversation ON conversation.id = response.conversation_id
    JOIN chat_message_group AS question
      ON question.id = response.reply_to_id AND question.conversation_id = conversation.id
    JOIN chat_participants AS question_author
      ON question_author.id = question.author_participant_id AND question_author.entity_name = 'user'
    JOIN chat_participants AS response_author
      ON response_author.id = response.author_participant_id
     AND response_author.id = $1::integer
     AND response_author.entity_name = 'application'
    JOIN chat_participant_mapping AS actor_mapping ON actor_mapping.conversation_id = conversation.id
    JOIN chat_participants AS actor_participant
      ON actor_participant.id = actor_mapping.participant_id AND actor_participant.entity_name = 'user'
     AND (actor_participant.entity_meta ->> 'id')::bigint = $2::bigint
    JOIN chat_participant_mapping AS application_mapping
      ON application_mapping.conversation_id = conversation.id AND application_mapping.participant_id = response_author.id
    JOIN application_versions AS application_version
      ON application_version.id = $3::integer
     AND application_version.id = (application_mapping.entity_settings ->> 'version_id')::integer
     AND application_version.application_id = $4::integer
     AND application_version.application_id = (response_author.entity_meta ->> 'id')::integer
    JOIN elitea_runtime.execution_jobs AS job
      ON job.execution_id = response.task_id AND job.tenant_id = $5::integer::text
     AND job.resource_project_id = $5::integer AND job.projection_project_id = $5::integer
     AND job.actor_id = $2::bigint::text AND job.capability_id = 'agent.execute.application.v1'
    JOIN elitea_runtime.agent_execution_jobs AS binding
      ON binding.execution_id = job.execution_id AND binding.generation = job.generation
     AND binding.input_bundle_id = job.input_bundle_id AND binding.client_stream_id = conversation.uuid::text
     AND binding.client_message_id = response.uuid::text AND binding.client_execution_generation = $6::text
    JOIN elitea_runtime.input_bundle_entries AS entry
      ON entry.input_bundle_id = job.input_bundle_id AND entry.entry_id = binding.request_entry_id
     AND entry.semantic_role = 'agent.execution_request' AND entry.content_digest = $7::bytea
    WHERE conversation.uuid = $8::uuid AND response.uuid = $9::uuid
      AND question.uuid = $10::uuid AND NOT response.is_streaming
      AND response.meta -> 'pipeline_static_v1' = $11::jsonb
      AND response.meta ->> 'execution_generation' = $6::text
      AND response.meta ->> 'thread_id' = $12::text
      AND NOT (response.meta ? 'hitl_interrupt') AND NOT (response.meta ? 'hitl_interrupts')
      AND NOT (response.meta ? 'authorization_requests') AND NOT (response.meta ? 'output_limit_reached')
      AND (conversation.author_id = $2::bigint
           OR (question_author.entity_meta ->> 'id')::bigint = $2::bigint)
      AND (response_author.entity_meta ->> 'project_id')::integer = $5::integer
    FOR UPDATE OF response
), updated AS (
    UPDATE chat_message_group AS response
    SET meta = response.meta - 'pipeline_static_v1', is_streaming = TRUE,
        task_id = $13::text, updated_at = clock_timestamp()
    FROM resolved WHERE response.id = resolved.id RETURNING response.id, response.uuid
)
SELECT updated.id AS response_message_group_id, updated.uuid AS response_message_id FROM updated
`

type ResumeCurrentAgentStaticParams struct {
	TargetParticipantID  int32       `db:"target_participant_id" json:"target_participant_id"`
	ActorUserID          int64       `db:"actor_user_id" json:"actor_user_id"`
	ApplicationVersionID int32       `db:"application_version_id" json:"application_version_id"`
	ApplicationID        int32       `db:"application_id" json:"application_id"`
	ProjectID            int32       `db:"project_id" json:"project_id"`
	ExecutionGeneration  string      `db:"execution_generation" json:"execution_generation"`
	InputDigest          []byte      `db:"input_digest" json:"input_digest"`
	ConversationUuid     pgtype.UUID `db:"conversation_uuid" json:"conversation_uuid"`
	ResponseMessageID    pgtype.UUID `db:"response_message_id" json:"response_message_id"`
	QuestionID           pgtype.UUID `db:"question_id" json:"question_id"`
	StaticPauseJson      []byte      `db:"static_pause_json" json:"static_pause_json"`
	ThreadID             string      `db:"thread_id" json:"thread_id"`
	ExecutionID          string      `db:"execution_id" json:"execution_id"`
}

type ResumeCurrentAgentStaticRow struct {
	ResponseMessageGroupID int32       `db:"response_message_group_id" json:"response_message_group_id"`
	ResponseMessageID      pgtype.UUID `db:"response_message_id" json:"response_message_id"`
}

func (q *Queries) ResumeCurrentAgentStatic(ctx context.Context, arg ResumeCurrentAgentStaticParams) (ResumeCurrentAgentStaticRow, error) {
	row := q.db.QueryRow(ctx, resumeCurrentAgentStatic,
		arg.TargetParticipantID,
		arg.ActorUserID,
		arg.ApplicationVersionID,
		arg.ApplicationID,
		arg.ProjectID,
		arg.ExecutionGeneration,
		arg.InputDigest,
		arg.ConversationUuid,
		arg.ResponseMessageID,
		arg.QuestionID,
		arg.StaticPauseJson,
		arg.ThreadID,
		arg.ExecutionID,
	)
	var i ResumeCurrentAgentStaticRow
	err := row.Scan(&i.ResponseMessageGroupID, &i.ResponseMessageID)
	return i, err
}

const resumeCurrentAgentStaticTools = `-- name: ResumeCurrentAgentStaticTools :one
WITH resolved AS MATERIALIZED (
    SELECT response.id, response.uuid
    FROM chat_message_group AS response
    JOIN chat_conversations AS conversation ON conversation.id = response.conversation_id
    JOIN chat_message_group AS question
      ON question.id = response.reply_to_id AND question.conversation_id = conversation.id
    JOIN chat_participants AS question_author
      ON question_author.id = question.author_participant_id AND question_author.entity_name = 'user'
    JOIN chat_participants AS response_author
      ON response_author.id = response.author_participant_id
     AND response_author.id = $1::integer
     AND response_author.entity_name = 'application'
    JOIN chat_participant_mapping AS actor_mapping ON actor_mapping.conversation_id = conversation.id
    JOIN chat_participants AS actor_participant
      ON actor_participant.id = actor_mapping.participant_id AND actor_participant.entity_name = 'user'
     AND (actor_participant.entity_meta ->> 'id')::bigint = $2::bigint
    JOIN chat_participant_mapping AS application_mapping
      ON application_mapping.conversation_id = conversation.id AND application_mapping.participant_id = response_author.id
    JOIN application_versions AS application_version
      ON application_version.id = $3::integer
     AND application_version.id = (application_mapping.entity_settings ->> 'version_id')::integer
     AND application_version.application_id = $4::integer
     AND application_version.application_id = (response_author.entity_meta ->> 'id')::integer
    JOIN elitea_runtime.execution_jobs AS job
      ON job.execution_id = response.task_id AND job.tenant_id = $5::integer::text
     AND job.resource_project_id = $5::integer AND job.projection_project_id = $5::integer
     AND job.actor_id = $2::bigint::text AND job.capability_id = 'agent.execute.application.v1'
    JOIN elitea_runtime.agent_execution_jobs AS binding
      ON binding.execution_id = job.execution_id AND binding.generation = job.generation
     AND binding.input_bundle_id = job.input_bundle_id AND binding.client_stream_id = conversation.uuid::text
     AND binding.client_message_id = response.uuid::text AND binding.client_execution_generation = $6::text
    JOIN elitea_runtime.input_bundle_entries AS entry
      ON entry.input_bundle_id = job.input_bundle_id AND entry.entry_id = binding.request_entry_id
     AND entry.semantic_role = 'agent.execution_request' AND entry.content_digest = $7::bytea
    WHERE conversation.uuid = $8::uuid AND response.uuid = $9::uuid
      AND question.uuid = $10::uuid AND NOT response.is_streaming
      AND response.meta -> 'pipeline_static_tools_v1' = $11::jsonb
      AND jsonb_typeof($12::jsonb) = 'array'
      AND jsonb_array_length($12::jsonb) BETWEEN 1 AND 16
      AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements($12::jsonb) AS selected(value)
          WHERE NOT EXISTS (SELECT 1 FROM jsonb_array_elements(response.meta -> 'pipeline_static_tools_v1' -> 'pauses') AS pause(value)
              WHERE pause.value -> 'proof' -> 'pause_id' = selected.value))
      AND response.meta ->> 'execution_generation' = $6::text
      AND response.meta ->> 'thread_id' = $13::text
      AND NOT (response.meta ? 'output_limit_reached')
      AND (conversation.author_id = $2::bigint
           OR (question_author.entity_meta ->> 'id')::bigint = $2::bigint)
      AND (response_author.entity_meta ->> 'project_id')::integer = $5::integer
    FOR UPDATE OF response
), updated AS (
    UPDATE chat_message_group AS response
    SET meta = (response.meta - 'pipeline_static_tools_v1') || CASE
        WHEN EXISTS (SELECT 1 FROM jsonb_array_elements(response.meta -> 'pipeline_static_tools_v1' -> 'pauses') AS pause(value)
            WHERE NOT ($12::jsonb @> jsonb_build_array(pause.value -> 'proof' -> 'pause_id')))
        THEN jsonb_build_object('pipeline_static_tools_v1', (response.meta -> 'pipeline_static_tools_v1') || jsonb_build_object('pauses',
            (SELECT jsonb_agg(pause.value ORDER BY pause.ordinality) FROM jsonb_array_elements(response.meta -> 'pipeline_static_tools_v1' -> 'pauses') WITH ORDINALITY AS pause(value, ordinality)
             WHERE NOT ($12::jsonb @> jsonb_build_array(pause.value -> 'proof' -> 'pause_id')))))
        ELSE '{}'::jsonb END, is_streaming = TRUE,
        task_id = $14::text, updated_at = clock_timestamp()
    FROM resolved WHERE response.id = resolved.id RETURNING response.id, response.uuid
)
SELECT updated.id AS response_message_group_id, updated.uuid AS response_message_id FROM updated
`

type ResumeCurrentAgentStaticToolsParams struct {
	TargetParticipantID  int32       `db:"target_participant_id" json:"target_participant_id"`
	ActorUserID          int64       `db:"actor_user_id" json:"actor_user_id"`
	ApplicationVersionID int32       `db:"application_version_id" json:"application_version_id"`
	ApplicationID        int32       `db:"application_id" json:"application_id"`
	ProjectID            int32       `db:"project_id" json:"project_id"`
	ExecutionGeneration  string      `db:"execution_generation" json:"execution_generation"`
	InputDigest          []byte      `db:"input_digest" json:"input_digest"`
	ConversationUuid     pgtype.UUID `db:"conversation_uuid" json:"conversation_uuid"`
	ResponseMessageID    pgtype.UUID `db:"response_message_id" json:"response_message_id"`
	QuestionID           pgtype.UUID `db:"question_id" json:"question_id"`
	StaticToolsJson      []byte      `db:"static_tools_json" json:"static_tools_json"`
	StaticPauseIds       []byte      `db:"static_pause_ids" json:"static_pause_ids"`
	ThreadID             string      `db:"thread_id" json:"thread_id"`
	ExecutionID          string      `db:"execution_id" json:"execution_id"`
}

type ResumeCurrentAgentStaticToolsRow struct {
	ResponseMessageGroupID int32       `db:"response_message_group_id" json:"response_message_group_id"`
	ResponseMessageID      pgtype.UUID `db:"response_message_id" json:"response_message_id"`
}

func (q *Queries) ResumeCurrentAgentStaticTools(ctx context.Context, arg ResumeCurrentAgentStaticToolsParams) (ResumeCurrentAgentStaticToolsRow, error) {
	row := q.db.QueryRow(ctx, resumeCurrentAgentStaticTools,
		arg.TargetParticipantID,
		arg.ActorUserID,
		arg.ApplicationVersionID,
		arg.ApplicationID,
		arg.ProjectID,
		arg.ExecutionGeneration,
		arg.InputDigest,
		arg.ConversationUuid,
		arg.ResponseMessageID,
		arg.QuestionID,
		arg.StaticToolsJson,
		arg.StaticPauseIds,
		arg.ThreadID,
		arg.ExecutionID,
	)
	var i ResumeCurrentAgentStaticToolsRow
	err := row.Scan(&i.ResponseMessageGroupID, &i.ResponseMessageID)
	return i, err
}
