// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_pipeline_hitl.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const segmentCurrentPipelineHITL = `-- name: SegmentCurrentPipelineHITL :one
WITH paused AS MATERIALIZED (
    SELECT response.id, response.uuid, response.conversation_id,
           response.author_participant_id, actor.id AS actor_participant_id
    FROM chat_message_group AS response
    JOIN chat_participant_mapping AS actor_mapping
      ON actor_mapping.conversation_id = response.conversation_id
    JOIN chat_participants AS actor
      ON actor.id = actor_mapping.participant_id
     AND actor.entity_name = 'user'
     AND actor.entity_meta ->> 'id' = $1::bigint::text
    WHERE response.id = $2::integer
      AND response.task_id = $3::text
      AND response.is_streaming
    FOR UPDATE OF response
), finalized AS (
    UPDATE chat_message_group AS response
    SET is_streaming = FALSE,
        task_id = $4::text,
        updated_at = clock_timestamp(),
        meta = response.meta || jsonb_build_object('pipeline_hitl_resolution', jsonb_build_object(
            'interrupt_id', $5::text,
            'node_name', $6::text,
            'action', $7::text,
            'decision_message_id', $8::uuid::text,
            'continuation_message_id', $9::uuid::text))
    FROM paused WHERE response.id = paused.id
    RETURNING response.id
), removed_provisional AS (
    DELETE FROM chat_message_items AS item USING finalized
    WHERE item.message_group_id = finalized.id AND item.item_type = 'text_message'
      AND item.meta -> 'runtime_stream_provisional' = 'true'::jsonb
), review_item AS (
    INSERT INTO chat_message_items (uuid, item_type, order_index, meta, message_group_id)
    SELECT gen_random_uuid(), 'text_message',
           (SELECT count(*)::integer FROM chat_message_items WHERE message_group_id = finalized.id),
           jsonb_build_object('kind', 'pipeline_hitl_prompt', 'status', 'resolved',
               'interrupt_id', $5::text, 'node_name', $6::text,
               'action', $7::text), finalized.id
    FROM finalized RETURNING id
), review_text AS (
    INSERT INTO chat_messages_text (id, content)
    SELECT id, $10::text FROM review_item
), decision_group AS (
    INSERT INTO chat_message_group (uuid, author_participant_id, conversation_id,
                                   sent_to_id, meta, is_streaming, created_at)
    SELECT $8::uuid, paused.actor_participant_id, paused.conversation_id,
           paused.author_participant_id,
           jsonb_build_object('pipeline_hitl_decision', jsonb_build_object(
               'interrupt_id', $5::text, 'node_name', $6::text,
               'action', $7::text)), FALSE, clock_timestamp()
    FROM paused JOIN finalized ON finalized.id = paused.id
    RETURNING id, conversation_id, sent_to_id, created_at
), decision_item AS (
    INSERT INTO chat_message_items (uuid, item_type, order_index, meta, message_group_id)
    SELECT gen_random_uuid(), 'text_message', 0,
           jsonb_build_object('kind', 'pipeline_hitl_decision', 'interrupt_id', $5::text,
               'node_name', $6::text, 'action', $7::text), id
    FROM decision_group RETURNING id
), decision_text AS (
    INSERT INTO chat_messages_text (id, content)
    SELECT id, $11::text FROM decision_item
), continuation AS (
    INSERT INTO chat_message_group (uuid, author_participant_id, conversation_id,
                                   reply_to_id, meta, is_streaming, created_at, task_id)
    SELECT $9::uuid, decision_group.sent_to_id, decision_group.conversation_id,
           decision_group.id,
           jsonb_build_object('thread_id', $12::text,
               'execution_generation', $13::text,
               'pipeline_hitl_parent', jsonb_build_object('interrupt_id', $5::text,
                   'prompt_message_id', paused.uuid::text,
                   'decision_message_id', $8::uuid::text)),
           TRUE, decision_group.created_at + interval '1 microsecond', $3::text
    FROM decision_group JOIN paused ON paused.conversation_id = decision_group.conversation_id
    RETURNING id, uuid
)
SELECT id AS response_message_group_id, uuid AS response_message_id FROM continuation
`

type SegmentCurrentPipelineHITLParams struct {
	ActorUserID         int64       `db:"actor_user_id" json:"actor_user_id"`
	PausedResponseID    int32       `db:"paused_response_id" json:"paused_response_id"`
	ExecutionID         string      `db:"execution_id" json:"execution_id"`
	PreviousTaskID      *string     `db:"previous_task_id" json:"previous_task_id"`
	InterruptID         string      `db:"interrupt_id" json:"interrupt_id"`
	NodeName            string      `db:"node_name" json:"node_name"`
	DecisionAction      string      `db:"decision_action" json:"decision_action"`
	DecisionID          pgtype.UUID `db:"decision_id" json:"decision_id"`
	ContinuationID      pgtype.UUID `db:"continuation_id" json:"continuation_id"`
	ReviewMessage       string      `db:"review_message" json:"review_message"`
	DecisionText        string      `db:"decision_text" json:"decision_text"`
	ThreadID            string      `db:"thread_id" json:"thread_id"`
	ExecutionGeneration string      `db:"execution_generation" json:"execution_generation"`
}

type SegmentCurrentPipelineHITLRow struct {
	ResponseMessageGroupID int32       `db:"response_message_group_id" json:"response_message_group_id"`
	ResponseMessageID      pgtype.UUID `db:"response_message_id" json:"response_message_id"`
}

// The admission transaction already locks the conversation and consumes the
// exact pending decision with ResumeCurrentAgentHITL. The repository rechecks
// direct scope from that statement's pre-update metadata before this write.
func (q *Queries) SegmentCurrentPipelineHITL(ctx context.Context, arg SegmentCurrentPipelineHITLParams) (SegmentCurrentPipelineHITLRow, error) {
	row := q.db.QueryRow(ctx, segmentCurrentPipelineHITL,
		arg.ActorUserID,
		arg.PausedResponseID,
		arg.ExecutionID,
		arg.PreviousTaskID,
		arg.InterruptID,
		arg.NodeName,
		arg.DecisionAction,
		arg.DecisionID,
		arg.ContinuationID,
		arg.ReviewMessage,
		arg.DecisionText,
		arg.ThreadID,
		arg.ExecutionGeneration,
	)
	var i SegmentCurrentPipelineHITLRow
	err := row.Scan(&i.ResponseMessageGroupID, &i.ResponseMessageID)
	return i, err
}
