// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_mixed_pause.sql

package sqlcgen

import (
	"context"
)

const finalizeCurrentAgentMixedPause = `-- name: FinalizeCurrentAgentMixedPause :execrows
UPDATE chat_message_group
SET is_streaming = FALSE,
    meta = meta || jsonb_build_object(
        'thread_id', $1::text,
        'hitl_interrupt', $2::jsonb,
        'hitl_interrupts', $3::jsonb,
        'authorization_requests', $4::jsonb,
        'is_error', FALSE,
        'error', '',
        'invoked_skills', $5::jsonb
    ),
    updated_at = clock_timestamp()
WHERE id = $6::bigint
`

type FinalizeCurrentAgentMixedPauseParams struct {
	ThreadID              string `db:"thread_id" json:"thread_id"`
	HitlInterrupt         []byte `db:"hitl_interrupt" json:"hitl_interrupt"`
	HitlInterrupts        []byte `db:"hitl_interrupts" json:"hitl_interrupts"`
	AuthorizationRequests []byte `db:"authorization_requests" json:"authorization_requests"`
	InvokedSkills         []byte `db:"invoked_skills" json:"invoked_skills"`
	MessageGroupID        int64  `db:"message_group_id" json:"message_group_id"`
}

func (q *Queries) FinalizeCurrentAgentMixedPause(ctx context.Context, arg FinalizeCurrentAgentMixedPauseParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeCurrentAgentMixedPause,
		arg.ThreadID,
		arg.HitlInterrupt,
		arg.HitlInterrupts,
		arg.AuthorizationRequests,
		arg.InvokedSkills,
		arg.MessageGroupID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
