// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_version_skills.sql

package sqlcgen

import (
	"context"
)

const copyApplicationVersionSkills = `-- name: CopyApplicationVersionSkills :execrows

INSERT INTO entity_skill_mapping (entity_version_id, entity_type, skill_id, skill_version_id)
SELECT target.id, mapping.entity_type, mapping.skill_id, mapping.skill_version_id
FROM application_versions AS source
JOIN application_versions AS target ON target.application_id = source.application_id
JOIN entity_skill_mapping AS mapping ON mapping.entity_version_id = source.id
WHERE source.id = $1::integer
  AND target.id = $2::text::integer
  AND source.id <> target.id
ORDER BY mapping.id
`

type CopyApplicationVersionSkillsParams struct {
	SourceVersionID int32  `db:"source_version_id" json:"source_version_id"`
	TargetVersionID string `db:"target_version_id" json:"target_version_id"`
}

// The tenant executor installs a transaction-local search_path. These queries
// never accept a schema from the caller.
func (q *Queries) CopyApplicationVersionSkills(ctx context.Context, arg CopyApplicationVersionSkillsParams) (int64, error) {
	result, err := q.db.Exec(ctx, copyApplicationVersionSkills, arg.SourceVersionID, arg.TargetVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteApplicationVersionWithSkills = `-- name: DeleteApplicationVersionWithSkills :one
WITH deleted AS (
    DELETE FROM application_versions
    WHERE application_id = $1::text::integer
      AND id = $2::text::integer
    RETURNING id, application_id
), deleted_skills AS (
    DELETE FROM entity_skill_mapping
    WHERE entity_version_id IN (SELECT id FROM deleted)
), touched AS (
    UPDATE applications SET updated_at = now()
    WHERE id IN (SELECT application_id FROM deleted)
)
SELECT count(*)::bigint FROM deleted
`

type DeleteApplicationVersionWithSkillsParams struct {
	ApplicationID string `db:"application_id" json:"application_id"`
	VersionID     string `db:"version_id" json:"version_id"`
}

// entity_skill_mapping is polymorphic and has no version FK. Remove only the
// bindings of the version actually deleted, including on create compensation.
func (q *Queries) DeleteApplicationVersionWithSkills(ctx context.Context, arg DeleteApplicationVersionWithSkillsParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteApplicationVersionWithSkills, arg.ApplicationID, arg.VersionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
