// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_projects.sql

package sqlcgen

import (
	"context"
)

const canManageCurrentTracingConfiguration = `-- name: CanManageCurrentTracingConfiguration :one
SELECT CASE WHEN
    EXISTS (
        SELECT 1
        FROM public.auth_core__project_user_role AS assignment
        JOIN public.auth_core__project_role AS project_role
          ON project_role.id = assignment.role_id
         AND project_role.project_id = assignment.project_id
        WHERE assignment.project_id = $1::bigint
          AND assignment.user_id = $2::bigint
          AND project_role.name = ANY(ARRAY['admin', 'super_admin', 'system']::text[])
    )
    OR EXISTS (
        SELECT 1
        FROM centry.project AS project
        WHERE project.id = $1::bigint
          AND project.name = 'project_user_' || $2::bigint::text
    )
THEN TRUE ELSE FALSE END AS can_manage
`

type CanManageCurrentTracingConfigurationParams struct {
	ProjectID int64 `db:"project_id" json:"project_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

// Exact current-platform containment for tracing credentials. Project role
// identifiers are compared exactly: billing-admin does
// not carry administrator authority. The personal-project signal is
// independent of role assignment so a missing role row cannot revoke an
// owner's access to project_user_<userID>.
func (q *Queries) CanManageCurrentTracingConfiguration(ctx context.Context, arg CanManageCurrentTracingConfigurationParams) (bool, error) {
	row := q.db.QueryRow(ctx, canManageCurrentTracingConfiguration, arg.ProjectID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const isCurrentUserProjectMember = `-- name: IsCurrentUserProjectMember :one
SELECT EXISTS (
    SELECT 1
    FROM public.auth_core__project_user_role AS assignment
    JOIN centry.project AS project ON project.id = assignment.project_id
    WHERE assignment.user_id = $1::integer
      AND assignment.project_id = $2::integer
      AND project.create_success IS TRUE
      AND project.suspended IS FALSE
) AS is_member
`

type IsCurrentUserProjectMemberParams struct {
	UserID    int32 `db:"user_id" json:"user_id"`
	ProjectID int32 `db:"project_id" json:"project_id"`
}

func (q *Queries) IsCurrentUserProjectMember(ctx context.Context, arg IsCurrentUserProjectMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCurrentUserProjectMember, arg.UserID, arg.ProjectID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listCurrentUserProjects = `-- name: ListCurrentUserProjects :many
WITH candidate_projects AS MATERIALIZED (
    SELECT
        project.id,
        project.name,
        project.owner_id,
        project.plugins,
        project.keycloak_groups,
        project.create_success,
        project.suspended
    FROM centry.project AS project
    WHERE (
        $4::text IS NULL
        OR project.name ILIKE ('%' || $4::text || '%')
    )
    ORDER BY project.id
    LIMIT $6::integer
    OFFSET $5::integer
), member_projects AS MATERIALIZED (
    SELECT DISTINCT assignment.project_id
    FROM public.auth_core__project_user_role AS assignment
    WHERE assignment.user_id = $3::integer
)
SELECT
    project.id,
    project.name,
    project.owner_id,
    project.plugins,
    project.keycloak_groups,
    project.create_success,
    project.suspended,
    project_group.id AS group_id,
    project_group.name AS group_name
FROM candidate_projects AS project
JOIN member_projects AS membership ON membership.project_id = project.id
LEFT JOIN centry.project_group_association AS association
    ON association.project_id = project.id
LEFT JOIN centry.project_group AS project_group
    ON project_group.id = association.group_id
WHERE (
    NOT $1::boolean
    OR project.id <> $2::integer
    OR EXISTS (
        SELECT 1
        FROM public.auth_core__project_user_role AS assignment
        JOIN public.auth_core__project_role AS project_role
            ON project_role.id = assignment.role_id
            AND project_role.project_id = assignment.project_id
        WHERE assignment.project_id = project.id
          AND assignment.user_id = $3::integer
          AND project_role.name = 'admin'
    )
)
ORDER BY project.id, project_group.id
`

type ListCurrentUserProjectsParams struct {
	CheckPublicRole bool    `db:"check_public_role" json:"check_public_role"`
	PublicProjectID int32   `db:"public_project_id" json:"public_project_id"`
	UserID          int32   `db:"user_id" json:"user_id"`
	Search          *string `db:"search" json:"search"`
	Offset          *int32  `db:"offset" json:"offset"`
	Limit           *int32  `db:"limit" json:"limit"`
}

type ListCurrentUserProjectsRow struct {
	ID             int32    `db:"id" json:"id"`
	Name           string   `db:"name" json:"name"`
	OwnerID        int32    `db:"owner_id" json:"owner_id"`
	Plugins        []string `db:"plugins" json:"plugins"`
	KeycloakGroups []byte   `db:"keycloak_groups" json:"keycloak_groups"`
	CreateSuccess  bool     `db:"create_success" json:"create_success"`
	Suspended      bool     `db:"suspended" json:"suspended"`
	GroupID        *int32   `db:"group_id" json:"group_id"`
	GroupName      *string  `db:"group_name" json:"group_name"`
}

func (q *Queries) ListCurrentUserProjects(ctx context.Context, arg ListCurrentUserProjectsParams) ([]ListCurrentUserProjectsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentUserProjects,
		arg.CheckPublicRole,
		arg.PublicProjectID,
		arg.UserID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentUserProjectsRow{}
	for rows.Next() {
		var i ListCurrentUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Plugins,
			&i.KeycloakGroups,
			&i.CreateSuccess,
			&i.Suspended,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCurrentPersonalProjectID = `-- name: ResolveCurrentPersonalProjectID :one
WITH personal_project AS MATERIALIZED (
    SELECT project.id
    FROM centry.project AS project
    WHERE project.name = ('project_user_' || $1::integer::text)
    ORDER BY project.id
    LIMIT 1
), member_personal_project AS MATERIALIZED (
    SELECT project.id
    FROM personal_project AS project
    WHERE EXISTS (
        SELECT 1
        FROM public.auth_core__project_user_role AS assignment
        WHERE assignment.project_id = project.id
          AND assignment.user_id = $1::integer
    )
), resolved_project AS (
    SELECT project.id AS project_id
    FROM member_personal_project AS project

    UNION ALL

    SELECT substring(
               user_account.email
               FROM '^system_user_([0-9]+)@centry[.]user$'
           )::integer AS project_id
    FROM public.auth_core__user AS user_account
    WHERE user_account.id = $1::integer
      AND user_account.email ~ '^system_user_[0-9]+@centry[.]user$'
      AND NOT EXISTS (SELECT 1 FROM personal_project)
)
SELECT project.project_id::integer AS project_id
FROM resolved_project AS project
LIMIT 1
`

// This is the exact current projects_get_personal_project_id decision tree:
// a named personal project wins only when the user has any project-role
// assignment; the system-user email fallback is considered only when that
// named project does not exist.
func (q *Queries) ResolveCurrentPersonalProjectID(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, resolveCurrentPersonalProjectID, userID)
	var project_id int32
	err := row.Scan(&project_id)
	return project_id, err
}
