// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_provisioning.sql

package sqlcgen

import (
	"context"
)

const acquireAuthProviderAdvisoryLock = `-- name: AcquireAuthProviderAdvisoryLock :exec
SELECT pg_advisory_xact_lock(
    hashtextextended($1::text, 0)
)
`

func (q *Queries) AcquireAuthProviderAdvisoryLock(ctx context.Context, providerRef string) error {
	_, err := q.db.Exec(ctx, acquireAuthProviderAdvisoryLock, providerRef)
	return err
}

const assignAuthUserRoleByNameAndMode = `-- name: AssignAuthUserRoleByNameAndMode :execrows
INSERT INTO public.auth_core__user_role (user_id, role_id)
SELECT $1::integer, role.id
FROM public.auth_core__role AS role
WHERE role.name = $2::varchar(64)
  AND role.mode = $3::varchar(64)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignAuthUserRoleByNameAndModeParams struct {
	UserID   int32  `db:"user_id" json:"user_id"`
	RoleName string `db:"role_name" json:"role_name"`
	Mode     string `db:"mode" json:"mode"`
}

func (q *Queries) AssignAuthUserRoleByNameAndMode(ctx context.Context, arg AssignAuthUserRoleByNameAndModeParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignAuthUserRoleByNameAndMode, arg.UserID, arg.RoleName, arg.Mode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const assignExistingProjectRoles = `-- name: AssignExistingProjectRoles :execrows
INSERT INTO public.auth_core__project_user_role (project_id, user_id, role_id)
SELECT
    $1::integer,
    $2::integer,
    role.id
FROM public.auth_core__project_role AS role
WHERE role.project_id = $1::integer
  AND role.name = ANY($3::text[])
ON CONFLICT (project_id, user_id, role_id) DO NOTHING
`

type AssignExistingProjectRolesParams struct {
	ProjectID int32    `db:"project_id" json:"project_id"`
	UserID    int32    `db:"user_id" json:"user_id"`
	RoleNames []string `db:"role_names" json:"role_names"`
}

func (q *Queries) AssignExistingProjectRoles(ctx context.Context, arg AssignExistingProjectRolesParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignExistingProjectRoles, arg.ProjectID, arg.UserID, arg.RoleNames)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAuthUserRolesInMode = `-- name: CountAuthUserRolesInMode :one
SELECT count(*)
FROM public.auth_core__user_role AS user_role
JOIN public.auth_core__role AS role ON role.id = user_role.role_id
WHERE user_role.user_id = $1::integer
  AND role.mode = $2::varchar(64)
`

type CountAuthUserRolesInModeParams struct {
	UserID int32  `db:"user_id" json:"user_id"`
	Mode   string `db:"mode" json:"mode"`
}

func (q *Queries) CountAuthUserRolesInMode(ctx context.Context, arg CountAuthUserRolesInModeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthUserRolesInMode, arg.UserID, arg.Mode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthUserByEmailIfMissing = `-- name: CreateAuthUserByEmailIfMissing :one
INSERT INTO public.auth_core__user (email, name)
VALUES ($1::text, $2::text)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, name, last_login, suspended
`

type CreateAuthUserByEmailIfMissingParams struct {
	Email string `db:"email" json:"email"`
	Name  string `db:"name" json:"name"`
}

func (q *Queries) CreateAuthUserByEmailIfMissing(ctx context.Context, arg CreateAuthUserByEmailIfMissingParams) (AuthCoreUser, error) {
	row := q.db.QueryRow(ctx, createAuthUserByEmailIfMissing, arg.Email, arg.Name)
	var i AuthCoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.LastLogin,
		&i.Suspended,
	)
	return i, err
}

const getAuthUserByEmailForProvisioning = `-- name: GetAuthUserByEmailForProvisioning :one
SELECT id, email, name, last_login, suspended
FROM public.auth_core__user
WHERE email = $1::text
FOR UPDATE
`

func (q *Queries) GetAuthUserByEmailForProvisioning(ctx context.Context, email string) (AuthCoreUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmailForProvisioning, email)
	var i AuthCoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.LastLogin,
		&i.Suspended,
	)
	return i, err
}

const getAuthUserByProviderForProvisioning = `-- name: GetAuthUserByProviderForProvisioning :one
SELECT
    owner.id,
    owner.email,
    owner.name,
    owner.last_login,
    owner.suspended
FROM public.auth_core__user_provider AS provider
JOIN public.auth_core__user AS owner ON owner.id = provider.user_id
WHERE provider.provider_ref = $1::text
FOR UPDATE OF provider, owner
`

func (q *Queries) GetAuthUserByProviderForProvisioning(ctx context.Context, providerRef string) (AuthCoreUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByProviderForProvisioning, providerRef)
	var i AuthCoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.LastLogin,
		&i.Suspended,
	)
	return i, err
}

const hasAuthAdministrationAdminRole = `-- name: HasAuthAdministrationAdminRole :one
SELECT EXISTS (
    SELECT 1
    FROM public.auth_core__user_role AS user_role
    JOIN public.auth_core__role AS role ON role.id = user_role.role_id
    WHERE user_role.user_id = $1::integer
      AND role.mode = 'administration'
      AND role.name IN ('admin', 'super_admin')
)::boolean
`

func (q *Queries) HasAuthAdministrationAdminRole(ctx context.Context, userID int32) (bool, error) {
	row := q.db.QueryRow(ctx, hasAuthAdministrationAdminRole, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const linkAuthProviderIfMissing = `-- name: LinkAuthProviderIfMissing :execrows
INSERT INTO public.auth_core__user_provider (user_id, provider_ref)
VALUES ($1::integer, $2::text)
ON CONFLICT (provider_ref) DO NOTHING
`

type LinkAuthProviderIfMissingParams struct {
	UserID      int32  `db:"user_id" json:"user_id"`
	ProviderRef string `db:"provider_ref" json:"provider_ref"`
}

func (q *Queries) LinkAuthProviderIfMissing(ctx context.Context, arg LinkAuthProviderIfMissingParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkAuthProviderIfMissing, arg.UserID, arg.ProviderRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchProvisionedAuthUser = `-- name: TouchProvisionedAuthUser :one
UPDATE public.auth_core__user
SET
    last_login = clock_timestamp() AT TIME ZONE 'UTC',
    name = CASE
        WHEN name IS NULL OR name = '' THEN $1::text
        ELSE name
    END
WHERE id = $2::integer
  AND suspended = false
RETURNING id, email, name, last_login, suspended
`

type TouchProvisionedAuthUserParams struct {
	Name   string `db:"name" json:"name"`
	UserID int32  `db:"user_id" json:"user_id"`
}

func (q *Queries) TouchProvisionedAuthUser(ctx context.Context, arg TouchProvisionedAuthUserParams) (AuthCoreUser, error) {
	row := q.db.QueryRow(ctx, touchProvisionedAuthUser, arg.Name, arg.UserID)
	var i AuthCoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.LastLogin,
		&i.Suspended,
	)
	return i, err
}
