// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configurations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCurrentConfigurations = `-- name: CountCurrentConfigurations :one
SELECT count(*)
FROM configuration
WHERE project_id = $1::integer
  AND (COALESCE(cardinality($2::integer[]), 0) = 0 OR id = ANY($2::integer[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR type = ANY($3::text[]))
  AND (COALESCE(cardinality($4::text[]), 0) = 0 OR section = ANY($4::text[]))
  AND ($5::text = '' OR label ILIKE ('%' || $5::text || '%'))
`

type CountCurrentConfigurationsParams struct {
	ProjectID  int32    `db:"project_id" json:"project_id"`
	Ids        []int32  `db:"ids" json:"ids"`
	Types      []string `db:"types" json:"types"`
	Sections   []string `db:"sections" json:"sections"`
	LabelQuery string   `db:"label_query" json:"label_query"`
}

func (q *Queries) CountCurrentConfigurations(ctx context.Context, arg CountCurrentConfigurationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrentConfigurations,
		arg.ProjectID,
		arg.Ids,
		arg.Types,
		arg.Sections,
		arg.LabelQuery,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCurrentSharedConfigurations = `-- name: CountCurrentSharedConfigurations :one
SELECT count(*)
FROM configuration
WHERE project_id = $1::integer
  AND shared = true
  AND (COALESCE(cardinality($2::integer[]), 0) = 0 OR id = ANY($2::integer[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR type = ANY($3::text[]))
  AND (COALESCE(cardinality($4::text[]), 0) = 0 OR section = ANY($4::text[]))
`

type CountCurrentSharedConfigurationsParams struct {
	ProjectID int32    `db:"project_id" json:"project_id"`
	Ids       []int32  `db:"ids" json:"ids"`
	Types     []string `db:"types" json:"types"`
	Sections  []string `db:"sections" json:"sections"`
}

func (q *Queries) CountCurrentSharedConfigurations(ctx context.Context, arg CountCurrentSharedConfigurationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrentSharedConfigurations,
		arg.ProjectID,
		arg.Ids,
		arg.Types,
		arg.Sections,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCurrentConfiguration = `-- name: DeleteCurrentConfiguration :one
DELETE FROM configuration
WHERE id = $1::integer
  AND project_id = $2::integer
RETURNING id
`

type DeleteCurrentConfigurationParams struct {
	ConfigurationID int32 `db:"configuration_id" json:"configuration_id"`
	ProjectID       int32 `db:"project_id" json:"project_id"`
}

func (q *Queries) DeleteCurrentConfiguration(ctx context.Context, arg DeleteCurrentConfigurationParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteCurrentConfiguration, arg.ConfigurationID, arg.ProjectID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findCurrentConfigurationByEliteaTitle = `-- name: FindCurrentConfigurationByEliteaTitle :one

SELECT uuid::text AS configuration_uuid,
       project_id,
       type,
       data,
       shared
FROM configuration
WHERE project_id = $1::integer
  AND elitea_title = $2::text
  AND (NOT $3::boolean OR shared = true)
LIMIT 1
`

type FindCurrentConfigurationByEliteaTitleParams struct {
	ProjectID   int32  `db:"project_id" json:"project_id"`
	EliteaTitle string `db:"elitea_title" json:"elitea_title"`
	SharedOnly  bool   `db:"shared_only" json:"shared_only"`
}

type FindCurrentConfigurationByEliteaTitleRow struct {
	ConfigurationUuid string `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32  `db:"project_id" json:"project_id"`
	Type              string `db:"type" json:"type"`
	Data              []byte `db:"data" json:"data"`
	Shared            bool   `db:"shared" json:"shared"`
}

// These unqualified names are intentional. Every query is executed inside a
// transaction whose local search_path is derived from the authorized project.
// This file projects the existing 16-column tenant table; it does not define a
// replacement configuration store.
func (q *Queries) FindCurrentConfigurationByEliteaTitle(ctx context.Context, arg FindCurrentConfigurationByEliteaTitleParams) (FindCurrentConfigurationByEliteaTitleRow, error) {
	row := q.db.QueryRow(ctx, findCurrentConfigurationByEliteaTitle, arg.ProjectID, arg.EliteaTitle, arg.SharedOnly)
	var i FindCurrentConfigurationByEliteaTitleRow
	err := row.Scan(
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Type,
		&i.Data,
		&i.Shared,
	)
	return i, err
}

const findCurrentEmbeddingConfigurations = `-- name: FindCurrentEmbeddingConfigurations :many
SELECT uuid::text AS configuration_uuid,
       project_id,
       type,
       section,
       data,
       shared
FROM configuration
WHERE project_id = $1::integer
  AND type = 'embedding_model'
  AND section = 'embedding'
  AND status_ok = true
  AND data->>'name' = $2::text
  AND (NOT $3::boolean OR shared = true)
ORDER BY id ASC
LIMIT 2
`

type FindCurrentEmbeddingConfigurationsParams struct {
	ProjectID  int32  `db:"project_id" json:"project_id"`
	ModelName  string `db:"model_name" json:"model_name"`
	SharedOnly bool   `db:"shared_only" json:"shared_only"`
}

type FindCurrentEmbeddingConfigurationsRow struct {
	ConfigurationUuid string `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32  `db:"project_id" json:"project_id"`
	Type              string `db:"type" json:"type"`
	Section           string `db:"section" json:"section"`
	Data              []byte `db:"data" json:"data"`
	Shared            bool   `db:"shared" json:"shared"`
}

// The current Configurations -> LiteLLM model projection keys embedding
// models by data.name. A two-row sentinel lets the adapter reject duplicate
// mutable definitions instead of selecting one silently.
func (q *Queries) FindCurrentEmbeddingConfigurations(ctx context.Context, arg FindCurrentEmbeddingConfigurationsParams) ([]FindCurrentEmbeddingConfigurationsRow, error) {
	rows, err := q.db.Query(ctx, findCurrentEmbeddingConfigurations, arg.ProjectID, arg.ModelName, arg.SharedOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindCurrentEmbeddingConfigurationsRow{}
	for rows.Next() {
		var i FindCurrentEmbeddingConfigurationsRow
		if err := rows.Scan(
			&i.ConfigurationUuid,
			&i.ProjectID,
			&i.Type,
			&i.Section,
			&i.Data,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentConfiguration = `-- name: GetCurrentConfiguration :one
SELECT configuration.id,
       configuration.uuid::text AS configuration_uuid,
       configuration.project_id,
       configuration.label,
       configuration.elitea_title,
       configuration.type,
       configuration.section,
       configuration.data,
       configuration.meta,
       configuration.shared,
       configuration.status_ok,
       configuration.status_logs,
       configuration.source,
       configuration.author_id,
       configuration.created_at,
       configuration.updated_at,
       EXISTS (
           SELECT 1
           FROM centry.social_pins
           WHERE social_pins.entity = 'configuration'
             AND social_pins.project_id = $1::integer
             AND social_pins.entity_id = configuration.id
       ) AS is_pinned
FROM configuration
WHERE configuration.id = $2::integer
  AND configuration.project_id = $1::integer
LIMIT 1
`

type GetCurrentConfigurationParams struct {
	ProjectID       int32 `db:"project_id" json:"project_id"`
	ConfigurationID int32 `db:"configuration_id" json:"configuration_id"`
}

type GetCurrentConfigurationRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	IsPinned          bool             `db:"is_pinned" json:"is_pinned"`
}

func (q *Queries) GetCurrentConfiguration(ctx context.Context, arg GetCurrentConfigurationParams) (GetCurrentConfigurationRow, error) {
	row := q.db.QueryRow(ctx, getCurrentConfiguration, arg.ProjectID, arg.ConfigurationID)
	var i GetCurrentConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Label,
		&i.EliteaTitle,
		&i.Type,
		&i.Section,
		&i.Data,
		&i.Meta,
		&i.Shared,
		&i.StatusOk,
		&i.StatusLogs,
		&i.Source,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPinned,
	)
	return i, err
}

const getCurrentModelCatalogBounds = `-- name: GetCurrentModelCatalogBounds :one
SELECT count(*)::bigint AS row_count,
       COALESCE(sum(candidate.projected_bytes), 0)::bigint AS projected_bytes
FROM (
    SELECT octet_length(data::text)::bigint
             + octet_length(elitea_title)
             + octet_length(section)
             + COALESCE(octet_length(label), 0) AS projected_bytes
    FROM configuration
    WHERE project_id = $1::integer
      AND section = $2::text
      AND status_ok = true
      AND (NOT $3::boolean OR shared = true)
    ORDER BY id ASC
    LIMIT $4::integer
) AS candidate
`

type GetCurrentModelCatalogBoundsParams struct {
	ProjectID  int32  `db:"project_id" json:"project_id"`
	Section    string `db:"section" json:"section"`
	SharedOnly bool   `db:"shared_only" json:"shared_only"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

type GetCurrentModelCatalogBoundsRow struct {
	RowCount       int64 `db:"row_count" json:"row_count"`
	ProjectedBytes int64 `db:"projected_bytes" json:"projected_bytes"`
}

// Raw data is intentional: the Go adapter performs type-safe, redacted
// decoding before applying section-specific response shaping. ID order gives
// duplicate candidates a deterministic baseline order.
func (q *Queries) GetCurrentModelCatalogBounds(ctx context.Context, arg GetCurrentModelCatalogBoundsParams) (GetCurrentModelCatalogBoundsRow, error) {
	row := q.db.QueryRow(ctx, getCurrentModelCatalogBounds,
		arg.ProjectID,
		arg.Section,
		arg.SharedOnly,
		arg.LimitRows,
	)
	var i GetCurrentModelCatalogBoundsRow
	err := row.Scan(&i.RowCount, &i.ProjectedBytes)
	return i, err
}

const insertCurrentConfiguration = `-- name: InsertCurrentConfiguration :one
INSERT INTO configuration (
    uuid, project_id, label, elitea_title, type, section, data, meta, shared,
    status_ok, status_logs, source, author_id
) VALUES (
    $1::text::uuid,
    $2::integer,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::jsonb,
    $8::jsonb,
    $9::boolean,
    $10::boolean,
    $11::text,
    $12::text,
    $13::integer
)
RETURNING id,
          uuid::text AS configuration_uuid,
          project_id,
          label,
          elitea_title,
          type,
          section,
          data,
          meta,
          shared,
          status_ok,
          status_logs,
          source,
          author_id,
          created_at,
          updated_at,
          false AS is_pinned
`

type InsertCurrentConfigurationParams struct {
	ConfigurationUuid string  `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32   `db:"project_id" json:"project_id"`
	Label             *string `db:"label" json:"label"`
	EliteaTitle       string  `db:"elitea_title" json:"elitea_title"`
	ConfigurationType string  `db:"configuration_type" json:"configuration_type"`
	Section           string  `db:"section" json:"section"`
	Data              []byte  `db:"data" json:"data"`
	Meta              []byte  `db:"meta" json:"meta"`
	Shared            bool    `db:"shared" json:"shared"`
	StatusOk          bool    `db:"status_ok" json:"status_ok"`
	StatusLogs        *string `db:"status_logs" json:"status_logs"`
	Source            string  `db:"source" json:"source"`
	AuthorID          *int32  `db:"author_id" json:"author_id"`
}

type InsertCurrentConfigurationRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	IsPinned          bool             `db:"is_pinned" json:"is_pinned"`
}

func (q *Queries) InsertCurrentConfiguration(ctx context.Context, arg InsertCurrentConfigurationParams) (InsertCurrentConfigurationRow, error) {
	row := q.db.QueryRow(ctx, insertCurrentConfiguration,
		arg.ConfigurationUuid,
		arg.ProjectID,
		arg.Label,
		arg.EliteaTitle,
		arg.ConfigurationType,
		arg.Section,
		arg.Data,
		arg.Meta,
		arg.Shared,
		arg.StatusOk,
		arg.StatusLogs,
		arg.Source,
		arg.AuthorID,
	)
	var i InsertCurrentConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Label,
		&i.EliteaTitle,
		&i.Type,
		&i.Section,
		&i.Data,
		&i.Meta,
		&i.Shared,
		&i.StatusOk,
		&i.StatusLogs,
		&i.Source,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPinned,
	)
	return i, err
}

const listCurrentConfigurationOptionCandidates = `-- name: ListCurrentConfigurationOptionCandidates :many
SELECT elitea_title,
       label,
       type,
       section,
       shared,
       project_id
FROM configuration
WHERE project_id = $1::integer
  AND (
      (
          COALESCE(cardinality($2::text[]), 0) > 0
          AND type = ANY($2::text[])
      )
      OR (
          COALESCE(cardinality($3::text[]), 0) > 0
          AND section = ANY($3::text[])
      )
  )
  AND (NOT $4::boolean OR shared = true)
ORDER BY id ASC
LIMIT $5::integer
`

type ListCurrentConfigurationOptionCandidatesParams struct {
	ProjectID  int32    `db:"project_id" json:"project_id"`
	Types      []string `db:"types" json:"types"`
	Sections   []string `db:"sections" json:"sections"`
	SharedOnly bool     `db:"shared_only" json:"shared_only"`
	LimitRows  int32    `db:"limit_rows" json:"limit_rows"`
}

type ListCurrentConfigurationOptionCandidatesRow struct {
	EliteaTitle string  `db:"elitea_title" json:"elitea_title"`
	Label       *string `db:"label" json:"label"`
	Type        string  `db:"type" json:"type"`
	Section     string  `db:"section" json:"section"`
	Shared      bool    `db:"shared" json:"shared"`
	ProjectID   int32   `db:"project_id" json:"project_id"`
}

// This deliberately projects only the six fields exposed by nested
// configuration options. The same bounded query is run first in the current
// project and, when requested, in the public project with shared_only=true.
func (q *Queries) ListCurrentConfigurationOptionCandidates(ctx context.Context, arg ListCurrentConfigurationOptionCandidatesParams) ([]ListCurrentConfigurationOptionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentConfigurationOptionCandidates,
		arg.ProjectID,
		arg.Types,
		arg.Sections,
		arg.SharedOnly,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentConfigurationOptionCandidatesRow{}
	for rows.Next() {
		var i ListCurrentConfigurationOptionCandidatesRow
		if err := rows.Scan(
			&i.EliteaTitle,
			&i.Label,
			&i.Type,
			&i.Section,
			&i.Shared,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentConfigurationTypes = `-- name: ListCurrentConfigurationTypes :many
SELECT DISTINCT type
FROM configuration
WHERE project_id = $1::integer
  AND ($2::text = '' OR section = $2::text)
ORDER BY type ASC
LIMIT $3::integer
`

type ListCurrentConfigurationTypesParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	Section   string `db:"section" json:"section"`
	LimitRows int32  `db:"limit_rows" json:"limit_rows"`
}

// Empty section intentionally disables the section predicate for the exact
// current UI contract. The caller caps limit_rows at the 257-row sentinel.
func (q *Queries) ListCurrentConfigurationTypes(ctx context.Context, arg ListCurrentConfigurationTypesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listCurrentConfigurationTypes, arg.ProjectID, arg.Section, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentConfigurations = `-- name: ListCurrentConfigurations :many
SELECT configuration.id,
       configuration.uuid::text AS configuration_uuid,
       configuration.project_id,
       configuration.label,
       configuration.elitea_title,
       configuration.type,
       configuration.section,
       configuration.data,
       configuration.meta,
       configuration.shared,
       configuration.status_ok,
       configuration.status_logs,
       configuration.source,
       configuration.author_id,
       configuration.created_at,
       configuration.updated_at,
       COALESCE(social_pins.id IS NOT NULL, false)::boolean AS is_pinned
FROM configuration
LEFT JOIN centry.social_pins
  ON social_pins.entity = 'configuration'
 AND social_pins.project_id = $1::integer
 AND social_pins.entity_id = configuration.id
WHERE configuration.project_id = $1::integer
  AND (COALESCE(cardinality($2::integer[]), 0) = 0 OR configuration.id = ANY($2::integer[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR configuration.type = ANY($3::text[]))
  AND (COALESCE(cardinality($4::text[]), 0) = 0 OR configuration.section = ANY($4::text[]))
  AND ($5::text = '' OR configuration.label ILIKE ('%' || $5::text || '%'))
ORDER BY
  (social_pins.id IS NOT NULL) DESC,
  social_pins.updated_at DESC NULLS LAST,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'id'            THEN configuration.id END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'id'            THEN configuration.id END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'uuid'          THEN configuration.uuid END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'uuid'          THEN configuration.uuid END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'project_id'    THEN configuration.project_id END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'project_id'    THEN configuration.project_id END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'label'         THEN configuration.label END ASC NULLS LAST,
  CASE WHEN $6::text = 'desc' AND $7::text = 'label'         THEN configuration.label END DESC NULLS LAST,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'elitea_title'  THEN configuration.elitea_title END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'elitea_title'  THEN configuration.elitea_title END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'type'          THEN configuration.type END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'type'          THEN configuration.type END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'section'       THEN configuration.section END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'section'       THEN configuration.section END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'data'          THEN configuration.data END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'data'          THEN configuration.data END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'meta'          THEN configuration.meta END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'meta'          THEN configuration.meta END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'shared'        THEN configuration.shared END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'shared'        THEN configuration.shared END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'status_ok'     THEN configuration.status_ok END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'status_ok'     THEN configuration.status_ok END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'status_logs'   THEN configuration.status_logs END ASC NULLS LAST,
  CASE WHEN $6::text = 'desc' AND $7::text = 'status_logs'   THEN configuration.status_logs END DESC NULLS LAST,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'source'        THEN configuration.source END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'source'        THEN configuration.source END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'author_id'     THEN configuration.author_id END ASC NULLS LAST,
  CASE WHEN $6::text = 'desc' AND $7::text = 'author_id'     THEN configuration.author_id END DESC NULLS LAST,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'created_at'    THEN configuration.created_at END ASC,
  CASE WHEN $6::text = 'desc' AND $7::text = 'created_at'    THEN configuration.created_at END DESC,
  CASE WHEN $6::text = 'asc'  AND $7::text = 'updated_at'    THEN configuration.updated_at END ASC NULLS LAST,
  CASE WHEN $6::text = 'desc' AND $7::text = 'updated_at'    THEN configuration.updated_at END DESC NULLS LAST,
  configuration.id ASC
LIMIT $9::integer
OFFSET $8::integer
`

type ListCurrentConfigurationsParams struct {
	ProjectID  int32    `db:"project_id" json:"project_id"`
	Ids        []int32  `db:"ids" json:"ids"`
	Types      []string `db:"types" json:"types"`
	Sections   []string `db:"sections" json:"sections"`
	LabelQuery string   `db:"label_query" json:"label_query"`
	SortOrder  string   `db:"sort_order" json:"sort_order"`
	SortBy     string   `db:"sort_by" json:"sort_by"`
	OffsetRows int32    `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32    `db:"limit_rows" json:"limit_rows"`
}

type ListCurrentConfigurationsRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	IsPinned          bool             `db:"is_pinned" json:"is_pinned"`
}

func (q *Queries) ListCurrentConfigurations(ctx context.Context, arg ListCurrentConfigurationsParams) ([]ListCurrentConfigurationsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentConfigurations,
		arg.ProjectID,
		arg.Ids,
		arg.Types,
		arg.Sections,
		arg.LabelQuery,
		arg.SortOrder,
		arg.SortBy,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentConfigurationsRow{}
	for rows.Next() {
		var i ListCurrentConfigurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigurationUuid,
			&i.ProjectID,
			&i.Label,
			&i.EliteaTitle,
			&i.Type,
			&i.Section,
			&i.Data,
			&i.Meta,
			&i.Shared,
			&i.StatusOk,
			&i.StatusLogs,
			&i.Source,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentModelConfigurations = `-- name: ListCurrentModelConfigurations :many
SELECT id,
       project_id,
       label,
       elitea_title,
       section,
       data,
       shared
FROM configuration
WHERE project_id = $1::integer
  AND section = $2::text
  AND status_ok = true
  AND (NOT $3::boolean OR shared = true)
ORDER BY id ASC
LIMIT $4::integer
`

type ListCurrentModelConfigurationsParams struct {
	ProjectID  int32  `db:"project_id" json:"project_id"`
	Section    string `db:"section" json:"section"`
	SharedOnly bool   `db:"shared_only" json:"shared_only"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

type ListCurrentModelConfigurationsRow struct {
	ID          int32   `db:"id" json:"id"`
	ProjectID   int32   `db:"project_id" json:"project_id"`
	Label       *string `db:"label" json:"label"`
	EliteaTitle string  `db:"elitea_title" json:"elitea_title"`
	Section     string  `db:"section" json:"section"`
	Data        []byte  `db:"data" json:"data"`
	Shared      bool    `db:"shared" json:"shared"`
}

func (q *Queries) ListCurrentModelConfigurations(ctx context.Context, arg ListCurrentModelConfigurationsParams) ([]ListCurrentModelConfigurationsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentModelConfigurations,
		arg.ProjectID,
		arg.Section,
		arg.SharedOnly,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentModelConfigurationsRow{}
	for rows.Next() {
		var i ListCurrentModelConfigurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Label,
			&i.EliteaTitle,
			&i.Section,
			&i.Data,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentSharedConfigurations = `-- name: ListCurrentSharedConfigurations :many
SELECT id,
       uuid::text AS configuration_uuid,
       project_id,
       label,
       elitea_title,
       type,
       section,
       data,
       meta,
       shared,
       status_ok,
       status_logs,
       source,
       author_id,
       created_at,
       updated_at,
       false AS is_pinned
FROM configuration
WHERE project_id = $1::integer
  AND shared = true
  AND (COALESCE(cardinality($2::integer[]), 0) = 0 OR id = ANY($2::integer[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR type = ANY($3::text[]))
  AND (COALESCE(cardinality($4::text[]), 0) = 0 OR section = ANY($4::text[]))
ORDER BY
  CASE WHEN $5::text = 'asc'  AND $6::text = 'id'            THEN id END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'id'            THEN id END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'uuid'          THEN uuid END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'uuid'          THEN uuid END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'project_id'    THEN project_id END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'project_id'    THEN project_id END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'label'         THEN label END ASC NULLS LAST,
  CASE WHEN $5::text = 'desc' AND $6::text = 'label'         THEN label END DESC NULLS LAST,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'elitea_title'  THEN elitea_title END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'elitea_title'  THEN elitea_title END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'type'          THEN type END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'type'          THEN type END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'section'       THEN section END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'section'       THEN section END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'data'          THEN data END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'data'          THEN data END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'meta'          THEN meta END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'meta'          THEN meta END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'shared'        THEN shared END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'shared'        THEN shared END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'status_ok'     THEN status_ok END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'status_ok'     THEN status_ok END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'status_logs'   THEN status_logs END ASC NULLS LAST,
  CASE WHEN $5::text = 'desc' AND $6::text = 'status_logs'   THEN status_logs END DESC NULLS LAST,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'source'        THEN source END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'source'        THEN source END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'author_id'     THEN author_id END ASC NULLS LAST,
  CASE WHEN $5::text = 'desc' AND $6::text = 'author_id'     THEN author_id END DESC NULLS LAST,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'created_at'    THEN created_at END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'created_at'    THEN created_at END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'updated_at'    THEN updated_at END ASC NULLS LAST,
  CASE WHEN $5::text = 'desc' AND $6::text = 'updated_at'    THEN updated_at END DESC NULLS LAST,
  id ASC
LIMIT $8::integer
OFFSET $7::integer
`

type ListCurrentSharedConfigurationsParams struct {
	ProjectID  int32    `db:"project_id" json:"project_id"`
	Ids        []int32  `db:"ids" json:"ids"`
	Types      []string `db:"types" json:"types"`
	Sections   []string `db:"sections" json:"sections"`
	SortOrder  string   `db:"sort_order" json:"sort_order"`
	SortBy     string   `db:"sort_by" json:"sort_by"`
	OffsetRows int32    `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32    `db:"limit_rows" json:"limit_rows"`
}

type ListCurrentSharedConfigurationsRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	IsPinned          bool             `db:"is_pinned" json:"is_pinned"`
}

func (q *Queries) ListCurrentSharedConfigurations(ctx context.Context, arg ListCurrentSharedConfigurationsParams) ([]ListCurrentSharedConfigurationsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentSharedConfigurations,
		arg.ProjectID,
		arg.Ids,
		arg.Types,
		arg.Sections,
		arg.SortOrder,
		arg.SortBy,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentSharedConfigurationsRow{}
	for rows.Next() {
		var i ListCurrentSharedConfigurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigurationUuid,
			&i.ProjectID,
			&i.Label,
			&i.EliteaTitle,
			&i.Type,
			&i.Section,
			&i.Data,
			&i.Meta,
			&i.Shared,
			&i.StatusOk,
			&i.StatusLogs,
			&i.Source,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceCurrentConfiguration = `-- name: ReplaceCurrentConfiguration :one
UPDATE configuration
SET label = $1::text,
    elitea_title = $2::text,
    data = $3::jsonb,
    meta = $4::jsonb,
    shared = $5::boolean,
    status_ok = $6::boolean,
    status_logs = $7::text,
    updated_at = now()
WHERE id = $8::integer
  AND project_id = $9::integer
RETURNING id,
          uuid::text AS configuration_uuid,
          project_id,
          label,
          elitea_title,
          type,
          section,
          data,
          meta,
          shared,
          status_ok,
          status_logs,
          source,
          author_id,
          created_at,
          updated_at,
          false AS is_pinned
`

type ReplaceCurrentConfigurationParams struct {
	Label           *string `db:"label" json:"label"`
	EliteaTitle     string  `db:"elitea_title" json:"elitea_title"`
	Data            []byte  `db:"data" json:"data"`
	Meta            []byte  `db:"meta" json:"meta"`
	Shared          bool    `db:"shared" json:"shared"`
	StatusOk        bool    `db:"status_ok" json:"status_ok"`
	StatusLogs      *string `db:"status_logs" json:"status_logs"`
	ConfigurationID int32   `db:"configuration_id" json:"configuration_id"`
	ProjectID       int32   `db:"project_id" json:"project_id"`
}

type ReplaceCurrentConfigurationRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	IsPinned          bool             `db:"is_pinned" json:"is_pinned"`
}

func (q *Queries) ReplaceCurrentConfiguration(ctx context.Context, arg ReplaceCurrentConfigurationParams) (ReplaceCurrentConfigurationRow, error) {
	row := q.db.QueryRow(ctx, replaceCurrentConfiguration,
		arg.Label,
		arg.EliteaTitle,
		arg.Data,
		arg.Meta,
		arg.Shared,
		arg.StatusOk,
		arg.StatusLogs,
		arg.ConfigurationID,
		arg.ProjectID,
	)
	var i ReplaceCurrentConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Label,
		&i.EliteaTitle,
		&i.Type,
		&i.Section,
		&i.Data,
		&i.Meta,
		&i.Shared,
		&i.StatusOk,
		&i.StatusLogs,
		&i.Source,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPinned,
	)
	return i, err
}
