// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_oauth_clients.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMCPOAuthClient = `-- name: InsertMCPOAuthClient :exec
INSERT INTO elitea_auth.mcp_oauth_clients
    (id, project_id, actor_id, client_id, token_endpoint, resource, encrypted_credentials, secret_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertMCPOAuthClientParams struct {
	ID                   string             `db:"id" json:"id"`
	ProjectID            int32              `db:"project_id" json:"project_id"`
	ActorID              int32              `db:"actor_id" json:"actor_id"`
	ClientID             string             `db:"client_id" json:"client_id"`
	TokenEndpoint        string             `db:"token_endpoint" json:"token_endpoint"`
	Resource             string             `db:"resource" json:"resource"`
	EncryptedCredentials []byte             `db:"encrypted_credentials" json:"encrypted_credentials"`
	SecretExpiresAt      pgtype.Timestamptz `db:"secret_expires_at" json:"secret_expires_at"`
}

func (q *Queries) InsertMCPOAuthClient(ctx context.Context, arg InsertMCPOAuthClientParams) error {
	_, err := q.db.Exec(ctx, insertMCPOAuthClient,
		arg.ID,
		arg.ProjectID,
		arg.ActorID,
		arg.ClientID,
		arg.TokenEndpoint,
		arg.Resource,
		arg.EncryptedCredentials,
		arg.SecretExpiresAt,
	)
	return err
}

const loadMCPOAuthClient = `-- name: LoadMCPOAuthClient :one
UPDATE elitea_auth.mcp_oauth_clients
SET idle_expires_at = clock_timestamp() + interval '30 days'
WHERE id = $1 AND project_id = $2 AND actor_id = $3
  AND client_id = $4 AND token_endpoint = $5 AND resource = $6
  AND idle_expires_at > clock_timestamp()
  AND (secret_expires_at IS NULL OR secret_expires_at > clock_timestamp())
RETURNING encrypted_credentials
`

type LoadMCPOAuthClientParams struct {
	ID            string `db:"id" json:"id"`
	ProjectID     int32  `db:"project_id" json:"project_id"`
	ActorID       int32  `db:"actor_id" json:"actor_id"`
	ClientID      string `db:"client_id" json:"client_id"`
	TokenEndpoint string `db:"token_endpoint" json:"token_endpoint"`
	Resource      string `db:"resource" json:"resource"`
}

func (q *Queries) LoadMCPOAuthClient(ctx context.Context, arg LoadMCPOAuthClientParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadMCPOAuthClient,
		arg.ID,
		arg.ProjectID,
		arg.ActorID,
		arg.ClientID,
		arg.TokenEndpoint,
		arg.Resource,
	)
	var encrypted_credentials []byte
	err := row.Scan(&encrypted_credentials)
	return encrypted_credentials, err
}

const pruneMCPOAuthClients = `-- name: PruneMCPOAuthClients :exec
DELETE FROM elitea_auth.mcp_oauth_clients
WHERE id IN (
    SELECT id FROM elitea_auth.mcp_oauth_clients
    WHERE idle_expires_at <= clock_timestamp()
    ORDER BY idle_expires_at, id
    LIMIT 128
)
`

func (q *Queries) PruneMCPOAuthClients(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneMCPOAuthClients)
	return err
}
