// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkDeleteCurrentNotifications = `-- name: BulkDeleteCurrentNotifications :execrows
DELETE FROM centry.notifications
WHERE user_id = $1
  AND id = ANY($2::integer[])
`

type BulkDeleteCurrentNotificationsParams struct {
	UserID          int32   `db:"user_id" json:"user_id"`
	NotificationIds []int32 `db:"notification_ids" json:"notification_ids"`
}

func (q *Queries) BulkDeleteCurrentNotifications(ctx context.Context, arg BulkDeleteCurrentNotificationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkDeleteCurrentNotifications, arg.UserID, arg.NotificationIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkSetCurrentNotificationsSeen = `-- name: BulkSetCurrentNotificationsSeen :execrows
UPDATE centry.notifications
SET is_seen = $1,
    updated_at = NOW()
WHERE user_id = $2
  AND is_seen <> $1
  AND (
      $3::boolean
      OR id = ANY($4::integer[])
  )
`

type BulkSetCurrentNotificationsSeenParams struct {
	IsSeen           bool    `db:"is_seen" json:"is_seen"`
	UserID           int32   `db:"user_id" json:"user_id"`
	AllNotifications bool    `db:"all_notifications" json:"all_notifications"`
	NotificationIds  []int32 `db:"notification_ids" json:"notification_ids"`
}

func (q *Queries) BulkSetCurrentNotificationsSeen(ctx context.Context, arg BulkSetCurrentNotificationsSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkSetCurrentNotificationsSeen,
		arg.IsSeen,
		arg.UserID,
		arg.AllNotifications,
		arg.NotificationIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCurrentNotifications = `-- name: CountCurrentNotifications :one
SELECT COUNT(*)::bigint
FROM centry.notifications
WHERE user_id = $1
  AND (NOT $2::boolean OR NOT is_seen)
  AND ($3::text = '' OR event_type = $3)
  AND NOT EXISTS (
      SELECT 1
      FROM unnest($4::text[]) AS search_word(value)
      WHERE COALESCE(meta ->> 'message', '')
            NOT ILIKE ('%' || search_word.value || '%') ESCAPE '\'
  )
`

type CountCurrentNotificationsParams struct {
	UserID      int32    `db:"user_id" json:"user_id"`
	OnlyNew     bool     `db:"only_new" json:"only_new"`
	EventType   string   `db:"event_type" json:"event_type"`
	SearchWords []string `db:"search_words" json:"search_words"`
}

func (q *Queries) CountCurrentNotifications(ctx context.Context, arg CountCurrentNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrentNotifications,
		arg.UserID,
		arg.OnlyNew,
		arg.EventType,
		arg.SearchWords,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const currentNotificationSyncClock = `-- name: CurrentNotificationSyncClock :one
SELECT clock_timestamp()::timestamptz AS now
`

// The database clock a `changes_since` page is computed against (ADR-0025
// WP6): the stamps are written by triggers on this clock, so the settle
// bound and the expiry check must read it too, not the application's.
func (q *Queries) CurrentNotificationSyncClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, currentNotificationSyncClock)
	var now pgtype.Timestamptz
	err := row.Scan(&now)
	return now, err
}

const deleteCurrentNotification = `-- name: DeleteCurrentNotification :execrows
DELETE FROM centry.notifications
WHERE id = $1
  AND user_id = $2
`

type DeleteCurrentNotificationParams struct {
	NotificationID int32 `db:"notification_id" json:"notification_id"`
	UserID         int32 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteCurrentNotification(ctx context.Context, arg DeleteCurrentNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCurrentNotification, arg.NotificationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrentNotification = `-- name: GetCurrentNotification :one
SELECT id,
       uuid::text AS uuid,
       is_seen,
       project_id,
       user_id,
       meta,
       event_type,
       created_at,
       updated_at
FROM centry.notifications
WHERE id = $1
  AND user_id = $2
`

type GetCurrentNotificationParams struct {
	NotificationID int32 `db:"notification_id" json:"notification_id"`
	UserID         int32 `db:"user_id" json:"user_id"`
}

type GetCurrentNotificationRow struct {
	ID        int32            `db:"id" json:"id"`
	Uuid      string           `db:"uuid" json:"uuid"`
	IsSeen    bool             `db:"is_seen" json:"is_seen"`
	ProjectID int32            `db:"project_id" json:"project_id"`
	UserID    int32            `db:"user_id" json:"user_id"`
	Meta      []byte           `db:"meta" json:"meta"`
	EventType string           `db:"event_type" json:"event_type"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetCurrentNotification(ctx context.Context, arg GetCurrentNotificationParams) (GetCurrentNotificationRow, error) {
	row := q.db.QueryRow(ctx, getCurrentNotification, arg.NotificationID, arg.UserID)
	var i GetCurrentNotificationRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.IsSeen,
		&i.ProjectID,
		&i.UserID,
		&i.Meta,
		&i.EventType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurrentNotificationChanges = `-- name: ListCurrentNotificationChanges :many
SELECT id,
       uuid::text AS uuid,
       is_seen,
       project_id,
       user_id,
       meta,
       event_type,
       created_at,
       updated_at,
       sync_at
FROM centry.notifications
WHERE user_id = $1
  AND (sync_at, id) > ($2::timestamptz, $3::bigint)
ORDER BY sync_at, id
LIMIT $4
`

type ListCurrentNotificationChangesParams struct {
	UserID    int32              `db:"user_id" json:"user_id"`
	AfterAt   pgtype.Timestamptz `db:"after_at" json:"after_at"`
	AfterID   int64              `db:"after_id" json:"after_id"`
	PageLimit int32              `db:"page_limit" json:"page_limit"`
}

type ListCurrentNotificationChangesRow struct {
	ID        int32              `db:"id" json:"id"`
	Uuid      string             `db:"uuid" json:"uuid"`
	IsSeen    bool               `db:"is_seen" json:"is_seen"`
	ProjectID int32              `db:"project_id" json:"project_id"`
	UserID    int32              `db:"user_id" json:"user_id"`
	Meta      []byte             `db:"meta" json:"meta"`
	EventType string             `db:"event_type" json:"event_type"`
	CreatedAt pgtype.Timestamp   `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp   `db:"updated_at" json:"updated_at"`
	SyncAt    pgtype.Timestamptz `db:"sync_at" json:"sync_at"`
}

// The caller's notifications whose sync_at stamp (shared 0144) is after the
// cursor position, oldest change first.
func (q *Queries) ListCurrentNotificationChanges(ctx context.Context, arg ListCurrentNotificationChangesParams) ([]ListCurrentNotificationChangesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentNotificationChanges,
		arg.UserID,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentNotificationChangesRow{}
	for rows.Next() {
		var i ListCurrentNotificationChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.IsSeen,
			&i.ProjectID,
			&i.UserID,
			&i.Meta,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentNotificationTombstones = `-- name: ListCurrentNotificationTombstones :many
SELECT id,
       notification_id,
       COALESCE(notification_uuid::text, ''::text)::text AS notification_uuid,
       deleted_at
FROM centry.notification_tombstones
WHERE user_id = $1
  AND (deleted_at, id) > ($2::timestamptz, $3::bigint)
ORDER BY deleted_at, id
LIMIT $4
`

type ListCurrentNotificationTombstonesParams struct {
	UserID    int32              `db:"user_id" json:"user_id"`
	AfterAt   pgtype.Timestamptz `db:"after_at" json:"after_at"`
	AfterID   int64              `db:"after_id" json:"after_id"`
	PageLimit int32              `db:"page_limit" json:"page_limit"`
}

type ListCurrentNotificationTombstonesRow struct {
	ID               int64              `db:"id" json:"id"`
	NotificationID   int32              `db:"notification_id" json:"notification_id"`
	NotificationUuid string             `db:"notification_uuid" json:"notification_uuid"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// The caller's notification deletions after the cursor position.
func (q *Queries) ListCurrentNotificationTombstones(ctx context.Context, arg ListCurrentNotificationTombstonesParams) ([]ListCurrentNotificationTombstonesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentNotificationTombstones,
		arg.UserID,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentNotificationTombstonesRow{}
	for rows.Next() {
		var i ListCurrentNotificationTombstonesRow
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.NotificationUuid,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentNotifications = `-- name: ListCurrentNotifications :many
SELECT id,
       uuid::text AS uuid,
       is_seen,
       project_id,
       user_id,
       meta,
       event_type,
       created_at,
       updated_at
FROM centry.notifications
WHERE user_id = $1
  AND (NOT $2::boolean OR NOT is_seen)
  AND ($3::text = '' OR event_type = $3)
  AND NOT EXISTS (
      SELECT 1
      FROM unnest($4::text[]) AS search_word(value)
      WHERE COALESCE(meta ->> 'message', '')
            NOT ILIKE ('%' || search_word.value || '%') ESCAPE '\'
  )
ORDER BY
  CASE WHEN $5::text = 'id' AND $6::text = 'asc' THEN id END ASC,
  CASE WHEN $5::text = 'id' AND $6::text = 'desc' THEN id END DESC,
  CASE WHEN $5::text = 'uuid' AND $6::text = 'asc' THEN uuid END ASC,
  CASE WHEN $5::text = 'uuid' AND $6::text = 'desc' THEN uuid END DESC,
  CASE WHEN $5::text = 'is_seen' AND $6::text = 'asc' THEN is_seen END ASC,
  CASE WHEN $5::text = 'is_seen' AND $6::text = 'desc' THEN is_seen END DESC,
  CASE WHEN $5::text = 'project_id' AND $6::text = 'asc' THEN project_id END ASC,
  CASE WHEN $5::text = 'project_id' AND $6::text = 'desc' THEN project_id END DESC,
  CASE WHEN $5::text = 'user_id' AND $6::text = 'asc' THEN user_id END ASC,
  CASE WHEN $5::text = 'user_id' AND $6::text = 'desc' THEN user_id END DESC,
  CASE WHEN $5::text = 'meta' AND $6::text = 'asc' THEN meta END ASC,
  CASE WHEN $5::text = 'meta' AND $6::text = 'desc' THEN meta END DESC,
  CASE WHEN $5::text = 'event_type' AND $6::text = 'asc' THEN event_type END ASC,
  CASE WHEN $5::text = 'event_type' AND $6::text = 'desc' THEN event_type END DESC,
  CASE WHEN $5::text = 'created_at' AND $6::text = 'asc' THEN created_at END ASC,
  CASE WHEN $5::text = 'created_at' AND $6::text = 'desc' THEN created_at END DESC,
  CASE WHEN $5::text = 'updated_at' AND $6::text = 'asc' THEN updated_at END ASC,
  CASE WHEN $5::text = 'updated_at' AND $6::text = 'desc' THEN updated_at END DESC,
  id DESC
LIMIT $8
OFFSET $7
`

type ListCurrentNotificationsParams struct {
	UserID      int32    `db:"user_id" json:"user_id"`
	OnlyNew     bool     `db:"only_new" json:"only_new"`
	EventType   string   `db:"event_type" json:"event_type"`
	SearchWords []string `db:"search_words" json:"search_words"`
	SortBy      string   `db:"sort_by" json:"sort_by"`
	SortOrder   string   `db:"sort_order" json:"sort_order"`
	PageOffset  int32    `db:"page_offset" json:"page_offset"`
	PageLimit   int32    `db:"page_limit" json:"page_limit"`
}

type ListCurrentNotificationsRow struct {
	ID        int32            `db:"id" json:"id"`
	Uuid      string           `db:"uuid" json:"uuid"`
	IsSeen    bool             `db:"is_seen" json:"is_seen"`
	ProjectID int32            `db:"project_id" json:"project_id"`
	UserID    int32            `db:"user_id" json:"user_id"`
	Meta      []byte           `db:"meta" json:"meta"`
	EventType string           `db:"event_type" json:"event_type"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListCurrentNotifications(ctx context.Context, arg ListCurrentNotificationsParams) ([]ListCurrentNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentNotifications,
		arg.UserID,
		arg.OnlyNew,
		arg.EventType,
		arg.SearchWords,
		arg.SortBy,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentNotificationsRow{}
	for rows.Next() {
		var i ListCurrentNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.IsSeen,
			&i.ProjectID,
			&i.UserID,
			&i.Meta,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCurrentNotificationSeen = `-- name: MarkCurrentNotificationSeen :one
WITH changed AS (
    UPDATE centry.notifications AS notification
    SET is_seen = TRUE,
        updated_at = NOW()
    WHERE notification.id = $1
      AND notification.user_id = $2
      AND NOT notification.is_seen
    RETURNING notification.id,
              notification.uuid::text AS uuid,
              notification.is_seen,
              notification.project_id,
              notification.user_id,
              notification.meta,
              notification.event_type,
              notification.created_at,
              notification.updated_at
)
SELECT id, uuid, is_seen, project_id, user_id, meta, event_type, created_at, updated_at FROM changed
UNION ALL
SELECT id,
       uuid::text AS uuid,
       is_seen,
       project_id,
       user_id,
       meta,
       event_type,
       created_at,
       updated_at
FROM centry.notifications
WHERE id = $1
  AND user_id = $2
  AND NOT EXISTS (SELECT 1 FROM changed)
LIMIT 1
`

type MarkCurrentNotificationSeenParams struct {
	NotificationID int32 `db:"notification_id" json:"notification_id"`
	UserID         int32 `db:"user_id" json:"user_id"`
}

type MarkCurrentNotificationSeenRow struct {
	ID        int32            `db:"id" json:"id"`
	Uuid      string           `db:"uuid" json:"uuid"`
	IsSeen    bool             `db:"is_seen" json:"is_seen"`
	ProjectID int32            `db:"project_id" json:"project_id"`
	UserID    int32            `db:"user_id" json:"user_id"`
	Meta      []byte           `db:"meta" json:"meta"`
	EventType string           `db:"event_type" json:"event_type"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) MarkCurrentNotificationSeen(ctx context.Context, arg MarkCurrentNotificationSeenParams) (MarkCurrentNotificationSeenRow, error) {
	row := q.db.QueryRow(ctx, markCurrentNotificationSeen, arg.NotificationID, arg.UserID)
	var i MarkCurrentNotificationSeenRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.IsSeen,
		&i.ProjectID,
		&i.UserID,
		&i.Meta,
		&i.EventType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
