// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pgvector.sql

package sqlcgen

import (
	"context"
)

const deleteCurrentProjectPgvectorConfiguration = `-- name: DeleteCurrentProjectPgvectorConfiguration :execrows

DELETE FROM configuration
WHERE project_id = $1::integer
  AND elitea_title = $2::text
  AND type = 'pgvector'
  AND section = 'vectorstorage'
  AND source = 'system'
`

type DeleteCurrentProjectPgvectorConfigurationParams struct {
	ProjectID   int32  `db:"project_id" json:"project_id"`
	EliteaTitle string `db:"elitea_title" json:"elitea_title"`
}

// The exact inverse of the statement above, and only that row. The four
// identity predicates repeat the ones the upsert conflicts on, so a
// user-created configuration that happens to carry the same title is never
// removed by a rollback of the system row.
func (q *Queries) DeleteCurrentProjectPgvectorConfiguration(ctx context.Context, arg DeleteCurrentProjectPgvectorConfigurationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCurrentProjectPgvectorConfiguration, arg.ProjectID, arg.EliteaTitle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existsCurrentProjectPgvectorConfiguration = `-- name: ExistsCurrentProjectPgvectorConfiguration :one

SELECT EXISTS (
    SELECT 1 FROM configuration
    WHERE project_id = $1::integer
      AND elitea_title = $2::text
      AND type = 'pgvector'
      AND section = 'vectorstorage'
      AND source = 'system'
) AS present
`

type ExistsCurrentProjectPgvectorConfigurationParams struct {
	ProjectID   int32  `db:"project_id" json:"project_id"`
	EliteaTitle string `db:"elitea_title" json:"elitea_title"`
}

// Whether the project's system PgVector row exists. It reads the same four
// identity predicates the upsert and the delete above use, so a user-created
// configuration that happens to carry the title does not count. The project
// delete asks it inside its deciding transaction (#1211).
func (q *Queries) ExistsCurrentProjectPgvectorConfiguration(ctx context.Context, arg ExistsCurrentProjectPgvectorConfigurationParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsCurrentProjectPgvectorConfiguration, arg.ProjectID, arg.EliteaTitle)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const upsertCurrentProjectPgvectorConfiguration = `-- name: UpsertCurrentProjectPgvectorConfiguration :one

INSERT INTO configuration (
    uuid,
    project_id,
    label,
    elitea_title,
    type,
    section,
    data,
    meta,
    shared,
    status_ok,
    status_logs,
    source,
    author_id
) VALUES (
    $1::text::uuid,
    $2::integer,
    $3::text,
    $4::text,
    'pgvector',
    'vectorstorage',
    jsonb_build_object(
        'connection_string',
        '{{secret.pgvector_project_connstr}}'::text
    ),
    '{}'::jsonb,
    false,
    true,
    NULL,
    'system',
    NULL
)
ON CONFLICT (elitea_title) DO UPDATE
SET data = EXCLUDED.data,
    updated_at = now()
WHERE configuration.project_id = EXCLUDED.project_id
  AND configuration.type = EXCLUDED.type
  AND configuration.section = EXCLUDED.section
  AND configuration.source = EXCLUDED.source
RETURNING id
`

type UpsertCurrentProjectPgvectorConfigurationParams struct {
	ConfigurationUuid string  `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32   `db:"project_id" json:"project_id"`
	Label             *string `db:"label" json:"label"`
	EliteaTitle       string  `db:"elitea_title" json:"elitea_title"`
}

// The project transaction establishes the authorized p_<project_id>
// search_path before this statement runs. The public PgVector bootstrap
// configuration is never copied into this tenant row: only the current vault
// reference is stored.
func (q *Queries) UpsertCurrentProjectPgvectorConfiguration(ctx context.Context, arg UpsertCurrentProjectPgvectorConfigurationParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertCurrentProjectPgvectorConfiguration,
		arg.ConfigurationUuid,
		arg.ProjectID,
		arg.Label,
		arg.EliteaTitle,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
