// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireAuthProviderAdvisoryLock(ctx context.Context, providerRef string) error
	AddNewAuthUserToRootGroup(ctx context.Context, userID int32) (int64, error)
	AdvanceScheduledJobCursor(ctx context.Context, arg AdvanceScheduledJobCursorParams) (int64, error)
	AllocateIndexGeneration(ctx context.Context, arg AllocateIndexGenerationParams) (int64, error)
	AssignAuthUserRoleByNameAndMode(ctx context.Context, arg AssignAuthUserRoleByNameAndModeParams) (int64, error)
	AssignExistingProjectRoles(ctx context.Context, arg AssignExistingProjectRolesParams) (int64, error)
	AuthorizeRuntimeValidationProject(ctx context.Context, arg AuthorizeRuntimeValidationProjectParams) (bool, error)
	BulkDeleteCurrentNotifications(ctx context.Context, arg BulkDeleteCurrentNotificationsParams) (int64, error)
	BulkSetCurrentNotificationsSeen(ctx context.Context, arg BulkSetCurrentNotificationsSeenParams) (int64, error)
	// Exact current-platform containment for tracing credentials. Project role
	// identifiers are compared exactly: billing-admin does
	// not carry administrator authority. The personal-project signal is
	// independent of role assignment so a missing role row cannot revoke an
	// owner's access to project_user_<userID>.
	CanManageCurrentTracingConfiguration(ctx context.Context, arg CanManageCurrentTracingConfigurationParams) (bool, error)
	CancelCurrentAgentExecution(ctx context.Context, arg CancelCurrentAgentExecutionParams) (CancelCurrentAgentExecutionRow, error)
	// Claim only the oldest unfinished revision for each configuration. A lower
	// pending, retrying, processing, or dead revision remains an explicit ordering
	// barrier. Expired processing rows are reclaimed with a new caller-owned lease
	// token. Expired rows already at the attempt cap are retired in a bounded
	// batch and remain dead ordering barriers. The transaction ends with this
	// statement; reconciliation happens outside the database transaction.
	ClaimConfigurationLifecycleEvents(ctx context.Context, arg ClaimConfigurationLifecycleEventsParams) ([]ClaimConfigurationLifecycleEventsRow, error)
	ClaimExactIndexMetaInitialization(ctx context.Context, arg ClaimExactIndexMetaInitializationParams) (ClaimExactIndexMetaInitializationRow, error)
	// Claims a bounded batch of expired, unconsumed grants for the retention
	// sweeper, and returns what it needs to reclaim the bytes.
	//
	// WHY THIS EXISTS. CreateArtifactTransferGrant hands out a presigned PUT and
	// writes only this row. The elitea_storage.objects row appears at commit and
	// nowhere else. A caller who uploads to the signed URL and never commits
	// therefore leaves bytes with no metadata row: SumArtifactProjectBytes cannot
	// count them against max_total_bytes, and ListExpiredArtifactObjects cannot
	// see them, because both read only the objects table. Nothing time-driven
	// reclaimed them.
	//
	// WHY IT CLAIMS INSTEAD OF SELECTING. Setting consumed_at in the same
	// statement that selects the row is what makes the sweep safe against a
	// commit in flight. MarkArtifactTransferGrantConsumed already carries
	// `AND consumed_at IS NULL`, so a commit that races a claimed grant loses the
	// mark and answers 409. A plain SELECT followed by a delete has the opposite
	// outcome. The commit writes a metadata row. The sweeper then deletes the
	// bytes underneath it. The project is charged for an object that no longer
	// exists, and no later sweep can heal that.
	//
	// FOR UPDATE SKIP LOCKED lets two replicas sweep at the same time without
	// either waiting on the other. The row itself is kept, not deleted, so a late
	// commit still sees the 409 rather than a 404.
	ClaimExpiredArtifactTransferGrants(ctx context.Context, arg ClaimExpiredArtifactTransferGrantsParams) ([]ClaimExpiredArtifactTransferGrantsRow, error)
	ClaimPendingIndexMetaInitializations(ctx context.Context, arg ClaimPendingIndexMetaInitializationsParams) ([]ClaimPendingIndexMetaInitializationsRow, error)
	ClaimScheduledJobCursor(ctx context.Context, arg ClaimScheduledJobCursorParams) (int64, error)
	ClaimScheduledOccurrence(ctx context.Context, arg ClaimScheduledOccurrenceParams) (int64, error)
	CompareAndSwapCurrentConfigurationRenameToolkit(ctx context.Context, arg CompareAndSwapCurrentConfigurationRenameToolkitParams) (int64, error)
	CompleteScheduledOccurrence(ctx context.Context, arg CompleteScheduledOccurrenceParams) (int64, error)
	// The tenant executor installs a transaction-local search_path. These queries
	// never accept a schema from the caller.
	CopyApplicationVersionSkills(ctx context.Context, arg CopyApplicationVersionSkillsParams) (int64, error)
	CountActiveRuntimeExecutionsUpTo(ctx context.Context, arg CountActiveRuntimeExecutionsUpToParams) (int64, error)
	CountArtifactBucketObjects(ctx context.Context, bucketID int64) (int64, error)
	CountAttachmentChunks(ctx context.Context, arg CountAttachmentChunksParams) (int64, error)
	CountAuthUserRolesInMode(ctx context.Context, arg CountAuthUserRolesInModeParams) (int64, error)
	CountCurrentConfigurations(ctx context.Context, arg CountCurrentConfigurationsParams) (int64, error)
	CountCurrentNotifications(ctx context.Context, arg CountCurrentNotificationsParams) (int64, error)
	CountCurrentSharedConfigurations(ctx context.Context, arg CountCurrentSharedConfigurationsParams) (int64, error)
	CreateArtifactBucket(ctx context.Context, arg CreateArtifactBucketParams) (EliteaStorageBucket, error)
	// id::text/RETURNING id::text: transfer_grants.id is a native uuid column;
	// casting to text on both sides keeps the Go-side type a plain string,
	// matching this codebase's established convention (e.g.
	// InsertArtifactBucketExpiryNotification, S14) rather than pgtype.UUID.
	// upload_id (S16) is set only when CreateTransferGrant started a native
	// multipart upload; a normal single-shot grant passes it as NULL.
	CreateArtifactTransferGrant(ctx context.Context, arg CreateArtifactTransferGrantParams) (CreateArtifactTransferGrantRow, error)
	CreateAuthUserByEmailIfMissing(ctx context.Context, arg CreateAuthUserByEmailIfMissingParams) (AuthCoreUser, error)
	CreatePATForActiveUser(ctx context.Context, arg CreatePATForActiveUserParams) (CreatePATForActiveUserRow, error)
	// A binding is written once, in the same transaction as the token INSERT, and
	// after the membership check. There is no update query on purpose: a binding is
	// a fact about a key, not a setting that changes under a running integration
	// (spec-llm-project-scope §4).
	CreateTokenProjectBinding(ctx context.Context, arg CreateTokenProjectBindingParams) error
	//
	// Is a response in this conversation still marked as being written?
	//
	// WHY THIS EXISTS, and why it is not the overlap gate itself. The overlap gate
	// lives twice, in the WHERE of ResolveCurrentApplicationTurn /
	// ResolveCurrentAdhocTurn and again in InsertCurrentApplicationTurn /
	// InsertCurrentAdhocTurn, where it is race-free. Neither can say WHY it matched
	// nothing: both simply return no rows, and the caller answers 422
	// `unsupported_agent_execution` for all ~25 reasons at once.
	//
	// One of those reasons is not a refusal at all, it is a WINDOW. The browser
	// ends a turn on the `pipeline_finish` node event (the client predicate is
	// apps/elitea-web/src/features/chat-messages/lib/chatStreamTurnEnd.ts) and
	// re-enables the composer there. `is_streaming` is only cleared later, by
	// FinalizeCurrentAgentFullMessage, when the WORKER's separate terminal output
	// frame is projected. Measured on the standalone stack: `pipeline_finish`
	// durable at 21:53:47.319, composer released at ~.55, second send at .621,
	// `is_streaming` cleared at .824 — the second turn was refused 422 inside a
	// ~500ms window in which the product had already invited it.
	//
	// This probe answers only "is that window open", so the start path can WAIT for
	// it to close rather than refusing a turn the user was invited to send. It is
	// deliberately BROADER than the gate (no newest-response or retried-question
	// narrowing): a superset only ever costs a bounded wait that then falls through
	// to the same answer, whereas restating those sub-clauses would put a third
	// copy of the gate in the tree for them to drift apart.
	CurrentConversationResponseSettling(ctx context.Context, conversationUuid pgtype.UUID) (bool, error)
	// The social access feature is optional. Return 0 when its override table is
	// absent, including the older organization-only folder schema. Return 1 when
	// the complete access projection exists. Return -1 when overrides exist
	// without their dependencies, which the repository refuses.
	CurrentFolderAccessState(ctx context.Context) (int32, error)
	CurrentNotificationHighWater(ctx context.Context, userID int32) (int64, error)
	// entity_skill_mapping is polymorphic and has no version FK. Remove only the
	// bindings of the version actually deleted, including on create compensation.
	DeleteApplicationVersionWithSkills(ctx context.Context, arg DeleteApplicationVersionWithSkillsParams) (int64, error)
	DeleteArtifactObjectRows(ctx context.Context, ids []int64) (int64, error)
	DeleteArtifactObjects(ctx context.Context, arg DeleteArtifactObjectsParams) (int64, error)
	DeleteAttachmentChunks(ctx context.Context, arg DeleteAttachmentChunksParams) (int64, error)
	DeleteCurrentAgentProvisionalText(ctx context.Context, arg DeleteCurrentAgentProvisionalTextParams) error
	DeleteCurrentConfiguration(ctx context.Context, arg DeleteCurrentConfigurationParams) (int32, error)
	DeleteCurrentNotification(ctx context.Context, arg DeleteCurrentNotificationParams) (int64, error)
	// The exact inverse of the statement above, and only that row. The four
	// identity predicates repeat the ones the upsert conflicts on, so a
	// user-created configuration that happens to carry the same title is never
	// removed by a rollback of the system row.
	DeleteCurrentProjectPgvectorConfiguration(ctx context.Context, arg DeleteCurrentProjectPgvectorConfigurationParams) (int64, error)
	DeletePATByID(ctx context.Context, id int32) (int64, error)
	// Reclaims chunk rows for a chunked upload that was abandoned before its
	// final chunk arrived (browser tab closed, connection lost) — the only
	// other path that deletes these rows is the completed-merge path
	// (DeleteAttachmentChunks above), which an abandoned upload never reaches.
	// Legacy's equivalent is utils/file_utils.py's cleanup_stale_chunks, a
	// 12-hour local-disk TTL swept by the elitea_core_cleanup_stale_chunks RPC.
	DeleteStaleAttachmentChunks(ctx context.Context, receivedAt pgtype.Timestamptz) (int64, error)
	// The list and get responses read the binding back through the LEFT JOIN
	// above, so no point-read query exists. A separate read would be a second round
	// trip for a value the same row already carries.
	// Token deletion deletes the binding explicitly, in the same transaction, and
	// does NOT rely on ON DELETE CASCADE (spec-llm-project-scope §3.1). Migration
	// 0071 guards its foreign key with to_regclass, because elitea-migrate can run
	// before pylon creates auth_core. When the guard skips, the migration is still
	// ledgered as applied and no later run adds the constraint, so that database
	// has no cascade for its whole life. The constraint stays as the second of two
	// independent guarantees; this query is the first.
	DeleteTokenProjectBinding(ctx context.Context, tokenID int32) error
	EnsureRuntimeAdmissionPolicy(ctx context.Context, arg EnsureRuntimeAdmissionPolicyParams) error
	FinalizeCurrentAgentAuthorizationPause(ctx context.Context, arg FinalizeCurrentAgentAuthorizationPauseParams) (int64, error)
	FinalizeCurrentAgentFullMessage(ctx context.Context, arg FinalizeCurrentAgentFullMessageParams) (int64, error)
	FinalizeCurrentAgentHITLPause(ctx context.Context, arg FinalizeCurrentAgentHITLPauseParams) (int64, error)
	// These unqualified names are intentional. Every query is executed inside a
	// transaction whose local search_path is derived from the authorized project.
	// This file projects the existing 16-column tenant table; it does not define a
	// replacement configuration store.
	FindCurrentConfigurationByEliteaTitle(ctx context.Context, arg FindCurrentConfigurationByEliteaTitleParams) (FindCurrentConfigurationByEliteaTitleRow, error)
	// The current Configurations -> LiteLLM model projection keys embedding
	// models by data.name. A two-row sentinel lets the adapter reject duplicate
	// mutable definitions instead of selecting one silently.
	FindCurrentEmbeddingConfigurations(ctx context.Context, arg FindCurrentEmbeddingConfigurationsParams) ([]FindCurrentEmbeddingConfigurationsRow, error)
	GetActivePATForUser(ctx context.Context, userID int32) (GetActivePATForUserRow, error)
	GetActivePATPrincipalByID(ctx context.Context, tokenID int32) (GetActivePATPrincipalByIDRow, error)
	// This is the single query the credential validator runs for every request.
	// The token binding rides along on the row the validator already reads, so a
	// bound token costs no additional round trip on the request path
	// (spec-llm-project-scope §3.2). Do not split it into a second lookup.
	//
	// bound_project_active carries the lifecycle state of the bound project on the
	// same row, for the same reason. Suspension is a reversible boolean on
	// centry.project and revokes no binding, so a bound token kept spending a
	// suspended project's budget and credentials. The middleware re-checks the
	// state here instead (spec-llm-project-scope §7 invariant 3).
	//
	// BOTH joins must stay LEFT joins. Most personal access tokens carry no
	// binding, and an inner join on centry.project would drop every one of those
	// rows. That breaks authentication for the majority of callers.
	GetActivePATPrincipalByUUID(ctx context.Context, uuid string) (GetActivePATPrincipalByUUIDRow, error)
	GetActiveProjectSystemPAT(ctx context.Context, projectID int32) (GetActiveProjectSystemPATRow, error)
	GetActiveUserPrincipalByID(ctx context.Context, userID int32) (GetActiveUserPrincipalByIDRow, error)
	GetAgentExecutionAdmissionByIdempotency(ctx context.Context, arg GetAgentExecutionAdmissionByIdempotencyParams) (GetAgentExecutionAdmissionByIdempotencyRow, error)
	GetAgentExecutionTerminalNodeEvent(ctx context.Context, arg GetAgentExecutionTerminalNodeEventParams) (GetAgentExecutionTerminalNodeEventRow, error)
	GetArtifactBucket(ctx context.Context, arg GetArtifactBucketParams) (EliteaStorageBucket, error)
	// ListExpiredArtifactObjects (below) has no request-bound project scope — it
	// scans elitea_storage.objects across every project, which only carries
	// bucket_id, not project_id/name. The retention sweeper (S14) uses this to
	// resolve the (project_id, bucket name) a physical ObjectRef needs before it
	// can delete an expired object's bytes from the ObjectStore backend.
	GetArtifactBucketByID(ctx context.Context, id int64) (EliteaStorageBucket, error)
	// elitea_storage.buckets has no user-identifying column of its own (S8 never
	// captured a creating user) — the retention sweeper (S14) resolves a
	// notification recipient via centry.project.owner_id instead, the only
	// existing project->user mapping that needs no new schema. See
	// docs/plans/storage-migration-plan.md S14's note on this open question.
	GetArtifactBucketOwningProjectUserID(ctx context.Context, id int32) (int32, error)
	GetArtifactProjectStoragePolicy(ctx context.Context, projectID int64) (EliteaStorageProjectStoragePolicy, error)
	// Scoped by project_id, not just id: grant IDs are unguessable UUIDs, but
	// every other artifact route requires a matching {projectID}, and this one
	// should not be the exception that lets a caller commit a grant belonging
	// to a project they only guessed the ID for.
	GetArtifactTransferGrant(ctx context.Context, arg GetArtifactTransferGrantParams) (GetArtifactTransferGrantRow, error)
	// Unscoped by project_id, unlike GetArtifactTransferGrant above — used only
	// by S16's multipart continuation endpoints (part presign, complete,
	// abort), which must distinguish "grant does not exist" (404) from "grant
	// exists but belongs to a different project" (403 AccessDenied): the
	// plan's own S16 acceptance criterion ("a part call with another project's
	// grant returns 403") requires exactly that distinction, which a
	// project-scoped WHERE clause can't make — a wrong project and a
	// nonexistent id both return zero rows. See handler.go's
	// requireOwnedMultipartGrant for where the 403 decision actually happens.
	GetArtifactTransferGrantByID(ctx context.Context, id string) (GetArtifactTransferGrantByIDRow, error)
	GetAuthUserByEmailForProvisioning(ctx context.Context, email string) (AuthCoreUser, error)
	GetAuthUserByProviderForProvisioning(ctx context.Context, providerRef string) (AuthCoreUser, error)
	GetCurrentActiveAuthUser(ctx context.Context, userID int32) (AuthCoreUser, error)
	GetCurrentAgentInvokedSkills(ctx context.Context, messageGroupID int64) (string, error)
	// The read half of the legacy `application_task` surface. It resolves the
	// durable execution from the RESPONSE MESSAGE, exactly the way
	// CancelCurrentAgentExecution does, so a caller can never name a foreign
	// execution id and read another project's run state.
	//
	// The ownership predicate is byte-for-byte the cancel query's: the caller owns
	// the conversation, or the caller wrote the question this response answers.
	// A reader that could see more than the canceller could stop would be a
	// disclosure the cancel path already refuses.
	GetCurrentAgentTaskStatus(ctx context.Context, arg GetCurrentAgentTaskStatusParams) (GetCurrentAgentTaskStatusRow, error)
	GetCurrentAgentTraceBinding(ctx context.Context, arg GetCurrentAgentTraceBindingParams) (GetCurrentAgentTraceBindingRow, error)
	GetCurrentConfiguration(ctx context.Context, arg GetCurrentConfigurationParams) (GetCurrentConfigurationRow, error)
	GetCurrentConfigurationRenameToolkit(ctx context.Context, arg GetCurrentConfigurationRenameToolkitParams) (GetCurrentConfigurationRenameToolkitRow, error)
	// Current-platform folder access is a restrictive overlay on project RBAC.
	// A toolkit outside a folder, or inside a folder without an override, remains
	// visible. A no_access override hides both toolkit and MCP folder item kinds.
	GetCurrentMCPToolkitVisibleToActor(ctx context.Context, arg GetCurrentMCPToolkitVisibleToActorParams) (EliteaTool, error)
	// Raw data is intentional: the Go adapter performs type-safe, redacted
	// decoding before applying section-specific response shaping. ID order gives
	// duplicate candidates a deterministic baseline order.
	GetCurrentModelCatalogBounds(ctx context.Context, arg GetCurrentModelCatalogBoundsParams) (GetCurrentModelCatalogBoundsRow, error)
	GetCurrentNotification(ctx context.Context, arg GetCurrentNotificationParams) (GetCurrentNotificationRow, error)
	GetCurrentTenantSchema(ctx context.Context) (string, error)
	// The unqualified table name is intentional. This query runs only inside an
	// authorized project transaction whose local search_path is p_<project_id>.
	GetCurrentToolkit(ctx context.Context, toolkitID int32) (EliteaTool, error)
	GetDurableIndexResultArtifact(ctx context.Context, arg GetDurableIndexResultArtifactParams) (GetDurableIndexResultArtifactRow, error)
	GetExpectedAgentExecutionHeader(ctx context.Context, arg GetExpectedAgentExecutionHeaderParams) (GetExpectedAgentExecutionHeaderRow, error)
	GetExpectedIndexIngestHeader(ctx context.Context, arg GetExpectedIndexIngestHeaderParams) (GetExpectedIndexIngestHeaderRow, error)
	// GetExpectedToolkitCallToolHeader is the output plane's admitted-binding read.
	// Unlike its agent counterpart it needs no capability-owned table: everything
	// it returns is on execution_jobs, input_bundles and input_bundle_entries.
	//
	GetExpectedToolkitCallToolHeader(ctx context.Context, arg GetExpectedToolkitCallToolHeaderParams) (GetExpectedToolkitCallToolHeaderRow, error)
	GetExpectedToolkitExecuteReadHeader(ctx context.Context, arg GetExpectedToolkitExecuteReadHeaderParams) (GetExpectedToolkitExecuteReadHeaderRow, error)
	// S20c: keyed only by the table's actual primary key, no execution_jobs
	// join — used both by CommitArtifact's duplicate-PK reconciliation (decide
	// exact-retry vs genuine conflict) and by ResolveArtifact (find the
	// storage_record_id to resolve a read grant against). Unlike
	// GetDurableIndexResultArtifact above, this does not re-check
	// tenant/projection/command identity; ResolveArtifact does that itself
	// against the row's own execution_id/generation/resource_project_id.
	GetIndexResultArtifactByPrimaryKey(ctx context.Context, arg GetIndexResultArtifactByPrimaryKeyParams) (GetIndexResultArtifactByPrimaryKeyRow, error)
	// The project vault row serializes configuration mutations for one project,
	// so selecting the last indexed revision is sufficient inside the same
	// transaction. The unique key remains the final integrity fence.
	GetLatestConfigurationLifecycleRevision(ctx context.Context, arg GetLatestConfigurationLifecycleRevisionParams) (int64, error)
	GetOwnedPAT(ctx context.Context, arg GetOwnedPATParams) (GetOwnedPATRow, error)
	GetPendingAgentExecutionDispatch(ctx context.Context, arg GetPendingAgentExecutionDispatchParams) (GetPendingAgentExecutionDispatchRow, error)
	GetPendingToolkitExecuteReadDispatch(ctx context.Context, arg GetPendingToolkitExecuteReadDispatchParams) (GetPendingToolkitExecuteReadDispatchRow, error)
	GetPreparedAgentExecutionEnvelope(ctx context.Context, arg GetPreparedAgentExecutionEnvelopeParams) (GetPreparedAgentExecutionEnvelopeRow, error)
	GetPreparedToolkitExecuteReadEnvelope(ctx context.Context, arg GetPreparedToolkitExecuteReadEnvelopeParams) (GetPreparedToolkitExecuteReadEnvelopeRow, error)
	GetRuntimeAdmissionByIdempotency(ctx context.Context, arg GetRuntimeAdmissionByIdempotencyParams) (GetRuntimeAdmissionByIdempotencyRow, error)
	GetScheduledJobCursorForUpdate(ctx context.Context, jobID string) (GetScheduledJobCursorForUpdateRow, error)
	// toolkit.call_tool.v1 — the producer's durable half.
	//
	// WHY THERE IS NO PER-CAPABILITY BINDING TABLE HERE. index.ingest.v1 and
	// agent.execute.*.v1 each own one (`index_ingest_jobs`, `agent_execution_jobs`)
	// because a BACKGROUND publisher rebuilds their command minutes later, from the
	// database alone. A tool run is admitted and dispatched inside ONE bounded
	// synchronous request, so the command scalars the worker needs — toolkit type,
	// tool name, toolkit id and version — never leave the process that built them
	// and never need a row. The two input entry ids are recovered from
	// `input_bundle_entries.semantic_role`, which is already durable.
	//
	// What that costs, stated rather than hidden: a crash between admission and the
	// Redis append leaves an outbox row that nothing will ever publish. That is the
	// right answer for a synchronous run — the caller's request died with the
	// process, so "nothing ran" is true — but the row must not go on consuming
	// admission capacity, which is what
	// LockExpiredNoAuthorityToolkitCallToolExecutions below is for.
	//
	// Every JOIN the agent queries make to `agent_execution_jobs` is replaced by the
	// capability predicate those queries ALREADY carry beside it. The join was
	// scoping, not data, on every one of them except the pending-dispatch load,
	// which this capability does not have.
	GetToolkitCallToolAdmissionByIdempotency(ctx context.Context, arg GetToolkitCallToolAdmissionByIdempotencyParams) (GetToolkitCallToolAdmissionByIdempotencyRow, error)
	// GetToolkitCallToolInputEntries recovers the two entry ids the worker command
	// names, from the roles that are already durable. It is the reason this
	// capability needs no binding table of its own.
	//
	GetToolkitCallToolInputEntries(ctx context.Context, arg GetToolkitCallToolInputEntriesParams) ([]GetToolkitCallToolInputEntriesRow, error)
	GetToolkitExecuteReadAdmissionByIdempotency(ctx context.Context, arg GetToolkitExecuteReadAdmissionByIdempotencyParams) (GetToolkitExecuteReadAdmissionByIdempotencyRow, error)
	GetToolkitExecuteReadCompletion(ctx context.Context, arg GetToolkitExecuteReadCompletionParams) (GetToolkitExecuteReadCompletionRow, error)
	HasAuthAdministrationAdminRole(ctx context.Context, userID int32) (bool, error)
	InsertAgentExecutionBinding(ctx context.Context, arg InsertAgentExecutionBindingParams) error
	InsertAgentExecutionJob(ctx context.Context, arg InsertAgentExecutionJobParams) (string, error)
	InsertArtifactBucketExpiryNotification(ctx context.Context, arg InsertArtifactBucketExpiryNotificationParams) (int64, error)
	InsertConfigurationLifecycleEvent(ctx context.Context, arg InsertConfigurationLifecycleEventParams) error
	InsertCurrentAdhocTurn(ctx context.Context, arg InsertCurrentAdhocTurnParams) (InsertCurrentAdhocTurnRow, error)
	// #606: one uploaded chat attachment, as an `attachment_message` item on the
	// QUESTION group plus its 1:1 payload row.
	//
	// Both rows in ONE statement, via a data-modifying CTE, rather than two calls:
	// chat_messages_attachment's primary key IS the item's id (0127 shares the
	// key so the discriminator and the payload cannot disagree), so the payload
	// insert must see the id the item insert generated. Doing it in one statement
	// also means there is no window in which an `attachment_message` item exists
	// with no payload — the shape ListMessageGroups treats as "no attachment row"
	// and renders as nothing.
	//
	// order_index is supplied, not computed with count(*) the way
	// InsertCurrentAgentTextItem does it: these items are written inside the
	// admission transaction immediately after the question item, so the caller
	// already knows the sequence (1, 2, ... — the question's text item holds 0,
	// matching pylon's enumerate(attachments_info, start=1) at
	// rpc/chat_all.py:303). A count(*) here would additionally re-read a table it
	// is writing to, per attachment.
	//
	// `content` is cast to json, NOT jsonb: 0127 records why the deployed column
	// is json (a shared table pylon also reads/writes, where jsonb's key
	// reordering and whitespace normalisation would change the stored bytes).
	InsertCurrentAgentAttachmentItem(ctx context.Context, arg InsertCurrentAgentAttachmentItemParams) error
	InsertCurrentAgentTextContent(ctx context.Context, arg InsertCurrentAgentTextContentParams) error
	InsertCurrentAgentTextItem(ctx context.Context, messageGroupID int64) (int32, error)
	InsertCurrentApplicationTurn(ctx context.Context, arg InsertCurrentApplicationTurnParams) (InsertCurrentApplicationTurnRow, error)
	InsertCurrentConfiguration(ctx context.Context, arg InsertCurrentConfigurationParams) (InsertCurrentConfigurationRow, error)
	InsertCurrentIndexScheduleNotification(ctx context.Context, arg InsertCurrentIndexScheduleNotificationParams) (int64, error)
	InsertCurrentIndexTerminalNotification(ctx context.Context, arg InsertCurrentIndexTerminalNotificationParams) (int64, error)
	InsertIndexIngestExecutionJob(ctx context.Context, arg InsertIndexIngestExecutionJobParams) (string, error)
	InsertIndexIngestJob(ctx context.Context, arg InsertIndexIngestJobParams) error
	// S20c: the writer side of elitea_runtime.index_result_artifacts —
	// GetDurableIndexResultArtifact above is the pre-existing read side
	// (ArtifactVerifier.VerifyDurable), this is IndexResultArtifactWriter's own
	// CommitArtifact. No ON CONFLICT: a (artifact_id, immutable_version)
	// collision is handled in Go (repos.IndexResultArtifactWriter), which
	// distinguishes a safe exact-content retry from a genuine identity
	// conflict — a bare ON CONFLICT DO NOTHING can't make that distinction
	// from the write alone.
	//
	// metadata_created_at is set explicitly to the same value as
	// bytes_verified_at, rather than left to its own DEFAULT clock_timestamp()
	// — confirmed empirically (a real 23514 violation, not by inspection) that
	// a client-computed bytes_verified_at is always microseconds earlier than
	// a server-side DEFAULT evaluated at INSERT time, which the table's own
	// index_result_artifact_verified_order CHECK (bytes_verified_at >=
	// metadata_created_at) rejects. Reusing one Go-computed timestamp for both
	// columns guarantees equality, which satisfies >=.
	InsertIndexResultArtifact(ctx context.Context, arg InsertIndexResultArtifactParams) (InsertIndexResultArtifactRow, error)
	InsertMCPOAuthClient(ctx context.Context, arg InsertMCPOAuthClientParams) error
	InsertRuntimeCommandOutbox(ctx context.Context, arg InsertRuntimeCommandOutboxParams) error
	InsertRuntimeInputBundle(ctx context.Context, arg InsertRuntimeInputBundleParams) error
	InsertRuntimeInputBundleEntry(ctx context.Context, arg InsertRuntimeInputBundleEntryParams) error
	InsertScheduledJobCursor(ctx context.Context, arg InsertScheduledJobCursorParams) error
	InsertScheduledOccurrence(ctx context.Context, arg InsertScheduledOccurrenceParams) error
	InsertToolkitCallToolJob(ctx context.Context, arg InsertToolkitCallToolJobParams) (string, error)
	InsertToolkitExecuteReadBinding(ctx context.Context, arg InsertToolkitExecuteReadBindingParams) error
	InsertToolkitExecuteReadJob(ctx context.Context, arg InsertToolkitExecuteReadJobParams) (string, error)
	InsertToolkitExecuteReadResult(ctx context.Context, arg InsertToolkitExecuteReadResultParams) error
	InstallCurrentTenantSearchPath(ctx context.Context, searchPath string) (string, error)
	IsCurrentAgentCancellationReplay(ctx context.Context, arg IsCurrentAgentCancellationReplayParams) (bool, error)
	IsCurrentUserProjectMember(ctx context.Context, arg IsCurrentUserProjectMemberParams) (bool, error)
	LinkAuthProviderIfMissing(ctx context.Context, arg LinkAuthProviderIfMissingParams) (int64, error)
	ListActiveCurrentProjectIDs(ctx context.Context, limitRows int32) ([]int32, error)
	ListActiveIndexIngestTarget(ctx context.Context, arg ListActiveIndexIngestTargetParams) ([]string, error)
	ListArtifactBuckets(ctx context.Context, projectID int64) ([]EliteaStorageBucket, error)
	ListArtifactBucketsNeedingExpiryNotice(ctx context.Context, arg ListArtifactBucketsNeedingExpiryNoticeParams) ([]EliteaStorageBucket, error)
	ListArtifactObjects(ctx context.Context, arg ListArtifactObjectsParams) ([]EliteaStorageObject, error)
	// Required by S18's per-project byte-usage gauge: the retention sweeper
	// (S14) needs to enumerate every project that owns at least one non-deleted
	// bucket before it can call SumArtifactProjectBytes per project. This
	// service owns no "projects" table of its own (see elitea_storage.buckets'
	// own project_id column, a bare BIGINT with no local FK) — the set of
	// known projects is defined operationally as "has at least one bucket."
	ListArtifactProjectIDsWithBuckets(ctx context.Context) ([]int64, error)
	// Read by the merge step once CountAttachmentChunks reaches total_chunks —
	// ORDER BY chunk_index reconstructs the original byte stream regardless of
	// arrival order, matching legacy's merge_chunks reading 0..total_chunks-1.
	ListAttachmentChunksOrdered(ctx context.Context, arg ListAttachmentChunksOrderedParams) ([]ListAttachmentChunksOrderedRow, error)
	ListClaimableScheduledOccurrences(ctx context.Context, arg ListClaimableScheduledOccurrencesParams) ([]ListClaimableScheduledOccurrencesRow, error)
	// This deliberately projects only the six fields exposed by nested
	// configuration options. The same bounded query is run first in the current
	// project and, when requested, in the public project with shared_only=true.
	ListCurrentConfigurationOptionCandidates(ctx context.Context, arg ListCurrentConfigurationOptionCandidatesParams) ([]ListCurrentConfigurationOptionCandidatesRow, error)
	ListCurrentConfigurationRenameToolkits(ctx context.Context, arg ListCurrentConfigurationRenameToolkitsParams) ([]ListCurrentConfigurationRenameToolkitsRow, error)
	// Empty section intentionally disables the section predicate for the exact
	// current UI contract. The caller caps limit_rows at the 257-row sentinel.
	ListCurrentConfigurationTypes(ctx context.Context, arg ListCurrentConfigurationTypesParams) ([]string, error)
	ListCurrentConfigurations(ctx context.Context, arg ListCurrentConfigurationsParams) ([]ListCurrentConfigurationsRow, error)
	// The unqualified toolkit table is intentional. These queries execute only
	// inside an authorized project transaction whose local search_path is the
	// exact p_<project_id> tenant schema.
	ListCurrentIndexScheduleProjects(ctx context.Context, arg ListCurrentIndexScheduleProjectsParams) ([]int32, error)
	ListCurrentIndexScheduleToolkits(ctx context.Context, arg ListCurrentIndexScheduleToolkitsParams) ([]ListCurrentIndexScheduleToolkitsRow, error)
	ListCurrentModelConfigurations(ctx context.Context, arg ListCurrentModelConfigurationsParams) ([]ListCurrentModelConfigurationsRow, error)
	ListCurrentNotificationEventsAfter(ctx context.Context, arg ListCurrentNotificationEventsAfterParams) ([]ListCurrentNotificationEventsAfterRow, error)
	ListCurrentNotifications(ctx context.Context, arg ListCurrentNotificationsParams) ([]ListCurrentNotificationsRow, error)
	ListCurrentProjectAuthors(ctx context.Context, projectID int32) ([]ListCurrentProjectAuthorsRow, error)
	ListCurrentSharedConfigurations(ctx context.Context, arg ListCurrentSharedConfigurationsParams) ([]ListCurrentSharedConfigurationsRow, error)
	// The unqualified table name is intentional. This query runs only inside an
	// authorized project transaction whose local search_path is p_<project_id>.
	//
	// The two predicates are independent to preserve the current endpoint:
	// requesting MCP rows does not implicitly include application rows, and
	// requesting application rows does not implicitly include MCP rows.
	ListCurrentToolkitTypes(ctx context.Context, arg ListCurrentToolkitTypesParams) ([]string, error)
	ListCurrentUserProjects(ctx context.Context, arg ListCurrentUserProjectsParams) ([]ListCurrentUserProjectsRow, error)
	ListExpectedIndexIngestEntries(ctx context.Context, arg ListExpectedIndexIngestEntriesParams) ([]ListExpectedIndexIngestEntriesRow, error)
	ListExpiredArtifactObjects(ctx context.Context, arg ListExpiredArtifactObjectsParams) ([]EliteaStorageObject, error)
	// The LEFT JOIN onto elitea_identity.token_project_binding is what lets a user
	// see which project a key bills (ADR-0018, spec-llm-project-scope §4). It is a
	// LEFT JOIN because an unbound token is the default and must still be listed.
	ListOwnedPATs(ctx context.Context, userID int32) ([]ListOwnedPATsRow, error)
	ListPendingAgentExecutionIDs(ctx context.Context, arg ListPendingAgentExecutionIDsParams) ([]string, error)
	ListPendingToolkitExecuteReadIDs(ctx context.Context, arg ListPendingToolkitExecuteReadIDsParams) ([]string, error)
	LoadIndexMetaInitializationWork(ctx context.Context, arg LoadIndexMetaInitializationWorkParams) (LoadIndexMetaInitializationWorkRow, error)
	LoadMCPOAuthClient(ctx context.Context, arg LoadMCPOAuthClientParams) ([]byte, error)
	LoadRuntimeAdmissionTiming(ctx context.Context, deadlineTtlMillis int64) (LoadRuntimeAdmissionTimingRow, error)
	LockAgentExecutionEnvelope(ctx context.Context, arg LockAgentExecutionEnvelopeParams) (LockAgentExecutionEnvelopeRow, error)
	LockAgentExecutionPublication(ctx context.Context, arg LockAgentExecutionPublicationParams) (LockAgentExecutionPublicationRow, error)
	LockCancelledNoAuthorityAgentExecutions(ctx context.Context, arg LockCancelledNoAuthorityAgentExecutionsParams) ([]LockCancelledNoAuthorityAgentExecutionsRow, error)
	LockCancelledNoAuthorityToolkitExecuteReads(ctx context.Context, arg LockCancelledNoAuthorityToolkitExecuteReadsParams) ([]LockCancelledNoAuthorityToolkitExecuteReadsRow, error)
	LockCurrentAgentConversation(ctx context.Context, conversationUuid pgtype.UUID) (int32, error)
	LockCurrentAgentResponseForTerminal(ctx context.Context, arg LockCurrentAgentResponseForTerminalParams) (int32, error)
	// The unqualified configuration relation is intentional. These queries run
	// only inside a tenant transaction whose local search_path was derived from an
	// already authorized positive project identity.
	LockCurrentConfigurationForMutation(ctx context.Context, arg LockCurrentConfigurationForMutationParams) (LockCurrentConfigurationForMutationRow, error)
	LockCurrentIndexScheduleToolkit(ctx context.Context, toolkitID int32) (LockCurrentIndexScheduleToolkitRow, error)
	LockCurrentIndexScheduleToolkitMeta(ctx context.Context, toolkitID int32) ([]byte, error)
	LockExpiredNoAuthorityAgentExecutions(ctx context.Context, arg LockExpiredNoAuthorityAgentExecutionsParams) ([]LockExpiredNoAuthorityAgentExecutionsRow, error)
	// LockExpiredNoAuthorityToolkitCallToolExecutions reclaims the capacity a run
	// that never reached Redis would otherwise hold forever. It selects only work
	// past its deadline that no worker ever claimed, which is exactly the crash
	// window this capability accepts in exchange for having no binding table.
	//
	LockExpiredNoAuthorityToolkitCallToolExecutions(ctx context.Context, arg LockExpiredNoAuthorityToolkitCallToolExecutionsParams) ([]LockExpiredNoAuthorityToolkitCallToolExecutionsRow, error)
	LockExpiredNoAuthorityToolkitExecuteReads(ctx context.Context, arg LockExpiredNoAuthorityToolkitExecuteReadsParams) ([]LockExpiredNoAuthorityToolkitExecuteReadsRow, error)
	LockPATByUUID(ctx context.Context, uuid string) (LockPATByUUIDRow, error)
	LockRuntimeAdmissionPolicy(ctx context.Context, capabilityID string) (int64, error)
	LockToolkitCallToolEnvelope(ctx context.Context, arg LockToolkitCallToolEnvelopeParams) (LockToolkitCallToolEnvelopeRow, error)
	LockToolkitCallToolPublication(ctx context.Context, arg LockToolkitCallToolPublicationParams) (LockToolkitCallToolPublicationRow, error)
	LockToolkitExecuteReadEnvelope(ctx context.Context, arg LockToolkitExecuteReadEnvelopeParams) (LockToolkitExecuteReadEnvelopeRow, error)
	LockToolkitExecuteReadPublication(ctx context.Context, arg LockToolkitExecuteReadPublicationParams) (LockToolkitExecuteReadPublicationRow, error)
	MarkAgentExecutionDispatched(ctx context.Context, arg MarkAgentExecutionDispatchedParams) (int64, error)
	MarkAgentExecutionPublished(ctx context.Context, arg MarkAgentExecutionPublishedParams) (int64, error)
	MarkArtifactBucketNotified(ctx context.Context, id int64) (int64, error)
	// consumed_at IS NULL in the WHERE clause, not just the SET, is the actual
	// single-use enforcement: 0 rows affected means either the grant does not
	// exist or was already consumed. The caller (commitTransferGrant) has
	// already fetched the row by this point, so 0 rows here unambiguously means
	// "already consumed" — see repository.go's MarkTransferGrantConsumed.
	// S16 also uses this to mark an aborted multipart grant terminal — see
	// AbortMultipartUpload.
	MarkArtifactTransferGrantConsumed(ctx context.Context, id string) (int64, error)
	MarkConfigurationLifecycleDead(ctx context.Context, arg MarkConfigurationLifecycleDeadParams) (int64, error)
	MarkConfigurationLifecycleDelivered(ctx context.Context, arg MarkConfigurationLifecycleDeliveredParams) (int64, error)
	MarkConfigurationLifecycleRetry(ctx context.Context, arg MarkConfigurationLifecycleRetryParams) (int64, error)
	MarkCurrentNotificationSeen(ctx context.Context, arg MarkCurrentNotificationSeenParams) (MarkCurrentNotificationSeenRow, error)
	MarkIndexMetaInitialized(ctx context.Context, arg MarkIndexMetaInitializedParams) (pgtype.Timestamptz, error)
	MarkToolkitCallToolDispatched(ctx context.Context, arg MarkToolkitCallToolDispatchedParams) (int64, error)
	MarkToolkitCallToolPublished(ctx context.Context, arg MarkToolkitCallToolPublishedParams) (int64, error)
	MarkToolkitExecuteReadDispatched(ctx context.Context, arg MarkToolkitExecuteReadDispatchedParams) (int64, error)
	MarkToolkitExecuteReadPublished(ctx context.Context, arg MarkToolkitExecuteReadPublishedParams) (int64, error)
	ProjectCurrentAgentStop(ctx context.Context, arg ProjectCurrentAgentStopParams) (ProjectCurrentAgentStopRow, error)
	PruneMCPOAuthClients(ctx context.Context) error
	QuarantineExpiredTerminalIndexMetaInitializations(ctx context.Context, quarantineLimit int32) (int64, error)
	QuarantineIndexMetaInitialization(ctx context.Context, arg QuarantineIndexMetaInitializationParams) (string, error)
	RefreshAgentExecutionPublication(ctx context.Context, arg RefreshAgentExecutionPublicationParams) (int64, error)
	RefreshToolkitExecuteReadPublication(ctx context.Context, arg RefreshToolkitExecuteReadPublicationParams) (int64, error)
	ReleaseIndexMetaInitialization(ctx context.Context, arg ReleaseIndexMetaInitializationParams) (int64, error)
	ReleaseScheduledOccurrenceForRetry(ctx context.Context, arg ReleaseScheduledOccurrenceForRetryParams) (int64, error)
	ReplaceCurrentConfiguration(ctx context.Context, arg ReplaceCurrentConfigurationParams) (ReplaceCurrentConfigurationRow, error)
	ReplaceCurrentDeletedLLMApplicationReferences(ctx context.Context, arg ReplaceCurrentDeletedLLMApplicationReferencesParams) (ReplaceCurrentDeletedLLMApplicationReferencesRow, error)
	RequestCurrentIndexIngestCancellation(ctx context.Context, arg RequestCurrentIndexIngestCancellationParams) (bool, error)
	ResetCurrentAgentResponse(ctx context.Context, arg ResetCurrentAgentResponseParams) (ResetCurrentAgentResponseRow, error)
	// Chat history for this turn: one entry per prior message group, whose
	// `content` is the group's items flattened into ONE LangChain content array.
	//
	// #606 part 3 added `attachment_message` to the items considered. Before it,
	// this LATERAL joined `text_message` alone, so a file attached in an EARLIER
	// turn was invisible to the model even though its row existed: the transcript
	// rendered it, the prompt did not mention it, and a follow-up question about
	// that file had nothing to answer from.
	//
	// The rule is pylon's, not an invention: chat_history.py:67-73 EXTENDS an
	// attachment item's stored `content` LIST into the group's content array,
	// in item order, alongside the text chunks -- it does not nest it, and does
	// not append one object per file. That is why the per-item CROSS JOIN LATERAL
	// emits chunk ROWS rather than a per-item array: `jsonb_agg` over the rows is
	// the flattening, and one ORDER BY (order_index, id, chunk_index) then orders
	// items and, within an item, its chunks -- the pre-#606 ordering unchanged for
	// a group that has only text.
	//
	// WHY THE JOINS BECAME LEFT JOINS AND THE FILTER BECAME A WHERE. The old
	// `FILTER (WHERE message_text.content <> '')` cannot survive: it tests a
	// column that is NULL for an attachment item, so it would drop every
	// attachment chunk. The empty-text exclusion moves into the text branch's own
	// WHERE (`COALESCE(message_text.content, '') <> ''`, which also preserves the
	// inner join's old refusal of a text item with no payload row), and an item
	// that contributes no chunk simply produces no row. A group left with no
	// chunks at all disappears from the subquery exactly as it used to when the
	// FILTER made its `content` NULL, so the outer
	// `jsonb_array_length(...) > 0` gate keeps behaving identically -- while an
	// ATTACHMENT-ONLY group (no text item, which the pre-#606 shape could not
	// represent at all) now survives it.
	//
	// `content` IS `json`, NOT `jsonb` (migrations/tenant/0127 records why), and
	// it is nullable with a pylon-era default of `'{}'::json` -- an OBJECT, not an
	// array. chat_history.py:70-74 carries a non-list fallback for exactly that
	// data. Here the CASE demands `jsonb_typeof(...) = 'array'` before expanding,
	// because `jsonb_array_elements` on a non-array raises 22023 and would fail
	// the whole resolve; a NULL or `{}` content contributes nothing instead of
	// injecting a chunk the model would have to read. The chunks are NOT
	// validated beyond that: their shape is the worker's and the model's
	// contract, and silently reshaping stored content here would make the
	// projection disagree with what the transcript renders.
	ResolveCurrentAdhocTurn(ctx context.Context, arg ResolveCurrentAdhocTurnParams) (ResolveCurrentAdhocTurnRow, error)
	ResolveCurrentApplicationNestingNode(ctx context.Context, applicationVersionID int32) (ResolveCurrentApplicationNestingNodeRow, error)
	// A LEFT JOIN, and the WHERE below is what keeps it an inner one for every
	// turn addressed at an agent in the conversation's OWN project.
	//
	// `application_versions` is a per-project table: this query runs inside the
	// conversation's tenant schema, so it can only ever see that project's rows.
	// A participant that names the catalogue twin of a PUBLISHED agent therefore
	// has no row to join here at all, and an inner join answered no rows -- the
	// 422 a conversation in project A got when it addressed an agent published in
	// the catalogue, which legacy allowed. The version for that one case is read
	// afterwards, from the catalogue project's own schema
	// (CurrentAgentStartRepository.resolveCatalogueApplicationVersion), so this
	// join is allowed to miss and the projection below is then a document of
	// nulls that the Go side REPLACES rather than reads.
	//
	// Nothing else may miss it: the WHERE demands `application_version.id IS NOT
	// NULL` for the same-project case, which restores the inner join's exact
	// refusal, and admits the missing row ONLY for a participant whose project is
	// the catalogue project and is not the conversation's own.
	// Chat history for this turn: one entry per prior message group, whose
	// `content` is the group's items flattened into ONE LangChain content array.
	//
	// #606 part 3 added `attachment_message` to the items considered. Before it,
	// this LATERAL joined `text_message` alone, so a file attached in an EARLIER
	// turn was invisible to the model even though its row existed: the transcript
	// rendered it, the prompt did not mention it, and a follow-up question about
	// that file had nothing to answer from.
	//
	// The rule is pylon's, not an invention: chat_history.py:67-73 EXTENDS an
	// attachment item's stored `content` LIST into the group's content array,
	// in item order, alongside the text chunks -- it does not nest it, and does
	// not append one object per file. That is why the per-item CROSS JOIN LATERAL
	// emits chunk ROWS rather than a per-item array: `jsonb_agg` over the rows is
	// the flattening, and one ORDER BY (order_index, id, chunk_index) then orders
	// items and, within an item, its chunks -- the pre-#606 ordering unchanged for
	// a group that has only text.
	//
	// WHY THE JOINS BECAME LEFT JOINS AND THE FILTER BECAME A WHERE. The old
	// `FILTER (WHERE message_text.content <> '')` cannot survive: it tests a
	// column that is NULL for an attachment item, so it would drop every
	// attachment chunk. The empty-text exclusion moves into the text branch's own
	// WHERE (`COALESCE(message_text.content, '') <> ''`, which also preserves the
	// inner join's old refusal of a text item with no payload row), and an item
	// that contributes no chunk simply produces no row. A group left with no
	// chunks at all disappears from the subquery exactly as it used to when the
	// FILTER made its `content` NULL, so the outer
	// `jsonb_array_length(...) > 0` gate keeps behaving identically -- while an
	// ATTACHMENT-ONLY group (no text item, which the pre-#606 shape could not
	// represent at all) now survives it.
	//
	// `content` IS `json`, NOT `jsonb` (migrations/tenant/0127 records why), and
	// it is nullable with a pylon-era default of `'{}'::json` -- an OBJECT, not an
	// array. chat_history.py:70-74 carries a non-list fallback for exactly that
	// data. Here the CASE demands `jsonb_typeof(...) = 'array'` before expanding,
	// because `jsonb_array_elements` on a non-array raises 22023 and would fail
	// the whole resolve; a NULL or `{}` content contributes nothing instead of
	// injecting a chunk the model would have to read. The chunks are NOT
	// validated beyond that: their shape is the worker's and the model's
	// contract, and silently reshaping stored content here would make the
	// projection disagree with what the transcript renders.
	ResolveCurrentApplicationTurn(ctx context.Context, arg ResolveCurrentApplicationTurnParams) (ResolveCurrentApplicationTurnRow, error)
	// The projection above is ResolveCurrentApplicationTurn's
	// `application_version_details_json` block, copied verbatim rather than shared.
	// Both copies sit between the `-- BEGIN/END shared
	// application_version_details_json projection` markers, and
	// TestSharedApplicationVersionDetailsProjectionsAreIdentical
	// (internal/db/sqlcgen/agent_chat_shared_projection_test.go) extracts both and
	// fails the build if a single byte between the markers diverges. Keep the
	// markers on their own lines and edit the two blocks together.
	// Both documents are read by the SAME decoder in the native
	// runtime (`OrdinaryNoToolProfile::from_nested_version` and
	// `FrozenToolSnapshot::from_version_details`,
	// services/elitea-worker-rust/src/agents/assembly.rs) and frozen by the SAME
	// freeze (`FreezeCurrentApplicationVersion`,
	// internal/application/agentexecution/tools.go), so a parent's definition and a
	// nested child's must have one shape. What is deliberately absent is everything
	// the turn projection derives from a conversation — chat history, participants,
	// the conversation's own internal-tool list — because a nested child has no
	// conversation: it is invoked as a tool inside the parent's turn.
	//
	// BOTH identity arguments are filters, and that is load-bearing rather than
	// defensive. The worker names the pair in its request path
	// (`/runtime-context/applications/{application_id}/versions/{version_id}`,
	// services/elitea-worker-rust/src/transport/runtime_context.rs:448-469) and
	// validates the pair it gets back (:554-564). Keying on the version alone would
	// let a stored reference whose `application_id` disagrees with its
	// `application_version_id` still resolve a definition — the exact mismatch
	// `materializeCurrentApplicationToolNestedSkills` refuses on the start path
	// (internal/infra/db/repos/agent_nesting.go).
	ResolveCurrentApplicationVersionDetails(ctx context.Context, arg ResolveCurrentApplicationVersionDetailsParams) (ResolveCurrentApplicationVersionDetailsRow, error)
	// The pending set is materialized through a CASE, exactly as
	// ResolveCurrentContinuation / ResumeCurrentAgentHITL do for `pending_hitl`,
	// and for a reason those queries only imply. A sibling
	// `AND jsonb_typeof(...) = 'array'` is NOT a guard: PostgreSQL costs and
	// reorders the quals of an AND (order_qual_clauses), and on PostgreSQL 16 it
	// already evaluates the length test first — so a `meta.authorization_requests`
	// holding JSON null, a scalar or an object raises 22023 ("cannot get array
	// length of a scalar" / "of a non-array") and turns this deliberate REFUSAL,
	// which the caller answers 422, into a 500. The CASE cannot change any
	// admitted row: whenever the ELSE arm is taken the typeof qual beside it is
	// already false, and an empty array fails `BETWEEN 1 AND 16` anyway.
	ResolveCurrentAuthorizationContinuation(ctx context.Context, arg ResolveCurrentAuthorizationContinuationParams) (ResolveCurrentAuthorizationContinuationRow, error)
	ResolveCurrentContinuation(ctx context.Context, arg ResolveCurrentContinuationParams) (ResolveCurrentContinuationRow, error)
	ResolveCurrentOutputLimitContinuation(ctx context.Context, arg ResolveCurrentOutputLimitContinuationParams) (ResolveCurrentOutputLimitContinuationRow, error)
	// This is the exact current projects_get_personal_project_id decision tree:
	// a named personal project wins only when the user has any project-role
	// assignment; the system-user email fallback is considered only when that
	// named project does not exist.
	ResolveCurrentPersonalProjectID(ctx context.Context, userID int32) (int32, error)
	ResolveCurrentRegeneration(ctx context.Context, arg ResolveCurrentRegenerationParams) (ResolveCurrentRegenerationRow, error)
	ResolveCurrentTenantContext(ctx context.Context, arg ResolveCurrentTenantContextParams) (ResolveCurrentTenantContextRow, error)
	ResolveIndexMetaInitialization(ctx context.Context, arg ResolveIndexMetaInitializationParams) (pgtype.Timestamptz, error)
	ResolveRuntimeExecutionEventCapability(ctx context.Context, arg ResolveRuntimeExecutionEventCapabilityParams) (string, error)
	ResumeCurrentAgentAuthorization(ctx context.Context, arg ResumeCurrentAgentAuthorizationParams) (ResumeCurrentAgentAuthorizationRow, error)
	ResumeCurrentAgentHITL(ctx context.Context, arg ResumeCurrentAgentHITLParams) (ResumeCurrentAgentHITLRow, error)
	ResumeCurrentAgentOutputLimit(ctx context.Context, arg ResumeCurrentAgentOutputLimitParams) (ResumeCurrentAgentOutputLimitRow, error)
	ScheduledDatabaseNow(ctx context.Context) (pgtype.Timestamptz, error)
	SetArtifactBucketPinned(ctx context.Context, arg SetArtifactBucketPinnedParams) (EliteaStorageBucket, error)
	// Configuration lifecycle internal effects. Unqualified tenant tables are
	// intentional: every such statement runs inside an authorized project
	// transaction whose local search_path is p_<project_id>.
	SetCurrentConfigurationLifecycleStatus(ctx context.Context, arg SetCurrentConfigurationLifecycleStatusParams) (int64, error)
	SoftDeleteArtifactBucket(ctx context.Context, id int64) (int64, error)
	StorePreparedAgentExecutionEnvelope(ctx context.Context, arg StorePreparedAgentExecutionEnvelopeParams) (int64, error)
	StorePreparedToolkitCallToolEnvelope(ctx context.Context, arg StorePreparedToolkitCallToolEnvelopeParams) (int64, error)
	StorePreparedToolkitExecuteReadEnvelope(ctx context.Context, arg StorePreparedToolkitExecuteReadEnvelopeParams) (int64, error)
	SumArtifactBucketBytes(ctx context.Context, bucketID int64) (int64, error)
	SumArtifactProjectBytes(ctx context.Context, projectID int64) (int64, error)
	SupersedeScheduledJobRevision(ctx context.Context, arg SupersedeScheduledJobRevisionParams) error
	TouchProvisionedAuthUser(ctx context.Context, arg TouchProvisionedAuthUserParams) (AuthCoreUser, error)
	// notified_at resets to NULL on every retention change: a bucket already
	// notified once for an earlier expires_at must be eligible for a fresh
	// notification against whatever new expires_at this update just set,
	// otherwise ListArtifactBucketsNeedingExpiryNotice's `notified_at IS NULL`
	// filter would permanently exclude it after the first notice.
	UpdateArtifactBucketRetention(ctx context.Context, arg UpdateArtifactBucketRetentionParams) (EliteaStorageBucket, error)
	UpdateArtifactBucketTags(ctx context.Context, arg UpdateArtifactBucketTagsParams) (EliteaStorageBucket, error)
	// #607: persist the text the worker extracted from ONE of this turn's
	// attachments, so a LATER turn sees the file's contents and not just its name.
	//
	// Pylon never needed this statement. It extracts at message-persist time and
	// appends the text to the item it has in hand, in the same process and the same
	// session (rpc/chat_all.py:344-377, with flag_modified(item, "content") at :376
	// because the column is `json`). Here the reader is the worker and the writer is
	// elitea-main, so the text comes back across a protocol
	// (AgentExecutionResultV1.attachment_contents) and lands here, on the terminal
	// path elitea-main already owns.
	//
	// MATCHED ON item.uuid, NOT ON (bucket, name). Attaching the same file twice in
	// one conversation is an ordinary thing to do and produces two rows with
	// identical bucket and name; a (bucket, name) match would write one file's text
	// onto the other's row. `chat_message_items.uuid` is UNIQUE (0123), so this
	// addresses at most one row.
	//
	// SCOPED IN SQL, NOT IN GO, AND THAT IS THE POINT. `item_id` arrives from a
	// worker process over gRPC. Trusting it would let any worker holding a valid
	// claim overwrite the content of ANY attachment row in the project by naming its
	// id -- another user's conversation included -- and the Go side has no cheap way
	// to prove otherwise without a second round trip it would then have to trust
	// itself to have made. The join does the proving instead: the item must hang off
	// the QUESTION group that `response_group` (the row
	// LockCurrentAgentResponseForTerminal just locked, and which the caller reached
	// only by matching message uuid + conversation uuid + task_id +
	// meta.execution_generation) replies to. An id outside that one question matches
	// nothing and the statement reports 0 rows.
	//
	// `reply_to_id` is the link, and it is written in the same statement that
	// creates both groups (InsertCurrentApplicationTurn / InsertCurrentAdhocTurn),
	// so it cannot be absent for a turn this path can reach.
	//
	// NO item_type PREDICATE, deliberately. `AND item.item_type =
	// 'attachment_message'` reads like prudence and is dead code:
	// chat_messages_attachment's primary key IS the item's id (0127), so the join
	// to it already proves the item is an attachment and no payload row can exist
	// under a `text_message` item. It was written, then removed, because no test
	// could tell the two versions apart -- deleting the predicate left every case
	// green, including the one that names the question's own text item. An
	// unfalsifiable guard is worse than none: it invites the next reader to believe
	// the write is checked in a way it is not.
	//
	// REPLACES `content` OUTRIGHT rather than appending a chunk. The value carried
	// across the seam is the complete array the column is to hold -- the scaffold's
	// header chunk, marker intact, plus the extracted text -- which is what makes a
	// redelivered terminal frame rewrite the same bytes instead of appending the
	// file's text a second time. An `||` append here would be idempotent only by
	// accident.
	//
	// `content` is cast to json, NOT jsonb, for the reason 0127 records: the column
	// is `json` because pylon reads and writes the same table, and jsonb's key
	// reordering and whitespace normalisation would change the stored bytes -- which
	// for this value includes the `elitea_attachment` marker a later turn's worker
	// reads to decide the file has already been extracted.
	UpdateCurrentAgentAttachmentContent(ctx context.Context, arg UpdateCurrentAgentAttachmentContentParams) (int64, error)
	UpdateCurrentIndexScheduleToolkitMeta(ctx context.Context, arg UpdateCurrentIndexScheduleToolkitMetaParams) (int64, error)
	UpsertArtifactObject(ctx context.Context, arg UpsertArtifactObjectParams) (EliteaStorageObject, error)
	// ON CONFLICT DO UPDATE, not DO NOTHING: a retried chunk_index (client
	// timeout, network retry) must overwrite the previous bytes for that index,
	// matching legacy's own local-disk behavior (writing to the same filename
	// twice replaces it) — never double-counted, since the primary key already
	// de-duplicates by chunk_index.
	UpsertAttachmentChunk(ctx context.Context, arg UpsertAttachmentChunkParams) error
	// The project transaction establishes the authorized p_<project_id>
	// search_path before this statement runs. The public PgVector bootstrap
	// configuration is never copied into this tenant row: only the current vault
	// reference is stored.
	UpsertCurrentProjectPgvectorConfiguration(ctx context.Context, arg UpsertCurrentProjectPgvectorConfigurationParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
