// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_toolkit_available_tools.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExpectedToolkitAvailableToolsHeader = `-- name: GetExpectedToolkitAvailableToolsHeader :one
SELECT j.tenant_id,
       j.resource_project_id,
       j.projection_project_id,
       j.capability_id,
       o.prepared_signed_envelope_bytes,
       o.prepared_signed_envelope_digest,
       j.command_id,
       j.execution_id,
       j.generation,
       b.input_bundle_id,
       b.manifest_digest AS input_bundle_digest
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.command_outbox AS o ON o.execution_id=j.execution_id AND o.generation=j.generation
JOIN elitea_runtime.input_bundles AS b
  ON b.input_bundle_id = j.input_bundle_id
WHERE j.execution_id = $1::text
  AND j.generation = $2::bigint
  AND j.capability_id = 'toolkit.available_tools.v1'
`

type GetExpectedToolkitAvailableToolsHeaderParams struct {
	ExecutionID string `db:"execution_id" json:"execution_id"`
	Generation  int64  `db:"generation" json:"generation"`
}

type GetExpectedToolkitAvailableToolsHeaderRow struct {
	TenantID                     string `db:"tenant_id" json:"tenant_id"`
	ResourceProjectID            int32  `db:"resource_project_id" json:"resource_project_id"`
	ProjectionProjectID          int32  `db:"projection_project_id" json:"projection_project_id"`
	CapabilityID                 string `db:"capability_id" json:"capability_id"`
	PreparedSignedEnvelopeBytes  []byte `db:"prepared_signed_envelope_bytes" json:"prepared_signed_envelope_bytes"`
	PreparedSignedEnvelopeDigest []byte `db:"prepared_signed_envelope_digest" json:"prepared_signed_envelope_digest"`
	CommandID                    string `db:"command_id" json:"command_id"`
	ExecutionID                  string `db:"execution_id" json:"execution_id"`
	Generation                   int64  `db:"generation" json:"generation"`
	InputBundleID                string `db:"input_bundle_id" json:"input_bundle_id"`
	InputBundleDigest            []byte `db:"input_bundle_digest" json:"input_bundle_digest"`
}

func (q *Queries) GetExpectedToolkitAvailableToolsHeader(ctx context.Context, arg GetExpectedToolkitAvailableToolsHeaderParams) (GetExpectedToolkitAvailableToolsHeaderRow, error) {
	row := q.db.QueryRow(ctx, getExpectedToolkitAvailableToolsHeader, arg.ExecutionID, arg.Generation)
	var i GetExpectedToolkitAvailableToolsHeaderRow
	err := row.Scan(
		&i.TenantID,
		&i.ResourceProjectID,
		&i.ProjectionProjectID,
		&i.CapabilityID,
		&i.PreparedSignedEnvelopeBytes,
		&i.PreparedSignedEnvelopeDigest,
		&i.CommandID,
		&i.ExecutionID,
		&i.Generation,
		&i.InputBundleID,
		&i.InputBundleDigest,
	)
	return i, err
}

const getToolkitAvailableToolsAdmissionByIdempotency = `-- name: GetToolkitAvailableToolsAdmissionByIdempotency :one
SELECT j.execution_id,
       j.command_id,
       j.generation,
       j.request_digest,
       j.admitted_at,
       o.deadline
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.command_outbox AS o
  ON o.execution_id = j.execution_id AND o.generation = j.generation
WHERE j.idempotency_scope = $1::text
  AND j.idempotency_key = $2::text
  AND j.capability_id = 'toolkit.available_tools.v1'
`

type GetToolkitAvailableToolsAdmissionByIdempotencyParams struct {
	IdempotencyScope string `db:"idempotency_scope" json:"idempotency_scope"`
	IdempotencyKey   string `db:"idempotency_key" json:"idempotency_key"`
}

type GetToolkitAvailableToolsAdmissionByIdempotencyRow struct {
	ExecutionID   string             `db:"execution_id" json:"execution_id"`
	CommandID     string             `db:"command_id" json:"command_id"`
	Generation    int64              `db:"generation" json:"generation"`
	RequestDigest []byte             `db:"request_digest" json:"request_digest"`
	AdmittedAt    pgtype.Timestamptz `db:"admitted_at" json:"admitted_at"`
	Deadline      pgtype.Timestamptz `db:"deadline" json:"deadline"`
}

func (q *Queries) GetToolkitAvailableToolsAdmissionByIdempotency(ctx context.Context, arg GetToolkitAvailableToolsAdmissionByIdempotencyParams) (GetToolkitAvailableToolsAdmissionByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getToolkitAvailableToolsAdmissionByIdempotency, arg.IdempotencyScope, arg.IdempotencyKey)
	var i GetToolkitAvailableToolsAdmissionByIdempotencyRow
	err := row.Scan(
		&i.ExecutionID,
		&i.CommandID,
		&i.Generation,
		&i.RequestDigest,
		&i.AdmittedAt,
		&i.Deadline,
	)
	return i, err
}

const getToolkitAvailableToolsArtifactForOutput = `-- name: GetToolkitAvailableToolsArtifactForOutput :one
SELECT a.artifact_id,a.immutable_version,j.input_bundle_id,
       e.entry_id AS settings_entry_id,e.entry_version AS settings_entry_version,
       e.content_digest AS settings_content_digest,a.digest,a.byte_length,
       a.media_type,a.classification,a.bytes_verified_at
FROM elitea_runtime.index_result_artifacts AS a
JOIN elitea_runtime.execution_jobs AS j
  ON j.execution_id=a.execution_id AND j.generation=a.generation
  AND j.resource_project_id=a.resource_project_id
JOIN elitea_runtime.input_bundle_entries AS e
  ON e.input_bundle_id=j.input_bundle_id
  AND e.semantic_role='toolkit.available_tools.settings'
WHERE a.execution_id=$1::text
  AND a.generation=$2::bigint
  AND a.artifact_id=$3::text
  AND a.immutable_version=$4::text
  AND j.capability_id='toolkit.available_tools.v1'
`

type GetToolkitAvailableToolsArtifactForOutputParams struct {
	ExecutionID      string `db:"execution_id" json:"execution_id"`
	Generation       int64  `db:"generation" json:"generation"`
	ArtifactID       string `db:"artifact_id" json:"artifact_id"`
	ImmutableVersion string `db:"immutable_version" json:"immutable_version"`
}

type GetToolkitAvailableToolsArtifactForOutputRow struct {
	ArtifactID            string             `db:"artifact_id" json:"artifact_id"`
	ImmutableVersion      string             `db:"immutable_version" json:"immutable_version"`
	InputBundleID         string             `db:"input_bundle_id" json:"input_bundle_id"`
	SettingsEntryID       string             `db:"settings_entry_id" json:"settings_entry_id"`
	SettingsEntryVersion  string             `db:"settings_entry_version" json:"settings_entry_version"`
	SettingsContentDigest []byte             `db:"settings_content_digest" json:"settings_content_digest"`
	Digest                []byte             `db:"digest" json:"digest"`
	ByteLength            int64              `db:"byte_length" json:"byte_length"`
	MediaType             string             `db:"media_type" json:"media_type"`
	Classification        string             `db:"classification" json:"classification"`
	BytesVerifiedAt       pgtype.Timestamptz `db:"bytes_verified_at" json:"bytes_verified_at"`
}

func (q *Queries) GetToolkitAvailableToolsArtifactForOutput(ctx context.Context, arg GetToolkitAvailableToolsArtifactForOutputParams) (GetToolkitAvailableToolsArtifactForOutputRow, error) {
	row := q.db.QueryRow(ctx, getToolkitAvailableToolsArtifactForOutput,
		arg.ExecutionID,
		arg.Generation,
		arg.ArtifactID,
		arg.ImmutableVersion,
	)
	var i GetToolkitAvailableToolsArtifactForOutputRow
	err := row.Scan(
		&i.ArtifactID,
		&i.ImmutableVersion,
		&i.InputBundleID,
		&i.SettingsEntryID,
		&i.SettingsEntryVersion,
		&i.SettingsContentDigest,
		&i.Digest,
		&i.ByteLength,
		&i.MediaType,
		&i.Classification,
		&i.BytesVerifiedAt,
	)
	return i, err
}

const getToolkitAvailableToolsInputEntries = `-- name: GetToolkitAvailableToolsInputEntries :many
SELECT e.entry_id,
       e.semantic_role,
       e.entry_version,
       e.content_digest
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.input_bundle_entries AS e
  ON e.input_bundle_id = j.input_bundle_id
WHERE j.execution_id = $1::text
  AND j.generation = $2::bigint
  AND j.capability_id = 'toolkit.available_tools.v1'
ORDER BY e.semantic_role
`

type GetToolkitAvailableToolsInputEntriesParams struct {
	ExecutionID string `db:"execution_id" json:"execution_id"`
	Generation  int64  `db:"generation" json:"generation"`
}

type GetToolkitAvailableToolsInputEntriesRow struct {
	EntryID       string `db:"entry_id" json:"entry_id"`
	SemanticRole  string `db:"semantic_role" json:"semantic_role"`
	EntryVersion  string `db:"entry_version" json:"entry_version"`
	ContentDigest []byte `db:"content_digest" json:"content_digest"`
}

func (q *Queries) GetToolkitAvailableToolsInputEntries(ctx context.Context, arg GetToolkitAvailableToolsInputEntriesParams) ([]GetToolkitAvailableToolsInputEntriesRow, error) {
	rows, err := q.db.Query(ctx, getToolkitAvailableToolsInputEntries, arg.ExecutionID, arg.Generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetToolkitAvailableToolsInputEntriesRow{}
	for rows.Next() {
		var i GetToolkitAvailableToolsInputEntriesRow
		if err := rows.Scan(
			&i.EntryID,
			&i.SemanticRole,
			&i.EntryVersion,
			&i.ContentDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertToolkitAvailableToolsJob = `-- name: InsertToolkitAvailableToolsJob :one
INSERT INTO elitea_runtime.execution_jobs (
    execution_id, generation, command_id, tenant_id, resource_project_id,
    projection_project_id, actor_id, principal_ref, capability_id,
    capability_version, input_bundle_id, request_digest,
    idempotency_scope, idempotency_key, state, desired_state, admitted_at
) VALUES (
    $1::text,
    $2::bigint,
    $3::text,
    $4::text,
    $5::integer,
    $6::integer,
    $7::text,
    $8::text,
    'toolkit.available_tools.v1',
    $9::text,
    $10::text,
    $11::bytea,
    $12::text,
    $13::text,
    $14::text,
    'RUNNING',
    $15::timestamptz
)
ON CONFLICT (idempotency_scope, idempotency_key) DO NOTHING
RETURNING execution_id
`

type InsertToolkitAvailableToolsJobParams struct {
	ExecutionID         string             `db:"execution_id" json:"execution_id"`
	Generation          int64              `db:"generation" json:"generation"`
	CommandID           string             `db:"command_id" json:"command_id"`
	TenantID            string             `db:"tenant_id" json:"tenant_id"`
	ResourceProjectID   int32              `db:"resource_project_id" json:"resource_project_id"`
	ProjectionProjectID int32              `db:"projection_project_id" json:"projection_project_id"`
	ActorID             string             `db:"actor_id" json:"actor_id"`
	PrincipalRef        string             `db:"principal_ref" json:"principal_ref"`
	CapabilityVersion   string             `db:"capability_version" json:"capability_version"`
	InputBundleID       string             `db:"input_bundle_id" json:"input_bundle_id"`
	RequestDigest       []byte             `db:"request_digest" json:"request_digest"`
	IdempotencyScope    string             `db:"idempotency_scope" json:"idempotency_scope"`
	IdempotencyKey      string             `db:"idempotency_key" json:"idempotency_key"`
	State               string             `db:"state" json:"state"`
	AdmittedAt          pgtype.Timestamptz `db:"admitted_at" json:"admitted_at"`
}

func (q *Queries) InsertToolkitAvailableToolsJob(ctx context.Context, arg InsertToolkitAvailableToolsJobParams) (string, error) {
	row := q.db.QueryRow(ctx, insertToolkitAvailableToolsJob,
		arg.ExecutionID,
		arg.Generation,
		arg.CommandID,
		arg.TenantID,
		arg.ResourceProjectID,
		arg.ProjectionProjectID,
		arg.ActorID,
		arg.PrincipalRef,
		arg.CapabilityVersion,
		arg.InputBundleID,
		arg.RequestDigest,
		arg.IdempotencyScope,
		arg.IdempotencyKey,
		arg.State,
		arg.AdmittedAt,
	)
	var execution_id string
	err := row.Scan(&execution_id)
	return execution_id, err
}

const lockExpiredNoAuthorityToolkitAvailableToolsExecutions = `-- name: LockExpiredNoAuthorityToolkitAvailableToolsExecutions :many
SELECT o.outbox_id,
       j.execution_id,
       j.generation,
       j.projection_project_id,
       j.desired_state
FROM elitea_runtime.command_outbox AS o
JOIN elitea_runtime.execution_jobs AS j
  ON j.execution_id = o.execution_id AND j.generation = o.generation
WHERE o.deadline <= clock_timestamp()
  AND o.retired_at IS NULL
  AND o.authority_granted_at IS NULL
  AND o.stream_name = $1::text
  AND j.desired_state <> 'CANCELLED'
  AND j.state IN ('PENDING', 'DISPATCHED')
  AND j.capability_id = 'toolkit.available_tools.v1'
  AND j.generation = 1
  AND NOT EXISTS (
      SELECT 1
      FROM elitea_runtime.execution_claims AS c
      WHERE c.execution_id = j.execution_id AND c.generation = j.generation
  )
ORDER BY o.deadline, o.outbox_id
LIMIT $2::integer
FOR UPDATE OF j, o SKIP LOCKED
`

type LockExpiredNoAuthorityToolkitAvailableToolsExecutionsParams struct {
	StreamName string `db:"stream_name" json:"stream_name"`
	BatchLimit int32  `db:"batch_limit" json:"batch_limit"`
}

type LockExpiredNoAuthorityToolkitAvailableToolsExecutionsRow struct {
	OutboxID            string `db:"outbox_id" json:"outbox_id"`
	ExecutionID         string `db:"execution_id" json:"execution_id"`
	Generation          int64  `db:"generation" json:"generation"`
	ProjectionProjectID int32  `db:"projection_project_id" json:"projection_project_id"`
	DesiredState        string `db:"desired_state" json:"desired_state"`
}

func (q *Queries) LockExpiredNoAuthorityToolkitAvailableToolsExecutions(ctx context.Context, arg LockExpiredNoAuthorityToolkitAvailableToolsExecutionsParams) ([]LockExpiredNoAuthorityToolkitAvailableToolsExecutionsRow, error) {
	rows, err := q.db.Query(ctx, lockExpiredNoAuthorityToolkitAvailableToolsExecutions, arg.StreamName, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockExpiredNoAuthorityToolkitAvailableToolsExecutionsRow{}
	for rows.Next() {
		var i LockExpiredNoAuthorityToolkitAvailableToolsExecutionsRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.ExecutionID,
			&i.Generation,
			&i.ProjectionProjectID,
			&i.DesiredState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockToolkitAvailableToolsEnvelope = `-- name: LockToolkitAvailableToolsEnvelope :one
SELECT o.prepared_signed_envelope_bytes,
       o.prepared_signed_envelope_digest,
       COALESCE(o.prepared_signature_profile, 0) AS prepared_signature_profile,
       COALESCE(o.prepared_key_id, '') AS prepared_key_id,
       (o.published_at IS NOT NULL)::boolean AS published,
       (o.retired_at IS NOT NULL)::boolean AS retired,
       (o.deadline <= clock_timestamp())::boolean AS deadline_expired,
       (o.authority_granted_at IS NOT NULL)::boolean AS authority_granted,
       j.state
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.command_outbox AS o
  ON o.execution_id = j.execution_id AND o.generation = j.generation
WHERE o.outbox_id = $1::text
  AND o.stream_name = $2::text
  AND j.capability_id = 'toolkit.available_tools.v1'
  AND j.generation = 1
  AND j.desired_state = 'RUNNING'
FOR UPDATE OF j, o
`

type LockToolkitAvailableToolsEnvelopeParams struct {
	OutboxID   string `db:"outbox_id" json:"outbox_id"`
	StreamName string `db:"stream_name" json:"stream_name"`
}

type LockToolkitAvailableToolsEnvelopeRow struct {
	PreparedSignedEnvelopeBytes  []byte `db:"prepared_signed_envelope_bytes" json:"prepared_signed_envelope_bytes"`
	PreparedSignedEnvelopeDigest []byte `db:"prepared_signed_envelope_digest" json:"prepared_signed_envelope_digest"`
	PreparedSignatureProfile     int32  `db:"prepared_signature_profile" json:"prepared_signature_profile"`
	PreparedKeyID                string `db:"prepared_key_id" json:"prepared_key_id"`
	Published                    bool   `db:"published" json:"published"`
	Retired                      bool   `db:"retired" json:"retired"`
	DeadlineExpired              bool   `db:"deadline_expired" json:"deadline_expired"`
	AuthorityGranted             bool   `db:"authority_granted" json:"authority_granted"`
	State                        string `db:"state" json:"state"`
}

func (q *Queries) LockToolkitAvailableToolsEnvelope(ctx context.Context, arg LockToolkitAvailableToolsEnvelopeParams) (LockToolkitAvailableToolsEnvelopeRow, error) {
	row := q.db.QueryRow(ctx, lockToolkitAvailableToolsEnvelope, arg.OutboxID, arg.StreamName)
	var i LockToolkitAvailableToolsEnvelopeRow
	err := row.Scan(
		&i.PreparedSignedEnvelopeBytes,
		&i.PreparedSignedEnvelopeDigest,
		&i.PreparedSignatureProfile,
		&i.PreparedKeyID,
		&i.Published,
		&i.Retired,
		&i.DeadlineExpired,
		&i.AuthorityGranted,
		&i.State,
	)
	return i, err
}

const lockToolkitAvailableToolsPublication = `-- name: LockToolkitAvailableToolsPublication :one
SELECT j.execution_id,
       j.generation,
       j.state,
       o.prepared_signed_envelope_digest,
       o.published_envelope_digest,
       (o.published_at IS NOT NULL)::boolean AS published,
       (o.retired_at IS NOT NULL)::boolean AS retired,
       (o.deadline <= clock_timestamp())::boolean AS deadline_expired,
       (o.authority_granted_at IS NOT NULL)::boolean AS authority_granted
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.command_outbox AS o
  ON o.execution_id = j.execution_id AND o.generation = j.generation
WHERE o.outbox_id = $1::text
  AND o.stream_name = $2::text
  AND j.capability_id = 'toolkit.available_tools.v1'
  AND j.generation = 1
  AND j.desired_state = 'RUNNING'
FOR UPDATE OF j, o
`

type LockToolkitAvailableToolsPublicationParams struct {
	OutboxID   string `db:"outbox_id" json:"outbox_id"`
	StreamName string `db:"stream_name" json:"stream_name"`
}

type LockToolkitAvailableToolsPublicationRow struct {
	ExecutionID                  string `db:"execution_id" json:"execution_id"`
	Generation                   int64  `db:"generation" json:"generation"`
	State                        string `db:"state" json:"state"`
	PreparedSignedEnvelopeDigest []byte `db:"prepared_signed_envelope_digest" json:"prepared_signed_envelope_digest"`
	PublishedEnvelopeDigest      []byte `db:"published_envelope_digest" json:"published_envelope_digest"`
	Published                    bool   `db:"published" json:"published"`
	Retired                      bool   `db:"retired" json:"retired"`
	DeadlineExpired              bool   `db:"deadline_expired" json:"deadline_expired"`
	AuthorityGranted             bool   `db:"authority_granted" json:"authority_granted"`
}

func (q *Queries) LockToolkitAvailableToolsPublication(ctx context.Context, arg LockToolkitAvailableToolsPublicationParams) (LockToolkitAvailableToolsPublicationRow, error) {
	row := q.db.QueryRow(ctx, lockToolkitAvailableToolsPublication, arg.OutboxID, arg.StreamName)
	var i LockToolkitAvailableToolsPublicationRow
	err := row.Scan(
		&i.ExecutionID,
		&i.Generation,
		&i.State,
		&i.PreparedSignedEnvelopeDigest,
		&i.PublishedEnvelopeDigest,
		&i.Published,
		&i.Retired,
		&i.DeadlineExpired,
		&i.AuthorityGranted,
	)
	return i, err
}

const markToolkitAvailableToolsDispatched = `-- name: MarkToolkitAvailableToolsDispatched :execrows
UPDATE elitea_runtime.execution_jobs
SET state = 'DISPATCHED'
WHERE execution_id = $1::text
  AND generation = $2::bigint
  AND capability_id = 'toolkit.available_tools.v1'
  AND desired_state = 'RUNNING'
  AND state = 'PENDING'
`

type MarkToolkitAvailableToolsDispatchedParams struct {
	ExecutionID string `db:"execution_id" json:"execution_id"`
	Generation  int64  `db:"generation" json:"generation"`
}

func (q *Queries) MarkToolkitAvailableToolsDispatched(ctx context.Context, arg MarkToolkitAvailableToolsDispatchedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markToolkitAvailableToolsDispatched, arg.ExecutionID, arg.Generation)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markToolkitAvailableToolsPublished = `-- name: MarkToolkitAvailableToolsPublished :execrows
UPDATE elitea_runtime.command_outbox
SET published_at = clock_timestamp(),
    published_envelope_digest = $1::bytea,
    publish_attempts = publish_attempts + 1,
    last_error_code = NULL,
    last_visibility_at = clock_timestamp()
WHERE outbox_id = $2::text
  AND published_at IS NULL
  AND retired_at IS NULL
  AND authority_granted_at IS NULL
  AND deadline > clock_timestamp()
  AND prepared_signed_envelope_digest = $1::bytea
`

type MarkToolkitAvailableToolsPublishedParams struct {
	EnvelopeDigest []byte `db:"envelope_digest" json:"envelope_digest"`
	OutboxID       string `db:"outbox_id" json:"outbox_id"`
}

func (q *Queries) MarkToolkitAvailableToolsPublished(ctx context.Context, arg MarkToolkitAvailableToolsPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markToolkitAvailableToolsPublished, arg.EnvelopeDigest, arg.OutboxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storePreparedToolkitAvailableToolsEnvelope = `-- name: StorePreparedToolkitAvailableToolsEnvelope :execrows
UPDATE elitea_runtime.command_outbox
SET prepared_signed_envelope_bytes = $1::bytea,
    prepared_signed_envelope_digest = $2::bytea,
    prepared_signature_profile = $3::integer,
    prepared_key_id = $4::text,
    prepared_at = clock_timestamp()
WHERE outbox_id = $5::text
  AND retired_at IS NULL
  AND authority_granted_at IS NULL
  AND published_at IS NULL
  AND prepared_signed_envelope_bytes IS NULL
  AND deadline > clock_timestamp()
`

type StorePreparedToolkitAvailableToolsEnvelopeParams struct {
	EnvelopeBytes    []byte `db:"envelope_bytes" json:"envelope_bytes"`
	EnvelopeDigest   []byte `db:"envelope_digest" json:"envelope_digest"`
	SignatureProfile int32  `db:"signature_profile" json:"signature_profile"`
	KeyID            string `db:"key_id" json:"key_id"`
	OutboxID         string `db:"outbox_id" json:"outbox_id"`
}

func (q *Queries) StorePreparedToolkitAvailableToolsEnvelope(ctx context.Context, arg StorePreparedToolkitAvailableToolsEnvelopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, storePreparedToolkitAvailableToolsEnvelope,
		arg.EnvelopeBytes,
		arg.EnvelopeDigest,
		arg.SignatureProfile,
		arg.KeyID,
		arg.OutboxID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
