// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_toolkit_call_tool.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExpectedToolkitCallToolHeader = `-- name: GetExpectedToolkitCallToolHeader :one
SELECT j.tenant_id,
       j.resource_project_id,
       j.projection_project_id,
       j.capability_id,
       j.command_id,
       j.execution_id,
       j.generation,
       b.input_bundle_id,
       b.manifest_digest AS input_bundle_digest
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.input_bundles AS b
  ON b.input_bundle_id = j.input_bundle_id
WHERE j.execution_id = $1::text
  AND j.generation = $2::bigint
  AND j.capability_id = 'toolkit.call_tool.v1'
`

type GetExpectedToolkitCallToolHeaderParams struct {
	ExecutionID string `db:"execution_id" json:"execution_id"`
	Generation  int64  `db:"generation" json:"generation"`
}

type GetExpectedToolkitCallToolHeaderRow struct {
	TenantID            string `db:"tenant_id" json:"tenant_id"`
	ResourceProjectID   int32  `db:"resource_project_id" json:"resource_project_id"`
	ProjectionProjectID int32  `db:"projection_project_id" json:"projection_project_id"`
	CapabilityID        string `db:"capability_id" json:"capability_id"`
	CommandID           string `db:"command_id" json:"command_id"`
	ExecutionID         string `db:"execution_id" json:"execution_id"`
	Generation          int64  `db:"generation" json:"generation"`
	InputBundleID       string `db:"input_bundle_id" json:"input_bundle_id"`
	InputBundleDigest   []byte `db:"input_bundle_digest" json:"input_bundle_digest"`
}

// GetExpectedToolkitCallToolHeader is the output plane's admitted-binding read.
// Unlike its agent counterpart it needs no capability-owned table: everything
// it returns is on execution_jobs, input_bundles and input_bundle_entries.
func (q *Queries) GetExpectedToolkitCallToolHeader(ctx context.Context, arg GetExpectedToolkitCallToolHeaderParams) (GetExpectedToolkitCallToolHeaderRow, error) {
	row := q.db.QueryRow(ctx, getExpectedToolkitCallToolHeader, arg.ExecutionID, arg.Generation)
	var i GetExpectedToolkitCallToolHeaderRow
	err := row.Scan(
		&i.TenantID,
		&i.ResourceProjectID,
		&i.ProjectionProjectID,
		&i.CapabilityID,
		&i.CommandID,
		&i.ExecutionID,
		&i.Generation,
		&i.InputBundleID,
		&i.InputBundleDigest,
	)
	return i, err
}

const getToolkitCallToolAdmissionByIdempotency = `-- name: GetToolkitCallToolAdmissionByIdempotency :one

SELECT j.execution_id,
       j.command_id,
       j.generation,
       j.request_digest,
       j.admitted_at,
       o.deadline
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.command_outbox AS o
  ON o.execution_id = j.execution_id AND o.generation = j.generation
WHERE j.idempotency_scope = $1::text
  AND j.idempotency_key = $2::text
  AND j.capability_id = 'toolkit.call_tool.v1'
`

type GetToolkitCallToolAdmissionByIdempotencyParams struct {
	IdempotencyScope string `db:"idempotency_scope" json:"idempotency_scope"`
	IdempotencyKey   string `db:"idempotency_key" json:"idempotency_key"`
}

type GetToolkitCallToolAdmissionByIdempotencyRow struct {
	ExecutionID   string             `db:"execution_id" json:"execution_id"`
	CommandID     string             `db:"command_id" json:"command_id"`
	Generation    int64              `db:"generation" json:"generation"`
	RequestDigest []byte             `db:"request_digest" json:"request_digest"`
	AdmittedAt    pgtype.Timestamptz `db:"admitted_at" json:"admitted_at"`
	Deadline      pgtype.Timestamptz `db:"deadline" json:"deadline"`
}

// toolkit.call_tool.v1 — the producer's durable half.
//
// WHY THERE IS NO PER-CAPABILITY BINDING TABLE HERE. index.ingest.v1 and
// agent.execute.*.v1 each own one (`index_ingest_jobs`, `agent_execution_jobs`)
// because a BACKGROUND publisher rebuilds their command minutes later, from the
// database alone. A tool run is admitted and dispatched inside ONE bounded
// synchronous request, so the command scalars the worker needs — toolkit type,
// tool name, toolkit id and version — never leave the process that built them
// and never need a row. The two input entry ids are recovered from
// `input_bundle_entries.semantic_role`, which is already durable.
//
// What that costs, stated rather than hidden: a crash between admission and the
// Redis append leaves an outbox row that nothing will ever publish. That is the
// right answer for a synchronous run — the caller's request died with the
// process, so "nothing ran" is true — but the row must not go on consuming
// admission capacity, which is what
// LockExpiredNoAuthorityToolkitCallToolExecutions below is for.
//
// Every JOIN the agent queries make to `agent_execution_jobs` is replaced by the
// capability predicate those queries ALREADY carry beside it. The join was
// scoping, not data, on every one of them except the pending-dispatch load,
// which this capability does not have.
func (q *Queries) GetToolkitCallToolAdmissionByIdempotency(ctx context.Context, arg GetToolkitCallToolAdmissionByIdempotencyParams) (GetToolkitCallToolAdmissionByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getToolkitCallToolAdmissionByIdempotency, arg.IdempotencyScope, arg.IdempotencyKey)
	var i GetToolkitCallToolAdmissionByIdempotencyRow
	err := row.Scan(
		&i.ExecutionID,
		&i.CommandID,
		&i.Generation,
		&i.RequestDigest,
		&i.AdmittedAt,
		&i.Deadline,
	)
	return i, err
}

const getToolkitCallToolInputEntries = `-- name: GetToolkitCallToolInputEntries :many
SELECT e.entry_id,
       e.semantic_role,
       e.entry_version,
       e.content_digest
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.input_bundle_entries AS e
  ON e.input_bundle_id = j.input_bundle_id
WHERE j.execution_id = $1::text
  AND j.generation = $2::bigint
  AND j.capability_id = 'toolkit.call_tool.v1'
  AND e.semantic_role IN (
      'toolkit.call_tool.settings',
      'toolkit.call_tool.arguments'
  )
ORDER BY e.semantic_role
`

type GetToolkitCallToolInputEntriesParams struct {
	ExecutionID string `db:"execution_id" json:"execution_id"`
	Generation  int64  `db:"generation" json:"generation"`
}

type GetToolkitCallToolInputEntriesRow struct {
	EntryID       string `db:"entry_id" json:"entry_id"`
	SemanticRole  string `db:"semantic_role" json:"semantic_role"`
	EntryVersion  string `db:"entry_version" json:"entry_version"`
	ContentDigest []byte `db:"content_digest" json:"content_digest"`
}

// GetToolkitCallToolInputEntries recovers the two entry ids the worker command
// names, from the roles that are already durable. It is the reason this
// capability needs no binding table of its own.
func (q *Queries) GetToolkitCallToolInputEntries(ctx context.Context, arg GetToolkitCallToolInputEntriesParams) ([]GetToolkitCallToolInputEntriesRow, error) {
	rows, err := q.db.Query(ctx, getToolkitCallToolInputEntries, arg.ExecutionID, arg.Generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetToolkitCallToolInputEntriesRow{}
	for rows.Next() {
		var i GetToolkitCallToolInputEntriesRow
		if err := rows.Scan(
			&i.EntryID,
			&i.SemanticRole,
			&i.EntryVersion,
			&i.ContentDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertToolkitCallToolJob = `-- name: InsertToolkitCallToolJob :one
INSERT INTO elitea_runtime.execution_jobs (
    execution_id, generation, command_id, tenant_id, resource_project_id,
    projection_project_id, actor_id, principal_ref, capability_id,
    capability_version, input_bundle_id, request_digest,
    idempotency_scope, idempotency_key, state, desired_state, admitted_at
) VALUES (
    $1::text,
    $2::bigint,
    $3::text,
    $4::text,
    $5::integer,
    $6::integer,
    $7::text,
    $8::text,
    'toolkit.call_tool.v1',
    $9::text,
    $10::text,
    $11::bytea,
    $12::text,
    $13::text,
    $14::text,
    'RUNNING',
    $15::timestamptz
)
ON CONFLICT (idempotency_scope, idempotency_key) DO NOTHING
RETURNING execution_id
`

type InsertToolkitCallToolJobParams struct {
	ExecutionID         string             `db:"execution_id" json:"execution_id"`
	Generation          int64              `db:"generation" json:"generation"`
	CommandID           string             `db:"command_id" json:"command_id"`
	TenantID            string             `db:"tenant_id" json:"tenant_id"`
	ResourceProjectID   int32              `db:"resource_project_id" json:"resource_project_id"`
	ProjectionProjectID int32              `db:"projection_project_id" json:"projection_project_id"`
	ActorID             string             `db:"actor_id" json:"actor_id"`
	PrincipalRef        string             `db:"principal_ref" json:"principal_ref"`
	CapabilityVersion   string             `db:"capability_version" json:"capability_version"`
	InputBundleID       string             `db:"input_bundle_id" json:"input_bundle_id"`
	RequestDigest       []byte             `db:"request_digest" json:"request_digest"`
	IdempotencyScope    string             `db:"idempotency_scope" json:"idempotency_scope"`
	IdempotencyKey      string             `db:"idempotency_key" json:"idempotency_key"`
	State               string             `db:"state" json:"state"`
	AdmittedAt          pgtype.Timestamptz `db:"admitted_at" json:"admitted_at"`
}

func (q *Queries) InsertToolkitCallToolJob(ctx context.Context, arg InsertToolkitCallToolJobParams) (string, error) {
	row := q.db.QueryRow(ctx, insertToolkitCallToolJob,
		arg.ExecutionID,
		arg.Generation,
		arg.CommandID,
		arg.TenantID,
		arg.ResourceProjectID,
		arg.ProjectionProjectID,
		arg.ActorID,
		arg.PrincipalRef,
		arg.CapabilityVersion,
		arg.InputBundleID,
		arg.RequestDigest,
		arg.IdempotencyScope,
		arg.IdempotencyKey,
		arg.State,
		arg.AdmittedAt,
	)
	var execution_id string
	err := row.Scan(&execution_id)
	return execution_id, err
}

const lockExpiredNoAuthorityToolkitCallToolExecutions = `-- name: LockExpiredNoAuthorityToolkitCallToolExecutions :many
SELECT o.outbox_id,
       j.execution_id,
       j.generation,
       j.projection_project_id,
       j.desired_state
FROM elitea_runtime.command_outbox AS o
JOIN elitea_runtime.execution_jobs AS j
  ON j.execution_id = o.execution_id AND j.generation = o.generation
WHERE o.deadline <= clock_timestamp()
  AND o.retired_at IS NULL
  AND o.authority_granted_at IS NULL
  AND o.stream_name = $1::text
  AND j.desired_state <> 'CANCELLED'
  AND j.state IN ('PENDING', 'DISPATCHED')
  AND j.capability_id = 'toolkit.call_tool.v1'
  AND j.generation = 1
  AND NOT EXISTS (
      SELECT 1
      FROM elitea_runtime.execution_claims AS c
      WHERE c.execution_id = j.execution_id AND c.generation = j.generation
  )
ORDER BY o.deadline, o.outbox_id
LIMIT $2::integer
FOR UPDATE OF j, o SKIP LOCKED
`

type LockExpiredNoAuthorityToolkitCallToolExecutionsParams struct {
	StreamName string `db:"stream_name" json:"stream_name"`
	BatchLimit int32  `db:"batch_limit" json:"batch_limit"`
}

type LockExpiredNoAuthorityToolkitCallToolExecutionsRow struct {
	OutboxID            string `db:"outbox_id" json:"outbox_id"`
	ExecutionID         string `db:"execution_id" json:"execution_id"`
	Generation          int64  `db:"generation" json:"generation"`
	ProjectionProjectID int32  `db:"projection_project_id" json:"projection_project_id"`
	DesiredState        string `db:"desired_state" json:"desired_state"`
}

// LockExpiredNoAuthorityToolkitCallToolExecutions reclaims the capacity a run
// that never reached Redis would otherwise hold forever. It selects only work
// past its deadline that no worker ever claimed, which is exactly the crash
// window this capability accepts in exchange for having no binding table.
func (q *Queries) LockExpiredNoAuthorityToolkitCallToolExecutions(ctx context.Context, arg LockExpiredNoAuthorityToolkitCallToolExecutionsParams) ([]LockExpiredNoAuthorityToolkitCallToolExecutionsRow, error) {
	rows, err := q.db.Query(ctx, lockExpiredNoAuthorityToolkitCallToolExecutions, arg.StreamName, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockExpiredNoAuthorityToolkitCallToolExecutionsRow{}
	for rows.Next() {
		var i LockExpiredNoAuthorityToolkitCallToolExecutionsRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.ExecutionID,
			&i.Generation,
			&i.ProjectionProjectID,
			&i.DesiredState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockToolkitCallToolEnvelope = `-- name: LockToolkitCallToolEnvelope :one
SELECT o.prepared_signed_envelope_bytes,
       o.prepared_signed_envelope_digest,
       COALESCE(o.prepared_signature_profile, 0) AS prepared_signature_profile,
       COALESCE(o.prepared_key_id, '') AS prepared_key_id,
       (o.published_at IS NOT NULL)::boolean AS published,
       (o.retired_at IS NOT NULL)::boolean AS retired,
       (o.deadline <= clock_timestamp())::boolean AS deadline_expired,
       (o.authority_granted_at IS NOT NULL)::boolean AS authority_granted,
       j.state
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.command_outbox AS o
  ON o.execution_id = j.execution_id AND o.generation = j.generation
WHERE o.outbox_id = $1::text
  AND o.stream_name = $2::text
  AND j.capability_id = 'toolkit.call_tool.v1'
  AND j.generation = 1
  AND j.desired_state = 'RUNNING'
FOR UPDATE OF j, o
`

type LockToolkitCallToolEnvelopeParams struct {
	OutboxID   string `db:"outbox_id" json:"outbox_id"`
	StreamName string `db:"stream_name" json:"stream_name"`
}

type LockToolkitCallToolEnvelopeRow struct {
	PreparedSignedEnvelopeBytes  []byte `db:"prepared_signed_envelope_bytes" json:"prepared_signed_envelope_bytes"`
	PreparedSignedEnvelopeDigest []byte `db:"prepared_signed_envelope_digest" json:"prepared_signed_envelope_digest"`
	PreparedSignatureProfile     int32  `db:"prepared_signature_profile" json:"prepared_signature_profile"`
	PreparedKeyID                string `db:"prepared_key_id" json:"prepared_key_id"`
	Published                    bool   `db:"published" json:"published"`
	Retired                      bool   `db:"retired" json:"retired"`
	DeadlineExpired              bool   `db:"deadline_expired" json:"deadline_expired"`
	AuthorityGranted             bool   `db:"authority_granted" json:"authority_granted"`
	State                        string `db:"state" json:"state"`
}

func (q *Queries) LockToolkitCallToolEnvelope(ctx context.Context, arg LockToolkitCallToolEnvelopeParams) (LockToolkitCallToolEnvelopeRow, error) {
	row := q.db.QueryRow(ctx, lockToolkitCallToolEnvelope, arg.OutboxID, arg.StreamName)
	var i LockToolkitCallToolEnvelopeRow
	err := row.Scan(
		&i.PreparedSignedEnvelopeBytes,
		&i.PreparedSignedEnvelopeDigest,
		&i.PreparedSignatureProfile,
		&i.PreparedKeyID,
		&i.Published,
		&i.Retired,
		&i.DeadlineExpired,
		&i.AuthorityGranted,
		&i.State,
	)
	return i, err
}

const lockToolkitCallToolPublication = `-- name: LockToolkitCallToolPublication :one
SELECT j.execution_id,
       j.generation,
       j.state,
       o.prepared_signed_envelope_digest,
       o.published_envelope_digest,
       (o.published_at IS NOT NULL)::boolean AS published,
       (o.retired_at IS NOT NULL)::boolean AS retired,
       (o.deadline <= clock_timestamp())::boolean AS deadline_expired,
       (o.authority_granted_at IS NOT NULL)::boolean AS authority_granted
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.command_outbox AS o
  ON o.execution_id = j.execution_id AND o.generation = j.generation
WHERE o.outbox_id = $1::text
  AND o.stream_name = $2::text
  AND j.capability_id = 'toolkit.call_tool.v1'
  AND j.generation = 1
  AND j.desired_state = 'RUNNING'
FOR UPDATE OF j, o
`

type LockToolkitCallToolPublicationParams struct {
	OutboxID   string `db:"outbox_id" json:"outbox_id"`
	StreamName string `db:"stream_name" json:"stream_name"`
}

type LockToolkitCallToolPublicationRow struct {
	ExecutionID                  string `db:"execution_id" json:"execution_id"`
	Generation                   int64  `db:"generation" json:"generation"`
	State                        string `db:"state" json:"state"`
	PreparedSignedEnvelopeDigest []byte `db:"prepared_signed_envelope_digest" json:"prepared_signed_envelope_digest"`
	PublishedEnvelopeDigest      []byte `db:"published_envelope_digest" json:"published_envelope_digest"`
	Published                    bool   `db:"published" json:"published"`
	Retired                      bool   `db:"retired" json:"retired"`
	DeadlineExpired              bool   `db:"deadline_expired" json:"deadline_expired"`
	AuthorityGranted             bool   `db:"authority_granted" json:"authority_granted"`
}

func (q *Queries) LockToolkitCallToolPublication(ctx context.Context, arg LockToolkitCallToolPublicationParams) (LockToolkitCallToolPublicationRow, error) {
	row := q.db.QueryRow(ctx, lockToolkitCallToolPublication, arg.OutboxID, arg.StreamName)
	var i LockToolkitCallToolPublicationRow
	err := row.Scan(
		&i.ExecutionID,
		&i.Generation,
		&i.State,
		&i.PreparedSignedEnvelopeDigest,
		&i.PublishedEnvelopeDigest,
		&i.Published,
		&i.Retired,
		&i.DeadlineExpired,
		&i.AuthorityGranted,
	)
	return i, err
}

const markToolkitCallToolDispatched = `-- name: MarkToolkitCallToolDispatched :execrows
UPDATE elitea_runtime.execution_jobs
SET state = 'DISPATCHED'
WHERE execution_id = $1::text
  AND generation = $2::bigint
  AND capability_id = 'toolkit.call_tool.v1'
  AND desired_state = 'RUNNING'
  AND state = 'PENDING'
`

type MarkToolkitCallToolDispatchedParams struct {
	ExecutionID string `db:"execution_id" json:"execution_id"`
	Generation  int64  `db:"generation" json:"generation"`
}

func (q *Queries) MarkToolkitCallToolDispatched(ctx context.Context, arg MarkToolkitCallToolDispatchedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markToolkitCallToolDispatched, arg.ExecutionID, arg.Generation)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markToolkitCallToolPublished = `-- name: MarkToolkitCallToolPublished :execrows
UPDATE elitea_runtime.command_outbox
SET published_at = clock_timestamp(),
    published_envelope_digest = $1::bytea,
    publish_attempts = publish_attempts + 1,
    last_error_code = NULL,
    last_visibility_at = clock_timestamp()
WHERE outbox_id = $2::text
  AND published_at IS NULL
  AND retired_at IS NULL
  AND authority_granted_at IS NULL
  AND deadline > clock_timestamp()
  AND prepared_signed_envelope_digest = $1::bytea
`

type MarkToolkitCallToolPublishedParams struct {
	EnvelopeDigest []byte `db:"envelope_digest" json:"envelope_digest"`
	OutboxID       string `db:"outbox_id" json:"outbox_id"`
}

func (q *Queries) MarkToolkitCallToolPublished(ctx context.Context, arg MarkToolkitCallToolPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markToolkitCallToolPublished, arg.EnvelopeDigest, arg.OutboxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storePreparedToolkitCallToolEnvelope = `-- name: StorePreparedToolkitCallToolEnvelope :execrows
UPDATE elitea_runtime.command_outbox
SET prepared_signed_envelope_bytes = $1::bytea,
    prepared_signed_envelope_digest = $2::bytea,
    prepared_signature_profile = $3::integer,
    prepared_key_id = $4::text,
    prepared_at = clock_timestamp()
WHERE outbox_id = $5::text
  AND retired_at IS NULL
  AND authority_granted_at IS NULL
  AND published_at IS NULL
  AND prepared_signed_envelope_bytes IS NULL
  AND deadline > clock_timestamp()
`

type StorePreparedToolkitCallToolEnvelopeParams struct {
	EnvelopeBytes    []byte `db:"envelope_bytes" json:"envelope_bytes"`
	EnvelopeDigest   []byte `db:"envelope_digest" json:"envelope_digest"`
	SignatureProfile int32  `db:"signature_profile" json:"signature_profile"`
	KeyID            string `db:"key_id" json:"key_id"`
	OutboxID         string `db:"outbox_id" json:"outbox_id"`
}

func (q *Queries) StorePreparedToolkitCallToolEnvelope(ctx context.Context, arg StorePreparedToolkitCallToolEnvelopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, storePreparedToolkitCallToolEnvelope,
		arg.EnvelopeBytes,
		arg.EnvelopeDigest,
		arg.SignatureProfile,
		arg.KeyID,
		arg.OutboxID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
