/* oxlint-disable max-lines --
   GENERATED file: one member per token id, so its length is the token count,
   not a complexity signal. scripts/check-budgets.mjs exempts .d.ts from the
   §3.5 file-length budget for the same reason; oxlint's max-lines has no
   generated-file notion, so the exemption is declared here, in the generator. */
/**
 * GENERATED by scripts/gen-brand-tokens.mjs — do not edit by hand.
 *
 * Module augmentation for the Elitea token set (spec §4.2). Every id in the
 * default pack's scheme records becomes a typed member, so component code
 * reads `theme.vars.palette.<path>` (R-T7) with full type checking; MUI
 * derives `theme.vars.palette` from `Palette`, so augmenting `Palette`
 * (and the two structural interfaces it delegates to) is sufficient.
 *
 * Members are declared on the READ side only (Palette / TypeBackground /
 * TypeText / PaletteColor). The *Options* side stays MUI's, because
 * toMuiPalette builds its result dynamically and hands it over as
 * PaletteOptions at one documented boundary.
 */
import '@mui/material/styles';

declare module '@mui/material/styles' {
  interface Palette {
    aiAssistant: {
      iconBackground: string;
      iconBorder: string;
      iconGradientEnd: string;
      iconGradientStart: string;
    };
    border: {
      aiProviderAccordion: string;
      artifactDivider: string;
      attention: string;
      cardsOutlines: string;
      cardsOutlinesGradient: string;
      category: {
        selected: string;
      };
      chatContinue: string;
      chatEditPlaceholderBorder: string;
      conversationItemDivider: string;
      error: string;
      flowNode: string;
      highlightUserMessage: string;
      hover: string;
      indexResult: {
        error: string;
        info: string;
        success: string;
        warning: string;
      };
      inputHover: string;
      lines: string;
      mcp: {
        loginSuccess: string;
        logout: string;
      };
      notificationItem: string;
      reindexInfoContainer: string;
      sidebarDivider: string;
      table: string;
      tips: string;
      toolCardGradient: string;
      userMessageEditor: string;
    };
    boxShadow: {
      aiAnswer: string;
      default: string;
      onboarding: string;
      tag: string;
      tagEditorPaper: string;
    };
    capability: {
      reasoning: {
        background: string;
        icon: string;
      };
      vision: {
        background: string;
        icon: string;
      };
    };
    checkbox: {
      active: string;
      default: string;
      disabled: string;
      hover: {
        off: string;
        on: string;
      };
      mark: string;
    };
    diff: {
      added: string;
      removed: string;
    };
    icon: {
      fill: {
        active: string;
        attention: string;
        button: string;
        default: string;
        delete: string;
        disabled: string;
        error: string;
        inactive: string;
        info: string;
        is_default: string;
        magicAssistant: string;
        primary: string;
        secondary: string;
        send: string;
        stateButton: string;
        stateButtonHover: string;
        success: string;
        successModal: string;
        tips: string;
        trophy: string;
        warning: string;
      };
      indexResult: {
        error: string;
        info: string;
        success: string;
        warning: string;
      };
      main: string;
      tagChip: {
        active: string;
        default: string;
        disabled: string;
        hover: string;
      };
    };
    nodeColors: {
      agent: string;
      code: string;
      condition: string;
      custom: string;
      decision: string;
      function: string;
      hitl: string;
      llm: string;
      loop: string;
      loop_from_tool: string;
      mcp: string;
      pipeline: string;
      printer: string;
      router: string;
      state_modifier: string;
      tool: string;
      toolkit: string;
    };
    radio: {
      active: string;
      default: string;
      disabled: string;
      hover: {
        off: string;
      };
    };
    scrollbar: {
      thumb: string;
      thumbHover: string;
    };
    split: {
      default: string;
      disabled: string;
      hover: string;
      pressed: string;
      text: {
        default: string;
        disabled: string;
        pressed: string;
      };
    };
    status: {
      draft: string;
      onModeration: string;
      published: string;
      publishedBackground: string;
      publishedBorder: string;
      publishedIcon: string;
      publishedText: string;
      rejected: string;
      rejectedText: string;
      userApproval: string;
      warningText: string;
    };
    step: {
      active: string;
      completed: {
        background: string;
        border: string;
        icon: string;
      };
      default: {
        border: string;
        icon: string;
      };
    };
    suggestionChip: {
      background: {
        default: string;
        hover: string;
      };
      border: string;
      text: {
        default: string;
        hover: string;
      };
    };
  }

  interface TypeBackground {
    agentModal: {
      background: string;
      border: string;
      content: {
        background: string;
        border: string;
      };
    };
    aiAnswerActions: string;
    aiAnswerBkg: string;
    aiParticipantIcon: string;
    aiProviderAccordion: {
      default: string;
      hover: string;
    };
    attention: string;
    avatar: string;
    banner: {
      border: string;
      default: string;
    };
    button: {
      agentHub: {
        active: string;
        default: string;
        hover: string;
        iconGradient: string;
        shadowActive: string;
        shadowDefault: string;
        shadowHover: string;
        textGradient: string;
      };
      alarm: {
        default: string;
        disabled: string;
        hover: string;
        pressed: string;
      };
      danger: string;
      default: string;
      drawerMenu: {
        default: string;
        hover: string;
        selected: string;
      };
      iconCounter: {
        pressed: string;
      };
      iconLabelButton: {
        default: string;
        disabled: string;
        hover: string;
        selected: string;
      };
      magicAssistant: string;
      maxi: {
        default: string;
        hover: string;
        pressed: string;
      };
      neutral: {
        default: string;
        disabled: string;
        hover: string;
        pressed: string;
      };
      normal: string;
      positive: {
        default: string;
        disabled: string;
        hover: string;
        pressed: string;
      };
      primary: {
        default: string;
        disabled: string;
        hover: string;
        pressed: string;
      };
      secondary: {
        default: string;
        disabled: string;
        hover: string;
        pressed: string;
      };
      special: {
        default: string;
        hover: string;
        pressed: string;
      };
      tertiary: {
        hover: string;
        pressed: string;
      };
    };
    card: {
      default: string;
      gradientDark: string;
      hover: string;
      hoverBorderGradient: string;
      hoverShadow: string;
    };
    categoriesButton: {
      selected: {
        active: string;
        hover: string;
      };
    };
    categoryHeader: string;
    chatBkg: string;
    chatContinueBackground: string;
    codeMirrorEditor: string;
    conversation: {
      hover: string;
      normal: string;
      selected: string;
    };
    conversationBottomCover: string;
    conversationEditor: string;
    conversationStarters: {
      default: string;
      hover: string;
    };
    conversationTopCover: string;
    dataGrid: {
      main: string;
      row: {
        selected: string;
      };
      secondary: string;
    };
    default: string;
    deprecated: string;
    dragging: string;
    eliteaDefault: string;
    emptyState: {
      default: string;
    };
    errorBkg: string;
    folder: {
      active: string;
      borderActive: string;
      borderGradient: string;
      borderHover: string;
      default: string;
      shadow: string;
    };
    highlightUserMessage: string;
    icon: {
      checkedBox: string;
      default: string;
      entityBorderGradient: string;
      entityGradient: string;
      trophy: string;
    };
    imageAttachment: string;
    indexResult: {
      error: string;
      info: string;
      success: string;
      warning: string;
    };
    info: string;
    interactiveTourPrompt: {
      backdrop: string;
      borderGradient: string;
      card: string;
      counter: string;
      dividerGradient: string;
    };
    mcp: {
      loginSuccess: string;
      logout: string;
    };
    modal: {
      simple: string;
    };
    notificationList: string;
    onboarding: string;
    onboardingBody: string;
    pageSection: string;
    participant: {
      active: string;
      cover: string;
      default: string;
      hover: string;
    };
    resourceCard: {
      blue: {
        borderGradient: string;
        card: string;
        divider: string;
        icon: string;
        iconBorderGradient: string;
        iconColor: string;
      };
      green: {
        borderGradient: string;
        card: string;
        divider: string;
        icon: string;
        iconBorderGradient: string;
        iconColor: string;
      };
      orange: {
        borderGradient: string;
        card: string;
        divider: string;
        icon: string;
        iconBorderGradient: string;
        iconColor: string;
      };
      pink: {
        borderGradient: string;
        card: string;
        divider: string;
        icon: string;
        iconBorderGradient: string;
        iconColor: string;
      };
      purple: {
        borderGradient: string;
        card: string;
        divider: string;
        icon: string;
        iconBorderGradient: string;
        iconColor: string;
      };
    };
    secondary: string;
    section: string;
    select: {
      hover: string;
      selected: {
        default: string;
        hover: string;
      };
    };
    settingsPage: string;
    showContextDialog: string;
    sideBar: string;
    switch: {
      default: {
        off: {
          thumb: string;
          track: string;
        };
        on: {
          thumb: string;
          track: string;
        };
      };
      disabled: {
        off: {
          thumb: string;
          track: string;
        };
        on: {
          thumb: string;
          track: string;
        };
      };
    };
    tab: {
      active: string;
      default: string;
      disabled: string;
      hover: string;
    };
    tabButton: {
      active: string;
      default: string;
      disabled: string;
      hover: string;
    };
    tabPanel: string;
    tabs: {
      default: string;
    };
    tag: {
      default: string;
      selected: string;
    };
    tagChip: {
      active: {
        default: string;
        hover: string;
      };
      default: string;
      disabled: string;
      hover: string;
    };
    tagEditor: {
      tag: string;
    };
    text: {
      highlight: string;
    };
    tips: string;
    toolCard: {
      hover: string;
    };
    toolkitDetailLeftPanel: string;
    toolkitDetailRightPanel: string;
    tooltip: {
      code: string;
      default: string;
    };
    userInputBackground: string;
    userInputBackgroundActive: string;
    userInputBorderDark: string;
    userInputBorderLight: string;
    userInputBorderShadow: string;
    userMessageActions: string;
    warning: string;
    warning40: string;
    warning8: string;
    warningBkg: string;
    welcome: {
      inner: string;
      outside: string;
    };
    wrongBkg: string;
  }

  interface TypeText {
    attention: string;
    button: {
      auxiliary: string;
      auxiliaryDefault: string;
      auxiliaryHover: string;
      auxiliaryPressed: string;
      disabled: string;
      maxiDefault: string;
      primary: string;
      secondary: string;
      secondaryPressed: string;
      showMore: string;
      specialDefault: string;
      specialPressed: string;
    };
    contextHighLight: string;
    createButton: string;
    default: string;
    deleteAlertEntityName: string;
    deleteAlertText: string;
    deprecated: string;
    error: string;
    groupedTitle: {
      default: string;
    };
    highlighted: string;
    indexResult: {
      error: string;
      info: string;
      success: string;
      warning: string;
    };
    info: string;
    input: {
      disabled: string;
      label: string;
      placeholder: string;
      placeholderSecondary: string;
      primary: string;
    };
    link: string;
    linkSeen: string;
    mcp: {
      loginSuccess: string;
      logout: string;
    };
    metrics: string;
    participant: {
      default: string;
    };
    primary: string;
    secondary: string;
    select: {
      selected: {
        primary: string;
        secondary: string;
      };
    };
    tabButton: {
      active: string;
      default: string;
      disabled: string;
      hover: string;
    };
    tag: {
      default: string;
      selected: string;
    };
    tagChip: {
      active: string;
      default: string;
      disabled: string;
    };
    tips: string;
    tooltip: string;
    warningText: string;
  }

  interface PaletteColor {
    hover: string;
    pressed: string;
    secondary: string;
    yellow: string;
  }

  interface Shape {
    radiusSm: number;
    radiusMd: number;
    radiusLg: number;
    radiusPill: number;
  }
}
