/**
 * Loads every `content/**\/*.mdx` page's COMPONENT lazily, via
 * `import.meta.glob(..., { eager: false })`, one per-slug loader wrapped in
 * React `lazy()` — only the page a reader is actually on ships its own JS
 * chunk instead of every page compiling into the entry's single chunk (see
 * `bundle-budget.json`'s docs `initialNote` for the history: all 126 pages
 * eager measured 351.2 KiB gzip initial).
 *
 * Frontmatter (title/description, needed synchronously for nav/search/
 * prev-next, the page's `<h1>`, `document.title`, `<meta name="description">`)
 * comes from `page-meta.generated.json` (`scripts/docs-build-search-
 * index.mjs`) instead of a second `import.meta.glob(..., { eager: true,
 * import: 'frontmatter' })` read of the SAME `.mdx` files. That second glob
 * was the first thing tried here, and it does not work: Rollup then sees
 * every page both statically imported (the eager frontmatter glob) and
 * dynamically imported (this lazy component glob) from this one module, and
 * folds every page's compiled component back into the eagerly-loaded graph
 * to satisfy the static edge — measured 353.2 KiB gzip initial, no smaller
 * than the all-eager baseline this file replaces. Reading frontmatter out of
 * a plain JSON file sidesteps that: JSON is not an MDX module, so importing
 * it eagerly never pulls a page's component along with it. `page-meta
 * .generated.json` specifically (not the heavier `search-index.generated
 * .json`, which also has every page's full prose, ~85 KiB gzip) is what
 * keeps this eager import cheap. See that generator script's header for the
 * fuller version of this note.
 *
 * `docs-content.test.ts` does NOT import this module — `vitest.config.ts`
 * (see that test file's own header) registers no MDX plugin, so it
 * re-derives the same slug list from the raw files on disk instead.
 * `slugFromPath` here and `slugFor` there must therefore agree, and both
 * files say so.
 */
import { lazy } from 'react';
import type { ComponentType, LazyExoticComponent } from 'react';

import type { MdxFrontmatter } from './content-types';
// Generated by `scripts/docs-build-search-index.mjs`, re-run automatically
// before every `vite build --mode docs` (wired into `build:docs` in
// package.json); committed like `src/routeTree.gen.ts`. See this module's
// own header for why `title`/`description` are read from here rather than
// the MDX modules themselves, and from this small file rather than the
// heavier `search-index.generated.json` `search.ts` loads.
import pageMetaEntries from './page-meta.generated.json';

interface MdxModule {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- the
  // component map's own values are `ComponentType<any>` for the same
  // contravariance reason `components/index.ts` documents.
  readonly default: ComponentType<{ components?: Record<string, ComponentType<any>> }>;
}

interface PageMetaEntry {
  readonly slug: string;
  readonly title: string;
  readonly description: string;
}

const componentLoaders = import.meta.glob<MdxModule>('./content/**/*.mdx', { eager: false });

export interface ContentEntry {
  readonly slug: string;
  readonly frontmatter: MdxFrontmatter;
  readonly Component: LazyExoticComponent<MdxModule['default']>;
}

function slugFromPath(path: string): string {
  // `path` looks like './content/index.mdx' or './content/quick-start.mdx'.
  const rel = path.replace(/^\.\/content\//, '').replace(/\.mdx$/, '');
  return rel === 'index' ? '' : rel;
}

const frontmatterBySlug = new Map<string, MdxFrontmatter>();
for (const pageMeta of pageMetaEntries as PageMetaEntry[]) {
  frontmatterBySlug.set(pageMeta.slug, { title: pageMeta.title, description: pageMeta.description });
}

// `lazy()` is called once per slug, at module init, and the resulting
// component is cached here — NOT re-created per render. A fresh `lazy()`
// wrapper on every render would give React a new component identity each
// time, which would defeat its "already resolved" cache and could re-trigger
// Suspense on a page that already finished loading.
const lazyComponentBySlug = new Map<string, LazyExoticComponent<MdxModule['default']>>();
for (const [path, loader] of Object.entries(componentLoaders)) {
  lazyComponentBySlug.set(slugFromPath(path), lazy(loader));
}

export function getContentEntry(slug: string): ContentEntry | undefined {
  const frontmatter = frontmatterBySlug.get(slug);
  const Component = lazyComponentBySlug.get(slug);
  if (frontmatter === undefined || Component === undefined) return undefined;
  return { slug, frontmatter, Component };
}
