/**
 * Client-side search over the docs (PREAMBLE decision 2). The index itself
 * is built at build time by `scripts/docs-build-search-index.mjs`, which
 * walks `content/**\/*.mdx`, strips MDX/JSX syntax down to prose, and writes
 * `search-index.generated.json` (gitignored — a build artifact, not source).
 * This module only loads that file and wraps it in a `minisearch` instance;
 * it does no content extraction of its own.
 *
 * The generated file is imported as a plain JSON module rather than fetched
 * at runtime: it bundles into the same JS chunk `App.tsx` already loads, so
 * there is no second network round-trip before the search box works, and no
 * risk of the index 404ing under a `base` the fetch call got wrong.
 */
import MiniSearch from 'minisearch';

// Generated by `scripts/docs-build-search-index.mjs`, re-run automatically
// before every `vite build --mode docs` (wired into `build:docs` in
// package.json). Committed like `src/routeTree.gen.ts` — a stale copy from
// the last content change, rather than absent — so `tsc --noEmit` and a
// content-only `npm run dev` both have something real to resolve; run the
// script by hand after editing `content/**` between builds (see this entry's
// README).
import generatedEntries from './search-index.generated.json';

interface SearchDocument {
  readonly id: string;
  readonly slug: string;
  readonly title: string;
  readonly text: string;
}

export interface SearchResult {
  readonly slug: string;
  readonly title: string;
  readonly excerpt: string;
  readonly score: number;
}

function buildIndex(): MiniSearch<SearchDocument> {
  const miniSearch = new MiniSearch<SearchDocument>({
    fields: ['title', 'text'],
    storeFields: ['slug', 'title', 'text'],
    searchOptions: { prefix: true, fuzzy: 0.2, boost: { title: 2 } },
  });
  const documents = generatedEntries as SearchDocument[];
  miniSearch.addAll(documents);
  return miniSearch;
}

let indexInstance: MiniSearch<SearchDocument> | undefined;

function getIndex(): MiniSearch<SearchDocument> {
  indexInstance ??= buildIndex();
  return indexInstance;
}

const EXCERPT_RADIUS = 60;

function excerptAround(text: string, query: string): string {
  const lower = text.toLowerCase();
  const at = lower.indexOf(query.toLowerCase());
  if (at === -1) return text.slice(0, EXCERPT_RADIUS * 2);
  const start = Math.max(0, at - EXCERPT_RADIUS);
  const end = Math.min(text.length, at + query.length + EXCERPT_RADIUS);
  return `${start > 0 ? '…' : ''}${text.slice(start, end)}${end < text.length ? '…' : ''}`;
}

/** Searches the built-time index; empty query returns no results rather than
 * every page, so an empty search box does not paint the whole nav twice. */
export function search(query: string): SearchResult[] {
  const trimmed = query.trim();
  if (trimmed === '') return [];
  const hits = getIndex().search(trimmed);
  return hits.map((hit) => {
    const doc = hit as unknown as SearchDocument & { score: number };
    return {
      slug: doc.slug,
      title: doc.title,
      excerpt: excerptAround(doc.text, trimmed),
      score: doc.score,
    };
  });
}
