package runtimecomposition

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"io"
	"sort"
)

const (
	currentToolkitCatalogueSnapshotVersion = "elitea.current-toolkit-catalogue-snapshot.v1"
	// The catalogue holds one settings schema and one metadata block per type
	// and measured 77,682 bytes at SDK revision b5113a1. It is a SEPARATE file
	// from the argument-schema snapshot on purpose: that file is 595,983 bytes
	// against a 1 MiB ceiling whose own comment asks that raising it be a
	// deliberate decision, and merging these two payloads would have spent that
	// headroom. Keep this budget at a quarter of the other one — the payload is
	// bounded by the number of SETTINGS fields, which does not grow with the
	// number of tools.
	maxCurrentToolkitCatalogueSnapshotBytes = 1 << 18
)

// ErrCurrentToolkitCatalogueSnapshotInvalid reports a built-in catalogue
// snapshot that this binary cannot serve. It is fatal at composition, like its
// argument-schema sibling: a catalogue that will not parse means the create
// page has no toolkit types, and answering with a shorter list silently is the
// failure this whole surface exists to remove.
var ErrCurrentToolkitCatalogueSnapshotInvalid = errors.New(
	"current toolkit catalogue snapshot is invalid",
)

// This projection is generated by the same script and the same registry read as
// current_toolkit_schema_snapshot.json
// (scripts/contract/sync_toolkit_schema_snapshot.py). It is data, not code.
//
//go:embed current_toolkit_catalogue_snapshot.json
var pinnedCurrentToolkitCatalogueSnapshotJSON []byte

type currentToolkitCatalogueSnapshotDocument struct {
	SchemaVersion string                                     `json:"schema_version"`
	SDKRevision   string                                     `json:"sdk_revision"`
	Entries       []currentToolkitCatalogueSnapshotJSONEntry `json:"entries"`
}

type currentToolkitCatalogueSnapshotJSONEntry struct {
	Type string `json:"type"`
	// ImportKey is the name elitea_sdk.tools registers the toolkit under, and
	// the name a failed import is recorded under in FAILED_IMPORTS. It is NOT
	// the type: the Kubernetes toolkit is registered as "k8s" and published as
	// the type "kubernetes". A worker capability answer keyed on the type would
	// silently never match that toolkit, so the join runs through this field.
	//
	// nil means the SDK imports the toolkit unconditionally — the runtime
	// toolkits (artifact, memory, mcp, sandbox, vectorstore, ...) — so no
	// import of it can fail.
	ImportKey *string `json:"import_key"`
	// Metadata is the type's label, categories, icon and hidden flag, plus the
	// two fields the reference deployment injects. It drives the grouping of
	// the create page's type chooser.
	Metadata map[string]any `json:"metadata"`
	// Settings is the JSON Schema of the type's settings: the create form.
	// Its properties.selected_tools carries no args_schemas — those live in the
	// argument-schema snapshot and ListTypeSchemas joins the two.
	Settings map[string]any `json:"settings"`
}

type currentToolkitCatalogueEntry struct {
	importKey string
	metadata  map[string]any
	settings  map[string]any
}

// CurrentToolkitCatalogueSnapshot is an immutable projection of the settings
// schema and metadata of every built-in toolkit type. Returned maps are always
// detached copies: the served catalogue is written to per request.
type CurrentToolkitCatalogueSnapshot struct {
	sdkRevision string
	entries     map[string]currentToolkitCatalogueEntry
}

// LoadPinnedCurrentToolkitCatalogueSnapshot loads the catalogue of the SDK
// revision the Python worker image is admitted to run.
func LoadPinnedCurrentToolkitCatalogueSnapshot() (*CurrentToolkitCatalogueSnapshot, error) {
	return LoadCurrentToolkitCatalogueSnapshot(pinnedCurrentToolkitCatalogueSnapshotJSON)
}

// LoadCurrentToolkitCatalogueSnapshot parses one bounded, deterministic
// catalogue projection.
func LoadCurrentToolkitCatalogueSnapshot(data []byte) (*CurrentToolkitCatalogueSnapshot, error) {
	if len(data) == 0 || len(data) > maxCurrentToolkitCatalogueSnapshotBytes {
		return nil, ErrCurrentToolkitCatalogueSnapshotInvalid
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	decoder.UseNumber()
	var document currentToolkitCatalogueSnapshotDocument
	if err := decoder.Decode(&document); err != nil {
		return nil, ErrCurrentToolkitCatalogueSnapshotInvalid
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return nil, ErrCurrentToolkitCatalogueSnapshotInvalid
	}
	if document.SchemaVersion != currentToolkitCatalogueSnapshotVersion ||
		!validCurrentToolkitSchemaIdentifier(document.SDKRevision) ||
		len(document.Entries) == 0 ||
		len(document.Entries) > maxCurrentToolkitSchemaEntries {
		return nil, ErrCurrentToolkitCatalogueSnapshotInvalid
	}

	entries := make(map[string]currentToolkitCatalogueEntry, len(document.Entries))
	previousType := ""
	for index := range document.Entries {
		entry := document.Entries[index]
		if !validCurrentToolkitSchemaIdentifier(entry.Type) ||
			entry.Metadata == nil || entry.Settings == nil ||
			(index != 0 && entry.Type <= previousType) {
			return nil, ErrCurrentToolkitCatalogueSnapshotInvalid
		}
		previousType = entry.Type
		importKey := ""
		if entry.ImportKey != nil {
			importKey = *entry.ImportKey
			if !validCurrentToolkitSchemaIdentifier(importKey) {
				return nil, ErrCurrentToolkitCatalogueSnapshotInvalid
			}
		}
		// One budget per entry, as the argument-schema snapshot does: the
		// metadata and the settings of a type share the node ceiling, so a
		// type cannot buy extra tree by splitting it across the two blocks.
		budget := currentToolkitSchemaTreeBudget{}
		metadata, err := cloneCurrentToolkitSchemaObject(entry.Metadata, 0, &budget)
		if err != nil {
			return nil, ErrCurrentToolkitCatalogueSnapshotInvalid
		}
		settings, err := cloneCurrentToolkitSchemaObject(entry.Settings, 0, &budget)
		if err != nil {
			return nil, ErrCurrentToolkitCatalogueSnapshotInvalid
		}
		entries[entry.Type] = currentToolkitCatalogueEntry{
			importKey: importKey,
			metadata:  metadata,
			settings:  settings,
		}
	}
	return &CurrentToolkitCatalogueSnapshot{
		sdkRevision: document.SDKRevision,
		entries:     entries,
	}, nil
}

func (s *CurrentToolkitCatalogueSnapshot) SDKRevision() string {
	if s == nil {
		return ""
	}
	return s.sdkRevision
}

func (s *CurrentToolkitCatalogueSnapshot) EntryCount() int {
	if s == nil {
		return 0
	}
	return len(s.entries)
}

// ToolkitTypes returns every built-in toolkit type the catalogue declares,
// sorted.
func (s *CurrentToolkitCatalogueSnapshot) ToolkitTypes() []string {
	if s == nil {
		return nil
	}
	types := make([]string, 0, len(s.entries))
	for toolkitType := range s.entries {
		types = append(types, toolkitType)
	}
	sort.Strings(types)
	return types
}

// ToolkitImportKey returns the SDK registry import key of one type. An empty
// key with found=true means the SDK imports the toolkit unconditionally.
func (s *CurrentToolkitCatalogueSnapshot) ToolkitImportKey(toolkitType string) (string, bool) {
	if s == nil {
		return "", false
	}
	entry, found := s.entries[toolkitType]
	if !found {
		return "", false
	}
	return entry.importKey, true
}

// ToolkitCatalogueEntry returns detached copies of one type's settings schema
// and metadata. found=false means the type is not a built-in SDK toolkit.
//
// Both maps are rebuilt on every call. The caller serves them into an HTTP
// response and then writes to them — the guardrail filter and the capability
// projection both edit the served schema — so a shared tree would leak one
// request's edits into the next.
func (s *CurrentToolkitCatalogueSnapshot) ToolkitCatalogueEntry(
	toolkitType string,
) (map[string]any, map[string]any, bool, error) {
	if s == nil || !validCurrentToolkitSchemaIdentifier(toolkitType) {
		return nil, nil, false, ErrCurrentToolkitCatalogueSnapshotInvalid
	}
	entry, found := s.entries[toolkitType]
	if !found {
		return nil, nil, false, nil
	}
	budget := currentToolkitSchemaTreeBudget{}
	settings, err := cloneCurrentToolkitSchemaObject(entry.settings, 0, &budget)
	if err != nil {
		return nil, nil, false, ErrCurrentToolkitCatalogueSnapshotInvalid
	}
	metadata, err := cloneCurrentToolkitSchemaObject(entry.metadata, 0, &budget)
	if err != nil {
		return nil, nil, false, ErrCurrentToolkitCatalogueSnapshotInvalid
	}
	return settings, metadata, true, nil
}
