/**
 * ParticipantItem styles — extracted to keep the component ≤ 400 lines (spec §3.5).
 */
import type { SxProps, Theme } from '@mui/material/styles';

export const participantItemStyles = (theme: { vars: { shape: { radiusMd: string } } }): Record<string, SxProps<Theme> | ((c: boolean, i: boolean | undefined) => SxProps<Theme>)> => ({
  normalItemWrapper: { display: 'flex', flexDirection: 'column', width: '100%' },
  contentWrapper: (collapsed: boolean, isActive: boolean | undefined) => ({
    cursor: 'pointer',
    padding: collapsed ? '0 0' : '0.5rem 0.75rem',
    borderRadius: theme.vars.shape.radiusMd,
    gap: '0.5rem',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: collapsed ? 'center' : 'flex-start',
    width: '100%',
    height: '2.5rem',
    boxSizing: 'border-box',
    background: isActive ? 'background.participant.active' : 'background.participant.default',
    border: isActive ? '0.0625rem solid' : 'none',
    borderColor: 'split.hover',
    '&:hover': { background: 'background.participant.hover' },
  }),
  nameWrapper: {
    flex: 1,
    maxWidth: 'calc(100% - 2.125rem)',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '.5rem',
  },
  nameContent: {
    flex: 1,
    minWidth: '50%',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: 'inline-flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  attentionWrapper: (isActive: boolean | undefined) => ({
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    padding: '.5rem 1rem',
    borderWidth: '.0625rem',
    borderStyle: 'solid',
    borderColor: 'border.attention',
    borderRadius: theme.vars.shape.radiusMd,
    backgroundColor: 'background.attention',
    width: '100%',
    gap: '.5rem',
    cursor: isActive ? 'pointer' : 'default',
  }),
  attentionHeader: { display: 'flex', flexDirection: 'row', gap: '.75rem', height: '1.75rem', alignItems: 'center' },
  attentionNameBox: { flex: 1, maxWidth: 'calc(100% - 2.125rem)', display: 'flex', flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'center' },
  attentionDisplayName: { flex: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  attentionEditingText: { maxWidth: '50%', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  attentionMessageRow: { display: 'flex', flexDirection: 'row', gap: '0.9rem' },
  attentionIcon: { paddingLeft: '0.25rem', width: '1rem', height: '1rem', '& svg': { fill: 'icon.fill.attention' } },
  attentionMessage: { wordBreak: 'break-word' },
  infoMessageRow: { display: 'flex', flexDirection: 'row', alignItems: 'flex-start', gap: '.375rem', padding: '0 .75rem .25rem' },
  infoIcon: { display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, width: '1rem', height: '1rem', '& svg, & path': { fill: 'icon.fill.secondary' } },
  iconBoxNormal: (isActive: boolean | undefined) => ({
    width: '1.5rem', height: '1.5rem', minWidth: '1.5rem',
    borderRadius: 'var(--el-shape-radiusMd, 8px)', backgroundColor: isActive ? 'action.selected' : 'background.paper',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: (t: Theme) => t.typography.bodySmall.fontSize, fontWeight: 600, overflow: 'hidden',
  }),
  iconBoxAttention: {
    width: '1.5rem', height: '1.5rem', minWidth: '1.5rem',
    borderRadius: 'var(--el-shape-radiusMd, 8px)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: (t: Theme) => t.typography.bodySmall.fontSize, fontWeight: 600, overflow: 'hidden',
  },
});
