/**
 * Ported from `apps/elitea-ui/src/[fsd]/features/pipelines/flow-editor/lib/
 * helpers/node.helpers.jsx` (unit A2c).
 *
 * `isDeprecatedNodeType`'s baseline (`node.helpers.jsx:30-32`) reads
 * `DeprecatedConstants.DeprecatedNodes`, defined in a SIBLING file
 * (`constants/deprecated.constants.js`) that is NOT in this unit's owned-file
 * list (the wave2-partition.json `A2` entry assigns it to a different flow-
 * editor sub-unit, alongside the `DeprecatedTips` UI copy this unit's
 * functions never read). Per this mission's stated precedent for
 * not-owned-but-needed dependencies, `DEPRECATED_NODE_TYPES` below is a
 * local, minimal duplicate of just the array `isDeprecatedNodeType` needs —
 * not the full `deprecated.constants.js` port (that stays the owning
 * sub-unit's to build, including `DeprecatedTips`).
 *
 * `getNodeColor`/`getNodeIconByType` read `theme.vars.palette.*` (R-T7,
 * `no-theme-palette`) instead of the baseline's `theme.palette.*` — the
 * `nodeColors` token set is already a real MUI `Palette` augmentation
 * (`shared/brand/tokens/palette.augment.d.ts`, generated by unit T1/T2 from
 * `lightPalette.js`/`darkPalette.js:554-575`'s `nodeColors` object), so this
 * reads the SAME real per-node-type colours the baseline hard-coded, just
 * through the CSS-variable-backed accessor this app's theming requires.
 *
 * **Disclosed deviation:** the baseline's icon-colour fallback and the
 * unmatched-node-colour fallback are both raw hex literals
 * (`'#666666'`/icon default). This repo's `no-raw-color` fence (R-T1) bans
 * hex literals outside `shared/brand/tokens/` entirely — `getNodeColor`'s
 * final fallback is `theme.vars.palette.text.secondary` (the same neutral
 * token `getNodeIconByType` already uses for its own icon colour) instead
 * of the baseline's bare `'#666666'`. Visually equivalent (both are the
 * app's neutral/secondary gray), sourced from the token system rather than
 * a duplicated literal.
 */
import RepeatIcon from '@mui/icons-material/Repeat';
import RepeatOneIcon from '@mui/icons-material/RepeatOne';
import type { Theme } from '@mui/material/styles';
import type { ComponentType, CSSProperties, ReactElement } from 'react';

import { PipelineNodeTypes } from '../constants/flowEditor.constants';
import { AgentIcon } from '@/shared/ui/icons/agent-icon';
import { CodeIcon } from '@/shared/ui/icons/code-icon';
import { ConditionIcon } from '@/shared/ui/icons/condition-icon';
import { DecisionIcon } from '@/shared/ui/icons/decision-icon';
import { FlagIcon } from '@/shared/ui/icons/flag-icon';
import { FlowIcon } from '@/shared/ui/icons/flow-icon';
import { HumanIcon } from '@/shared/ui/icons/human-icon';
import { JsonIcon } from '@/shared/ui/icons/json-icon';
import { McpIcon } from '@/shared/ui/icons/mcp-icon';
import { ModelIcon } from '@/shared/ui/icons/model-icon';
import { PrinterIcon } from '@/shared/ui/icons/printer-icon';
import { RouterIcon } from '@/shared/ui/icons/router-icon';
import { StateModifierIcon } from '@/shared/ui/icons/state-modifier-icon';
import { ToolIcon } from '@/shared/ui/icons/tool-icon';
import { VectorIcon as FunctionIcon } from '@/shared/ui/icons/vector-icon';

/** `deprecated.constants.js:39-46`'s `DeprecatedNodes` array — see module doc comment. */
const DEPRECATED_NODE_TYPES: ReadonlySet<string> = new Set([
  PipelineNodeTypes.Function,
  PipelineNodeTypes.Condition,
  PipelineNodeTypes.Pipeline,
  PipelineNodeTypes.Loop,
  PipelineNodeTypes.LoopFromTool,
  PipelineNodeTypes.Tool,
]);

export const getNodeColor = (nodeType: string, theme: Theme | undefined): string => {
  const nodeColors = theme?.vars.palette.nodeColors as Record<string, string> | undefined;
  return nodeColors?.[nodeType] ?? nodeColors?.['custom'] ?? theme?.vars.palette.text.secondary ?? '';
};

export const isDeprecatedNodeType = (type: string): boolean => DEPRECATED_NODE_TYPES.has(type);

interface IconProps {
  readonly style?: CSSProperties;
  readonly fill?: string;
}

/** One icon component per `PipelineNodeTypes` value that has a dedicated glyph — everything else falls back to `JsonIcon` (baseline `node.helpers.jsx`'s own `default` case). */
const ICON_BY_NODE_TYPE: Readonly<Record<string, ComponentType<IconProps>>> = {
  [PipelineNodeTypes.Mcp]: McpIcon,
  [PipelineNodeTypes.LLM]: ModelIcon,
  [PipelineNodeTypes.Toolkit]: ToolIcon,
  [PipelineNodeTypes.Tool]: ToolIcon,
  [PipelineNodeTypes.Function]: FunctionIcon,
  [PipelineNodeTypes.Condition]: ConditionIcon,
  [PipelineNodeTypes.Decision]: DecisionIcon,
  [PipelineNodeTypes.LoopFromTool]: RepeatIcon,
  [PipelineNodeTypes.Loop]: RepeatOneIcon,
  [PipelineNodeTypes.Agent]: AgentIcon,
  [PipelineNodeTypes.Pipeline]: FlowIcon,
  [PipelineNodeTypes.Router]: RouterIcon,
  [PipelineNodeTypes.StateModifier]: StateModifierIcon,
  [PipelineNodeTypes.Code]: CodeIcon,
  [PipelineNodeTypes.Printer]: PrinterIcon,
  [PipelineNodeTypes.Hitl]: HumanIcon,
  [PipelineNodeTypes.Custom]: JsonIcon,
  [PipelineNodeTypes.End]: FlagIcon,
};

export const getNodeIconByType = (type: string, theme: Theme, specifiedColor?: string): ReactElement => {
  const iconColor = specifiedColor ?? theme.vars.palette.text.secondary;
  const style: CSSProperties = { fontSize: theme.typography.bodyMedium.fontSize, color: iconColor };
  const Icon = ICON_BY_NODE_TYPE[type] ?? JsonIcon;
  return <Icon style={style} fill={iconColor} />;
};
