/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as ProjectIdSplatRouteImport } from './routes/$projectId.$'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAgentsHubRouteImport } from './routes/_shell/agents-hub'
import { Route as ShellChatRouteImport } from './routes/_shell/chat'
import { Route as ShellEliteaCatalogRouteImport } from './routes/_shell/elitea-catalog'
import { Route as ShellHelpCenterRouteImport } from './routes/_shell/help-center'
import { Route as ShellMcpAuthCallbackRouteImport } from './routes/_shell/mcp-auth-callback'
import { Route as ShellModeSwitchRouteImport } from './routes/_shell/mode-switch'
import { Route as ShellOnboardingRouteImport } from './routes/_shell/onboarding'
import { Route as ShellSettingsRouteRouteImport } from './routes/_shell/settings/route'
import { Route as ShellAgentsIndexRouteImport } from './routes/_shell/agents/index'
import { Route as ShellAgentsTabRouteImport } from './routes/_shell/agents/$tab'
import { Route as ShellAgentsCreateRouteImport } from './routes/_shell/agents/create'
import { Route as ShellAppsIndexRouteImport } from './routes/_shell/apps/index'
import { Route as ShellAppsTabRouteImport } from './routes/_shell/apps/$tab'
import { Route as ShellAppsCreateRouteImport } from './routes/_shell/apps/create'
import { Route as ShellArtifactsIndexRouteImport } from './routes/_shell/artifacts/index'
import { Route as ShellArtifactsCreateBucketRouteImport } from './routes/_shell/artifacts/create-bucket'
import { Route as ShellChatConversationIdRouteImport } from './routes/_shell/chat.$conversationId'
import { Route as ShellCredentialsIndexRouteImport } from './routes/_shell/credentials/index'
import { Route as ShellCredentialsTabRouteImport } from './routes/_shell/credentials/$tab'
import { Route as ShellCredentialsCreateCredentialRouteImport } from './routes/_shell/credentials/create-credential'
import { Route as ShellDeepwikiIndexRouteImport } from './routes/_shell/deepwiki.index'
import { Route as ShellDeepwikiToolkitIdRouteImport } from './routes/_shell/deepwiki.$toolkitId'
import { Route as ShellMcpsIndexRouteImport } from './routes/_shell/mcps/index'
import { Route as ShellMcpsTabRouteImport } from './routes/_shell/mcps/$tab'
import { Route as ShellMcpsCreateRouteImport } from './routes/_shell/mcps/create'
import { Route as ShellPipelinesIndexRouteImport } from './routes/_shell/pipelines/index'
import { Route as ShellPipelinesTabRouteImport } from './routes/_shell/pipelines/$tab'
import { Route as ShellPipelinesCreateRouteImport } from './routes/_shell/pipelines/create'
import { Route as ShellSettingsIndexRouteImport } from './routes/_shell/settings/index'
import { Route as ShellSettingsTabRouteImport } from './routes/_shell/settings/$tab'
import { Route as ShellSettingsAiPersonalityRouteImport } from './routes/_shell/settings/ai-personality'
import { Route as ShellSettingsAnalyticsRouteImport } from './routes/_shell/settings/analytics'
import { Route as ShellSettingsCreateConfigurationRouteImport } from './routes/_shell/settings/create-configuration'
import { Route as ShellSettingsCreatePersonalTokenRouteImport } from './routes/_shell/settings/create-personal-token'
import { Route as ShellSettingsEnvironmentRouteImport } from './routes/_shell/settings/environment'
import { Route as ShellSettingsMemoryRouteImport } from './routes/_shell/settings/memory'
import { Route as ShellSettingsModelConfigurationRouteImport } from './routes/_shell/settings/model-configuration'
import { Route as ShellSettingsNotificationsRouteImport } from './routes/_shell/settings/notifications'
import { Route as ShellSettingsPersonalizationRouteImport } from './routes/_shell/settings/personalization'
import { Route as ShellSettingsPreferencesRouteImport } from './routes/_shell/settings/preferences'
import { Route as ShellSettingsProjectParamsRouteImport } from './routes/_shell/settings/project-params'
import { Route as ShellSettingsPromptsRouteImport } from './routes/_shell/settings/prompts'
import { Route as ShellSettingsSecretsRouteImport } from './routes/_shell/settings/secrets'
import { Route as ShellSettingsTokensRouteImport } from './routes/_shell/settings/tokens'
import { Route as ShellSettingsUsageRouteImport } from './routes/_shell/settings/usage'
import { Route as ShellSettingsUsersRouteImport } from './routes/_shell/settings/users'
import { Route as ShellSkillsIndexRouteImport } from './routes/_shell/skills/index'
import { Route as ShellSkillsTabRouteImport } from './routes/_shell/skills/$tab'
import { Route as ShellSkillsCreateRouteImport } from './routes/_shell/skills/create'
import { Route as ShellToolkitsIndexRouteImport } from './routes/_shell/toolkits/index'
import { Route as ShellToolkitsTabRouteImport } from './routes/_shell/toolkits/$tab'
import { Route as ShellToolkitsCreateRouteImport } from './routes/_shell/toolkits/create'
import { Route as ShellUserPublicTabRouteImport } from './routes/_shell/user-public/$tab'
import { Route as SharedChatTokenRouteImport } from './routes/shared.chat.$token'
import { Route as ShellAgentsTabAgentIdRouteImport } from './routes/_shell/agents/$tab.$agentId'
import { Route as ShellAppsTabAppIdRouteImport } from './routes/_shell/apps/$tab.$appId'
import { Route as ShellAppsCreateAppTypeRouteImport } from './routes/_shell/apps/create.$appType'
import { Route as ShellCredentialsTabCredential_uidRouteImport } from './routes/_shell/credentials/$tab.$credential_uid'
import { Route as ShellCredentialsCreateCredentialCredentialTypeRouteImport } from './routes/_shell/credentials/create-credential.$credentialType'
import { Route as ShellMcpsTabMcpIdRouteImport } from './routes/_shell/mcps/$tab.$mcpId'
import { Route as ShellMcpsCreateMcpTypeRouteImport } from './routes/_shell/mcps/create.$mcpType'
import { Route as ShellPipelinesTabAgentIdRouteImport } from './routes/_shell/pipelines/$tab.$agentId'
import { Route as ShellSettingsCreateConfigurationCredentialTypeRouteImport } from './routes/_shell/settings/create-configuration.$credentialType'
import { Route as ShellSettingsEditConfigurationCredential_uidRouteImport } from './routes/_shell/settings/edit-configuration.$credential_uid'
import { Route as ShellSkillsTabSkillIdRouteImport } from './routes/_shell/skills/$tab.$skillId'
import { Route as ShellToolkitsTabToolkitIdRouteImport } from './routes/_shell/toolkits/$tab.$toolkitId'
import { Route as ShellToolkitsCreateToolkitTypeRouteImport } from './routes/_shell/toolkits/create.$toolkitType'
import { Route as ShellUserPublicAgentsAgentIdRouteImport } from './routes/_shell/user-public/agents.$agentId'
import { Route as ShellUserPublicAppsAppIdRouteImport } from './routes/_shell/user-public/apps.$appId'
import { Route as ShellUserPublicMcpsMcpIdRouteImport } from './routes/_shell/user-public/mcps.$mcpId'
import { Route as ShellUserPublicPipelinesAgentIdRouteImport } from './routes/_shell/user-public/pipelines.$agentId'
import { Route as ShellUserPublicToolkitsToolkitIdRouteImport } from './routes/_shell/user-public/toolkits.$toolkitId'
import { Route as ShellAgentsTabAgentIdVersionRouteImport } from './routes/_shell/agents/$tab.$agentId.$version'
import { Route as ShellPipelinesTabAgentIdVersionRouteImport } from './routes/_shell/pipelines/$tab.$agentId.$version'
import { Route as ShellSkillsTabSkillIdVersionRouteImport } from './routes/_shell/skills/$tab.$skillId.$version'
import { Route as ShellUserPublicAgentsAgentIdVersionRouteImport } from './routes/_shell/user-public/agents.$agentId.$version'
import { Route as ShellUserPublicPipelinesAgentIdVersionRouteImport } from './routes/_shell/user-public/pipelines.$agentId.$version'

const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdSplatRoute = ProjectIdSplatRouteImport.update({
  id: '/$projectId/$',
  path: '/$projectId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAgentsHubRoute = ShellAgentsHubRouteImport.update({
  id: '/agents-hub',
  path: '/agents-hub',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellChatRoute = ShellChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellEliteaCatalogRoute = ShellEliteaCatalogRouteImport.update({
  id: '/elitea-catalog',
  path: '/elitea-catalog',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellHelpCenterRoute = ShellHelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellMcpAuthCallbackRoute = ShellMcpAuthCallbackRouteImport.update({
  id: '/mcp-auth-callback',
  path: '/mcp-auth-callback',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellModeSwitchRoute = ShellModeSwitchRouteImport.update({
  id: '/mode-switch',
  path: '/mode-switch',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellOnboardingRoute = ShellOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellSettingsRouteRoute = ShellSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAgentsIndexRoute = ShellAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAgentsTabRoute = ShellAgentsTabRouteImport.update({
  id: '/agents/$tab',
  path: '/agents/$tab',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAgentsCreateRoute = ShellAgentsCreateRouteImport.update({
  id: '/agents/create',
  path: '/agents/create',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAppsIndexRoute = ShellAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAppsTabRoute = ShellAppsTabRouteImport.update({
  id: '/apps/$tab',
  path: '/apps/$tab',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAppsCreateRoute = ShellAppsCreateRouteImport.update({
  id: '/apps/create',
  path: '/apps/create',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellArtifactsIndexRoute = ShellArtifactsIndexRouteImport.update({
  id: '/artifacts/',
  path: '/artifacts/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellArtifactsCreateBucketRoute =
  ShellArtifactsCreateBucketRouteImport.update({
    id: '/artifacts/create-bucket',
    path: '/artifacts/create-bucket',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellChatConversationIdRoute = ShellChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ShellChatRoute,
} as any)
const ShellCredentialsIndexRoute = ShellCredentialsIndexRouteImport.update({
  id: '/credentials/',
  path: '/credentials/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellCredentialsTabRoute = ShellCredentialsTabRouteImport.update({
  id: '/credentials/$tab',
  path: '/credentials/$tab',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellCredentialsCreateCredentialRoute =
  ShellCredentialsCreateCredentialRouteImport.update({
    id: '/credentials/create-credential',
    path: '/credentials/create-credential',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellDeepwikiIndexRoute = ShellDeepwikiIndexRouteImport.update({
  id: '/deepwiki/',
  path: '/deepwiki/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellDeepwikiToolkitIdRoute = ShellDeepwikiToolkitIdRouteImport.update({
  id: '/deepwiki/$toolkitId',
  path: '/deepwiki/$toolkitId',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellMcpsIndexRoute = ShellMcpsIndexRouteImport.update({
  id: '/mcps/',
  path: '/mcps/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellMcpsTabRoute = ShellMcpsTabRouteImport.update({
  id: '/mcps/$tab',
  path: '/mcps/$tab',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellMcpsCreateRoute = ShellMcpsCreateRouteImport.update({
  id: '/mcps/create',
  path: '/mcps/create',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPipelinesIndexRoute = ShellPipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPipelinesTabRoute = ShellPipelinesTabRouteImport.update({
  id: '/pipelines/$tab',
  path: '/pipelines/$tab',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPipelinesCreateRoute = ShellPipelinesCreateRouteImport.update({
  id: '/pipelines/create',
  path: '/pipelines/create',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellSettingsIndexRoute = ShellSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSettingsRouteRoute,
} as any)
const ShellSettingsTabRoute = ShellSettingsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => ShellSettingsRouteRoute,
} as any)
const ShellSettingsAiPersonalityRoute =
  ShellSettingsAiPersonalityRouteImport.update({
    id: '/ai-personality',
    path: '/ai-personality',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSettingsAnalyticsRoute = ShellSettingsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellSettingsRouteRoute,
} as any)
const ShellSettingsCreateConfigurationRoute =
  ShellSettingsCreateConfigurationRouteImport.update({
    id: '/create-configuration',
    path: '/create-configuration',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSettingsCreatePersonalTokenRoute =
  ShellSettingsCreatePersonalTokenRouteImport.update({
    id: '/create-personal-token',
    path: '/create-personal-token',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSettingsEnvironmentRoute =
  ShellSettingsEnvironmentRouteImport.update({
    id: '/environment',
    path: '/environment',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSettingsMemoryRoute = ShellSettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => ShellSettingsRouteRoute,
} as any)
const ShellSettingsModelConfigurationRoute =
  ShellSettingsModelConfigurationRouteImport.update({
    id: '/model-configuration',
    path: '/model-configuration',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSettingsNotificationsRoute =
  ShellSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSettingsPersonalizationRoute =
  ShellSettingsPersonalizationRouteImport.update({
    id: '/personalization',
    path: '/personalization',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSettingsPreferencesRoute =
  ShellSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSettingsProjectParamsRoute =
  ShellSettingsProjectParamsRouteImport.update({
    id: '/project-params',
    path: '/project-params',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSettingsPromptsRoute = ShellSettingsPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => ShellSettingsRouteRoute,
} as any)
const ShellSettingsSecretsRoute = ShellSettingsSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => ShellSettingsRouteRoute,
} as any)
const ShellSettingsTokensRoute = ShellSettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => ShellSettingsRouteRoute,
} as any)
const ShellSettingsUsageRoute = ShellSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ShellSettingsRouteRoute,
} as any)
const ShellSettingsUsersRoute = ShellSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellSettingsRouteRoute,
} as any)
const ShellSkillsIndexRoute = ShellSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellSkillsTabRoute = ShellSkillsTabRouteImport.update({
  id: '/skills/$tab',
  path: '/skills/$tab',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellSkillsCreateRoute = ShellSkillsCreateRouteImport.update({
  id: '/skills/create',
  path: '/skills/create',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellToolkitsIndexRoute = ShellToolkitsIndexRouteImport.update({
  id: '/toolkits/',
  path: '/toolkits/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellToolkitsTabRoute = ShellToolkitsTabRouteImport.update({
  id: '/toolkits/$tab',
  path: '/toolkits/$tab',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellToolkitsCreateRoute = ShellToolkitsCreateRouteImport.update({
  id: '/toolkits/create',
  path: '/toolkits/create',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellUserPublicTabRoute = ShellUserPublicTabRouteImport.update({
  id: '/user-public/$tab',
  path: '/user-public/$tab',
  getParentRoute: () => ShellRouteRoute,
} as any)
const SharedChatTokenRoute = SharedChatTokenRouteImport.update({
  id: '/shared/chat/$token',
  path: '/shared/chat/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAgentsTabAgentIdRoute = ShellAgentsTabAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => ShellAgentsTabRoute,
} as any)
const ShellAppsTabAppIdRoute = ShellAppsTabAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => ShellAppsTabRoute,
} as any)
const ShellAppsCreateAppTypeRoute = ShellAppsCreateAppTypeRouteImport.update({
  id: '/$appType',
  path: '/$appType',
  getParentRoute: () => ShellAppsCreateRoute,
} as any)
const ShellCredentialsTabCredential_uidRoute =
  ShellCredentialsTabCredential_uidRouteImport.update({
    id: '/$credential_uid',
    path: '/$credential_uid',
    getParentRoute: () => ShellCredentialsTabRoute,
  } as any)
const ShellCredentialsCreateCredentialCredentialTypeRoute =
  ShellCredentialsCreateCredentialCredentialTypeRouteImport.update({
    id: '/$credentialType',
    path: '/$credentialType',
    getParentRoute: () => ShellCredentialsCreateCredentialRoute,
  } as any)
const ShellMcpsTabMcpIdRoute = ShellMcpsTabMcpIdRouteImport.update({
  id: '/$mcpId',
  path: '/$mcpId',
  getParentRoute: () => ShellMcpsTabRoute,
} as any)
const ShellMcpsCreateMcpTypeRoute = ShellMcpsCreateMcpTypeRouteImport.update({
  id: '/$mcpType',
  path: '/$mcpType',
  getParentRoute: () => ShellMcpsCreateRoute,
} as any)
const ShellPipelinesTabAgentIdRoute =
  ShellPipelinesTabAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => ShellPipelinesTabRoute,
  } as any)
const ShellSettingsCreateConfigurationCredentialTypeRoute =
  ShellSettingsCreateConfigurationCredentialTypeRouteImport.update({
    id: '/$credentialType',
    path: '/$credentialType',
    getParentRoute: () => ShellSettingsCreateConfigurationRoute,
  } as any)
const ShellSettingsEditConfigurationCredential_uidRoute =
  ShellSettingsEditConfigurationCredential_uidRouteImport.update({
    id: '/edit-configuration/$credential_uid',
    path: '/edit-configuration/$credential_uid',
    getParentRoute: () => ShellSettingsRouteRoute,
  } as any)
const ShellSkillsTabSkillIdRoute = ShellSkillsTabSkillIdRouteImport.update({
  id: '/$skillId',
  path: '/$skillId',
  getParentRoute: () => ShellSkillsTabRoute,
} as any)
const ShellToolkitsTabToolkitIdRoute =
  ShellToolkitsTabToolkitIdRouteImport.update({
    id: '/$toolkitId',
    path: '/$toolkitId',
    getParentRoute: () => ShellToolkitsTabRoute,
  } as any)
const ShellToolkitsCreateToolkitTypeRoute =
  ShellToolkitsCreateToolkitTypeRouteImport.update({
    id: '/$toolkitType',
    path: '/$toolkitType',
    getParentRoute: () => ShellToolkitsCreateRoute,
  } as any)
const ShellUserPublicAgentsAgentIdRoute =
  ShellUserPublicAgentsAgentIdRouteImport.update({
    id: '/user-public/agents/$agentId',
    path: '/user-public/agents/$agentId',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellUserPublicAppsAppIdRoute =
  ShellUserPublicAppsAppIdRouteImport.update({
    id: '/user-public/apps/$appId',
    path: '/user-public/apps/$appId',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellUserPublicMcpsMcpIdRoute =
  ShellUserPublicMcpsMcpIdRouteImport.update({
    id: '/user-public/mcps/$mcpId',
    path: '/user-public/mcps/$mcpId',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellUserPublicPipelinesAgentIdRoute =
  ShellUserPublicPipelinesAgentIdRouteImport.update({
    id: '/user-public/pipelines/$agentId',
    path: '/user-public/pipelines/$agentId',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellUserPublicToolkitsToolkitIdRoute =
  ShellUserPublicToolkitsToolkitIdRouteImport.update({
    id: '/user-public/toolkits/$toolkitId',
    path: '/user-public/toolkits/$toolkitId',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellAgentsTabAgentIdVersionRoute =
  ShellAgentsTabAgentIdVersionRouteImport.update({
    id: '/$version',
    path: '/$version',
    getParentRoute: () => ShellAgentsTabAgentIdRoute,
  } as any)
const ShellPipelinesTabAgentIdVersionRoute =
  ShellPipelinesTabAgentIdVersionRouteImport.update({
    id: '/$version',
    path: '/$version',
    getParentRoute: () => ShellPipelinesTabAgentIdRoute,
  } as any)
const ShellSkillsTabSkillIdVersionRoute =
  ShellSkillsTabSkillIdVersionRouteImport.update({
    id: '/$version',
    path: '/$version',
    getParentRoute: () => ShellSkillsTabSkillIdRoute,
  } as any)
const ShellUserPublicAgentsAgentIdVersionRoute =
  ShellUserPublicAgentsAgentIdVersionRouteImport.update({
    id: '/$version',
    path: '/$version',
    getParentRoute: () => ShellUserPublicAgentsAgentIdRoute,
  } as any)
const ShellUserPublicPipelinesAgentIdVersionRoute =
  ShellUserPublicPipelinesAgentIdVersionRouteImport.update({
    id: '/$version',
    path: '/$version',
    getParentRoute: () => ShellUserPublicPipelinesAgentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/settings': typeof ShellSettingsRouteRouteWithChildren
  '/$projectId/$': typeof ProjectIdSplatRoute
  '/agents-hub': typeof ShellAgentsHubRoute
  '/chat': typeof ShellChatRouteWithChildren
  '/elitea-catalog': typeof ShellEliteaCatalogRoute
  '/help-center': typeof ShellHelpCenterRoute
  '/mcp-auth-callback': typeof ShellMcpAuthCallbackRoute
  '/mode-switch': typeof ShellModeSwitchRoute
  '/onboarding': typeof ShellOnboardingRoute
  '/agents/$tab': typeof ShellAgentsTabRouteWithChildren
  '/agents/create': typeof ShellAgentsCreateRoute
  '/apps/$tab': typeof ShellAppsTabRouteWithChildren
  '/apps/create': typeof ShellAppsCreateRouteWithChildren
  '/artifacts/create-bucket': typeof ShellArtifactsCreateBucketRoute
  '/chat/$conversationId': typeof ShellChatConversationIdRoute
  '/credentials/$tab': typeof ShellCredentialsTabRouteWithChildren
  '/credentials/create-credential': typeof ShellCredentialsCreateCredentialRouteWithChildren
  '/deepwiki/$toolkitId': typeof ShellDeepwikiToolkitIdRoute
  '/mcps/$tab': typeof ShellMcpsTabRouteWithChildren
  '/mcps/create': typeof ShellMcpsCreateRouteWithChildren
  '/pipelines/$tab': typeof ShellPipelinesTabRouteWithChildren
  '/pipelines/create': typeof ShellPipelinesCreateRoute
  '/settings/$tab': typeof ShellSettingsTabRoute
  '/settings/ai-personality': typeof ShellSettingsAiPersonalityRoute
  '/settings/analytics': typeof ShellSettingsAnalyticsRoute
  '/settings/create-configuration': typeof ShellSettingsCreateConfigurationRouteWithChildren
  '/settings/create-personal-token': typeof ShellSettingsCreatePersonalTokenRoute
  '/settings/environment': typeof ShellSettingsEnvironmentRoute
  '/settings/memory': typeof ShellSettingsMemoryRoute
  '/settings/model-configuration': typeof ShellSettingsModelConfigurationRoute
  '/settings/notifications': typeof ShellSettingsNotificationsRoute
  '/settings/personalization': typeof ShellSettingsPersonalizationRoute
  '/settings/preferences': typeof ShellSettingsPreferencesRoute
  '/settings/project-params': typeof ShellSettingsProjectParamsRoute
  '/settings/prompts': typeof ShellSettingsPromptsRoute
  '/settings/secrets': typeof ShellSettingsSecretsRoute
  '/settings/tokens': typeof ShellSettingsTokensRoute
  '/settings/usage': typeof ShellSettingsUsageRoute
  '/settings/users': typeof ShellSettingsUsersRoute
  '/skills/$tab': typeof ShellSkillsTabRouteWithChildren
  '/skills/create': typeof ShellSkillsCreateRoute
  '/toolkits/$tab': typeof ShellToolkitsTabRouteWithChildren
  '/toolkits/create': typeof ShellToolkitsCreateRouteWithChildren
  '/user-public/$tab': typeof ShellUserPublicTabRoute
  '/shared/chat/$token': typeof SharedChatTokenRoute
  '/agents/': typeof ShellAgentsIndexRoute
  '/apps/': typeof ShellAppsIndexRoute
  '/artifacts/': typeof ShellArtifactsIndexRoute
  '/credentials/': typeof ShellCredentialsIndexRoute
  '/deepwiki/': typeof ShellDeepwikiIndexRoute
  '/mcps/': typeof ShellMcpsIndexRoute
  '/pipelines/': typeof ShellPipelinesIndexRoute
  '/settings/': typeof ShellSettingsIndexRoute
  '/skills/': typeof ShellSkillsIndexRoute
  '/toolkits/': typeof ShellToolkitsIndexRoute
  '/agents/$tab/$agentId': typeof ShellAgentsTabAgentIdRouteWithChildren
  '/apps/$tab/$appId': typeof ShellAppsTabAppIdRoute
  '/apps/create/$appType': typeof ShellAppsCreateAppTypeRoute
  '/credentials/$tab/$credential_uid': typeof ShellCredentialsTabCredential_uidRoute
  '/credentials/create-credential/$credentialType': typeof ShellCredentialsCreateCredentialCredentialTypeRoute
  '/mcps/$tab/$mcpId': typeof ShellMcpsTabMcpIdRoute
  '/mcps/create/$mcpType': typeof ShellMcpsCreateMcpTypeRoute
  '/pipelines/$tab/$agentId': typeof ShellPipelinesTabAgentIdRouteWithChildren
  '/settings/create-configuration/$credentialType': typeof ShellSettingsCreateConfigurationCredentialTypeRoute
  '/settings/edit-configuration/$credential_uid': typeof ShellSettingsEditConfigurationCredential_uidRoute
  '/skills/$tab/$skillId': typeof ShellSkillsTabSkillIdRouteWithChildren
  '/toolkits/$tab/$toolkitId': typeof ShellToolkitsTabToolkitIdRoute
  '/toolkits/create/$toolkitType': typeof ShellToolkitsCreateToolkitTypeRoute
  '/user-public/agents/$agentId': typeof ShellUserPublicAgentsAgentIdRouteWithChildren
  '/user-public/apps/$appId': typeof ShellUserPublicAppsAppIdRoute
  '/user-public/mcps/$mcpId': typeof ShellUserPublicMcpsMcpIdRoute
  '/user-public/pipelines/$agentId': typeof ShellUserPublicPipelinesAgentIdRouteWithChildren
  '/user-public/toolkits/$toolkitId': typeof ShellUserPublicToolkitsToolkitIdRoute
  '/agents/$tab/$agentId/$version': typeof ShellAgentsTabAgentIdVersionRoute
  '/pipelines/$tab/$agentId/$version': typeof ShellPipelinesTabAgentIdVersionRoute
  '/skills/$tab/$skillId/$version': typeof ShellSkillsTabSkillIdVersionRoute
  '/user-public/agents/$agentId/$version': typeof ShellUserPublicAgentsAgentIdVersionRoute
  '/user-public/pipelines/$agentId/$version': typeof ShellUserPublicPipelinesAgentIdVersionRoute
}
export interface FileRoutesByTo {
  '/auth-callback': typeof AuthCallbackRoute
  '/$projectId/$': typeof ProjectIdSplatRoute
  '/agents-hub': typeof ShellAgentsHubRoute
  '/chat': typeof ShellChatRouteWithChildren
  '/elitea-catalog': typeof ShellEliteaCatalogRoute
  '/help-center': typeof ShellHelpCenterRoute
  '/mcp-auth-callback': typeof ShellMcpAuthCallbackRoute
  '/mode-switch': typeof ShellModeSwitchRoute
  '/onboarding': typeof ShellOnboardingRoute
  '/': typeof ShellIndexRoute
  '/agents/$tab': typeof ShellAgentsTabRouteWithChildren
  '/agents/create': typeof ShellAgentsCreateRoute
  '/apps/$tab': typeof ShellAppsTabRouteWithChildren
  '/apps/create': typeof ShellAppsCreateRouteWithChildren
  '/artifacts/create-bucket': typeof ShellArtifactsCreateBucketRoute
  '/chat/$conversationId': typeof ShellChatConversationIdRoute
  '/credentials/$tab': typeof ShellCredentialsTabRouteWithChildren
  '/credentials/create-credential': typeof ShellCredentialsCreateCredentialRouteWithChildren
  '/deepwiki/$toolkitId': typeof ShellDeepwikiToolkitIdRoute
  '/mcps/$tab': typeof ShellMcpsTabRouteWithChildren
  '/mcps/create': typeof ShellMcpsCreateRouteWithChildren
  '/pipelines/$tab': typeof ShellPipelinesTabRouteWithChildren
  '/pipelines/create': typeof ShellPipelinesCreateRoute
  '/settings/$tab': typeof ShellSettingsTabRoute
  '/settings/ai-personality': typeof ShellSettingsAiPersonalityRoute
  '/settings/analytics': typeof ShellSettingsAnalyticsRoute
  '/settings/create-configuration': typeof ShellSettingsCreateConfigurationRouteWithChildren
  '/settings/create-personal-token': typeof ShellSettingsCreatePersonalTokenRoute
  '/settings/environment': typeof ShellSettingsEnvironmentRoute
  '/settings/memory': typeof ShellSettingsMemoryRoute
  '/settings/model-configuration': typeof ShellSettingsModelConfigurationRoute
  '/settings/notifications': typeof ShellSettingsNotificationsRoute
  '/settings/personalization': typeof ShellSettingsPersonalizationRoute
  '/settings/preferences': typeof ShellSettingsPreferencesRoute
  '/settings/project-params': typeof ShellSettingsProjectParamsRoute
  '/settings/prompts': typeof ShellSettingsPromptsRoute
  '/settings/secrets': typeof ShellSettingsSecretsRoute
  '/settings/tokens': typeof ShellSettingsTokensRoute
  '/settings/usage': typeof ShellSettingsUsageRoute
  '/settings/users': typeof ShellSettingsUsersRoute
  '/skills/$tab': typeof ShellSkillsTabRouteWithChildren
  '/skills/create': typeof ShellSkillsCreateRoute
  '/toolkits/$tab': typeof ShellToolkitsTabRouteWithChildren
  '/toolkits/create': typeof ShellToolkitsCreateRouteWithChildren
  '/user-public/$tab': typeof ShellUserPublicTabRoute
  '/shared/chat/$token': typeof SharedChatTokenRoute
  '/agents': typeof ShellAgentsIndexRoute
  '/apps': typeof ShellAppsIndexRoute
  '/artifacts': typeof ShellArtifactsIndexRoute
  '/credentials': typeof ShellCredentialsIndexRoute
  '/deepwiki': typeof ShellDeepwikiIndexRoute
  '/mcps': typeof ShellMcpsIndexRoute
  '/pipelines': typeof ShellPipelinesIndexRoute
  '/settings': typeof ShellSettingsIndexRoute
  '/skills': typeof ShellSkillsIndexRoute
  '/toolkits': typeof ShellToolkitsIndexRoute
  '/agents/$tab/$agentId': typeof ShellAgentsTabAgentIdRouteWithChildren
  '/apps/$tab/$appId': typeof ShellAppsTabAppIdRoute
  '/apps/create/$appType': typeof ShellAppsCreateAppTypeRoute
  '/credentials/$tab/$credential_uid': typeof ShellCredentialsTabCredential_uidRoute
  '/credentials/create-credential/$credentialType': typeof ShellCredentialsCreateCredentialCredentialTypeRoute
  '/mcps/$tab/$mcpId': typeof ShellMcpsTabMcpIdRoute
  '/mcps/create/$mcpType': typeof ShellMcpsCreateMcpTypeRoute
  '/pipelines/$tab/$agentId': typeof ShellPipelinesTabAgentIdRouteWithChildren
  '/settings/create-configuration/$credentialType': typeof ShellSettingsCreateConfigurationCredentialTypeRoute
  '/settings/edit-configuration/$credential_uid': typeof ShellSettingsEditConfigurationCredential_uidRoute
  '/skills/$tab/$skillId': typeof ShellSkillsTabSkillIdRouteWithChildren
  '/toolkits/$tab/$toolkitId': typeof ShellToolkitsTabToolkitIdRoute
  '/toolkits/create/$toolkitType': typeof ShellToolkitsCreateToolkitTypeRoute
  '/user-public/agents/$agentId': typeof ShellUserPublicAgentsAgentIdRouteWithChildren
  '/user-public/apps/$appId': typeof ShellUserPublicAppsAppIdRoute
  '/user-public/mcps/$mcpId': typeof ShellUserPublicMcpsMcpIdRoute
  '/user-public/pipelines/$agentId': typeof ShellUserPublicPipelinesAgentIdRouteWithChildren
  '/user-public/toolkits/$toolkitId': typeof ShellUserPublicToolkitsToolkitIdRoute
  '/agents/$tab/$agentId/$version': typeof ShellAgentsTabAgentIdVersionRoute
  '/pipelines/$tab/$agentId/$version': typeof ShellPipelinesTabAgentIdVersionRoute
  '/skills/$tab/$skillId/$version': typeof ShellSkillsTabSkillIdVersionRoute
  '/user-public/agents/$agentId/$version': typeof ShellUserPublicAgentsAgentIdVersionRoute
  '/user-public/pipelines/$agentId/$version': typeof ShellUserPublicPipelinesAgentIdVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/_shell/settings': typeof ShellSettingsRouteRouteWithChildren
  '/$projectId/$': typeof ProjectIdSplatRoute
  '/_shell/agents-hub': typeof ShellAgentsHubRoute
  '/_shell/chat': typeof ShellChatRouteWithChildren
  '/_shell/elitea-catalog': typeof ShellEliteaCatalogRoute
  '/_shell/help-center': typeof ShellHelpCenterRoute
  '/_shell/mcp-auth-callback': typeof ShellMcpAuthCallbackRoute
  '/_shell/mode-switch': typeof ShellModeSwitchRoute
  '/_shell/onboarding': typeof ShellOnboardingRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/agents/$tab': typeof ShellAgentsTabRouteWithChildren
  '/_shell/agents/create': typeof ShellAgentsCreateRoute
  '/_shell/apps/$tab': typeof ShellAppsTabRouteWithChildren
  '/_shell/apps/create': typeof ShellAppsCreateRouteWithChildren
  '/_shell/artifacts/create-bucket': typeof ShellArtifactsCreateBucketRoute
  '/_shell/chat/$conversationId': typeof ShellChatConversationIdRoute
  '/_shell/credentials/$tab': typeof ShellCredentialsTabRouteWithChildren
  '/_shell/credentials/create-credential': typeof ShellCredentialsCreateCredentialRouteWithChildren
  '/_shell/deepwiki/$toolkitId': typeof ShellDeepwikiToolkitIdRoute
  '/_shell/mcps/$tab': typeof ShellMcpsTabRouteWithChildren
  '/_shell/mcps/create': typeof ShellMcpsCreateRouteWithChildren
  '/_shell/pipelines/$tab': typeof ShellPipelinesTabRouteWithChildren
  '/_shell/pipelines/create': typeof ShellPipelinesCreateRoute
  '/_shell/settings/$tab': typeof ShellSettingsTabRoute
  '/_shell/settings/ai-personality': typeof ShellSettingsAiPersonalityRoute
  '/_shell/settings/analytics': typeof ShellSettingsAnalyticsRoute
  '/_shell/settings/create-configuration': typeof ShellSettingsCreateConfigurationRouteWithChildren
  '/_shell/settings/create-personal-token': typeof ShellSettingsCreatePersonalTokenRoute
  '/_shell/settings/environment': typeof ShellSettingsEnvironmentRoute
  '/_shell/settings/memory': typeof ShellSettingsMemoryRoute
  '/_shell/settings/model-configuration': typeof ShellSettingsModelConfigurationRoute
  '/_shell/settings/notifications': typeof ShellSettingsNotificationsRoute
  '/_shell/settings/personalization': typeof ShellSettingsPersonalizationRoute
  '/_shell/settings/preferences': typeof ShellSettingsPreferencesRoute
  '/_shell/settings/project-params': typeof ShellSettingsProjectParamsRoute
  '/_shell/settings/prompts': typeof ShellSettingsPromptsRoute
  '/_shell/settings/secrets': typeof ShellSettingsSecretsRoute
  '/_shell/settings/tokens': typeof ShellSettingsTokensRoute
  '/_shell/settings/usage': typeof ShellSettingsUsageRoute
  '/_shell/settings/users': typeof ShellSettingsUsersRoute
  '/_shell/skills/$tab': typeof ShellSkillsTabRouteWithChildren
  '/_shell/skills/create': typeof ShellSkillsCreateRoute
  '/_shell/toolkits/$tab': typeof ShellToolkitsTabRouteWithChildren
  '/_shell/toolkits/create': typeof ShellToolkitsCreateRouteWithChildren
  '/_shell/user-public/$tab': typeof ShellUserPublicTabRoute
  '/shared/chat/$token': typeof SharedChatTokenRoute
  '/_shell/agents/': typeof ShellAgentsIndexRoute
  '/_shell/apps/': typeof ShellAppsIndexRoute
  '/_shell/artifacts/': typeof ShellArtifactsIndexRoute
  '/_shell/credentials/': typeof ShellCredentialsIndexRoute
  '/_shell/deepwiki/': typeof ShellDeepwikiIndexRoute
  '/_shell/mcps/': typeof ShellMcpsIndexRoute
  '/_shell/pipelines/': typeof ShellPipelinesIndexRoute
  '/_shell/settings/': typeof ShellSettingsIndexRoute
  '/_shell/skills/': typeof ShellSkillsIndexRoute
  '/_shell/toolkits/': typeof ShellToolkitsIndexRoute
  '/_shell/agents/$tab/$agentId': typeof ShellAgentsTabAgentIdRouteWithChildren
  '/_shell/apps/$tab/$appId': typeof ShellAppsTabAppIdRoute
  '/_shell/apps/create/$appType': typeof ShellAppsCreateAppTypeRoute
  '/_shell/credentials/$tab/$credential_uid': typeof ShellCredentialsTabCredential_uidRoute
  '/_shell/credentials/create-credential/$credentialType': typeof ShellCredentialsCreateCredentialCredentialTypeRoute
  '/_shell/mcps/$tab/$mcpId': typeof ShellMcpsTabMcpIdRoute
  '/_shell/mcps/create/$mcpType': typeof ShellMcpsCreateMcpTypeRoute
  '/_shell/pipelines/$tab/$agentId': typeof ShellPipelinesTabAgentIdRouteWithChildren
  '/_shell/settings/create-configuration/$credentialType': typeof ShellSettingsCreateConfigurationCredentialTypeRoute
  '/_shell/settings/edit-configuration/$credential_uid': typeof ShellSettingsEditConfigurationCredential_uidRoute
  '/_shell/skills/$tab/$skillId': typeof ShellSkillsTabSkillIdRouteWithChildren
  '/_shell/toolkits/$tab/$toolkitId': typeof ShellToolkitsTabToolkitIdRoute
  '/_shell/toolkits/create/$toolkitType': typeof ShellToolkitsCreateToolkitTypeRoute
  '/_shell/user-public/agents/$agentId': typeof ShellUserPublicAgentsAgentIdRouteWithChildren
  '/_shell/user-public/apps/$appId': typeof ShellUserPublicAppsAppIdRoute
  '/_shell/user-public/mcps/$mcpId': typeof ShellUserPublicMcpsMcpIdRoute
  '/_shell/user-public/pipelines/$agentId': typeof ShellUserPublicPipelinesAgentIdRouteWithChildren
  '/_shell/user-public/toolkits/$toolkitId': typeof ShellUserPublicToolkitsToolkitIdRoute
  '/_shell/agents/$tab/$agentId/$version': typeof ShellAgentsTabAgentIdVersionRoute
  '/_shell/pipelines/$tab/$agentId/$version': typeof ShellPipelinesTabAgentIdVersionRoute
  '/_shell/skills/$tab/$skillId/$version': typeof ShellSkillsTabSkillIdVersionRoute
  '/_shell/user-public/agents/$agentId/$version': typeof ShellUserPublicAgentsAgentIdVersionRoute
  '/_shell/user-public/pipelines/$agentId/$version': typeof ShellUserPublicPipelinesAgentIdVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-callback'
    | '/settings'
    | '/$projectId/$'
    | '/agents-hub'
    | '/chat'
    | '/elitea-catalog'
    | '/help-center'
    | '/mcp-auth-callback'
    | '/mode-switch'
    | '/onboarding'
    | '/agents/$tab'
    | '/agents/create'
    | '/apps/$tab'
    | '/apps/create'
    | '/artifacts/create-bucket'
    | '/chat/$conversationId'
    | '/credentials/$tab'
    | '/credentials/create-credential'
    | '/deepwiki/$toolkitId'
    | '/mcps/$tab'
    | '/mcps/create'
    | '/pipelines/$tab'
    | '/pipelines/create'
    | '/settings/$tab'
    | '/settings/ai-personality'
    | '/settings/analytics'
    | '/settings/create-configuration'
    | '/settings/create-personal-token'
    | '/settings/environment'
    | '/settings/memory'
    | '/settings/model-configuration'
    | '/settings/notifications'
    | '/settings/personalization'
    | '/settings/preferences'
    | '/settings/project-params'
    | '/settings/prompts'
    | '/settings/secrets'
    | '/settings/tokens'
    | '/settings/usage'
    | '/settings/users'
    | '/skills/$tab'
    | '/skills/create'
    | '/toolkits/$tab'
    | '/toolkits/create'
    | '/user-public/$tab'
    | '/shared/chat/$token'
    | '/agents/'
    | '/apps/'
    | '/artifacts/'
    | '/credentials/'
    | '/deepwiki/'
    | '/mcps/'
    | '/pipelines/'
    | '/settings/'
    | '/skills/'
    | '/toolkits/'
    | '/agents/$tab/$agentId'
    | '/apps/$tab/$appId'
    | '/apps/create/$appType'
    | '/credentials/$tab/$credential_uid'
    | '/credentials/create-credential/$credentialType'
    | '/mcps/$tab/$mcpId'
    | '/mcps/create/$mcpType'
    | '/pipelines/$tab/$agentId'
    | '/settings/create-configuration/$credentialType'
    | '/settings/edit-configuration/$credential_uid'
    | '/skills/$tab/$skillId'
    | '/toolkits/$tab/$toolkitId'
    | '/toolkits/create/$toolkitType'
    | '/user-public/agents/$agentId'
    | '/user-public/apps/$appId'
    | '/user-public/mcps/$mcpId'
    | '/user-public/pipelines/$agentId'
    | '/user-public/toolkits/$toolkitId'
    | '/agents/$tab/$agentId/$version'
    | '/pipelines/$tab/$agentId/$version'
    | '/skills/$tab/$skillId/$version'
    | '/user-public/agents/$agentId/$version'
    | '/user-public/pipelines/$agentId/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-callback'
    | '/$projectId/$'
    | '/agents-hub'
    | '/chat'
    | '/elitea-catalog'
    | '/help-center'
    | '/mcp-auth-callback'
    | '/mode-switch'
    | '/onboarding'
    | '/'
    | '/agents/$tab'
    | '/agents/create'
    | '/apps/$tab'
    | '/apps/create'
    | '/artifacts/create-bucket'
    | '/chat/$conversationId'
    | '/credentials/$tab'
    | '/credentials/create-credential'
    | '/deepwiki/$toolkitId'
    | '/mcps/$tab'
    | '/mcps/create'
    | '/pipelines/$tab'
    | '/pipelines/create'
    | '/settings/$tab'
    | '/settings/ai-personality'
    | '/settings/analytics'
    | '/settings/create-configuration'
    | '/settings/create-personal-token'
    | '/settings/environment'
    | '/settings/memory'
    | '/settings/model-configuration'
    | '/settings/notifications'
    | '/settings/personalization'
    | '/settings/preferences'
    | '/settings/project-params'
    | '/settings/prompts'
    | '/settings/secrets'
    | '/settings/tokens'
    | '/settings/usage'
    | '/settings/users'
    | '/skills/$tab'
    | '/skills/create'
    | '/toolkits/$tab'
    | '/toolkits/create'
    | '/user-public/$tab'
    | '/shared/chat/$token'
    | '/agents'
    | '/apps'
    | '/artifacts'
    | '/credentials'
    | '/deepwiki'
    | '/mcps'
    | '/pipelines'
    | '/settings'
    | '/skills'
    | '/toolkits'
    | '/agents/$tab/$agentId'
    | '/apps/$tab/$appId'
    | '/apps/create/$appType'
    | '/credentials/$tab/$credential_uid'
    | '/credentials/create-credential/$credentialType'
    | '/mcps/$tab/$mcpId'
    | '/mcps/create/$mcpType'
    | '/pipelines/$tab/$agentId'
    | '/settings/create-configuration/$credentialType'
    | '/settings/edit-configuration/$credential_uid'
    | '/skills/$tab/$skillId'
    | '/toolkits/$tab/$toolkitId'
    | '/toolkits/create/$toolkitType'
    | '/user-public/agents/$agentId'
    | '/user-public/apps/$appId'
    | '/user-public/mcps/$mcpId'
    | '/user-public/pipelines/$agentId'
    | '/user-public/toolkits/$toolkitId'
    | '/agents/$tab/$agentId/$version'
    | '/pipelines/$tab/$agentId/$version'
    | '/skills/$tab/$skillId/$version'
    | '/user-public/agents/$agentId/$version'
    | '/user-public/pipelines/$agentId/$version'
  id:
    | '__root__'
    | '/_shell'
    | '/auth-callback'
    | '/_shell/settings'
    | '/$projectId/$'
    | '/_shell/agents-hub'
    | '/_shell/chat'
    | '/_shell/elitea-catalog'
    | '/_shell/help-center'
    | '/_shell/mcp-auth-callback'
    | '/_shell/mode-switch'
    | '/_shell/onboarding'
    | '/_shell/'
    | '/_shell/agents/$tab'
    | '/_shell/agents/create'
    | '/_shell/apps/$tab'
    | '/_shell/apps/create'
    | '/_shell/artifacts/create-bucket'
    | '/_shell/chat/$conversationId'
    | '/_shell/credentials/$tab'
    | '/_shell/credentials/create-credential'
    | '/_shell/deepwiki/$toolkitId'
    | '/_shell/mcps/$tab'
    | '/_shell/mcps/create'
    | '/_shell/pipelines/$tab'
    | '/_shell/pipelines/create'
    | '/_shell/settings/$tab'
    | '/_shell/settings/ai-personality'
    | '/_shell/settings/analytics'
    | '/_shell/settings/create-configuration'
    | '/_shell/settings/create-personal-token'
    | '/_shell/settings/environment'
    | '/_shell/settings/memory'
    | '/_shell/settings/model-configuration'
    | '/_shell/settings/notifications'
    | '/_shell/settings/personalization'
    | '/_shell/settings/preferences'
    | '/_shell/settings/project-params'
    | '/_shell/settings/prompts'
    | '/_shell/settings/secrets'
    | '/_shell/settings/tokens'
    | '/_shell/settings/usage'
    | '/_shell/settings/users'
    | '/_shell/skills/$tab'
    | '/_shell/skills/create'
    | '/_shell/toolkits/$tab'
    | '/_shell/toolkits/create'
    | '/_shell/user-public/$tab'
    | '/shared/chat/$token'
    | '/_shell/agents/'
    | '/_shell/apps/'
    | '/_shell/artifacts/'
    | '/_shell/credentials/'
    | '/_shell/deepwiki/'
    | '/_shell/mcps/'
    | '/_shell/pipelines/'
    | '/_shell/settings/'
    | '/_shell/skills/'
    | '/_shell/toolkits/'
    | '/_shell/agents/$tab/$agentId'
    | '/_shell/apps/$tab/$appId'
    | '/_shell/apps/create/$appType'
    | '/_shell/credentials/$tab/$credential_uid'
    | '/_shell/credentials/create-credential/$credentialType'
    | '/_shell/mcps/$tab/$mcpId'
    | '/_shell/mcps/create/$mcpType'
    | '/_shell/pipelines/$tab/$agentId'
    | '/_shell/settings/create-configuration/$credentialType'
    | '/_shell/settings/edit-configuration/$credential_uid'
    | '/_shell/skills/$tab/$skillId'
    | '/_shell/toolkits/$tab/$toolkitId'
    | '/_shell/toolkits/create/$toolkitType'
    | '/_shell/user-public/agents/$agentId'
    | '/_shell/user-public/apps/$appId'
    | '/_shell/user-public/mcps/$mcpId'
    | '/_shell/user-public/pipelines/$agentId'
    | '/_shell/user-public/toolkits/$toolkitId'
    | '/_shell/agents/$tab/$agentId/$version'
    | '/_shell/pipelines/$tab/$agentId/$version'
    | '/_shell/skills/$tab/$skillId/$version'
    | '/_shell/user-public/agents/$agentId/$version'
    | '/_shell/user-public/pipelines/$agentId/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProjectIdSplatRoute: typeof ProjectIdSplatRoute
  SharedChatTokenRoute: typeof SharedChatTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/$': {
      id: '/$projectId/$'
      path: '/$projectId/$'
      fullPath: '/$projectId/$'
      preLoaderRoute: typeof ProjectIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/agents-hub': {
      id: '/_shell/agents-hub'
      path: '/agents-hub'
      fullPath: '/agents-hub'
      preLoaderRoute: typeof ShellAgentsHubRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/chat': {
      id: '/_shell/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ShellChatRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/elitea-catalog': {
      id: '/_shell/elitea-catalog'
      path: '/elitea-catalog'
      fullPath: '/elitea-catalog'
      preLoaderRoute: typeof ShellEliteaCatalogRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/help-center': {
      id: '/_shell/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof ShellHelpCenterRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/mcp-auth-callback': {
      id: '/_shell/mcp-auth-callback'
      path: '/mcp-auth-callback'
      fullPath: '/mcp-auth-callback'
      preLoaderRoute: typeof ShellMcpAuthCallbackRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/mode-switch': {
      id: '/_shell/mode-switch'
      path: '/mode-switch'
      fullPath: '/mode-switch'
      preLoaderRoute: typeof ShellModeSwitchRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/onboarding': {
      id: '/_shell/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ShellOnboardingRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/agents/': {
      id: '/_shell/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof ShellAgentsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/agents/$tab': {
      id: '/_shell/agents/$tab'
      path: '/agents/$tab'
      fullPath: '/agents/$tab'
      preLoaderRoute: typeof ShellAgentsTabRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/agents/create': {
      id: '/_shell/agents/create'
      path: '/agents/create'
      fullPath: '/agents/create'
      preLoaderRoute: typeof ShellAgentsCreateRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/apps/': {
      id: '/_shell/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof ShellAppsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/apps/$tab': {
      id: '/_shell/apps/$tab'
      path: '/apps/$tab'
      fullPath: '/apps/$tab'
      preLoaderRoute: typeof ShellAppsTabRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/apps/create': {
      id: '/_shell/apps/create'
      path: '/apps/create'
      fullPath: '/apps/create'
      preLoaderRoute: typeof ShellAppsCreateRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/artifacts/': {
      id: '/_shell/artifacts/'
      path: '/artifacts'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ShellArtifactsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/artifacts/create-bucket': {
      id: '/_shell/artifacts/create-bucket'
      path: '/artifacts/create-bucket'
      fullPath: '/artifacts/create-bucket'
      preLoaderRoute: typeof ShellArtifactsCreateBucketRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/chat/$conversationId': {
      id: '/_shell/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ShellChatConversationIdRouteImport
      parentRoute: typeof ShellChatRoute
    }
    '/_shell/credentials/': {
      id: '/_shell/credentials/'
      path: '/credentials'
      fullPath: '/credentials/'
      preLoaderRoute: typeof ShellCredentialsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/credentials/$tab': {
      id: '/_shell/credentials/$tab'
      path: '/credentials/$tab'
      fullPath: '/credentials/$tab'
      preLoaderRoute: typeof ShellCredentialsTabRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/credentials/create-credential': {
      id: '/_shell/credentials/create-credential'
      path: '/credentials/create-credential'
      fullPath: '/credentials/create-credential'
      preLoaderRoute: typeof ShellCredentialsCreateCredentialRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/deepwiki/': {
      id: '/_shell/deepwiki/'
      path: '/deepwiki'
      fullPath: '/deepwiki/'
      preLoaderRoute: typeof ShellDeepwikiIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/deepwiki/$toolkitId': {
      id: '/_shell/deepwiki/$toolkitId'
      path: '/deepwiki/$toolkitId'
      fullPath: '/deepwiki/$toolkitId'
      preLoaderRoute: typeof ShellDeepwikiToolkitIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/mcps/': {
      id: '/_shell/mcps/'
      path: '/mcps'
      fullPath: '/mcps/'
      preLoaderRoute: typeof ShellMcpsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/mcps/$tab': {
      id: '/_shell/mcps/$tab'
      path: '/mcps/$tab'
      fullPath: '/mcps/$tab'
      preLoaderRoute: typeof ShellMcpsTabRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/mcps/create': {
      id: '/_shell/mcps/create'
      path: '/mcps/create'
      fullPath: '/mcps/create'
      preLoaderRoute: typeof ShellMcpsCreateRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pipelines/': {
      id: '/_shell/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof ShellPipelinesIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pipelines/$tab': {
      id: '/_shell/pipelines/$tab'
      path: '/pipelines/$tab'
      fullPath: '/pipelines/$tab'
      preLoaderRoute: typeof ShellPipelinesTabRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pipelines/create': {
      id: '/_shell/pipelines/create'
      path: '/pipelines/create'
      fullPath: '/pipelines/create'
      preLoaderRoute: typeof ShellPipelinesCreateRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/settings/': {
      id: '/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ShellSettingsIndexRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/$tab': {
      id: '/_shell/settings/$tab'
      path: '/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof ShellSettingsTabRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/ai-personality': {
      id: '/_shell/settings/ai-personality'
      path: '/ai-personality'
      fullPath: '/settings/ai-personality'
      preLoaderRoute: typeof ShellSettingsAiPersonalityRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/analytics': {
      id: '/_shell/settings/analytics'
      path: '/analytics'
      fullPath: '/settings/analytics'
      preLoaderRoute: typeof ShellSettingsAnalyticsRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/create-configuration': {
      id: '/_shell/settings/create-configuration'
      path: '/create-configuration'
      fullPath: '/settings/create-configuration'
      preLoaderRoute: typeof ShellSettingsCreateConfigurationRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/create-personal-token': {
      id: '/_shell/settings/create-personal-token'
      path: '/create-personal-token'
      fullPath: '/settings/create-personal-token'
      preLoaderRoute: typeof ShellSettingsCreatePersonalTokenRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/environment': {
      id: '/_shell/settings/environment'
      path: '/environment'
      fullPath: '/settings/environment'
      preLoaderRoute: typeof ShellSettingsEnvironmentRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/memory': {
      id: '/_shell/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof ShellSettingsMemoryRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/model-configuration': {
      id: '/_shell/settings/model-configuration'
      path: '/model-configuration'
      fullPath: '/settings/model-configuration'
      preLoaderRoute: typeof ShellSettingsModelConfigurationRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/notifications': {
      id: '/_shell/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ShellSettingsNotificationsRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/personalization': {
      id: '/_shell/settings/personalization'
      path: '/personalization'
      fullPath: '/settings/personalization'
      preLoaderRoute: typeof ShellSettingsPersonalizationRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/preferences': {
      id: '/_shell/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof ShellSettingsPreferencesRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/project-params': {
      id: '/_shell/settings/project-params'
      path: '/project-params'
      fullPath: '/settings/project-params'
      preLoaderRoute: typeof ShellSettingsProjectParamsRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/prompts': {
      id: '/_shell/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof ShellSettingsPromptsRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/secrets': {
      id: '/_shell/settings/secrets'
      path: '/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof ShellSettingsSecretsRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/tokens': {
      id: '/_shell/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof ShellSettingsTokensRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/usage': {
      id: '/_shell/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof ShellSettingsUsageRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/settings/users': {
      id: '/_shell/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof ShellSettingsUsersRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/skills/': {
      id: '/_shell/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof ShellSkillsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/skills/$tab': {
      id: '/_shell/skills/$tab'
      path: '/skills/$tab'
      fullPath: '/skills/$tab'
      preLoaderRoute: typeof ShellSkillsTabRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/skills/create': {
      id: '/_shell/skills/create'
      path: '/skills/create'
      fullPath: '/skills/create'
      preLoaderRoute: typeof ShellSkillsCreateRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/toolkits/': {
      id: '/_shell/toolkits/'
      path: '/toolkits'
      fullPath: '/toolkits/'
      preLoaderRoute: typeof ShellToolkitsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/toolkits/$tab': {
      id: '/_shell/toolkits/$tab'
      path: '/toolkits/$tab'
      fullPath: '/toolkits/$tab'
      preLoaderRoute: typeof ShellToolkitsTabRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/toolkits/create': {
      id: '/_shell/toolkits/create'
      path: '/toolkits/create'
      fullPath: '/toolkits/create'
      preLoaderRoute: typeof ShellToolkitsCreateRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/user-public/$tab': {
      id: '/_shell/user-public/$tab'
      path: '/user-public/$tab'
      fullPath: '/user-public/$tab'
      preLoaderRoute: typeof ShellUserPublicTabRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/shared/chat/$token': {
      id: '/shared/chat/$token'
      path: '/shared/chat/$token'
      fullPath: '/shared/chat/$token'
      preLoaderRoute: typeof SharedChatTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/agents/$tab/$agentId': {
      id: '/_shell/agents/$tab/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$tab/$agentId'
      preLoaderRoute: typeof ShellAgentsTabAgentIdRouteImport
      parentRoute: typeof ShellAgentsTabRoute
    }
    '/_shell/apps/$tab/$appId': {
      id: '/_shell/apps/$tab/$appId'
      path: '/$appId'
      fullPath: '/apps/$tab/$appId'
      preLoaderRoute: typeof ShellAppsTabAppIdRouteImport
      parentRoute: typeof ShellAppsTabRoute
    }
    '/_shell/apps/create/$appType': {
      id: '/_shell/apps/create/$appType'
      path: '/$appType'
      fullPath: '/apps/create/$appType'
      preLoaderRoute: typeof ShellAppsCreateAppTypeRouteImport
      parentRoute: typeof ShellAppsCreateRoute
    }
    '/_shell/credentials/$tab/$credential_uid': {
      id: '/_shell/credentials/$tab/$credential_uid'
      path: '/$credential_uid'
      fullPath: '/credentials/$tab/$credential_uid'
      preLoaderRoute: typeof ShellCredentialsTabCredential_uidRouteImport
      parentRoute: typeof ShellCredentialsTabRoute
    }
    '/_shell/credentials/create-credential/$credentialType': {
      id: '/_shell/credentials/create-credential/$credentialType'
      path: '/$credentialType'
      fullPath: '/credentials/create-credential/$credentialType'
      preLoaderRoute: typeof ShellCredentialsCreateCredentialCredentialTypeRouteImport
      parentRoute: typeof ShellCredentialsCreateCredentialRoute
    }
    '/_shell/mcps/$tab/$mcpId': {
      id: '/_shell/mcps/$tab/$mcpId'
      path: '/$mcpId'
      fullPath: '/mcps/$tab/$mcpId'
      preLoaderRoute: typeof ShellMcpsTabMcpIdRouteImport
      parentRoute: typeof ShellMcpsTabRoute
    }
    '/_shell/mcps/create/$mcpType': {
      id: '/_shell/mcps/create/$mcpType'
      path: '/$mcpType'
      fullPath: '/mcps/create/$mcpType'
      preLoaderRoute: typeof ShellMcpsCreateMcpTypeRouteImport
      parentRoute: typeof ShellMcpsCreateRoute
    }
    '/_shell/pipelines/$tab/$agentId': {
      id: '/_shell/pipelines/$tab/$agentId'
      path: '/$agentId'
      fullPath: '/pipelines/$tab/$agentId'
      preLoaderRoute: typeof ShellPipelinesTabAgentIdRouteImport
      parentRoute: typeof ShellPipelinesTabRoute
    }
    '/_shell/settings/create-configuration/$credentialType': {
      id: '/_shell/settings/create-configuration/$credentialType'
      path: '/$credentialType'
      fullPath: '/settings/create-configuration/$credentialType'
      preLoaderRoute: typeof ShellSettingsCreateConfigurationCredentialTypeRouteImport
      parentRoute: typeof ShellSettingsCreateConfigurationRoute
    }
    '/_shell/settings/edit-configuration/$credential_uid': {
      id: '/_shell/settings/edit-configuration/$credential_uid'
      path: '/edit-configuration/$credential_uid'
      fullPath: '/settings/edit-configuration/$credential_uid'
      preLoaderRoute: typeof ShellSettingsEditConfigurationCredential_uidRouteImport
      parentRoute: typeof ShellSettingsRouteRoute
    }
    '/_shell/skills/$tab/$skillId': {
      id: '/_shell/skills/$tab/$skillId'
      path: '/$skillId'
      fullPath: '/skills/$tab/$skillId'
      preLoaderRoute: typeof ShellSkillsTabSkillIdRouteImport
      parentRoute: typeof ShellSkillsTabRoute
    }
    '/_shell/toolkits/$tab/$toolkitId': {
      id: '/_shell/toolkits/$tab/$toolkitId'
      path: '/$toolkitId'
      fullPath: '/toolkits/$tab/$toolkitId'
      preLoaderRoute: typeof ShellToolkitsTabToolkitIdRouteImport
      parentRoute: typeof ShellToolkitsTabRoute
    }
    '/_shell/toolkits/create/$toolkitType': {
      id: '/_shell/toolkits/create/$toolkitType'
      path: '/$toolkitType'
      fullPath: '/toolkits/create/$toolkitType'
      preLoaderRoute: typeof ShellToolkitsCreateToolkitTypeRouteImport
      parentRoute: typeof ShellToolkitsCreateRoute
    }
    '/_shell/user-public/agents/$agentId': {
      id: '/_shell/user-public/agents/$agentId'
      path: '/user-public/agents/$agentId'
      fullPath: '/user-public/agents/$agentId'
      preLoaderRoute: typeof ShellUserPublicAgentsAgentIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/user-public/apps/$appId': {
      id: '/_shell/user-public/apps/$appId'
      path: '/user-public/apps/$appId'
      fullPath: '/user-public/apps/$appId'
      preLoaderRoute: typeof ShellUserPublicAppsAppIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/user-public/mcps/$mcpId': {
      id: '/_shell/user-public/mcps/$mcpId'
      path: '/user-public/mcps/$mcpId'
      fullPath: '/user-public/mcps/$mcpId'
      preLoaderRoute: typeof ShellUserPublicMcpsMcpIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/user-public/pipelines/$agentId': {
      id: '/_shell/user-public/pipelines/$agentId'
      path: '/user-public/pipelines/$agentId'
      fullPath: '/user-public/pipelines/$agentId'
      preLoaderRoute: typeof ShellUserPublicPipelinesAgentIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/user-public/toolkits/$toolkitId': {
      id: '/_shell/user-public/toolkits/$toolkitId'
      path: '/user-public/toolkits/$toolkitId'
      fullPath: '/user-public/toolkits/$toolkitId'
      preLoaderRoute: typeof ShellUserPublicToolkitsToolkitIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/agents/$tab/$agentId/$version': {
      id: '/_shell/agents/$tab/$agentId/$version'
      path: '/$version'
      fullPath: '/agents/$tab/$agentId/$version'
      preLoaderRoute: typeof ShellAgentsTabAgentIdVersionRouteImport
      parentRoute: typeof ShellAgentsTabAgentIdRoute
    }
    '/_shell/pipelines/$tab/$agentId/$version': {
      id: '/_shell/pipelines/$tab/$agentId/$version'
      path: '/$version'
      fullPath: '/pipelines/$tab/$agentId/$version'
      preLoaderRoute: typeof ShellPipelinesTabAgentIdVersionRouteImport
      parentRoute: typeof ShellPipelinesTabAgentIdRoute
    }
    '/_shell/skills/$tab/$skillId/$version': {
      id: '/_shell/skills/$tab/$skillId/$version'
      path: '/$version'
      fullPath: '/skills/$tab/$skillId/$version'
      preLoaderRoute: typeof ShellSkillsTabSkillIdVersionRouteImport
      parentRoute: typeof ShellSkillsTabSkillIdRoute
    }
    '/_shell/user-public/agents/$agentId/$version': {
      id: '/_shell/user-public/agents/$agentId/$version'
      path: '/$version'
      fullPath: '/user-public/agents/$agentId/$version'
      preLoaderRoute: typeof ShellUserPublicAgentsAgentIdVersionRouteImport
      parentRoute: typeof ShellUserPublicAgentsAgentIdRoute
    }
    '/_shell/user-public/pipelines/$agentId/$version': {
      id: '/_shell/user-public/pipelines/$agentId/$version'
      path: '/$version'
      fullPath: '/user-public/pipelines/$agentId/$version'
      preLoaderRoute: typeof ShellUserPublicPipelinesAgentIdVersionRouteImport
      parentRoute: typeof ShellUserPublicPipelinesAgentIdRoute
    }
  }
}

interface ShellSettingsCreateConfigurationRouteChildren {
  ShellSettingsCreateConfigurationCredentialTypeRoute: typeof ShellSettingsCreateConfigurationCredentialTypeRoute
}

const ShellSettingsCreateConfigurationRouteChildren: ShellSettingsCreateConfigurationRouteChildren =
  {
    ShellSettingsCreateConfigurationCredentialTypeRoute:
      ShellSettingsCreateConfigurationCredentialTypeRoute,
  }

const ShellSettingsCreateConfigurationRouteWithChildren =
  ShellSettingsCreateConfigurationRoute._addFileChildren(
    ShellSettingsCreateConfigurationRouteChildren,
  )

interface ShellSettingsRouteRouteChildren {
  ShellSettingsTabRoute: typeof ShellSettingsTabRoute
  ShellSettingsAiPersonalityRoute: typeof ShellSettingsAiPersonalityRoute
  ShellSettingsAnalyticsRoute: typeof ShellSettingsAnalyticsRoute
  ShellSettingsCreateConfigurationRoute: typeof ShellSettingsCreateConfigurationRouteWithChildren
  ShellSettingsCreatePersonalTokenRoute: typeof ShellSettingsCreatePersonalTokenRoute
  ShellSettingsEnvironmentRoute: typeof ShellSettingsEnvironmentRoute
  ShellSettingsMemoryRoute: typeof ShellSettingsMemoryRoute
  ShellSettingsModelConfigurationRoute: typeof ShellSettingsModelConfigurationRoute
  ShellSettingsNotificationsRoute: typeof ShellSettingsNotificationsRoute
  ShellSettingsPersonalizationRoute: typeof ShellSettingsPersonalizationRoute
  ShellSettingsPreferencesRoute: typeof ShellSettingsPreferencesRoute
  ShellSettingsProjectParamsRoute: typeof ShellSettingsProjectParamsRoute
  ShellSettingsPromptsRoute: typeof ShellSettingsPromptsRoute
  ShellSettingsSecretsRoute: typeof ShellSettingsSecretsRoute
  ShellSettingsTokensRoute: typeof ShellSettingsTokensRoute
  ShellSettingsUsageRoute: typeof ShellSettingsUsageRoute
  ShellSettingsUsersRoute: typeof ShellSettingsUsersRoute
  ShellSettingsIndexRoute: typeof ShellSettingsIndexRoute
  ShellSettingsEditConfigurationCredential_uidRoute: typeof ShellSettingsEditConfigurationCredential_uidRoute
}

const ShellSettingsRouteRouteChildren: ShellSettingsRouteRouteChildren = {
  ShellSettingsTabRoute: ShellSettingsTabRoute,
  ShellSettingsAiPersonalityRoute: ShellSettingsAiPersonalityRoute,
  ShellSettingsAnalyticsRoute: ShellSettingsAnalyticsRoute,
  ShellSettingsCreateConfigurationRoute:
    ShellSettingsCreateConfigurationRouteWithChildren,
  ShellSettingsCreatePersonalTokenRoute: ShellSettingsCreatePersonalTokenRoute,
  ShellSettingsEnvironmentRoute: ShellSettingsEnvironmentRoute,
  ShellSettingsMemoryRoute: ShellSettingsMemoryRoute,
  ShellSettingsModelConfigurationRoute: ShellSettingsModelConfigurationRoute,
  ShellSettingsNotificationsRoute: ShellSettingsNotificationsRoute,
  ShellSettingsPersonalizationRoute: ShellSettingsPersonalizationRoute,
  ShellSettingsPreferencesRoute: ShellSettingsPreferencesRoute,
  ShellSettingsProjectParamsRoute: ShellSettingsProjectParamsRoute,
  ShellSettingsPromptsRoute: ShellSettingsPromptsRoute,
  ShellSettingsSecretsRoute: ShellSettingsSecretsRoute,
  ShellSettingsTokensRoute: ShellSettingsTokensRoute,
  ShellSettingsUsageRoute: ShellSettingsUsageRoute,
  ShellSettingsUsersRoute: ShellSettingsUsersRoute,
  ShellSettingsIndexRoute: ShellSettingsIndexRoute,
  ShellSettingsEditConfigurationCredential_uidRoute:
    ShellSettingsEditConfigurationCredential_uidRoute,
}

const ShellSettingsRouteRouteWithChildren =
  ShellSettingsRouteRoute._addFileChildren(ShellSettingsRouteRouteChildren)

interface ShellChatRouteChildren {
  ShellChatConversationIdRoute: typeof ShellChatConversationIdRoute
}

const ShellChatRouteChildren: ShellChatRouteChildren = {
  ShellChatConversationIdRoute: ShellChatConversationIdRoute,
}

const ShellChatRouteWithChildren = ShellChatRoute._addFileChildren(
  ShellChatRouteChildren,
)

interface ShellAgentsTabAgentIdRouteChildren {
  ShellAgentsTabAgentIdVersionRoute: typeof ShellAgentsTabAgentIdVersionRoute
}

const ShellAgentsTabAgentIdRouteChildren: ShellAgentsTabAgentIdRouteChildren = {
  ShellAgentsTabAgentIdVersionRoute: ShellAgentsTabAgentIdVersionRoute,
}

const ShellAgentsTabAgentIdRouteWithChildren =
  ShellAgentsTabAgentIdRoute._addFileChildren(
    ShellAgentsTabAgentIdRouteChildren,
  )

interface ShellAgentsTabRouteChildren {
  ShellAgentsTabAgentIdRoute: typeof ShellAgentsTabAgentIdRouteWithChildren
}

const ShellAgentsTabRouteChildren: ShellAgentsTabRouteChildren = {
  ShellAgentsTabAgentIdRoute: ShellAgentsTabAgentIdRouteWithChildren,
}

const ShellAgentsTabRouteWithChildren = ShellAgentsTabRoute._addFileChildren(
  ShellAgentsTabRouteChildren,
)

interface ShellAppsTabRouteChildren {
  ShellAppsTabAppIdRoute: typeof ShellAppsTabAppIdRoute
}

const ShellAppsTabRouteChildren: ShellAppsTabRouteChildren = {
  ShellAppsTabAppIdRoute: ShellAppsTabAppIdRoute,
}

const ShellAppsTabRouteWithChildren = ShellAppsTabRoute._addFileChildren(
  ShellAppsTabRouteChildren,
)

interface ShellAppsCreateRouteChildren {
  ShellAppsCreateAppTypeRoute: typeof ShellAppsCreateAppTypeRoute
}

const ShellAppsCreateRouteChildren: ShellAppsCreateRouteChildren = {
  ShellAppsCreateAppTypeRoute: ShellAppsCreateAppTypeRoute,
}

const ShellAppsCreateRouteWithChildren = ShellAppsCreateRoute._addFileChildren(
  ShellAppsCreateRouteChildren,
)

interface ShellCredentialsTabRouteChildren {
  ShellCredentialsTabCredential_uidRoute: typeof ShellCredentialsTabCredential_uidRoute
}

const ShellCredentialsTabRouteChildren: ShellCredentialsTabRouteChildren = {
  ShellCredentialsTabCredential_uidRoute:
    ShellCredentialsTabCredential_uidRoute,
}

const ShellCredentialsTabRouteWithChildren =
  ShellCredentialsTabRoute._addFileChildren(ShellCredentialsTabRouteChildren)

interface ShellCredentialsCreateCredentialRouteChildren {
  ShellCredentialsCreateCredentialCredentialTypeRoute: typeof ShellCredentialsCreateCredentialCredentialTypeRoute
}

const ShellCredentialsCreateCredentialRouteChildren: ShellCredentialsCreateCredentialRouteChildren =
  {
    ShellCredentialsCreateCredentialCredentialTypeRoute:
      ShellCredentialsCreateCredentialCredentialTypeRoute,
  }

const ShellCredentialsCreateCredentialRouteWithChildren =
  ShellCredentialsCreateCredentialRoute._addFileChildren(
    ShellCredentialsCreateCredentialRouteChildren,
  )

interface ShellMcpsTabRouteChildren {
  ShellMcpsTabMcpIdRoute: typeof ShellMcpsTabMcpIdRoute
}

const ShellMcpsTabRouteChildren: ShellMcpsTabRouteChildren = {
  ShellMcpsTabMcpIdRoute: ShellMcpsTabMcpIdRoute,
}

const ShellMcpsTabRouteWithChildren = ShellMcpsTabRoute._addFileChildren(
  ShellMcpsTabRouteChildren,
)

interface ShellMcpsCreateRouteChildren {
  ShellMcpsCreateMcpTypeRoute: typeof ShellMcpsCreateMcpTypeRoute
}

const ShellMcpsCreateRouteChildren: ShellMcpsCreateRouteChildren = {
  ShellMcpsCreateMcpTypeRoute: ShellMcpsCreateMcpTypeRoute,
}

const ShellMcpsCreateRouteWithChildren = ShellMcpsCreateRoute._addFileChildren(
  ShellMcpsCreateRouteChildren,
)

interface ShellPipelinesTabAgentIdRouteChildren {
  ShellPipelinesTabAgentIdVersionRoute: typeof ShellPipelinesTabAgentIdVersionRoute
}

const ShellPipelinesTabAgentIdRouteChildren: ShellPipelinesTabAgentIdRouteChildren =
  {
    ShellPipelinesTabAgentIdVersionRoute: ShellPipelinesTabAgentIdVersionRoute,
  }

const ShellPipelinesTabAgentIdRouteWithChildren =
  ShellPipelinesTabAgentIdRoute._addFileChildren(
    ShellPipelinesTabAgentIdRouteChildren,
  )

interface ShellPipelinesTabRouteChildren {
  ShellPipelinesTabAgentIdRoute: typeof ShellPipelinesTabAgentIdRouteWithChildren
}

const ShellPipelinesTabRouteChildren: ShellPipelinesTabRouteChildren = {
  ShellPipelinesTabAgentIdRoute: ShellPipelinesTabAgentIdRouteWithChildren,
}

const ShellPipelinesTabRouteWithChildren =
  ShellPipelinesTabRoute._addFileChildren(ShellPipelinesTabRouteChildren)

interface ShellSkillsTabSkillIdRouteChildren {
  ShellSkillsTabSkillIdVersionRoute: typeof ShellSkillsTabSkillIdVersionRoute
}

const ShellSkillsTabSkillIdRouteChildren: ShellSkillsTabSkillIdRouteChildren = {
  ShellSkillsTabSkillIdVersionRoute: ShellSkillsTabSkillIdVersionRoute,
}

const ShellSkillsTabSkillIdRouteWithChildren =
  ShellSkillsTabSkillIdRoute._addFileChildren(
    ShellSkillsTabSkillIdRouteChildren,
  )

interface ShellSkillsTabRouteChildren {
  ShellSkillsTabSkillIdRoute: typeof ShellSkillsTabSkillIdRouteWithChildren
}

const ShellSkillsTabRouteChildren: ShellSkillsTabRouteChildren = {
  ShellSkillsTabSkillIdRoute: ShellSkillsTabSkillIdRouteWithChildren,
}

const ShellSkillsTabRouteWithChildren = ShellSkillsTabRoute._addFileChildren(
  ShellSkillsTabRouteChildren,
)

interface ShellToolkitsTabRouteChildren {
  ShellToolkitsTabToolkitIdRoute: typeof ShellToolkitsTabToolkitIdRoute
}

const ShellToolkitsTabRouteChildren: ShellToolkitsTabRouteChildren = {
  ShellToolkitsTabToolkitIdRoute: ShellToolkitsTabToolkitIdRoute,
}

const ShellToolkitsTabRouteWithChildren =
  ShellToolkitsTabRoute._addFileChildren(ShellToolkitsTabRouteChildren)

interface ShellToolkitsCreateRouteChildren {
  ShellToolkitsCreateToolkitTypeRoute: typeof ShellToolkitsCreateToolkitTypeRoute
}

const ShellToolkitsCreateRouteChildren: ShellToolkitsCreateRouteChildren = {
  ShellToolkitsCreateToolkitTypeRoute: ShellToolkitsCreateToolkitTypeRoute,
}

const ShellToolkitsCreateRouteWithChildren =
  ShellToolkitsCreateRoute._addFileChildren(ShellToolkitsCreateRouteChildren)

interface ShellUserPublicAgentsAgentIdRouteChildren {
  ShellUserPublicAgentsAgentIdVersionRoute: typeof ShellUserPublicAgentsAgentIdVersionRoute
}

const ShellUserPublicAgentsAgentIdRouteChildren: ShellUserPublicAgentsAgentIdRouteChildren =
  {
    ShellUserPublicAgentsAgentIdVersionRoute:
      ShellUserPublicAgentsAgentIdVersionRoute,
  }

const ShellUserPublicAgentsAgentIdRouteWithChildren =
  ShellUserPublicAgentsAgentIdRoute._addFileChildren(
    ShellUserPublicAgentsAgentIdRouteChildren,
  )

interface ShellUserPublicPipelinesAgentIdRouteChildren {
  ShellUserPublicPipelinesAgentIdVersionRoute: typeof ShellUserPublicPipelinesAgentIdVersionRoute
}

const ShellUserPublicPipelinesAgentIdRouteChildren: ShellUserPublicPipelinesAgentIdRouteChildren =
  {
    ShellUserPublicPipelinesAgentIdVersionRoute:
      ShellUserPublicPipelinesAgentIdVersionRoute,
  }

const ShellUserPublicPipelinesAgentIdRouteWithChildren =
  ShellUserPublicPipelinesAgentIdRoute._addFileChildren(
    ShellUserPublicPipelinesAgentIdRouteChildren,
  )

interface ShellRouteRouteChildren {
  ShellSettingsRouteRoute: typeof ShellSettingsRouteRouteWithChildren
  ShellAgentsHubRoute: typeof ShellAgentsHubRoute
  ShellChatRoute: typeof ShellChatRouteWithChildren
  ShellEliteaCatalogRoute: typeof ShellEliteaCatalogRoute
  ShellHelpCenterRoute: typeof ShellHelpCenterRoute
  ShellMcpAuthCallbackRoute: typeof ShellMcpAuthCallbackRoute
  ShellModeSwitchRoute: typeof ShellModeSwitchRoute
  ShellOnboardingRoute: typeof ShellOnboardingRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAgentsTabRoute: typeof ShellAgentsTabRouteWithChildren
  ShellAgentsCreateRoute: typeof ShellAgentsCreateRoute
  ShellAppsTabRoute: typeof ShellAppsTabRouteWithChildren
  ShellAppsCreateRoute: typeof ShellAppsCreateRouteWithChildren
  ShellArtifactsCreateBucketRoute: typeof ShellArtifactsCreateBucketRoute
  ShellCredentialsTabRoute: typeof ShellCredentialsTabRouteWithChildren
  ShellCredentialsCreateCredentialRoute: typeof ShellCredentialsCreateCredentialRouteWithChildren
  ShellDeepwikiToolkitIdRoute: typeof ShellDeepwikiToolkitIdRoute
  ShellMcpsTabRoute: typeof ShellMcpsTabRouteWithChildren
  ShellMcpsCreateRoute: typeof ShellMcpsCreateRouteWithChildren
  ShellPipelinesTabRoute: typeof ShellPipelinesTabRouteWithChildren
  ShellPipelinesCreateRoute: typeof ShellPipelinesCreateRoute
  ShellSkillsTabRoute: typeof ShellSkillsTabRouteWithChildren
  ShellSkillsCreateRoute: typeof ShellSkillsCreateRoute
  ShellToolkitsTabRoute: typeof ShellToolkitsTabRouteWithChildren
  ShellToolkitsCreateRoute: typeof ShellToolkitsCreateRouteWithChildren
  ShellUserPublicTabRoute: typeof ShellUserPublicTabRoute
  ShellAgentsIndexRoute: typeof ShellAgentsIndexRoute
  ShellAppsIndexRoute: typeof ShellAppsIndexRoute
  ShellArtifactsIndexRoute: typeof ShellArtifactsIndexRoute
  ShellCredentialsIndexRoute: typeof ShellCredentialsIndexRoute
  ShellDeepwikiIndexRoute: typeof ShellDeepwikiIndexRoute
  ShellMcpsIndexRoute: typeof ShellMcpsIndexRoute
  ShellPipelinesIndexRoute: typeof ShellPipelinesIndexRoute
  ShellSkillsIndexRoute: typeof ShellSkillsIndexRoute
  ShellToolkitsIndexRoute: typeof ShellToolkitsIndexRoute
  ShellUserPublicAgentsAgentIdRoute: typeof ShellUserPublicAgentsAgentIdRouteWithChildren
  ShellUserPublicAppsAppIdRoute: typeof ShellUserPublicAppsAppIdRoute
  ShellUserPublicMcpsMcpIdRoute: typeof ShellUserPublicMcpsMcpIdRoute
  ShellUserPublicPipelinesAgentIdRoute: typeof ShellUserPublicPipelinesAgentIdRouteWithChildren
  ShellUserPublicToolkitsToolkitIdRoute: typeof ShellUserPublicToolkitsToolkitIdRoute
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellSettingsRouteRoute: ShellSettingsRouteRouteWithChildren,
  ShellAgentsHubRoute: ShellAgentsHubRoute,
  ShellChatRoute: ShellChatRouteWithChildren,
  ShellEliteaCatalogRoute: ShellEliteaCatalogRoute,
  ShellHelpCenterRoute: ShellHelpCenterRoute,
  ShellMcpAuthCallbackRoute: ShellMcpAuthCallbackRoute,
  ShellModeSwitchRoute: ShellModeSwitchRoute,
  ShellOnboardingRoute: ShellOnboardingRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellAgentsTabRoute: ShellAgentsTabRouteWithChildren,
  ShellAgentsCreateRoute: ShellAgentsCreateRoute,
  ShellAppsTabRoute: ShellAppsTabRouteWithChildren,
  ShellAppsCreateRoute: ShellAppsCreateRouteWithChildren,
  ShellArtifactsCreateBucketRoute: ShellArtifactsCreateBucketRoute,
  ShellCredentialsTabRoute: ShellCredentialsTabRouteWithChildren,
  ShellCredentialsCreateCredentialRoute:
    ShellCredentialsCreateCredentialRouteWithChildren,
  ShellDeepwikiToolkitIdRoute: ShellDeepwikiToolkitIdRoute,
  ShellMcpsTabRoute: ShellMcpsTabRouteWithChildren,
  ShellMcpsCreateRoute: ShellMcpsCreateRouteWithChildren,
  ShellPipelinesTabRoute: ShellPipelinesTabRouteWithChildren,
  ShellPipelinesCreateRoute: ShellPipelinesCreateRoute,
  ShellSkillsTabRoute: ShellSkillsTabRouteWithChildren,
  ShellSkillsCreateRoute: ShellSkillsCreateRoute,
  ShellToolkitsTabRoute: ShellToolkitsTabRouteWithChildren,
  ShellToolkitsCreateRoute: ShellToolkitsCreateRouteWithChildren,
  ShellUserPublicTabRoute: ShellUserPublicTabRoute,
  ShellAgentsIndexRoute: ShellAgentsIndexRoute,
  ShellAppsIndexRoute: ShellAppsIndexRoute,
  ShellArtifactsIndexRoute: ShellArtifactsIndexRoute,
  ShellCredentialsIndexRoute: ShellCredentialsIndexRoute,
  ShellDeepwikiIndexRoute: ShellDeepwikiIndexRoute,
  ShellMcpsIndexRoute: ShellMcpsIndexRoute,
  ShellPipelinesIndexRoute: ShellPipelinesIndexRoute,
  ShellSkillsIndexRoute: ShellSkillsIndexRoute,
  ShellToolkitsIndexRoute: ShellToolkitsIndexRoute,
  ShellUserPublicAgentsAgentIdRoute:
    ShellUserPublicAgentsAgentIdRouteWithChildren,
  ShellUserPublicAppsAppIdRoute: ShellUserPublicAppsAppIdRoute,
  ShellUserPublicMcpsMcpIdRoute: ShellUserPublicMcpsMcpIdRoute,
  ShellUserPublicPipelinesAgentIdRoute:
    ShellUserPublicPipelinesAgentIdRouteWithChildren,
  ShellUserPublicToolkitsToolkitIdRoute: ShellUserPublicToolkitsToolkitIdRoute,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRouteRoute: ShellRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  ProjectIdSplatRoute: ProjectIdSplatRoute,
  SharedChatTokenRoute: SharedChatTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
