"""The ``fixture`` runner: real composition and upload over canned results.

``ELITEA_DEEPWIKI_RUNNER=fixture`` is for a stack that must exercise the whole
generate → land → read path — the facade's credential and callback handling,
this service's composition and artifact upload, the bucket, the wiki browser —
without the analysis engine's dependency closure, a git host or a model.
The browser journeys run against it.

It is :class:`LegacyToolRunner` with its tools injected, plus paced progress
events so a client sees a run in flight and can stop it. Everything
downstream of the tool call is the real code — the Go host's merge, egress
check, composition and upload, this package's publish. What is canned is
only what the engine would have computed.

The canned wiki is deterministic and derived from the request, so a test can
predict the keys that land: ``{owner}--{repo}--{branch}/…``. One page carries
a mermaid block that does not parse, on purpose — it is what the quick-fix
journey repairs.
"""
from __future__ import annotations

import asyncio
import json
from typing import Any

from .legacy_runner import LegacyToolRunner
# The ONE wiki-id derivation in this package. A fixture that derived a
# different one would land its pages under keys nothing reads.
from .wiki_context import display_repository_for, wiki_id_for

#: Progress the fixture emits before each tool answers, in order. The legacy
#: engine emitted prose like this through ``invocation_thinking``; the UI's
#: thinking log renders it verbatim.
STEPS: dict[str, tuple[str, ...]] = {
    "generate_wiki": (
        "Cloning the repository",
        "Indexing 12 files",
        "Planning the wiki structure",
        "Writing 3 pages",
        "Assembling the manifest",
    ),
    "ask": ("Searching the wiki index", "Composing the answer"),
    "deep_research": (
        "Planning the research",
        # A STRUCTURED event, not prose — see RESEARCH_TODOS below.
        "__RESEARCH_TODOS__",
        "Reading the relevant pages",
        "Writing the report",
    ),
}

#: The plan a fixture deep_research run publishes.
#:
#: The browser's research panel renders whatever the run's ``todo_update``
#: events carry, and renders NOTHING when there are none — correct for ``ask``
#: and indistinguishable from a panel wired up wrong. Until this list existed
#: no journey could tell those apart (DWIKI-012b is that journey). The Go
#: host's fixture (run/fixture.go, ResearchTodos) carries the SAME list: the
#: E2E stack runs that one, the standalone stack runs this one, and the
#: journey must pass on both. Shape is the browser-facing normalised one
#: (id/title/description/status) — the pre-normalisation ``content`` key
#: renders as "Untitled step".
RESEARCH_TODOS: tuple[dict[str, Any], ...] = (
    {"id": 1, "title": "Plan the research", "description": "", "status": "completed"},
    {"id": 2, "title": "Read the relevant pages", "description": "", "status": "in_progress"},
    {"id": 3, "title": "Write the report", "description": "", "status": "pending"},
)


def todo_update_event(todos: tuple[dict[str, Any], ...] = RESEARCH_TODOS) -> str:
    """The ``{event, data}`` envelope the browser's chat reducer routes to the research panel."""
    return json.dumps({"event": "todo_update", "data": {"items": list(todos)}})


def steps_for(tool_name: str) -> tuple[str, ...]:
    """STEPS with the structured placeholders resolved to their envelopes."""
    return tuple(todo_update_event() if step == "__RESEARCH_TODOS__" else step for step in STEPS.get(tool_name, ()))

BROKEN_MERMAID_PAGE = """# Request flow

The diagram below is deliberately broken: the fixture exists so the quick fix
has something to repair.

```mermaid
graph TD
  A[Client] -->
```

After the diagram.
"""


def generate_wiki(
    *,
    query: str,
    repo_config: dict[str, Any] | None = None,
    active_branch: str = "main",
    **_ignored: Any,
) -> dict[str, Any]:
    """A completed generation: manifest, structure, three pages, context."""
    wiki_id = wiki_id_for(repo_config, active_branch)
    # Read from the repo_config, not reversed out of the wiki id: an artifact
    # folder's name holds a "/" of its own, and turning every "--" back into a
    # "/" would rebuild a path that never existed.
    repository = display_repository_for(repo_config) or "fixture/repository"
    pages = {
        "wiki_pages/overview/getting-started.md": (
            f"# Getting started\n\nGenerated by the fixture runner for `{repository}` "
            f"in answer to: {query}\n"
        ),
        "wiki_pages/architecture/request-flow.md": BROKEN_MERMAID_PAGE,
        "wiki_pages/components/storage.md": (
            "# Storage\n\nObjects live in the `wiki-artifacts` bucket, one key per page.\n"
        ),
    }
    manifest = {
        "schema_version": 1,
        "wiki_id": wiki_id,
        "wiki_title": f"{repository.rsplit('/', 1)[-1]} wiki",
        "description": "Generated by the DeepWiki fixture runner.",
        "wiki_version_id": "fixture-1",
        "created_at": "2026-01-01T00:00:00Z",
        "canonical_repo_identifier": repository,
        "repository": repository,
        "branch": active_branch or "main",
        "provider_type": (repo_config or {}).get("provider_type") or "github",
        "pages": list(pages),
    }
    structure = {
        "title": manifest["wiki_title"],
        "sections": [
            {"title": "Overview", "pages": ["wiki_pages/overview/getting-started.md"]},
            {"title": "Architecture", "pages": ["wiki_pages/architecture/request-flow.md"]},
            {"title": "Components", "pages": ["wiki_pages/components/storage.md"]},
        ],
    }
    artifacts: list[dict[str, Any]] = [
        {
            "name": f"{wiki_id}/analysis/wiki_structure_fixture.json",
            "type": "application/json",
            "data": json.dumps(structure, indent=2),
        },
        *(
            {"name": f"{wiki_id}/{key}", "type": "text/markdown", "data": body}
            for key, body in pages.items()
        ),
        {
            "name": f"{wiki_id}/wiki_manifest_fixture-1.json",
            "type": "application/json",
            "data": json.dumps(manifest, indent=2),
        },
    ]
    return {
        "success": True,
        "result": f"Wiki generated: {len(pages)} pages",
        "wiki_id": wiki_id,
        "artifacts": artifacts,
        "repository_context": f"repository: {repository}\nbranch: {active_branch}\nfiles: 12\n",
    }


def ask(*, question: str, **_ignored: Any) -> dict[str, Any]:
    return {
        "success": True,
        "answer": f"Fixture answer to: {question}",
        "sources": [
            {"source": "wiki_pages/overview/getting-started.md"},
            {"source": "wiki_pages/components/storage.md"},
        ],
    }


def deep_research(*, question: str, research_type: str = "general", **_ignored: Any) -> dict[str, Any]:
    return {
        "success": True,
        "report": f"# Research report ({research_type})\n\nQuestion: {question}\n\nFindings: fixture.\n",
    }


def resolve_wiki(*, question: str, wikis: list | None = None, **_ignored: Any) -> dict[str, Any]:
    """The wiki resolver, without a model.

    Word overlap between the question and each candidate's id and title —
    which is what the model is asked for, and is decidable without one. The
    Go host's own fixture table (``run/fixture.go::fixtureResolveWiki``)
    scores identically, so a stack that runs either sidecar resolves the
    same wiki for the same question.
    """
    lowered = (question or "").lower()
    best, best_score = "", 0
    for candidate in wikis or []:
        if not isinstance(candidate, dict):
            continue
        wiki_id = str(candidate.get("wiki_id") or "")
        text = f"{wiki_id} {candidate.get('wiki_title') or ''}".lower()
        for separator in "-_/.":
            text = text.replace(separator, " ")
        score = sum(1 for word in text.split() if len(word) >= 3 and word in lowered)
        if score > best_score:
            best, best_score = wiki_id, score
    if not best and len(wikis or []) == 1:
        candidate = (wikis or [])[0]
        best = str(candidate.get("wiki_id") or "") if isinstance(candidate, dict) else ""
    return {"success": True, "wiki_id": best or "NONE"}


FIXTURE_TOOLS = {
    "generate_wiki": generate_wiki,
    "ask": ask,
    "deep_research": deep_research,
    "resolve_wiki": resolve_wiki,
}


class FixtureToolRunner(LegacyToolRunner):
    """The legacy runner over :data:`FIXTURE_TOOLS`, with paced progress."""

    name = "fixture"

    def __init__(self, settings=None) -> None:
        super().__init__(settings=settings, tools=dict(FIXTURE_TOOLS))
        self._step_seconds = float(getattr(settings, "fixture_step_seconds", 0.0) or 0.0)

    async def _paced(self, tool_name: str, context: Any) -> None:
        for step in steps_for(tool_name):
            # The checkpoint is what makes Stop work mid-run: a cancelled
            # invocation raises here instead of finishing and uploading.
            await context.checkpoint()
            await context.thinking(step)
            if self._step_seconds > 0:
                await asyncio.sleep(self._step_seconds)
